### ISSUE TITLE
Side window – Les visuels de la page mettent un moment à se charger correctement.

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorenv#1009]
A la première ouverture de la side window, les éléments s'affichent dans le désordre et dans un style différent pendant un moment plus ou moins long. 

![image](https://github.com/MTES-MCT/monitorenv/assets/71878648/c55194f9-7ceb-4238-955d-b8d927f35373)

**Comment by AdelineCelier** [comment]
@claire2212 ça me le fait encore un peu de mon côté...

https://github.com/MTES-MCT/monitorenv/assets/71878648/c5422214-0961-4592-ae4b-d6431b866e28

**Comment by claire2212** [comment]
@AdelineCelier je ne vois pas la side window dans la vidéo :-( Et c'est étrange j'avais testé de mon côté. Tu avais bien rechargé la page?
