### ISSUE TITLE
Rapportage - Ajuster l'affichage de la carte d'infraction

### ISSUE THREAD

**Issue by thoomasbro** [MTES-MCT/monitorenv#101]

**Comment by AdelineCelier** [comment]
En plus de l'UI de la carte, attention à modifier le "NR" à la place de la mention "Avec ou sans PV"

**Comment by thoomasbro** [comment]
> En plus de l'UI de la carte, attention à modifier le "NR" à la place de la mention "Avec ou sans PV"

NR est pour "non renseigné". Faut il mettre une valeur par défaut ?

**Comment by AdelineCelier** [comment]
Yes pardon je le spécifiais parce qu'aujourd'hui le choix du avec/sans PV n'est pas répercuté sur la carte.
Autrement par défaut on peut mettre **PV : -** ou **PV : nr**

**Comment by AdelineCelier** [comment]
Si j'enregistre une infraction sans cocher de case pour le PV, cela mentionne "Avec PV" malgré tout, au lieu de mettre la valeur par défaut.

**Comment by AdelineCelier** [comment]
@thoomasbro j'ai l'impression qu'il y a un truc bizarre qui se passe lorsque le nombre d'infractions ne correspond pas au nombre de contrôles : ça met des trucs genre "-1 RAS" dans la carte de contrôle du volet central
(scusi pour la capture d'écran ci-dessous un peu picassienne, je suis sur mon ptit écran d'ordi portable)

Je ne suis plus très au clair sur les règles métier concernant le nombre de contrôles VS le nombre d'infractions, faut-il limiter l'un par rapport à l'autre ? Si tu te souviens de ce qui a été dit on peut en parler, sinon je redemanderai en salle. 

![image](https://user-images.githubusercontent.com/71878648/203411074-a69ce76a-5c16-493a-9d9e-5f4e5feacbf6.png)

**Comment by AdelineCelier** [comment]
Normalement ce problème devrait être résolu en traitant le ticket #108 
Je passe donc ce ticket en "to be deployed in PROD".
