### ISSUE TITLE
Rapportage - Mettre à jour les administrations et unités

### ISSUE THREAD

**Issue by thoomasbro** [MTES-MCT/monitorenv#102]

**Comment by AdelineCelier** [comment]
Il semble qu'il manque des unités, ex. le PNM de Mayotte pour l'administration Parcs Naturels Marins... à moins qu'il y ait un problème d'affichage ? J'ai l'impression que la première ligne du menu déroulant est tronquée.

![image](https://user-images.githubusercontent.com/71878648/188886397-5bd628d3-6dd9-469f-94dc-f9726142e425.png)
