### ISSUE TITLE
Moyens - Cohérence avec le rapportage

### ISSUE THREAD

**Issue by thoomasbro** [MTES-MCT/monitorenv#103]
Assurer la cohérence des données entre la base de rapportage et les données retournées par l'API pour permettre un affichage correct au cas où un moyen aurait été retiré (non présent dans la liste des moyens) mais l'entrée serait toujours présente dans la mission. (Cas par exemple en cas d'historisation: moyen rendu non disponible à la sélection, mais information devant être affichée coté client)

**Comment by louptheron** [comment]
Dans la V2 avec normalisation des Administrations, Unités et Moyens, cette solution n'est plus nécessaire.
Un moyen référencé dans la table `mission_control_resources` ne peut être supprimé avec la contrainte FOREIGN KEY.
