### ISSUE TITLE
Signalements – Ajouter la cible dans la vue liste des signalements

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorenv#1041]
S'y afficherait le détail de la cible que vous avez saisi :
- si vous saisissez un nom (de navire, de personne, de société...), on l'afficherait
- pour les cibles de type navire, s'il n'y a pas de nom mais qu'il y a un MMSI, on afficherait le MMSI
- si vous n'avez saisi qu'un type de cible, on l'afficherait
- si vous n'avez rien saisi, on n'afficherait rien ;)
- petite particularité si la cible est "autre", il faudrait rendre le champ "description" obligatoire, afin qu'on ne puisse pas enregistrer un signalement avec une cible autre sans l'avoir décrite

**Comment by AdelineCelier** [comment]
@claire2212 j'ai mis à jour les écrans XD avec les cibles : https://xd.adobe.com/view/69dcd22c-eb8b-4ede-bd7c-473483429986-3c8f/screen/39cd7598-020c-4523-854a-2212a7d194f5/

Pour gagner de la place pour la colonne des cibles : 
- on ne met que "mission" dans le tag vert 
- on abrévie les tags contrôle à faire/fait et surveillance faite en "ctl à faire/fait" et "srv faite"
- on gagne encore un peu de place en abréviant le "(suspicion)" en "(susp.)"

Côté filtres, les changements : 
- ajout d'un filtre "type de cible"
- suppression du filtre "action réalisée"
- ajout de 2 cases à cocher "lié à une mission" / "non lié à une mission"

**Comment by claire2212** [comment]
@AdelineCelier : 
- Filtre type de cible : je ne filtre que sur "Véhicule", "personne morale", "personne physique", "autre" ?
- pour les tags, les changements de wording ne sont à faire que sur le tableau où je les répercutent partout?

**Comment by AdelineCelier** [comment]
- oui je pense que c'est suffisant comme valeurs de filtre, si on veut rechercher une info plus précise sur une cible l'idée serait plutôt de passer par la recherche
- on les répercute partout
- ah bah j'avais zappé, tant mieux

**Comment by AdelineCelier** [comment]
## Revue en cours

@claire2212 petits retours : 
- Possible d
- Puisqu'on a rendu le champ "description" obligatoire en cas de cible "Autre", je me demande s'il ne serait pas judicieux d'afficher la description (ou au moins son début) dans la colonne "cible" + dans l'en-tête du signalement ?
- Problème de calage des tag "ctl à faire"/ "ctl fait"/"srv faite" dans la carte de signalement lié à une mission dans le formulaire : j'ai l'impression qu'ils sont trop hauts
![image](https://github.com/MTES-MCT/monitorenv/assets/71878648/f5a14c56-1a34-4616-b657-3bb4baceb351)

**Comment by AdelineCelier** [comment]
Comme vu à l'instant sur MB, tenter de mettre le tag en haut à droite de la carte, au niveau de l'unité. 
Si le nom de l'unité est trop long, le tronquer avec des pointillés + un hover avec le nom complet.

**Comment by AdelineCelier** [comment]
Top, c'est mieux comme ça !
