### ISSUE TITLE
Note libre - depuis quelques jours les infos rentrées dans les observations des notes libres ne s'affichent plus

### ISSUE THREAD

**Issue by AlexiaLaunay** [MTES-MCT/monitorenv#1046]

**Comment by claire2212** [comment]
Bonjour @AlexiaLaunay , est-ce que tu pourrais me donner un exemple de mission s'il te plaît? 
Et est-ce que c'est l'encart du milieu que ne s'affiche pas du tout ou l'encart du milieu s'affiche mais le texte dans le champ `Observations` n'apparait pas ?

**Comment by claire2212** [comment]
@AlexiaLaunay c'est bon j'ai trouvé le souci, par conte les note libre saisie depuis la dernière mise ne production n'ont pas été enregistrées en base :-( 

Nous avons une mise en production prévue mardi à 14H, le problème sera résolu à ce moment là. D'ici là ça ne sert à rien de renseigner des notes libres, elles ne seront pas enregistrées
