### ISSUE TITLE
Unités – Améliorer recherche dans le module Unités de contrôle

### ISSUE THREAD

**Issue by AlexiaLaunay** [MTES-MCT/monitorenv#1048]
Manon : Pour l'instant on peut faire une recherche seulement avec le type précis du moyen (avion/hélicoptère/drone/semi-rigide/....) ce serait pas mal de pouvoir filtrer selon air/terre/mer.
On ne peut chercher que le nom de l'unité : serait pas mal de pouvoir chercher le nom du moyen.
Aussi, on peut soit afficher toutes les unités soit en afficher aucune. Je trouverai ça intéressant de pouvoir filtrer les unités (par exemple je veux voir afficher seulement les unités aérienne ou seulement les douanes).

**Comment by AdelineCelier** [comment]
Hello, bien noté ces retours, je les bascule dans notre kanban !

**Comment by AdelineCelier** [comment]
Je résume les points ici :

- [ ] rajouter un filtre moyen mer / terre / air => je dessine un écran
- [ ] ajouter recherche dans les noms de moyens dans la barre de recherche
- [ ] rétablir le filtrage de la carte avec les filtres sélectionnés dans le menu

**Comment by AdelineCelier** [comment]
Il manque les 2 points non cochés, je remets le ticket en todo

**Comment by AdelineCelier** [comment]
c'est good !
