### ISSUE TITLE
Bug - Notes non modifiables et inaccessibles

### ISSUE THREAD

**Issue by manonolivier** [MTES-MCT/monitorenv#1059]
En plus de l'impossibilité de faire des notes depuis le 28/11 : problème aussi pour obtenir le détail d'une "longue" note d'une missions qui date d'avant le bug. On ne peut pas les modifier mais également pas les ouvrir.
![mcgfgiiodjlhladm](https://github.com/MTES-MCT/monitorenv/assets/147587284/f36e7531-c495-4a77-a172-6896e4255108)

**Comment by claire2212** [comment]
@manonolivier @AdelineCelier  je viens de tester et la note est à nouveau accessible (depuis la mise en prod de ce jour) . je clôture ce ticket
