### ISSUE TITLE
[Semaphores] Suppression des sémaphores de la liste des unités

### ISSUE THREAD

**Issue by claire2212** [MTES-MCT/monitorenv#1074]
- Suppression des sémaphores dans la liste des unités (filtre mission + sélection unité dans formulaire de mission)

**Comment by AdelineCelier** [comment]
Après discussion avec le CACEM, il s'avère qu'ils n'ont pas un besoin spécifique d'une vue liste des sémaphores, mais un besoin plus large d'intégration de tout l'annuaire dans MonitorEnv. Je propose donc de créer un ticket dédié à la question de l'annuaire, et de ne conserver celui-ci que pour la suppression des sémaphores de la liste des unités.

**Comment by VincentAntoine** [comment]
Hello,
Dans un monde idéal, je dirais qu'il faudrait :
1. Une conversion des missions sémaphores 2023 en signalements à proprement parler
2. Supprimer les missions sémaphore 2023
3. Supprimer les sémaphores de la liste des unités

Mais je ne sais pas si ceci est bien réalisable, notamment le point 1. pour lequel il faut s'assurer que les informations saisies dans les missions sémaphores sont suffisantes pour créer des signalements et le point 2. qui présente le risque de supprimer des vraies missions dans lesquelles il y a aussi eu des actions de contrôle ou de surveillance, si la séparation entre vraies missions et missions de "signalement" n'est pas claire.

Il faudrait creuser ça dans les data pour répondre je pense.

Mais je n'ai pas tout l'historique de ce qui a peut-être déjà été fait, j'ai peu suivi le développement de la brique signalements.

**Comment by claire2212** [comment]
Fait par Alexia depuis le back-office de Monitor Env (archivage des unités de type `Sémaphore` et de l'administration `FOSIT`)
