### ISSUE TITLE
[Thématiques] Supprimer les thématiques si l'année de mission change et qu'il n'y a pas de date d'action

### ISSUE THREAD

**Issue by claire2212** [MTES-MCT/monitorenv#1075]
Suppression des `controlPlans` si : 
- Contrôle : année de date de mission change et le contrôle n'a pas de date d'action renseignée
- Surveillance : année de date de mission change et la surveillance n'a pas de date d'action renseignée OU année de mission change et la surveillance a des dates de surveillance identiques aux dates de mission

**Comment by AdelineCelier** [comment]
Yes ça marche bien de mon côté !
