### ISSUE TITLE
Rapportage – Ajustements encart d'infraction (en complément des règles de validation)

### ISSUE THREAD

**Issue by thoomasbro** [MTES-MCT/monitorenv#108]
Faut il gérer de manière spécifique le changement du type de cible lorsque des infractions sont déjà saisies ?

**Comment by AdelineCelier** [comment]
@thoomasbro je ne suis pas sure de comprendre ta question. 
Peut-être que le plus simple serait de dire que quand tu crées un nouveau contrôle, les champs "type de cible" et "type de véhicule" + le bouton "ajouter une nouvelle infraction" sont grisés tant que tu n'as pas rempli le champ "nombre total de contrôles". 
Ca permettra à l'utilisateur de ne pas oublier de remplir le nb de contrôles. Et une fois que celui-ci est rempli, tu peux ajouter des infractions et modifier comme tu veux les champs "type de cible" et "type de véhicule" pour que ça mette à jour les champs de la carte d'infraction. 
Tu penses que c'est ok comme ça ?

**Comment by thoomasbro** [comment]
En fait il y a 2 idées :
- comment inciter l'utilisateur à bien saisir tous les champs, notamment le nombre de contrôles. Ok pour interdire la saisie d'un type de véhicule ou l'ajout d'une infraction si le nombre de contrôles n'est pas rempli. Mais que se passe t il lorsque l'utilisateur supprime le nombre de contrôles ou saisie "0" ? Est ce qu'on ne peut pas juste mettre un message d'erreur sur le champ à la validation/navigation si le champ est laissé vide ?

- que se passe t il lorsque l'utilisateur change le type de véhicule alors que des infractions sont déjà saisies pour un autre type de véhicule ? Je pense qu'il faut supprimer les informations qui ne sont plus pertinentes.

**Comment by AdelineCelier** [comment]
Je me rends compte que je ne t'avais pas répondu. 
- je comprends cette première remarque, cela me va de plutôt mettre une erreur dans deux cas de figure : lorsque des infractions sont ouvertes avant d'avoir saisi le nombre total de contrôles, ou alors si le nombre d'infractions dépasse le nombre de contrôles. Je vais décliner les composants de champs avec un état "erreur" et mettre à jour les écrans dans ce sens.
- dans le cas d'un changement de cible ou de véhicule alors que des infractions sont déjà saisies, je serais effectivement pour une solution simple de suppression des infos non correspondantes, et tant pis si finalement l'utilisateur doit les re-remplir s'il revient en arrière. Je ne pense pas qu'un message d'alerte soit nécessaire dans ce cas.

**Comment by AdelineCelier** [comment]
Ok alors je me rends compte que je n'ai pas décliné cette histoire de champ bloquant en fonction du nombre de contrôles.
Mais j'ai les mêmes questionnements que pour le ticket #101, je vais tirer ça au clair rapidement.

**Comment by AdelineCelier** [comment]
C'est bon, j'ai mis mes idées au clair, notamment en terminant les champs bloquants. 

Je trouve qu'il y avait confusion dans le nommage des éléments. 
Pour plus de clarté, j'ai renommé les items de l'encart d'infraction :
- le bouton "ajouter une infraction" devient "ajouter un contrôle avec infraction"
- le libellé de l'encart "détailler une infraction d'une cible" devient "détails de la cible en infraction"
- le placeholder de l'encart vide "aucune infraction enregistrée pour le moment" devient "aucun contrôle avec infraction enregistré pour le moment". 

Je vois que tu as grisé le bouton pour ajouter des contrôles en infraction tant qu'on n'a pas renseigné le nb total de contrôles. 
Je propose qu'on garde la même logique et qu'on le grise quand le nb de contrôles en infraction est égal à celui du nb total de contrôles (cf. [écran 28](https://xd.adobe.com/view/973ae2b4-ecd1-419f-b092-8545e0d8ce57-c269/screen/779d7c9e-dfc5-4d26-b5c1-04b6f8fd2fcb)). Cela évitera de se retrouver avec des -1 RAS, comme évoqué dans le ticket [101](https://github.com/MTES-MCT/monitorenv/issues/101).
