### ISSUE TITLE
[Signalement] - Bug à l'enregistrement d'un signalement en 2024

### ISSUE THREAD

**Issue by claire2212** [MTES-MCT/monitorenv#1094]
La migration permettant de créer le `reporting_id` n'était pas correcte. J'ai crée une migration pour mettre à jour cette fonction et j'en ai profité pour mettre à jour le `reporting_id` du premier signalement (201-> 230001)

**Comment by AdelineCelier** [comment]
@claire2212 j'ai repéré 2 problèmes : 

- [ ] Je n'arrive pas à lier un 2è signalement à une mission depuis le formulaire de mission. Quand je le fais depuis le signalement en revanche ça fonctionne. 
- [ ] Le bouton "réinitialiser" du menu de rattachement d'un signalement à une mission ne fonctionne pas : je clique dessus mais ça ne désélectionne pas la mission que j'ai sélectionnée

**Comment by AdelineCelier** [comment]
Les deux problèmes me semblent réglés.
