### ISSUE TITLE
Ajout d'une action - possible d'ajouter une action "sensibilisation" comme "contrôle" et "surveillance"

### ISSUE THREAD

**Issue by manonolivier** [MTES-MCT/monitorenv#1101]

**Comment by AdelineCelier** [comment]
Hello @manonolivier, tu peux me donner un peu plus d'infos sur le cas d'usage ? 
Mettre un contrôle sans PV ça ne convient pas ?

**Comment by manonolivier** [comment]
Salut Adeline,

Cas d'usage : une unité va sur la plage en période de nidification des gravelots et arrête tous les gens qu'elle voit pour leur dire "attention aux gravelots", ce ne sont pas des contrôles puisque les personnes n'étaient pas en possible infraction (une possible infraction et donc un contrôle serait : 1 personne qui se dirige vers un groupe de gravelots ou des personnes avec un chien auprès d'un groupe de gravelots)

Le but est quand même de valorises la sensibilisation qui est plus qualitative que de la "simple" surveillance (il y a un effort de fait puisque c'est dans une période précise avec des cibles précises)

**Comment by AdelineCelier** [comment]
Hello @manonolivier,

Désolée du retard de ma réponse. 
Ok je comprends la démarche. Est-ce que c'est un point que vous avez validé en équipe ? 
Je pense qu'il faut voir ensemble comment on veut le matérialiser "conceptuellement" dans Monitor. Ajouter un nouveau type d'action ça peut impliquer pas mal de changements à diverses échelles, ce n'est pas anodin (pas forcément en termes techniques, plutôt en termes de fond et de structure de l'app). 

Pour moi ce type d'action a sa place dans une action de surveillance dans le sens où une unité va en même temps surveiller la plage (si on reprend ton ex) pour voir qu'il n'y a pas d'infraction. 
Si l'idée c'est de retrouver ce genre d'action en stats pour la valoriser, on peut simplement rajouter un champ ou une case à cocher dans la surveillance pour identifier celles qui ont donné lieu à des actions de sensibilisation. Qu'en pensez-vous ?

D'une certaine manière, ça rejoint la question du système de tags (cf le ticket #547) permettant de mentionner des points particuliers dans les missions qu'on veut suivre en stats.

**Comment by manonolivier** [comment]
Salut @AdelineCelier,

Oui c'est validé en équipe, on ne met plus de tickets dans le kanban monitor sans passer par toute l'équipe dont Pierre.

C'est une bonne idée de le mettre en surveillance parce qu'en effet, ce qu'on veut c'est que ça ressorte dans les stats, ça n'a pas de valeur opérationnelle. Par contre, nous aurons besoins de quantifier cette donnée et non pas juste de dire "cette surveillance a donné lieu a de la sensibilisation" mais "lors de cette mission, ils ont sensibilisé **xx personnes** sur cette **thématique**".

Comme on voudrait du détail, ça nous semblait plus lisible en ajoutant une action au même niveau que contrôle, surveillance et note libre.

**Comment by AdelineCelier** [comment]
Hello @manonolivier 

Ok je comprends le besoin de plus de détails. 
Mais juste on est d'accord qu'un bon nombre d'infos de cette action de sensibilisation seraient les mêmes que celles de la surveillance rentrée dans la mission ? 
- les dates
- la zone
- voire la ou les thématiques ?
Si oui, cela plaide pour inclure la notion de sensibilisation au sein de celle de surveillance. On pourrait ajouter une case à cocher "sensibilisation", qui ferait apparaître un champ "nombre de personnes sensibilisées". Concernant les thématiques : si ce sont la ou les mêmes que celle(s) de la surveillance, c'est le plus simple. S'il y a des différences possibles, il faut qu'on en discute.
On peut en reparler de vive voix la semaine prochaine ? Je serai à Étel.

**Comment by manonolivier** [comment]
@AdelineCelier On en reparle quand tu seras à Etel mais pour ne pas oublier, je le note : 
Il nous faut : 
- la date
- le point géographique (comme pour les contrôles)
- la thématique précise (le problème se pose pour les surveillances qui ont souvent plusieurs thématiques, il faut qu'on sache sur quelles thématiques ont porté les sensibilisations)

Si on fait le choix de mettre dans surveillance : à voir si ça ne surcharge pas trop la fenêtre

**Comment by AdelineCelier** [comment]
Après discussion en point de synchro CACEM, voici ce qui a été acté : 
Cela fait sens d'intégrer la notion de sensibilisation à une surveillance, car il n'y a pas de suspicion d'infraction vis-à-vis des personnes sensibilisées. 
Il n'y a pas besoin de rentrer dans le détail du point géographique, la zone de la mission suffit à positionner l'action. 
En revanche, les surveillance peuvent être multi-thématiques et il faut pouvoir désigner sur quelle thématique la sensibilisation a porté parmi les différentes sélectionnées dans la surveillance.

La tâche peut être découpée en 2 si elle nécessite un temps de dev important : 
- d'abord ajouter une case à cocher "sensibilisation" dans la surveillance + un champ "nb de personnes sensibilisées"
- puis le choix de la thématique sur laquelle la sensibilisation a porté.

**Comment by AdelineCelier** [comment]
All good pour moi !
