### ISSUE TITLE
Unités - Fiche unité sur la carte

### ISSUE THREAD

**Issue by ivangabriele** [MTES-MCT/monitorenv#1102]
## Retours UX

- [x] Formulaire d'ajout d'un contact : quand je sélectionne un type de contact, puis que dans la foulée je sélectionne "nom de contact personnalisé", le nom du type de contact précédemment sélectionné apparaît en anglais dans le champ
https://github.com/MTES-MCT/monitorfish/assets/71878648/438453fe-b718-4287-ba96-774760553726
**=> il y a la même chose côté Env**

- [x] Quand je clique sur le champ "secteur d'intervention" pour l'éditer, le texte déjà saisi est remplacé par le texte "Littoral des Alpes-Maritimes (06)"
https://github.com/MTES-MCT/monitorfish/assets/71878648/96982f7e-775c-49e1-bddb-7b1eeb61666a

- [x] Même mécanisme dans le champ "modalités de contact" : quand je clique dessus, ça affiche par défaut "CORG Alpes Maritimes (06)"...les Alpes Maritimes are taking the world's controoool RUUUUUN

## Retours UI

- [x] Lorsque le commentaire sur le moyen est long, agrandir la carte du moyen pour afficher jusqu'à 3 lignes. Au-delà de 3 lignes, mettre des points de suspension et un survol. 
![image](https://github.com/MTES-MCT/monitorfish/assets/71878648/9903e1db-d6f0-4186-8660-77b48f1700fb)

_Originally posted by @AdelineCelier in https://github.com/MTES-MCT/monitorfish/issues/2746#issuecomment-1840925933_

**Comment by AdelineCelier** [comment]
@ivangabriele les 3 premiers points sont bons pour moi, en revanche le point UI ne semble pas réglé : 
![image](https://github.com/MTES-MCT/monitorenv/assets/71878648/50c8077f-526a-4884-9965-2a948d267c16)

**Comment by ivangabriele** [comment]
> Mais dans ce cas il faudrait que le fond gris à gauche s'adapte à la hauteur de la carte + qu'il y a plus de marge sous la dernière ligne

**Comment by AdelineCelier** [comment]
@ivangabriele c'est mieux comme ça ! 
Bon et je vais faire la grosse reloue, mais le top serait que l'icône sur le fond gris se centre en hauteur, si c'est possible 😇 
![image](https://github.com/MTES-MCT/monitorenv/assets/71878648/489b5fd7-9612-4ccc-971b-36fcae709336)

Bon idem pas bloquant pour la mep bien entendu !

**Comment by AdelineCelier** [comment]
c'est bon !
