### ISSUE TITLE
Unités – Affichage des bases sur la carte

### ISSUE THREAD

**Issue by ivangabriele** [MTES-MCT/monitorenv#1105]
- [x] Sur l'affichage des bases au-dessus des sémaphores : l'icône des sémaphores est bien en-dessous de celle des bases maintenant, en revanche la pop-up des sémaphores reste au-dessus de celle des bases. Je le note ici, mais à voir ce qu'on décidera concernant le comportement des pop-ups. Peut-être qu'il ne faudrait qu'une pop-up ouverte à la fois, tous types de pop-ups confondus 👍🏻 
![image](https://github.com/MTES-MCT/monitorenv/assets/71878648/206f13e3-ed27-4097-8330-28b4c9df1538)

- [x] Sur le fait de donner plus de marge aux numéros dans les pastilles, je ne vois pas la différence...est-ce que parce que c'est trop léger ou bien est-ce que tes changements ne s'affichent pas chez moi ?
![image](https://github.com/MTES-MCT/monitorenv/assets/71878648/4461dcfc-5724-4d34-b2f2-c0b13bb37532)

- [x] Je n'avais pas repéré avant, mais le titre dans la fiche d'une unité n'est pas tronqué non plus, il faut faire comme pour le titre des bases
![image](https://github.com/MTES-MCT/monitorenv/assets/71878648/cf739a78-e653-46b9-a9da-e7113f9e9f7d)

- [x] Autre truc que je n'avais pas repéré : quand je filtre la liste des unités avec le moyen "drône", il y en a 3 qui remontent, mais seul 1 unité sur les 3 a effectivement un drône dans sa liste des moyens. 
![image](https://github.com/MTES-MCT/monitorenv/assets/71878648/d1c091a6-291f-485a-ab9c-a83d31eabe15)

_Originally posted by @AdelineCelier in https://github.com/MTES-MCT/monitorenv/issues/698#issuecomment-1816813298_

**Comment by ivangabriele** [comment]
> Autre truc que je n'avais pas repéré : quand je filtre la liste des unités avec le moyen "drône", il y en a 3 qui remontent, mais seul 1 unité sur les 3 a effectivement un drône dans sa liste des moyens.

@AdelineCelier Je ne suis pas sûr que ce bug existe encore, en tout cas je ne le vois pas en local ou en prod sur Env.

**Comment by AdelineCelier** [comment]
@ivangabriele ah en effet de mon côté aussi ça ne le fait plus ! Etonnant, je ne sais pas ce qui s'était passé pendant les tests, mais cela semble résolu :)

**Comment by AdelineCelier** [comment]
@ivangabriele
- sur le centrage des n° dans les pastilles : j'ai l'impression qu'il y a plus de marge en effet (comment as-tu fait ? tu as augmenté la taille des pastilles ?). En revanche les chiffres ne semblent pas rester centrés dans la pastille. Est-ce que tu veux essayer avec une autre typo ? Open Sans par ex ?
![image](https://github.com/MTES-MCT/monitorenv/assets/71878648/6432ca5b-2f1b-4492-adf6-1d83af5ab264)

- sur les titres dans la fiche unité, le titre s'affiche correctement l'infobulle de survol ne fonctionne pas : elle affiche [object Object], (Office Français de la Biodiversité,) par ex.

**Comment by ivangabriele** [comment]
@AdelineCelier Oui je veux bien tenter d'utiliser OpenSans du coup ^^.

**Comment by AdelineCelier** [comment]
@ivangabriele comme vu ensemble il reste juste à mettre les chiffres des pastilles des bases en 700, et on sera good !

**Comment by AdelineCelier** [comment]
C'est good, top merci !
