### ISSUE TITLE
Remplacement des termes "Office Français de la Biodiversité" et "Activités et manifestations soumises à évaluation d'incidence Natura 2000"

### ISSUE THREAD

**Issue by AlexiaLaunay** [MTES-MCT/monitorenv#1107]
Pour que les graphiques s'affichent correctement sur Métabase, est-ce qu'il serait possible de remplacer :
"Office Français de la Biodiversité" par "OFB"
et "Activités et manifestations soumises à évaluation d'incidence Natura 2000" par "EIN2000"
Merci !

**Comment by claire2212** [comment]
Hello @AlexiaLaunay , comme vu avec Pierre tu peux faire la modification directement dans QGIS. Je te laisse clôturer le ticket quand ce sera fait si ça te va.

**Comment by claire2212** [comment]
Hello @AlexiaLaunay , il semble que pour "Office Français de la Biodiversité" ce soit déjà fait.
Pour ce qui est de la thématique "Activités et manifestations soumises à évaluation d'incidence Natura 2000", on peut tout à fait modifier le nommage en "EIN2000" par contre cela s'affichera comme ça partout dans l'application  (en plus de l'affichage côté Metabase). C'est ok pour vous?

**Comment by AlexiaLaunay** [comment]
Hello @claire2212 , 
oui on avait modifié directement pour OFB.
Pour EIN2000, c'est mieux que ça reste en non abrégé dans ME. @Morraff teste une manip pour que ça s'affiche correctement dans les graphiques métabase sans modifier l'intitulé dans ME

**Comment by AdelineCelier** [comment]
Hello @AlexiaLaunay, tu sais si Morgan a réussi la manip de renommage dans MB ? Vous pensez encore avoir besoi d'aide sur ce ticket ou bien on peut le fermer ?

**Comment by Morraff** [comment]
ça demande une mise en prod donc on verra le résultat à la prochaine release

**Comment by AdelineCelier** [comment]
Ok ça marche, merci Morgan ! Pour info, la prochaine mep aura probablement lieu la semaine pro.
