### ISSUE TITLE
Rapportage - modale de confirmation du formulaire

### ISSUE THREAD

**Issue by thoomasbro** [MTES-MCT/monitorenv#111]
Afficher une modale de confirmation en cas de changements non enregistrés sur le formulaire de rapportage: 
- annulation de l'édition
- changement de contenu de la fenêtre d'édition

**Comment by AdelineCelier** [comment]
@thoomasbro quand j'ai montré les écrans développés à l'AU, Guillaume m'a fait remarquer que le bouton "annuler" n'était pas hyper clair, et que "quitter" le serait plus. Pourrais-tu modifier l'intitulé du bouton ? (je mets cette remarque ici car c'est pour moi directement lié à la modale de confirmation).

**Comment by AdelineCelier** [comment]
Top, je valide
