### ISSUE TITLE
[CouchesRéglementaires] Au premier chargement il y a un temps de "freeze" de l'appli 

### ISSUE THREAD

**Issue by claire2212** [MTES-MCT/monitorenv#1116]

**Comment by claire2212** [comment]
Aller voir au CACEM le 13/14 février pour voir si le souci est réglé

**Comment by claire2212** [comment]
@AdelineCelier j'ai l'impression que c'est réglé depuis la dernière MEP et les améliorations que Thomas a faites. Tu valides? Si c'est le cas je pense qu'on peut fermer le ticket

**Comment by AdelineCelier** [comment]
Ah oui en effet ça a l'air réglé ! Ok pour fermer le ticket.
