### ISSUE TITLE
Signalements - Retirer le scroll horizontal sur la vue liste et élargir la zone de clic sur les icônes de la carto

### ISSUE THREAD

**Issue by manonolivier** [MTES-MCT/monitorenv#1118]
Pour l'instant on ne peut le faire que depuis la carto et c'est pas pratique (superposition de signalement, fenêtre de détail des signalement (là où le bouton "éditer le signalement" se trouve) qui ne reste pas affiché donc impossible de modifier.

**Comment by AdelineCelier** [comment]
@manonolivier comme discuté ensemble hier, les deux problèmes sont en fait les suivants : 
- il y a un scroll horizontal inutile sur le tableau des signalements qui fait qu'on ne voit pas les boutons en fin de ligne. 
- pour figer la pop-up d'un signalement afin d'accéder au bouton "éditer le signalement", on peut cliquer sur le drapeau mais pas sur la croix. Ce serait pas mal d'étendre la zone cliquable à la croix.

Je renomme le ticket et le bascule dans notre kanban. 

ping @claire2212

**Comment by claire2212** [comment]
@manonolivier Bonjour, est ce que tu pourrais me dire la résolution de vos écrans au CACEM s'il te plaît ?
Pour le savoir tu peux ouvrir ce lien depuis un écran : https://fr.screenresolution.org/  et tu verras la résolution
Merci

**Comment by manonolivier** [comment]
Moi, Floriane, Christophe : 1920 x 1080

Alexia : 1680 x 1050

**Comment by AdelineCelier** [comment]
@claire2212 petits retours non bloquants pour la mep : 

- [ ] le bouton "réinitialiser les filtres" doit être justifié à gauche
- [ ] comme discuté, est-ce possible de fixer certains espacements dans le tableau ? 12 px à gauche des cases à cocher, 8 px entre les tags et 16 px à droite du tag le plus à droite
![image](https://github.com/MTES-MCT/monitorenv/assets/71878648/6aa8dd0b-fb44-43cc-bbac-b53fb11d4796)
