### ISSUE TITLE
[Thématiques] - Améliorations des filtres de la vue liste des missions et des signalements

### ISSUE THREAD

**Issue by claire2212** [MTES-MCT/monitorenv#1124]
Dans les filtres :
- quand les filtres sont paramétrés pour afficher des missions qui n'ont lieu que sur 1 année, on n'affiche que les thém. et ss-thém. de cette année
- quand ils sont paramétrés pour afficher des missions sur 2 années, on affiche les thém. et ss-thém. des deux années, et idéalement on les trie par année dans le filtre
- dans tous les cas, on les trie par ordre alphabétique, avec les "autres" à la fin, comme dans le formulaire

Décision sur l'affichage des filtres :

Filtre "Thématiques" -> grouper les thématiques par année
Filtre "Sous-thématiques" -> grouper les sous-thématiques par thématique et les trié par année (2024 en premier puis 2023)

**Comment by AdelineCelier** [comment]
Retour de Manon sur le sujet dans le ticket #1205.
A reprioriser donc. Toutefois on met pour l'instant de côté la question de trier les thématiques dans le menu quand il y a plusieurs années. Plus globalement, ce cas de plusieurs années sélectionnées dans le filtre "Période" du tableau étant vraiment rare, on peut essayer de le traiter rapidement si c'est possible.

**Comment by AdelineCelier** [comment]
@claire2212 cela me semble bon dans la version "minimale" qu'on avait identifié, à savoir : 
- on n'affiche que les thématiques de l'année en cours
- dans le cas d'une période à cheval sur 2 années, on affiche toutes les thématiques dans le menu déroulant, sans les trier. 

Ok pour toi si on remet le ticket dans le backlog pour la partie "tri des thématiques par année au sein du menu déroulant" ?
