### ISSUE TITLE
Besoin de faire apparaitre que les PNM font partie de l'OFB

### ISSUE THREAD

**Issue by manonolivier** [MTES-MCT/monitorenv#1135]
Deux solutions : 
- Mettre les unités PNM sous l'administration OFB (donc au même niveau que SD, Unité migrateurs, etc
- Ajouter "OFB" au niveau de Metabase après chaque PNM

==> Côté CACEM on préfèrerait la première option, ce serait logique par rapport à l'organisation AffMar (DDTM = DPM + Police de l'eau + Cultures marines + ULAM) mais dites-nous si ça va mettre le bazar côté stats ou si ça prend trop de temps à développer

**Comment by AdelineCelier** [comment]
@manonolivier @AlexiaLaunay 
Hello, si vous préférez l'option 1, c'est gérable par vous dans le backoffice (c'est pour ça que je taggue Alexia dans le ticket). 
Il faut juste voir avant avec Morgan et peut-être Vincent si ce changement d'administration de l'unité peut poser problème pour les stats, mais en tous cas pas besoin de développement.

**Comment by AlexiaLaunay** [comment]
@Morraff qu'en penses-tu ?

**Comment by Morraff** [comment]
@AdelineCelier @AlexiaLaunay @manonolivier Le changement a été effectué par Alexia et le changement est bien visible sur metabase. Cela a fonctionné comme prévu.
Comme discuté avec Adeline, on pourrait mettre en place un backoffice similaire pour les thématiques. Il s'agira toutefois de développer une procédure adéquate

**Comment by AdelineCelier** [comment]
J'ai noté la question du backoffice des thématiques dans le ticket #1160 et surtout dans le Miro de la roadmap Monitor. Je pense qu'on pourra l'aborder à partir du 2nd trimestre 2024. 
Ok pour vous si on ferme ce ticket ?
