### ISSUE TITLE
Ajouter des cases "régularisation administrative" et "sanction administrative"

### ISSUE THREAD

**Issue by manonolivier** [MTES-MCT/monitorenv#1136]
Un cas précis :
Constat d'un mouillage individuel avec corps-morts sans autorisation.
Une occupation sans titre peut faire l'objet d'une CGV mais pas forcément.
Parfois, l'administration préfère résoudre ça "à l'amiable" et régulariser. Elle fait un constat d'occupation sans titre et le transmet à la DDFIP qui va émettre un titre pour que la personne qui a occuper sans titre paie une redevance (le montant fixé est celui que la personne aurait payé si elle l'avait occupé légalement).

Même chose si on a une infraction dérangement de dauphins par un transporteur professionnel et on lui retire son permis de navigation.

Dans ces cas : Il y a une infraction et Pas de PV - Pas de Mise en demeure mais quand même une réponse donc ce n'est pas un simple rappel de réglementation.

(Par ailleurs pas de NATINF pour ça.)

**Comment by AdelineCelier** [comment]
Hello @manonolivier, je me rends compte que je n'ai pas répondu à ce ticket non plus. 
Si je comprends bien, pour une sanction administrative, il n'y a aucun PV qui est dressé ? Ou bien il y a un PV et la réponse n'est pas judiciaire mais administrative ?

Comme pour la question de la sensibilisation, je veux bien qu'on prenne un moment la semaine prochaine ensemble pour bien balayer les différents besoins et voir la manière la plus judicieuse de formaliser ça dans Env.

**Comment by manonolivier** [comment]
Salut @AdelineCelier,
Ca peut être suite à un PV que l'administration décide de mettre des sanctions administratives ou une régularisation mais pas forcément. Ca se fait souvent par l'édition de rapports administratifs par le contrôleur.

**Comment by AdelineCelier** [comment]
Pour résumer, on pourrait découper l'encart "infraction" comme suit :
- sanctions judiciaires
  - avec PV
  - sans PV
  - en attente
- sanctions administrations
  - sanction
  - régularisation 
  - en attente
- mise en demeure
  - oui
  - non
  - en attente
- tribunal compétent : en l'état il n'est pas du tout utilisé, et il n'est pas vraiment utile ni pour le CACEM ni pour les unités. Peut-être le retirer ?

A voir avec l'AU si ce point a des implications plus larges (côté RapportNav notamment), et s'il nécessite de creuser plus précisément le sujet des sanctions et suites. Il n'est pas urgent, on peut prendre le temps de creuser si on l'estime nécessaire.

**Comment by AdelineCelier** [comment]
**Update** : l'AU est ok pour faire ces premiers changements, on ira plus loin plus tard sur le sujet, une fois que les chantiers avec les procureurs sera plus avancé. Dans la même logique, on ne touche pas pour l'instant au champ "Tribunal compétent".

**Comment by AdelineCelier** [comment]
@maximeperraultdev, voilà un ex d'écran pour l'ajustement de l'encart d'infraction pour ajouter une différenciation entre sanction judiciaire et sanction admin : https://xd.adobe.com/view/c72c4b9f-8704-453c-9e85-c5a61bce1e6e-927f/screen/b61a3509-e1d8-41c1-9ce5-0362c1ac82e6/

**Comment by AdelineCelier** [comment]
@maximeperraultdev et @VincentAntoine, j'ai refait un point avec Manon, ce qui nous a permis de replacer le besoin : 

> Aujourd'hui il y a des services de DML qui remontent des infractions qu'elles traitent en mettant des sanctions/régularisations administratives sans forcément mettre de PV. Dans ce cas particulier, ces infos sont communiquées directement au CACEM, mais ce ne sera pas toujours le cas – donc l'info du nombre de sanctions/régularisations admin. faites ne sera pas exhaustif. Malgré tout, c'est un premier pas vers la récolte des suites données aux contrôles, et cela permet de commencer à valoriser ces données et à ne pas perdre de traces des retours de ces services administratifs.

En termes de choix d'infos, c'est effectivement plus logique de l'organiser ainsi : 

- Type d'infractions (on ne change pas cette section au final, désolée Maxime 😬)
  - Avec PV
  - Sans PV
  - En attente
  
- Réponses administratives
  - Sanction
  - Régularisation
  - En attente

- Mise en demeure
  - Oui
  - Non
  - En attente

**Comment by AdelineCelier** [comment]
@maximeperraultdev ça me semble bon, il faut juste rajouter les tags correspondants dans la carte du contrôle (colonne 2 de la mission), comme l'a rappelé avec sagacité Claire : 
- "x sanct. admin." 
- "x régul. admin."

**Comment by manonolivier** [comment]
@AdelineCelier @maximeperraultdev On a un petit problème, nous n'avons pas pensé à ajouter une case "pas de réponse admi" donc nous sommes obligés de remplir une "réponse admi" pour valider nos contrôles. je ne sais pas si je suis claire, n'hésitez pas à appeler le CACEM si besoin

**Comment by AdelineCelier** [comment]
Hiii zut en effet !! J'imagine qu'en attendant vous pouvez mettre "en attente" ?
On a 2 options possibles pour régler le souci : 
- soit on rajoute une option "aucune" dans "réponse admin"
- soit on fait en sorte que les champs de la section "réponse admin" ne soient pas bloquants. 
Qu'est-ce qui vous semble le mieux ?

**Comment by manonolivier** [comment]
@AdelineCelier le rendre non bloquant c'est pas mal (comme de toute manière la donnée ne sera pas hyper complète)

**Comment by maximeperraultdev** [comment]
@AdelineCelier @manonolivier ok, je repasse dessus et j'ajoute le tag en même temps. 👍

**Comment by maximeperraultdev** [comment]
@manonolivier Est-ce que c'est bloquant pour vous ? Voulez vous une mise en production aussi vite que possible (sinon ce sera livré la semaine prochaine) ?

**Comment by manonolivier** [comment]
@maximeperraultdev ça peut attendre une semaine, on récupérera les missions avec contrôle qu'on a fait entre temps

**Comment by manonolivier** [comment]
@AdelineCelier @maximeperraultdev vous y avez peut-être déjà pensé mais nous aurons besoin de décocher les cases "régularisation" "sanction" et "en attente" de la partie "réponse admin", pour l'instant ce n'est pas possible ni sur réponse admin ni pour PV et Mise en demeure

**Comment by AdelineCelier** [comment]
Les tags en plus dans la carte du contrôle sont bons. 

Reste à faire : ajouter une option "aucune" dans la section "réponse administrative" et la pré-cocher automatiquement.

**Comment by AdelineCelier** [comment]
@AlexiaLaunay les zones de la convention Marpol vont être ajoutées dans la prochaine mise en production. On se demandait : est-ce que tu sais si ces zones sont sujettes à des mises à jour de leurs tracés ou bien ce sont des zones fixes ?

**Comment by AdelineCelier** [comment]
C'est bonn !!
