### ISSUE TITLE
Pouvoir réinitialiser la zone même quand on ne l'a pas fermée.

### ISSUE THREAD

**Issue by manonolivier** [MTES-MCT/monitorenv#1137]
Pour l'instant on doit fermer la zone pour la réinitialiser / la supprimer si on se trompe. Ce n'est pas urgent mais est-ce que c'est possible de pouvoir réinitialiser sans la fermer.

**Comment by AdelineCelier** [comment]
Hello Manon, 
Quand tu dis "fermer", c'est bien fermer le polygone que tu es en train de tracer ?
Je ne sais pas si vous avez repéré, mais vous pouvez double-cliquer pour fermer automatiquement la zone...vu que c'est relativement rapide à faire, on se demande si ça vaut le coup de développer un truc spécifique, qu'en penses-tu ?

**Comment by manonolivier** [comment]
Oui c'est bien fermer le polygone.
C'est vrai qu'on peut double cliquer, c'est juste qu'on ne trouvait pas ça très intuitif de devoir créer une "fausse" zone pour créer la "vraie" zone.
Même chose si on commence à créer une zone (de surveillance ou de mission) et que finalement on ne veut plus la tracer, on doit créer la fausse zone, la valider puis la supprimer dans la fenêtre de la mission => pas très intuitif et rajoute des clics.

Encore une fois, ce n'est pas très important si ça demande un gros développement, on peut rester comme ça.
