### ISSUE TITLE
Signalements - bugs

### ISSUE THREAD

**Issue by manonolivier** [MTES-MCT/monitorenv#1138]
Pour Floriane : impossible de rattacher la mission à un signalement, le signalement n'apparaissait pas sur la carte. (peut-être un problème de connexion, c'est cata ce weekend).

Pour Manon : 
- Impossible de rattacher un signalement à une mission car les drapeaux des missions disparaissent quand on clique sur "rattacher à une mission" (que la mission soit clôturée ou non). Par contre, ça fonctionne à l'inverse, pour rattacher une mission à un signalement.

- Une fois le signalement lié à la mission, on peut ajouter un contrôle en le rattachant au signalement mais on ne peut pas rattacher le signalement à un contrôle déjà fait. Impossible de bouger ce curseur :
![image](https://github.com/MTES-MCT/monitorenv/assets/147587284/0e10716d-7ddc-4073-80fc-1f4c5f455f2e)
En soit, ce dernier point n'est pas grave vu que la plupart du temps le contrôle sera rentré dans MENV après le rattachement au signalement mais ça peut arriver qu'on enregistre le contrôle avant de rattacher le signalement (exemple d'aujourd'hui Floriane n'arrivait pas à rattacher la mission au signalement et a donc quand même rentré un contrôle dans la mission. Je suis arrivée après et j'ai réussi à lier le signalement, j'aurais bien voulu ne pas avoir à refaire un nouveau contrôle.)

- Quand on ajoute un contrôle lié à un signalement, on doit mettre un point de contrôle, ce serait pas mal d'avoir la possibilité de lier le contrôle au point de signalement (risque de poser problème par contre quand le signalement est une zone ? C'est pour ça qu'on ne l'a pas fait ?)
- Dans la même idée, ce serait possible de rentrer directement les informations de la cible du signalement dans la cible du contrôle ?

Je ne sais pas si c'est très clair. A dispo pour vous montrer / en discuter

**Comment by AdelineCelier** [comment]
Hello @manonolivier 

Je suis passée voir Floriane, on a refait des tests ensemble et on n'a pas réussi à reproduire les problèmes que vous avez rencontré. Je viens de refaire des tests de mon côté, idem je n'arrive pas à reproduire. On a convenu que si vous rencontrez à nouveau des problèmes, il ne faut pas hésiter à nous appeler direct, Claire ou moi (si c'est en HO ^^). 
On peut aussi s'appeler à ton retour de congés si tu repenses à des points qui peuvent nous aider à avancer ! 

Juste pour rappel de quelques points qui peuvent être utiles à l'équipe, au cas où les problèmes étaient liés à ça (même si d'après ce que tu décris dans le ticket Manon j'ai l'impression que tu avais fait gaffe à la plupart des points) :

- tant qu'on n'a pas l'enregistrement automatique des missions et des signalements, il faut bien veiller à **enregistrer le signalement ou la mission sitôt qu'on a fait une modification dedans** avant de procéder à des rattachements. Sinon il y a des risques que des choses soient enregistrées d'un côté et pas de l'autre, et que le système de rattachement fonctionne mal. A noter que normalement il n'y a pas de risque de perte de données. 
- pour rappel, pour qu'un signalement apparaisse bien sur la carte lors d'un rattachement à une mission, il faut qu'il ne soit pas archivé et que le bouton "nécessite un contrôle" en fin de formulaire soit bien activé. 
- idem pour le rattachement côté signalement, pour qu'une mission apparaisse sur la carte, il faut qu'elle soit **en cours**.
- pour rattacher un signalement à un contrôle via le contrôle, il faut bien que le signalement ait été **rattaché à la mission au préalable**, on ne peut pas rattacher un signalement direct depuis un contrôle. 

Concernant le pré-remplissage du contrôle avec les infos du signalement rattaché, j'ai créé le ticket #1146 car ce n'est pas le même sujet.

**Comment by manonolivier** [comment]
J'ai fait plein de tests ce matin

Pour le problème de lier à une mission existante : 
Au début :
- J'ouvre le signalement sur la fenêtre SIG (signalement en cours pas archivé et qui nécessite un contrôle). Je clique sur "lier le signalement à une mission". Les drapeaux des missions restent bien sur le SIG. Je clique sur le drapeau de la mission que je veux lier au signalement (mission en cours, ouverte pas clôturée). Ca ne fonctionne pas, rien ne se passe.
- Par contre, ça fonctionne quand j'ouvre le signalement dans la fenêtre "vue détaillée des signalements".
Mais maintenant tout fonctionne directement. On va croiser les doigts pour que ça ne recommence pas mais je laisse quand même une trace de ce qui s'est passé pour qu'on puisse revenir dessus si jamais ça se reproduit.
Pour info : avec mes tests de rattachement de signalements, ça a du faire bugger l'interface :
![image](https://github.com/MTES-MCT/monitorenv/assets/147587284/e35ae597-20ec-4462-99dc-9f730de222c2)
tous les boutons du tour de l'écran ont disparu. Pour qu'ils réapparaissent, j'ai juste eu à fermer la fenêtre "vue détaillée" des signalements et missions.

- Si on ouvre le signalement sur le SIG et qu'on clique sur "créer une mission pour ce signalement" rien ne se passe si la fenêtre "vue détaillée des missions" n'est pas ouverte avant. C'est à dire que je clique sur "créer une mission pour ce signalement", l'encart du signalement se ferme et rien ne se passe. Si j'ouvre la vue détaillée des missions après avoir cliqué sur créer une mission pour ce signalement ça ne fonctionne pas non plus. Par contre, ça fonctionne bien quand la vue détaillée des missions est au préalablement ouverte.

- Pour le problème de rattacher un signalement lié à une mission à un contrôle déjà fait : ça fonctionne aujourd'hui on peut en effet bouger le curseur "le contrôle est rattaché à un signalement" donc parfait

**Comment by claire2212** [comment]
Hello @manonolivier j'ai essayé de reproduire le problème quand on clique sur "créer une mission pour ce signalement" mais impossible.
Je viens a Etel la semaine prochaine (mardi 13 et mercredi 14), on pourra regarder ensemble si ça te va, tu me montreras directement sur ton poste.

**Comment by manonolivier** [comment]
Salut @claire2212, yes pas de soucis
Je ne suis pas là mardi 13 par contre et le 14 je commence vers 13/14h

**Comment by claire2212** [comment]
Salut @manonolivier , je viens de reproduire le souci d'ouverture d'une mission depuis un signalement ( ce qu'on a vu ensemble mercredi). 

Est-ce que tu peux re-tester et regarder si tu vois le même bandeau que dans la capture "Firefox a empêché ce site d'ouvrir une fenêtre pop-up". Si c'est le cas, tu peux cliquer sur "Autoriser les pop-up". 
Ca va t'ouvrir la fenêtre secondaire (mais avec la carte), tu la fermes tu re-testes l'ouverture depuis un signalement  et normalement ca devrait être bon!

Tiens moi au courant

<img width="1511" alt="Capture d’écran 2024-02-16 à 09 48 22" src="https://github.com/MTES-MCT/monitorenv/assets/23258718/2ad4eed0-1522-4916-96b6-c44b8665a6c0">

**Comment by manonolivier** [comment]
C'est bon ça fonctionne, merci @claire2212

**Comment by claire2212** [comment]
@manonolivier je clôture ce ticket dans ce cas.
