### ISSUE TITLE
Signalements – Pré-remplir le contrôle avec les coordonnées du signalement rattaché ?

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorenv#1146]
Reprise du commentaire de @manonolivier dans le ticket #1138.

On a retesté avec @claire2212 , quand on crée un contrôle à partir d'un signalement dans une mission, les champs suivants sont pré-remplis (s'ils ont bien été saisis dans le signalement bien sûr) : 
- thématique
- sous-thématique
- type de cible
Je me rends compte qu'on n'avait pas mentionné ce point-là dans la présentation qu'on vous a faite de la fonctionnalité fin 2023. J'ai mis à jour le document, n'hésitez surtout pas à aller le re-consulter quand vous avez un doute, il est fait pour ça ;)

On avait délibérément évité le remplissage auto du point de contrôle à partir du point de signalement en se disant que la cible peut bouger et donc ne pas être au même endroit au moment du contrôle. 
Et de plus il y a en effet le cas de la zone : on pourrait dire qu'on prend par défaut le centre de la zone pour le point de contrôle, mais ça ne me semble pas vraiment gage de précision. 

Perso j'ai l'impression qu'il y a un petit risque à automatiser ce remplissage du point de contrôle, mais dites-moi si vous n'êtes pas d'accord. 
Et est-ce que vous pouvez retester de votre côté le pré-remplissage des autres infos et nous dire si ça fonctionne bien ?

**Comment by manonolivier** [comment]
@AdelineCelier @claire2212 

Les thématiques et type de cible se remplissent bien automatiquement.

La grande majorité des signalements seront contrôlés au même endroit mais j'en parle lors de notre point hebdo pour voir ce que les autres en pensent et je reviens vers vous.

Je pensais à un truc sur le pré remplissage (désolée s'il fallait plutôt le dire dans un autre ticket vu que ce n'est pas lié à la position) : est-ce que c'est possible de pouvoir également remplir automatiquement l'identité de la cible ?
Je pense surtout aux moments où ça va être le rush cet été avec les mouillages med. Il faut qu'on remplisse : NOM - IMMATRICULATION - TAILLE ça va être chronophage de devoir tout remplir de nouveau dans le contrôle alors qu'on l'a déjà rempli dans le signalement.
Le fait de devoir remplir à nouveau des informations est également une source d'erreur, je pense qu'il y aura quelques incohérences entre les infos du contrôle et les infos du signalement.
La fiche "détails de la cible en infraction" dans la mission se ferme à chaque fois qu'on va sur l'action de signalement, ça rajoute des clics en plus à faire. 
==> Si c'est trop complexe à mettre en place, une solution serait d'afficher la fiche signalement sur le SIG et faire un copier coller manuel directement sur la fiche mission. Mais si c'était possible d'automatiser, on gagnerait un temps et une qualité précieuse.

**Comment by claire2212** [comment]
Salut @Manon, on peut tout à fait pré-remplir une infraction avec les infos : NOM - IMMATRICULATION - TAILLE. J'ai juste une question sur la taille : 
- Côté signalement le champ "taille" est un champ de type nombre, c'est à dire que vous renseignez à la main la taille (ex: 12, 24, ...)
- Côté mission  le champ "taille" est un sélecteur dans lequel vous choisissez une fourchette de taille (de 12 à 24m, moins de 12m, ...)

Est-ce que vous souhaitez : 
- qu'on garde ça comme ça et suivant la taille saisie dans le signalement je calcule la taille correspondant côté formulaire d'infraction (ex: 17mètres renseignés dans le signalement = de12 à 24m dans le formulaire d'infraction)
- Qu'on harmonise en gardant la solution du sélecteur de fourchette (de 12 à 24m, moins de 12m, ...)
- Qu'on harmonise en gardant la solution du champ de type nombre pou rune saisie manuelle (ex: 12, 24, ...)

**Comment by AdelineCelier** [comment]
Comme discuté ensemble à l'instant @claire2212, ce ticket est bon on peut le passer.
En revanche on s'est rendu compte que le fait que les champs des infos de cibles ne soit pas iso entre les signalements et les actions dans les missions peut prêter à confusion et qu'il vaudrait mieux les aligner. 
J'ouvre un nouveau ticket sur le sujet pour demander son avis au CACEM.

**Comment by manonolivier** [comment]
@AdelineCelier Revu en point hebdo le 23/10 avec Pierre et Alice. Nous préférons que ce soit rentré automatiquement car le lieu du signalement est quasi tout le temps le lieu du contrôle et ça permet d'éviter les erreurs.
Pour éviter d'oublier de modifier le point de contrôle quand il le faut, est-il possible de mettre une sorte de warning "position rentrée automatiquement" qui servirait de rappel au cas où il faut modifier le point

**Comment by AdelineCelier** [comment]
Hello @manonolivier, avec un peu de retard : ok je remets ce ticket dans "à développer". 
Je vais regarder pour l'ajout d'un petit encart. Il pourrait concerner toutes les infos pré-remplies automatiquement dans l'infraction à partir du signalement, pas seulement la position.

**Comment by AdelineCelier** [comment]
@claire2212 bon au final je pense que le plus simple est de mettre un encart bleu sous le point de contrôle quand celui-ci a automatiquement été calculé à partir de la position du signalement. L'encart disparaît si l'utilisateur supprime ou change la position du point de contrôle.

[Écran ici.](https://xd.adobe.com/view/eabe87d5-464f-4ff2-b804-04a365edc03b-bfed/screen/d2724145-8ba2-45fd-b754-b06b4eaad4e5/)

**Comment by AdelineCelier** [comment]
all good
