### ISSUE TITLE
Missions - Affichage de la date de création et MAJ de la mission dans le bandeau du bas

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorenv#1159]

**Comment by AdelineCelier** [comment]
Changements à prendre en compte dans le bandeau du bas : 
- ajouter un tag "enregistrement auto actif" et "enregistrement auto inactif"' :   
  - il est actif tant que la mission n'est pas clôturée : seuls les boutons "clôturer" et "fermer" apparaissent
  - il est inactif à partir du moment où la mission a été clôturée : le bouton "enregistrer" réapparaît en plus des 2 autres
- ajouter une phrase au milieu du bandeau : "Mission créée par [le CNSP / le CACEM], [aujourd'hui / hier / le...]  à [heure]. Dernière modification enregistrée à [heure]."

Écrans XD : https://xd.adobe.com/view/711de02d-169e-4c47-a6b8-7317c12293ef-244e/

**Comment by AdelineCelier** [comment]
@claire2212 all good, il manque juste l'apostrophe entre "aujourd" et "hui" dans le bandeau du bas ;)
