### ISSUE TITLE
[AMP] Affichage du volet résumé

### ISSUE THREAD

**Issue by thoomasbro** [MTES-MCT/monitorenv#1164]
Infos à ajouter dans le résumé des zones AMP : 
- Nature d'AMP : à récupérer dans la couche de l'OFB, champ 'des_desigf'
- Résumé Légicem : champ qui doit être alimenté par Alexia, comme pour le résumé reg. Voir avec elle pour la création de ce champ.

Écran XD ici : https://xd.adobe.com/view/9261c7a1-c1d2-4aed-9641-88a3854580c9-c732/screen/40740820-7649-433d-b55d-b378c2a9e835

**Comment by AdelineCelier** [comment]
En l'état c'est bon pour moi, à voir avec Alexia si elle n'a pas de difficulté à ajouter les url, mais j'imagine que ça devrait être bon. On rouvrira un ticket si besoin.
