### ISSUE TITLE
[Zones Administratives] Revoir le style des couches

### ISSUE THREAD

**Issue by thoomasbro** [MTES-MCT/monitorenv#1165]
Propositions à faire valider par le CACEM
- [ ] Ajouter des noms sur les limites transversales de mer et les limites de salure des eaux
- [ ] Ajouter le nom sur les départements
- [ ] Retirer les départements non littoraux

**Comment by AdelineCelier** [comment]
Je note aussi un ptit point UI : retirer le petit espace en trop tout en bas de la liste des zones administratives
![image](https://github.com/MTES-MCT/monitorenv/assets/71878648/13f371de-c4c8-425f-a6fb-52f62102d640)

**Comment by AdelineCelier** [comment]
@manonolivier voilà le ticket, pour rappel les questions :
- garde-t-on ou retire-t-on les départements non littoraux ?
- souhaitez-vous le nom des départements ?
- souhaitez-vous les noms des limites de salure des eaux et des limites transversales de mer ?
- d'autres remarques/demandes sur ces nouvelles zones admin (noms, mise en forme, délimitations...)

Merci pour vos retours, à toute :)

**Comment by AdelineCelier** [comment]
@thoomasbro récap des retours du CACEM : 
- gardre les départements non littoraux
- ajouter le nom des départements
- mettre les départements en filaire, pas de fond
- rendre les tracés plus lisibles en utilisant des couleurs plus fortes. 

Pour le dernier point, pas facile de proposer quelque chose sans pouvoir tester sur les tracés direct. 
Thomas est-ce qu'on peut s'appeler pour faire des tests en live quand tu abordes ce ticket ? 
Voilà ce que j'imagine, mais à confirmer en testant : 
  - Zones FAO/CIEM et zones AEM : on peut les laisser telles quelles pour l'instant, car en plus elles changent de couleur selon si elles sont sur fond clair ou fond foncé, c'est pas mal
  - Limites transversales de mer et limites de salure des eaux : les mettre en Maximum Red (#E1000F) et doubler leur épaisseur
  -  3 milles, 6 milles, 12 milles, zones ZEE, laisses des basses eaux, ligne de base droite, départements : on les met toutes à la même épaisseur (se baser sur l'épaisseur actuelle des 3-6-12) et on les met toutes de la même couleur que les Zones FAO/CIEM. Dans l'idéal, est-ce que ce serait possible de changer aussi leur couleur quand elles sont sur fond foncé ?
  - Eaux territoriales : on les met de la même couleur que les zones FAO/CIEM (avec idem le changement de couleur sur fond foncé) + la même couleur de fond en opacité 25%.

**Comment by AdelineCelier** [comment]
@thoomasbro il reste juste deux points pour moi (non bloquants pour la mep de demain) : 
- passer les laisses de basses eaux et la ligne de base droite dans le même bleu que les autres zones admin (en #767AB2 donc)
- est-ce qu'il serait possible aussi de passer le nom des départements dans ce même bleu ? En le testant là, je trouve qu'on a du mal à les distinguer des noms des villes qui sont sur le fond de carte
