### ISSUE TITLE
[Mission] - Garder ouverts les formulaires d'actions (et infractions) pendant la navigation

### ISSUE THREAD

**Issue by claire2212** [MTES-MCT/monitorenv#1187]
Lorsqu'on est sur une mission, avec un formulaire d'action ouvert (ex: contrôle avec infraction) celui se ferme dès qu'on navigue vers la liste de missions ou une autre page.

Ce qu'on veut : 
- Garder ouvert le dernier formulaire d'action ouvert
- Garder le formulaire d'infraction ouvert tant que l'utilisateur n'a pas cliqué sur "Valider l'infraction"

**Comment by AdelineCelier** [comment]
Hello @maximeperraultdev je vois plusieurs bugs.

**Premier essai** : j'ouvre un contrôle dans une mission, je bascule sur la vue liste et quand je reviens non seulement le formulaire est fermé mais le contrôle a disparu. J'avais d'abord rien saisi, puis j'ai recommencé en saisissant juste un trigramme, puis en saisissant une thématique et mon trigramme...à chaque fois le contrôle a disparu.

**Deuxième essai** : je saisis les champs thématique et sous-thématique, la date et le lieu + mon trigramme. Là le contrôle ne se ferme pas, en revanche quand je reviens sur le formulaire, les 2 dernières lettres du trigramme ont disparu.
