### ISSUE TITLE
Mission conjointe ME/MF - bugs du message d'avertissement

### ISSUE THREAD

**Issue by manonolivier** [MTES-MCT/monitorenv#1192]
![image](https://github.com/MTES-MCT/monitorenv/assets/147587284/85ca58fd-3624-48e4-94c2-4e4e51d5049b)

![image](https://github.com/MTES-MCT/monitorenv/assets/147587284/efb454d9-4713-4275-8866-dd2ba693798d)

Ca me met que le CNSP a déjà une mission en cours pour cette unité mais c'est faux, il y en a une le 6 qui est clôturée et une le 8 donc pas de mission ouverte par le CNSP le 07.
Autre problème, pour faire les screen, j'ai rouvert une mission (je n'ai pas rempli tous les champs donc elle n'apparait pas dans la liste) et ça me dit qu'une mission est ouverte par le CNSP mais pas par le CACEM (alors que pour le coup, il y en a bien une d'ouverte par le CACEM avec la même unité et le même jour.

Je crois que j'avais déjà fait un ticket là dessus mais je ne le retrouve pas donc désolée d'avance si vous m'aviez déjà répondu..

**Comment by AdelineCelier** [comment]
Vu avec Manon et Claire, on ne reproduit pas. Je clôture le ticket
