### ISSUE TITLE
Tri signalements ne fonctionne pas

### ISSUE THREAD

**Issue by manonolivier** [MTES-MCT/monitorenv#1206]
Au début c'est comme ça : 
![image](https://github.com/MTES-MCT/monitorenv/assets/147587284/579caeef-5569-4c7a-8b44-bb24df17dd07)

Et si je clique sur "Thématique" pour normalement les trier par ordre alphabétique, on peut voir que ça ne trie pas par thématique et je ne comprends pas l''ordre choisi : 
![image](https://github.com/MTES-MCT/monitorenv/assets/147587284/da0d2240-df2c-419b-8b89-3bb3bc0efba1)

**Comment by AdelineCelier** [comment]
@claire2212 il y a en effet encore un problème avec le tri alphabétique de la colonne des thématiques. 
L'ordre anté-alphabétique fonctionnze, mais pas l'ordre alphabétique :  
![image](https://github.com/MTES-MCT/monitorenv/assets/71878648/10cf387d-0fd3-4fc2-b88f-723da94af36f)

**Comment by AdelineCelier** [comment]
c'est bon, ça fonctionne cette fois !
