### ISSUE TITLE
pouvoir cliquer sur la mission qui a été effectuée suite au signalement directement depuis la fenetre signalement

### ISSUE THREAD

**Issue by manonolivier** [MTES-MCT/monitorenv#1208]
On ne peut pas cliquer sur le contrôle fait pour ouvrir la mission, ce serait pratique : 

![image](https://github.com/MTES-MCT/monitorenv/assets/147587284/b4ceea2b-1f6d-4986-a609-ed1262a0f8c9)

**Comment by AdelineCelier** [comment]
Hello @manonolivier, en effet ce serait pas mal ! Claire va le faire.
