### ISSUE TITLE
Points d'intérêt – Amélioration de la fonctionnalité

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorenv#1214]
**Après discussion avec le CACEM, il se trouve que la fonctionnalité est très utilisée comme post-it/pense-bête à tout faire.** 
Exemples d'usages donnés : 
- l'unité donne les coordonnées d'une cible et demande au CACEM de vérifier dans quelle zone elle est et si elle est en infraction ou non. 
- l'utilisateur CACEM rentre un point d'intérêt rapidement, qu'il transformera ensuite en signalement (=> cela rejoint ce qu'avait dessiné Guillaume, sur des tracés de points et de zones à la volée, qui peuvent ensuite être transformés en signalements, zones d'intérêt, etc.) 
- l'unité décrit la cinématique qu'elle aura pour sa prochaine mission, l'utilisateur CACEM dispose différents points d'intérêt pour s'en rappeler et préparer un brief pour l'unité

**Plusieurs points d'amélioration possibles de la fonctionnalité :** 

_Quick wins_
- [x] Retirer les types de points, qui ne sont pas utilisés par le CACEM 👍🏻 
- [x] Changer la couleur des points sur la carte, pour qu'ils soient plus lisibles (cf. ticket [751](https://github.com/MTES-MCT/monitorenv/issues/751) du CACEM) - cf [cet écran](https://xd.adobe.com/view/9261c7a1-c1d2-4aed-9641-88a3854580c9-c732/screen/89670a68-a3df-4bbf-81f9-c6e4ff3148de/)
   - couleur de la tête de l'épingle : Chinese Red, #A13112 👍🏻 
!(https://github.com/MTES-MCT/monitorenv/assets/71878648/eab63095-b683-409b-ab05-9e9f1e6c4feb)
   - couleur de la pointe de l'épingle : Charcoal, #3B4559 👍🏻 
   - mettre un contour extérieur de 1 px en Light Gray, #CCCFD6, afin que l'icône ressorte bien sur d'autres fonds de couleur (à voir s'il ne faudrait pas le systématiser pour tous les objets de la carte, je pense aux sémaphores par ex) 👍🏻 
   - voilà le svg de l'icône si besoin (il faut prendre la version large, 26x26 px) : 
![Pin_26x26](https://github.com/MTES-MCT/monitorenv/assets/71878648/1a6482a2-ac78-4656-a909-47bd0b96555b)

- [x] Pouvoir masquer/afficher tous les points d'intérêt (cf. ticket [745](https://github.com/MTES-MCT/monitorenv/issues/745) du CACEM) - cf [ce même écran](https://xd.adobe.com/view/9261c7a1-c1d2-4aed-9641-88a3854580c9-c732/screen/89670a68-a3df-4bbf-81f9-c6e4ff3148de/) 👍🏻 

_Dans un second temps si complexe_
- [ ] Créer un signalement à partir d'un point d'intérêt (à dessiner)

**Comment by AdelineCelier** [comment]
@maximeperraultdev les points cochés du ticket sont bons, en revanche je viens juste de remarquer un truc (qui n'est pas forcément bloquant pour la mep) : 
- quand j'ai créé un point et que je l'édite, ça ouvre le menu des points d'intérêts avec les infos du point remplies (normal)
![image](https://github.com/MTES-MCT/monitorenv/assets/71878648/a5fae0c5-4afa-4e8b-a7b2-1886ec6391b5)

- mais quand je supprime le point (via l'icône sur la pop-up du point d'intérêt), le point s'efface bien, mais le menu reste affiché, avec encore les infos du point supprimé dedans. Possible de fermer le menu à la suppression du point ?
![image](https://github.com/MTES-MCT/monitorenv/assets/71878648/bd290088-e093-4005-966d-756e06a774b2)

**Comment by maximeperraultdev** [comment]
@AdelineCelier ça marche je repasse dessus

**Comment by AdelineCelier** [comment]
- retirer le zoom à la création du point
- refaire une passe sur la fermeture des menus de droite : le menu missions et contrôles ne se ferme pas quand on clique sur un autre menu. 
- quand on ouvre le menu des points alors qu'ils sont masqués, ça les réaffiche automatiquement (œil par défaut)
- vérifier que quand les points sont masqués, on n'a jamais accès au pointeur
- quand on est en mode édition d'un point, le wording du bouton pour "enregistrer"

**Comment by AdelineCelier** [comment]
C'est good !
