### ISSUE TITLE
Missions – Problème marge entre thématique et sous-thématique

### ISSUE THREAD

**Issue by manonolivier** [MTES-MCT/monitorenv#1225]
![image](https://github.com/MTES-MCT/monitorenv/assets/147587284/c4a7229f-3028-4a9a-9ecc-8bd789529789)

Beaucoup d'écart entre thématique et sous-thématique pour surveillance et aussi contrôle

J'ai l'impression que ce n'était pas comme ça avant la mise en prod (celle avec les nouveaux icônes de missions) mais je me trompe peut-être.

**Comment by AdelineCelier** [comment]
Ah oui en effet il y a un petit couac visuel, je le bascule de notre côté ! 
Normalement l'espacement entre les deux champs doit être de 4 px (@claire2212 mea culpa je me rends compte que tous les écrans du XD ne sont pas à jour)

**Comment by AdelineCelier** [comment]
C'est bon, tout beau tout propre
