### ISSUE TITLE
[Mission] amélioration de la gestion de la suppression des missions

### ISSUE THREAD

**Issue by thoomasbro** [MTES-MCT/monitorenv#1227]
- [x] canDeleteMission doit renvoyer false si MonitorFish ne répond pas
- [x] Fix de l'url de connexion à MF en prod (https au lieu de http)
- [x] ne pas mettre en cache la requête canDeleteMission

**Comment by AdelineCelier** [comment]
@claire2212 je ne suis pas sure de pouvoir vérifier par moi-même les différents points ci-dessus, en tous cas le blocage de la suppression fonctionne bien. 
Est-ce que ce serait possible de faire des mini retouches sur la pop-up ?
- changer le titre de la pop-up qui apparaît et mettre "suppression impossible" au lieu de "supprimer la mission" ? Cela sera plus cohérent avec les autres pop-ups, du type "enregistrement impossible". 
- revoir l'espacement entre le bloc de texte et le bouton "fermer" : 32 px au lieu de 48 (ceci est valable pour toutes les pop-ups de ce type).
