### ISSUE TITLE
Synchro missions – Revoir le fonctionnement des zones de mission

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorenv#1228]
Décisions prises résumées ci-dessous (cf. présentation plus complète dans le [Miro ](https://miro.com/app/board/uXjVNY_Ur84=/)de la synchro des missions)
![image](https://github.com/MTES-MCT/monitorenv/assets/71878648/d944da02-3338-4079-bf81-ded9af612c45)

### A faire côté Env

- [x] Ne plus rendre obligatoire la zone de mission 👍🏻 
- [x] Rendre la zone de surveillance obligatoire à l'ouverture d'une surveillance. 👍🏻 
- [x] Retirer la case à cocher "zone de surveillance équivalente à la zone de mission" 👍🏻 
- [x] Si aucune zone de mission n'est rentrée, calculer automatiquement la zone de mission à partir de la localisation de la dernière action dans la chronologie de la mission (toutes actions confondues, CACEM et CNSP). Au clic sur la mission, cela s'afficherait comme sur [cet écran](https://xd.adobe.com/view/06d04fac-8722-43f0-b5d5-90601b20697e-5383/screen/45c48110-a991-4918-a1f7-18a06a4b63da), avec des cercles de 80 px de diamètre autour de chaque contrôle pour bien les faire ressortir. 
- [x] Reformuler le bouton d'ajout de zone de mission : `Ajouter une zone de mission manuelle` 👍🏻 
- [x] Lorsqu'il n'y a pas de zone manuelle saisie, afficher un encart en-dessous du bouton qui indique : "Actuellement, la zone de mission est automatiquement calculée selon le point ou la zone de la dernière action rapportée par l'unité." (cf. [cet écran](https://xd.adobe.com/view/bcb50441-8561-431e-9ce7-1a78965b60e4-e9e6/screen/85da77f3-57a9-44b1-a1cd-04171afe7969))
- [x] Lorsqu'il y a une zone manuelle saisie, cela s'affiche comme aujourd'hui, cf. [cet écran](https://xd.adobe.com/view/06d04fac-8722-43f0-b5d5-90601b20697e-5383/screen/febb08a5-a49a-4eca-a0e3-af59e81819c7). 👍🏻 
- [x] Faire une migration des zones de missions utilisées comme surveillances vers les géométries de surveillance

**Comment by AdelineCelier** [comment]
@claire2212 problèmes repérés : 
- quand tu crées une mission à partir d'un signalement, l'encart bleu "actuellement, la zone de mission est automatiquement calculée..." apparaît, alors qu'il n'y a pas d'action dans la mission à part le signalement
- quand je trace une zone de surveillance et que je la réinitialise, la réinitialisation n'est pas prise en comte pour la zone de mission : il y a donc la 1ère zone qui a été tracée qui sert de zone de mission, puis la 2è zone tracée qui sert de zone de surveillance. 
![image](https://github.com/MTES-MCT/monitorenv/assets/71878648/236cf13b-3ae9-4ebb-ae7a-0ede79c50da5)
![image](https://github.com/MTES-MCT/monitorenv/assets/71878648/3082d02a-602e-4623-9a33-09fb488f1b26)
- le cercle de zone de mission créé automatiquement autour des contrôles me semble vraiment gros, possible de le réduire d'env. 25% ? je vais demander à Loup de faire pareil côté Fish. 
- il y a encore des cas où la zone de mission devient noire par moments, là en l'occurrence c'est quand je passe la souris dans l'intersection des 2 zones
![image](https://github.com/MTES-MCT/monitorenv/assets/71878648/b547eb3f-e7c7-43e2-bab1-c198e1d814de)

**Comment by claire2212** [comment]
@AdelineCelier pour ce point : 
`quand je trace une zone de surveillance et que je la réinitialise, la réinitialisation n'est pas prise en comte pour la zone de mission : il y a donc la 1ère zone qui a été tracée qui sert de zone de mission, puis la 2è zone tracée qui sert de zone de surveillance.` 

Je viens de tester en inté et ca fonctionne normalement. J'ai créé une mission, j'ai ajouté une surveillance avec une zone. La zone de mission est bien à jour. Je supprime la zone de surveillance. Je n'ai plus de zone de mission. Je remets une nouvelle zone de surveillance, ma zone de mission est bien la même que ma zone de surveillance

**Comment by AdelineCelier** [comment]
Reste à faire 
- retirer les signalements à prendre en compte pour le calcul de la zone
- encore des problèmes de zones noires 😬
