### ISSUE TITLE
Rapportage - Règles de validation

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorenv#124]
**Champs bloquants au 1er enregistrement de la mission**
- Type de mission
- Intentions principales de mission
- Administration
- Unité
- Contact de l'unité
- Zone de mission
- Ouvert par
Cf. [écran 8 du XD](https://xd.adobe.com/view/973ae2b4-ecd1-419f-b092-8545e0d8ce57-c269/screen/3fd7f68b-873e-40b8-9639-5710d4cdb80c)

**Champs bloquants à la validation d'un contrôle en infraction**
- NATINF, que l'infraction soit avec ou sans PV (ce point est lié au ticket [185](https://github.com/MTES-MCT/monitorenv/issues/185))
Cf. [écran 24 du XD](https://xd.adobe.com/view/973ae2b4-ecd1-419f-b092-8545e0d8ce57-c269/screen/01549022-c0ce-4f35-a4d7-6d3c0e92dfbb/)

**Champs bloquants à la clôture de la mission pour les contrôles**
- thématique de contrôle
- sous-thématique de contrôle
- si "divers" ou "autre" dans les thématiques/sous-thématiques, champ de description (cf. ticket [182](https://github.com/MTES-MCT/monitorenv/issues/182))
- point de contrôle
Cf. écrans [29](https://xd.adobe.com/view/973ae2b4-ecd1-419f-b092-8545e0d8ce57-c269/screen/4152c4b8-c623-4e64-b191-0ae6fe117996/) à [31](https://xd.adobe.com/view/973ae2b4-ecd1-419f-b092-8545e0d8ce57-c269/screen/98cdabd1-144e-40f8-81d2-2343a9390c5b).
- Clôturé par

**Champs bloquants à la clôture de la mission pour les surveillances**
- thématique de surveillance
- sous-thématique de surveillance
- durée de la surveillance (soit remplir les champs, soit cocher la case, cf. ticket [205](https://github.com/MTES-MCT/monitorenv/issues/205))
- zone de la surveillance (soit un tracé, soit cocher la case)
Cf. écrans [35](https://xd.adobe.com/view/973ae2b4-ecd1-419f-b092-8545e0d8ce57-c269/screen/bfdc1624-d032-4ae3-a7f8-2c288454ff08) à [37](https://xd.adobe.com/view/973ae2b4-ecd1-419f-b092-8545e0d8ce57-c269/screen/f43e5b52-d40d-443a-b5ff-8102d0d6dabc).

**Comment by AdelineCelier** [comment]
@thoomasbro le CACEM m'a fait justement remarquer que je n'avais pas mis en bloquant le champ "clôturé par" pour valider la clôture de la mission. Je viens de le rajouter dans la liste.

**Comment by AdelineCelier** [comment]
@thoomasbro je me rends compte que j'avais noté un commentaire sur les champs bloquants dans un ticket qui n'avait rien à voir, je sais pas ce qui s'est passé. Je le reporte ici : 

> j'ai oublié de reporter un point abordé pendant la réunion CACEM de vendredi dernier : ils souhaiteraient que le champ NATINF soit bloquant même si c'est "Sans PV" qui est coché ! En gros dès qu'il y a eu infraction, il faut y associer un NATINF, qu'il y ait eu PV ou non. Le seul cas où le NATINF ne serait pas bloquant serait si le type d'infraction est "en attente". Et dans ce cas d'ailleurs ce serait intéressant de remonter un tag dans la colonne "alerte" de la vue liste des missions, disant qu'il y a une infraction à compléter.

**Comment by AdelineCelier** [comment]
@thoomasbro 
Le gros point bloquant que je vois à régler avant la MEP c'est que quand je clique sur "enregistrer et clôturer" sans avoir rempli tous les champs de mon contrôle, ça fait disparaitre le bouton pour ajouter un point de contrôle (cf. capture ci-dessous)
![image](https://user-images.githubusercontent.com/71878648/233685934-60fb87fb-ad71-4b2a-98fa-c6db994b741c.png)

Sinon mes autres retours : 
- je ne suis pas sure que les phrases "veuillez..." (cf. ci-dessous) soient nécessaires. Tu penses qu'il faut cette mention en plus des cadres rouges ? 
![image](https://user-images.githubusercontent.com/71878648/233686206-1e28f0f9-3088-4244-9130-1241f1248b33.png)
- la mention "requis" sous les date picker, c'est parce que tu ne peux pas facilement mettre le cadre du date picker en rouge ?

**Comment by TEAMCACEM** [comment]
@AdelineCelier @claire2212 Bonjour à vous deux, il y a un problème pour la règle de validation à la clôture concernant les thématiques de contrôle. Chez moi c'est bloquant mais chez Christophe et Alexia par exemple ça ne l'est pas. On a donc quelques contrôles et surveillance sans thématique (et les missions datent d'il n'y a pas longtemps par exemple une en octobre) je les corrige tant qu'il n'y en a pas beaucoup

**Comment by AdelineCelier** [comment]
Ok merci beaucoup de cette remontée. On va creuser le plus rapidement possible le problème. 
Et à terme on va mettre en place des tests sur cette question des champs bloquants, pour essayer d'éviter au max ces nouveaux problèmes 😬

**Comment by claire2212** [comment]
Hello @TEAMCACEM , j'ai bien identifié le souci. C'est en cours de correction, j'ai également ajouté des tests sur les champs obligatoires en cas de clôture. Ce sera réglé à la prochaine mise en prod.
Pour ce problème il n'y a malheureusement pas vraiment moyen de le contourner d'ici la prochaine mise en prod. Un grand sage a dit: "Seule la vigilance est importante"  ;-)
