### ISSUE TITLE
Synchro missions – Divers ajustements côté Env

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorenv#1241]
### Sur les champs bloquants

- [x] Le champ "Contact" ne doit plus être bloquant dans Env
- [ ] Le champ "Zone de surveillance" doit être bloquant dans Env (cf. ticket #2986)

### Sur le bandeau du bas et la pop-up de confirmation

- [x] Revoir formulation de la pop-up qui s'affiche quand on veut quitter le formulaire alors que l'enregistrement auto n'était pas actif : 
   - dans le bandeau de titre mettre "enregistrement impossible"
   - texte de la pop-up : mettre "de la mission" plutôt que "d'une mission" et retirer le "s" à erreur
   - revoir les marges de la pop-up (cf. [cet écran](https://xd.adobe.com/view/bcb50441-8561-431e-9ce7-1a78965b60e4-e9e6/screen/d4f7bab6-bffe-4d6e-8238-cf35a1ac3282)) : 48 px de blanc tournant autour du texte et des boutons, 32 px de marge entre le bloc de texte et les boutons, 8 px d'écart entre les deux boutons (modifiable dans monitor-ui)
![image](https://github.com/MTES-MCT/monitorfish/assets/71878648/6200a85e-1581-4b8c-b307-e76c14583016)

**Comment by AdelineCelier** [comment]
@claire2212 mes retours : 
- je pense qu'il faut mettre la pop-up "enregistrement impossible" également quand je clique sur "fermer" alors que j'ai créé une surveillance et que je n'ai pas saisi sa zone. En gros dès qu'il y a un champ bloquant dans le formulaire, en colonne 1 ou en colonne 3, faut mettre la pop-up.
- les cartes d'actions ont changé de taille quand elles n'ont pas encore de date j'ai l'impression (cf. capture). Il faudrait qu'elles restent constantes en largeur. 
![image](https://github.com/MTES-MCT/monitorenv/assets/71878648/53fdf45a-e20c-4635-8122-1818ad32d9d4)

**Comment by claire2212** [comment]
@AdelineCelier pour le premier point sur la pop-up c'est normalement le cas. je viens de tester en inté et j'ai bien la pop-up : 

<img width="1502" alt="Capture d’écran 2024-03-27 à 16 36 41" src="https://github.com/MTES-MCT/monitorenv/assets/23258718/a552e010-f90e-45e8-acab-21a2d6c4b01c">

**Comment by AdelineCelier** [comment]
All good !
