### ISSUE TITLE
Missions - Modifier les styles des champs en erreurs en rouge allégé

### ISSUE THREAD

**Issue by claire2212** [MTES-MCT/monitorenv#1242]
Dans le formulaire des missions :

Ne pas mettre en rouge le label
Ne pas afficher la phrase d'erreur
Ajouter le rouge sur les composants custom (non rsuite)
cf. Miro : https://miro.com/app/board/uXjVNY_Ur84=/
cf. écrans XD : https://xd.adobe.com/view/bcb50441-8561-431e-9ce7-1a78965b60e4-e9e6/

ticket Fish : https://github.com/MTES-MCT/monitorfish/issues/2969

**Comment by claire2212** [comment]
Afficher seulement les erreurs "custom ", par exemple `La date de fin doit être postérieure à celle de début`

**Comment by AdelineCelier** [comment]
@claire2212 comme discuté, revoir le fonctionnement des astérisques :
- elles sont là pour signifier que le champ doit être complété pour que la mission puisse être clôturée (et demain, qu'elle puisse être considérée comme "complétée"). 
- il faut donc en mettre pour tous les champs bloquants (à l'ouverture et à la clôture)

Autres points UI : 
- Ajuster hauteur de bandeau du bas : 16 px de marge en haut et en bas, 24 px de marge à gauche et à droite)
- Mettre 16 px entre les champs "en ligne"
- Pour les contrôles, passer les 3 champs en ligne à 176 px
- Modification du date picker : 
   - 4px d'écart entre le champ date et le champ heure
   - modification du wording : "date de début" et "date de fin"
- Gestion des UTC 
   - Remettre les (UTC) dans les libellés des date pickers, mais pas dans la timeline
   - Le retirer dans le titre de l'action
   - Retiter la phrase "Toutes les dates et heures sont en UTC", et passer la phrase restante en medium

**Comment by AdelineCelier** [comment]
Allez go ça part !
