### ISSUE TITLE
Missions - Ajouter le menu missions sur la carto avec la commande pour afficher/masquer et si possible les filtres

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorenv#125]
**A minima**
Ajouter la commande afficher/masquer

**Si plus de temps**
Rajouter les filtres

**Si extra time youhou trop facile**
Faire le menu "missions" en entier ;)

**Comment by AdelineCelier** [comment]
Je viens d'identifier un cas un peu limite : 
J'ai ouvert une nouvelle mission, j'ai fait "ajouter une zone de mission", j'ai basculé sur la vue carto pour dessiner la zone de mission, je l'ai validée, ce qui m'a remise sur la vue "normale" de la carto, avec le menu missions ouvert. J'ai eu le réflexe de cliquer sur "voir la vue détaillée des missions" pour rebasculer sur la vue missions. Cela m'a remis sur la liste des missions (logique), mais du coup cela a fermé sans enregistrer le formulaire de mission que j'étais en train de remplir... 
Ca ne devrait pas se produire souvent si les utilisateurs bossent bien en double screen, mais il faut peut-être prévoir quand même le cas ? Je ne sais pas trop quel comportement serait le plus pertinent : 
- soit ça revient sur le formulaire avec la modale "enregistrer les modifications ?", comme si l'utilisateur avait cliqué sur "quitter"
- soit ça rebascule direct sur les missions, avec le risque de perdre des infos d'un formulaire ouvert
- soit...as-tu une autre idée ?

**Comment by AdelineCelier** [comment]
3è point rebasculé dans le ticket #178

**Comment by thoomasbro** [comment]
> lorsque je clique sur l'œil pour masquer les missions, seuls les drapeaux disparaissent, pas les polygones

En fait seule la mission encore sélectionnée reste affichée. Les autres polygones sont masqués. Je pense que c'est étrange de masquer aussi la mission sélectionnée car c'est celle qui est affichée dans la deuxième fenêtre.

Je dirais qu'il faut laisser comme ça. Qu'en penses tu ?

**Comment by AdelineCelier** [comment]
Ah oui effectivement, c'est la mission dont le formulaire est ouvert qui reste affichée. Oui c'est vrai que ça semble assez logique.
Ok pour moi de laisser comme ça.

**Comment by AdelineCelier** [comment]
Top, les filtres se synchronisent bien entre la carte et le tableau des missions.
