### ISSUE TITLE
Missions – Aligner les champs d'infos de cible entre les signalements et les contrôles ?

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorenv#1253]
Hello @manonolivier 
En bossant sur le ticket de la complétion des champs d'info de cible à partir d'un signalement ([ticket #1146](https://github.com/MTES-MCT/monitorenv/issues/1146)), on s'est rendu compte que le fait que les infos à remplir n'étaient pas tout à fait les mêmes entre les signalements et les contrôles pouvait prêter à confusion. En effet, il n'y a pas de match exact entre les champs. 

**Côté contrôle, les champs pour les cibles de type "navire" sont les suivants :** 
- Immatriculation
- Type de navire
- Taille du navire
- Identité de la personne contrôlée

**Côté signalement, les champs pour les cibles de type "navire" sont les suivants :**
- MMSI
- Nom du navire
- IMO
- Nom du capitaine
- Immatriculation
- Taille

Plutôt que de tenter des correspondances, cela semble plus simple de mettre les mêmes champs des 2 côtés non ?
Les signalements ayant été faits plus récemment que les contrôles, j'aurais tendance à penser qu'il faut plutôt qu'on se base là-dessus, seriez-vous ok avec ça ? 
Si oui, il y a juste le champ "type de navire" qui est côté contrôle mais pas côté signalements : est-ce qu'il est utile, est-ce que vous le renseignez ? Si oui, faut-il le mettre aussi côté signalements ?

Je peux passer demain ou après-demain pour qu'on en parle de vive voix si besoin.

**Comment by AdelineCelier** [comment]
Hello @manonolivier non je crois bien que vous ne nous avez pas répondu sur ce point, qui est donc en stand-by pour l'instant !

**Comment by TEAMCACEM** [comment]
Il nous faut aussi type de navire côté signalements et on prend les champs signalement pour les mettre côté contrôle

**Comment by manonolivier** [comment]
Yes c'est niquel, merci @claire2212

**Comment by AdelineCelier** [comment]
@claire2212 pour les cibles de type Navire, c'est good, les champs sont iso entre signalements et contrôles. 
Est-ce qu'on ne profiterait pas pour rendre iso les autres types de véhicules ? 
-> Cibles "Autres véhicules marins"/ "véhicule terrestre" / "véhicule aérien" : ajouter un champ "identité de la personne contrôlée" côté formulaire de contrôle

**Comment by claire2212** [comment]
@AdelineCelier on peut faire un autre ticket pour ça?

**Comment by AdelineCelier** [comment]
Good !
