### ISSUE TITLE
Actualisation automatique des filtres - première ouverture

### ISSUE THREAD

**Issue by manonolivier** [MTES-MCT/monitorenv#1262]
Quand on ouvre ME le matin, le filtre qu'on a mis la veille est toujours en place mais il ne s'actualise pas.

Exemple : j'ai quitté ME hier en laissant le filtre "aujourd'hui", ce matin j'ouvre ME et le filtre "aujourd'hui" est toujours coché mais ME affiche 42 missions. Je clique sur réinitialiser les filtres et coche de nouveau "aujourd'hui" et là 22 missions sont affichées.

Ce n'est pas très dérangeant mais ce serait plus agréable, si possible, que lors de la première ouverture de ME de la journée, soit ça se réinitialise sur "une semaine" soit ça reste sur "aujourd'hui" mais ça montre vraiment les missions d’aujourd’hui.

**Comment by AdelineCelier** [comment]
Hello @manonolivier, bien vu merci, on va voir quand on peut traiter ce point.

**Comment by claire2212** [comment]
Je m'occupe finalement du ticket car j'ai fais le travail sur les signalements (le problème se posait aussi)

**Comment by AdelineCelier** [comment]
ça me semble bon, côté mission comme côté signalement !
