### ISSUE TITLE
Mettre en avant les icônes des signalements et des missions en cours

### ISSUE THREAD

**Issue by AlexiaLaunay** [MTES-MCT/monitorenv#1267]
Quand on affiche toutes les missions (clôturées, terminées, en cours et à venir) sur plusieurs jours (à la semaine par exemple). On ne voit pas forcément apparaitre les missions en cours rapidement.
Je vous mets l'exemple au Glénan : 
![image](https://github.com/MTES-MCT/monitorenv/assets/148067117/a80d919c-86f5-4d97-906c-71419ad39e17)

Il faut vraiment zoomer pour voir la mission en cours : 
![image](https://github.com/MTES-MCT/monitorenv/assets/148067117/8abab64b-9cb4-4fe4-aec4-5090ee08d1b1)

Merci !

**Comment by AdelineCelier** [comment]
C'est bon pour moi, l'ordre des missions permet de voir d'abord les "à venir", puis les "en cours", puis les "terminées".
