### ISSUE TITLE
Zone pour refermer la sous-thématique

### ISSUE THREAD

**Issue by manonolivier** [MTES-MCT/monitorenv#1268]
Je crois que c'est depuis la dernière mise en production mais je me trompe peut-être. Quand on choisi une sous-thématique, quand on souhaite fermer la liste déroulante, cliquer sur la zone vide en blanc de la sous-thématique ne fonctionne pas. On peut le faire pour la thématique.

C'est le cas pour les signalements et les missions.

C'est aussi le cas pour les moyens

**Comment by claire2212** [comment]
Hello @manonolivier quand tu parles de la "zone vide en blanc" c'est ce que j'ai entouré dans la capture ci-dessous ?

<img width="497" alt="Capture d’écran 2024-03-25 à 13 38 47" src="https://github.com/MTES-MCT/monitorenv/assets/23258718/6f7bf288-3c9d-46ce-bcd6-b9055996bf56">


En testant je remarque que la liste se ferme si tu cliques n'importe où à l'extérieur de ce sélecteur? Tu me confirmes? Si c'est le cas, le comportement est normal.

**Comment by manonolivier** [comment]
Oui c'est ça.
On a l'impression que ce n'était pas comme ça avant mais pas de soucis, on s'habituera !
