### ISSUE TITLE
Envoyer un bilan contrôle hebdomadaire aux unités

### ISSUE THREAD

**Issue by VincentAntoine** [MTES-MCT/monitorenv#1269]
- [ ] Envoi des actions env
- [ ] Envoi des contrôles pêche

**Comment by louptheron** [comment]
Exporter un CSV avec toutes les unités pour que le CACEM puisse vérifier celles flgag avec l'envoi d'emails/SMS

**Comment by VincentAntoine** [comment]
Essai en mode test (envoi des emails au CACEM et non aux unités) le 8 juillet. Le CACEM n'a pas reçu l'email, il semble manquer encore d'autres variables environnement. Les variables environnement seront vérifiées / définies lors de la MEP de 9 juillet, à retester ensuite.

**Comment by AdelineCelier** [comment]
Vu par Vincent : cela fonctionne bien en inté, on va pouvoir l'activer en prod
