### ISSUE TITLE
Ajouter un flag "Adresse de diffusion de l'unité" sur les contacts unité

### ISSUE THREAD

**Issue by VincentAntoine** [MTES-MCT/monitorenv#1271]
Prérequis à #1269 pour pouvoir qualifier les contacts et savoir quelles adresses email utiliser pour la diffusion des données de contrôle. Sera aussi utile pour la diffusion des préavis.

Ecrans d'Adeline : 
![Fiche unité_identifier les adresses et numéros de diffusion](https://github.com/MTES-MCT/monitorenv/assets/27647971/06012409-bac4-4963-9f4c-6f62d04f188f)

![Fiche unité_définir une adresse de diffusion_1](https://github.com/MTES-MCT/monitorenv/assets/27647971/8506b490-0f25-48ef-b3d8-690626f8864e)

![Fiche unité_définir une adresse de diffusion_2](https://github.com/MTES-MCT/monitorenv/assets/27647971/db83c95f-58d7-469e-8f70-a39e242bf67f)

![Fiche unité_modifier une adresse de diffusion](https://github.com/MTES-MCT/monitorenv/assets/27647971/50daa72e-b806-4b49-bfd1-596d618a33c0)

Reste à confirmer si on garde l'icône étoile ou une autre.

**Comment by VincentAntoine** [comment]
@louptheron le back est fait dans #1270 il reste le front à faire ;)

**Comment by AdelineCelier** [comment]
@ivangabriele je remets le lien vers les écrans ici (13 à 16) : https://xd.adobe.com/view/e419eaed-c054-4382-b1bb-fdf429fddeb9-b14a/screen/c409c0fb-4200-4252-8044-485069b0c541/

Et voici l'icône pour la diffusion 
![Distribution](https://github.com/MTES-MCT/monitorenv/assets/71878648/f0423b0a-bc0b-4f18-89c7-a53081ea6966)

**Comment by AdelineCelier** [comment]
Presque tout bon, je note juste 2 derniers mini retours : 

- est-ce qu'il y aurait moyen de faire une animation de disparition du bandeau ? là il disparaît brutalement, ce serait pas mal qu'il glisse vers le haut (je me demande si je n'avais pas fait ce retour côté Fish aussi, je ne sais pas si ça se gère dans monitor-ui ou direct dans les apps)
- désolée je ne l'ai pas noté dans le ticket mais sur les histoires de marge au niveau de l'icône "éditer", il faudrait faire la même chose sur les cartes des moyens 
![image](https://github.com/MTES-MCT/monitorenv/assets/71878648/eabd1fc5-a7f9-46ef-a78f-1afc4728da5c)

**Comment by claire2212** [comment]
je clôture ce ticket : 
- les marges ont été mise à jour pour le bouton d'édition
- création d'un ticket dans monitor-ui : https://github.com/MTES-MCT/monitor-ui/issues/1464
