### ISSUE TITLE
Surveillance en noir

### ISSUE THREAD

**Issue by manonolivier** [MTES-MCT/monitorenv#1279]
Aucun problème pour l'opérationnel mais comportement bizarre : 
Quand je passe ma souris sur la zone de surveillance du bas, celle du haut se colore en noir. Ca ne le fait pas quand je passe ma souris tout doucement donc je ne sais pas si vous réussirez à refaire le bug mais bon au cas où
![image](https://github.com/MTES-MCT/monitorenv/assets/147587284/5f46d065-b59f-4a5c-8198-69db5f0eef47)

**Comment by claire2212** [comment]
@manonolivier ok bien noté, ce sera corrigé

**Comment by claire2212** [comment]
Hello @manonolivier est-ce que ce problème est résolu? j'ai testé et je n'ai pas réussi à reproduire sur la mission en question (voir capture)
![Image](https://github.com/user-attachments/assets/275f6815-1a98-4b58-8baa-582715cc2bd3)


De plus, en recherchant la mission je me suis aperçue qu'il y avait potentiellement un doublon. Les deux premières lignes du tableau ont exactement les mêmes infos, le première ligne est le doublon je pense.
![Image](https://github.com/user-attachments/assets/3543137e-7268-4ec6-a6e5-63b85891ada5)

**Comment by manonolivier** [comment]
Salut @claire2212,

Ca ne me le fait pour cette mission et ça fait longtemps que je n'ai pas eu ce comportement de manière générale.

En effet, c'est une mission en doublon, je l'ai supprimée merci !

**Comment by claire2212** [comment]
@manonolivier ok je clôture le ticket dans ce cas.
