### ISSUE TITLE
[Mission] Mise en place de l'état de complétion des données des actions

### ISSUE THREAD

**Issue by claire2212** [MTES-MCT/monitorenv#1283]
### Liste 

- [x]  Ajout d'un filtre sur statut & complétion des données 👍🏻 
- [x] Ajouter deux colonnes statut et complétion des données 👍🏻 
  - Si un état est non-complété parmi la mission et les actions, on passe à "à compléter" 👍🏻 
- [x] Rajouter les filtre "Missions avec actions env" (voir ticket #1248) 👍🏻 
- [x] Supprimer le filtre "Ouvert par" (voir ticket #1248) 👍🏻 

### Formulaire 
- [x] Revoir les headers des colonnes du formulaire 👍🏻 

#### Mission
- [x] Afficher les tags de complétions 👍🏻 
- [x] A chaque enregistrement, calculer l'état de complétion de la mission et de l'action pour l'enregistrer en BDD 👍🏻 

#### Action

- [x] A chaque enregistrement, calculer l'état de complétion de la mission et de l'action pour l'enregistrer en BDD 👍🏻 
- [x] En dessous du titre de l'action, afficher les champs à compléter, ex. "12 champs à compléter pour la stat" 👍🏻 
- [x] Rajouter le bouton "Dupliquer" en haut de l'action 👍🏻 

### Données

- [x] Rajouter le champ `completion` dans les actions

**Comment by AdelineCelier** [comment]
### Revue UX

- [ ] Ajuster la taille du tableau de la vue liste des missions pour qu'il s'adapte à un écran de 1680 px de large. Cf [écran ici](https://xd.adobe.com/view/06d04fac-8722-43f0-b5d5-90601b20697e-5383/screen/daf2a56c-5229-4146-b7ec-484f4c832a87). 

### Revue UI

- [ ] Ce n'est pas la bonne icône pour le statut "à venir" : il faut que ce soit la ClockDashed (désolée je ne te l'avais peut-être pas envoyée) : 
![Dashed clock](https://github.com/MTES-MCT/monitorenv/assets/71878648/4eb87e81-6b94-441d-b71a-280e884ab116)

- [ ] Filtres "état des données" de la vue liste : mettre une majuscule à "Données" et pas au "à" de "à compléter" ou "à jour" ni au "c" de "complétées"
- [ ] Je me rends compte qu'il manque les cédilles de "Façade" dans le filtre et dans la colonne du tableau
- [ ] Header de la colonne 2 : rapprocher le bouton "ajouter" du bouton "lier un signalement" (8 px entre les deux boutons)

**Comment by AdelineCelier** [comment]
Tout est bon
