### ISSUE TITLE
[Mission] Mise à jour de la timeline des actions d'une mission et amélioration design

### ISSUE THREAD

**Issue by claire2212** [MTES-MCT/monitorenv#1285]
## Liste des actions

- [x] Dans la liste des actions, rajouter un trait entre les actions 👍🏻 
- [x] Rajouter le point d'exclamation en-dessous de la date dans la liste d'action 👍🏻 

## Formulaire 
- [x] Afficher le nouveau bandeau "Toast" lors de la création d'une mission
- [x] Afficher le bandeau quand on revient sur une mission terminée mais non-complétée

**Comment by AdelineCelier** [comment]
@claire2212 

- [ ] Il y a plusieurs secondes de latence avant que le bandeau de création de mission n'apparaisse
- [ ] La croix du bandeau temporaire me semble un peu trop à gauche, il faut x px de marge à droite de la croix
- [ ] Possible de faire la même animation pour l'apparition et la disparition du bandeau temporaire que pour le bandeau rétractable ? La différence serait que le temporaire disparaîtrait complètement sous le header. Seul petit point que je vois sur l'animation actuelle c'est que le texte semble apparaître un peu tôt, c'est comme s'il bougeait au sein du header...je ne sais pas si je suis très claire. Et c'est un point de détail, pas grave si compliqué à fixer.
