### ISSUE TITLE
Thématique signalements champ bloquant

### ISSUE THREAD

**Issue by manonolivier** [MTES-MCT/monitorenv#1287]
Pour l'instant ce n'est pas bloquant mais on s'est rendu compte qu'il y avait déjà des oublis (je les corrige cette semaine). Ce serait possible de rendre la thématique bloquante pour les signalements svp ?

**Comment by claire2212** [comment]
Hello @manonolivier , yes je m'occupe de ça. La sous-thématique également?

**Comment by manonolivier** [comment]
Salut @claire2212 Merci ! Et oui la sous-thématique aussi s'il te plait

**Comment by AdelineCelier** [comment]
@claire2212 les champs thématique et sous-thématique sont bien bloquants. 
Je pense qu'on peut harmoniser avec les champs rouges "allégés" des missions et retirer les phrases type "veuillez renseigner..." ou "requis" => évidemment pas bloquant pour la mep

**Comment by claire2212** [comment]
@AdelineCelier oui je comptais le faire pendant que je m'occupais de l'enregistrement automatique des signalements.
