### ISSUE TITLE
Pouvoir ajouter un point de contrôle en tapant directement les coordonnées données par l'unité

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorenv#131]
A dessiner : le fait-on direct depuis le formulaire (plus rapide), ou bien sur la carte, pour voir où "atterrit" le point de contrôle et s'assurer qu'il n'y a pas d'erreur ?
A demander à Xavier.

**Comment by AdelineCelier** [comment]
@thoomasbro d'ailleurs au sujet de ce ticket, si tu as des questions sur les modes d'interaction n'hésite pas à me les poser ! Il y a peut-être des choses que je n'ai pas identifié à l'usage. 
En refaisant un tour dans le backlog, je suis retombée sur le ticket #52

**Comment by thoomasbro** [comment]
Pour ce ticket, je vais reprendre le composant actuel de saisie de coordonnées.
Pour #52, il faudra revoir ce composant et le mettre dans la lib. (Donc ticket #52 à déplacer dans monitor-ui ?)

**Comment by AdelineCelier** [comment]
Ok c'est noté.
Il y a un kanban "monitor UI" ?

**Comment by thoomasbro** [comment]
Je ne sais pas s’il y a un kanban mais il y a les issues.Thomas BrossetLe 19 déc. 2022 à 13:58, AdelineCelier ***@***.***> a écrit :﻿
Ok c'est noté.
Il y a un kanban "monitor UI" ?
