### ISSUE TITLE
zone de surveillance - ajouter des possibilités de tracer un rond et un rectangle

### ISSUE THREAD

**Issue by manonolivier** [MTES-MCT/monitorenv#1313]
Nous devons maintenant tracer les zones de surveillance, pouvez-vous mettre les mêmes possibilités que pour le tracé des zones de mission svp ? (tracé libre, tracé rond, tracé rectangle) Merci

**Comment by claire2212** [comment]
Salut @manonolivier ok je rajoute ça.
