### ISSUE TITLE
[Mission] Suppression de l'état "clôturé"

### ISSUE THREAD

**Issue by claire2212** [MTES-MCT/monitorenv#1323]
- [x] Suppression en base de la colonne `closed`
- [x] Suppression du bouton `Clôturer`
- [x] Gestion du schéma de clôture quand la mission est terminée
- [ ] Vérifier les vues metabase + flow missions historiques

**Comment by AdelineCelier** [comment]
@claire2212 c'est bon pour moi côté interface, est-ce qu'il y a des trucs à revoir de ton côté ou de celui de Vincent ?
