### ISSUE TITLE
Signalement - Pouvoir ajouter plusieurs sources pour un signalement

### ISSUE THREAD

**Issue by AlexiaLaunay** [MTES-MCT/monitorenv#1325]
Hello,

Est-ce qu'il serait possible de pouvoir ajouter plusieurs sources pour un signalement ?
On a parfois le cas d'une drague qui part faire de l'extraction de granulats qui nous est signalée par deux voire trois sémaphores différents. Les sources sont différentes mais le signalement est le même.

Merci !

**Comment by AdelineCelier** [comment]
Hello @AlexiaLaunay on veut bien un peu plus d'infos sur ce ticket : 
- quel est le besoin exactement derrière cette volonté de saisir plusieurs sources pour le même signalement ? Est-ce un besoin statistique ou opérationnel ? Est-ce que vous avez besoin du détail de la source (tel et tel sémaphore l'ont signalé) ou plutôt di nombre d'occurrences du signalement (ce signalement a été remonté x fois) ? 
- si on ajoute plusieurs sources/occurrences, faut-il saisir plusieurs horaires, 1 à chaque fois que le signalement est remonté ? 
- pensez-vous que vous saurez identifier systématiuement si un signalement est déjà ouvert ou non ? Y a-t-il un risque de doublons ?

On peut en rediscuter si besoin de vive voix.

**Comment by manonolivier** [comment]
Salut @AdelineCelier,

- Besoin opérationnel principalement mais statistiques aussi.
Exemple 1 : sémaphore du Havre nous dit que la drague part en direction de la zone d'extraction. Le sémaphore de Fecamp nous dit qu'elle commence son extraction. Le sémaphore de Dieppe nous dit qu'elle quitte la zone pour décharger au port de Dieppe. => On a besoin que ces signalements apparaissent dans un seul signalement (la cible est la même) c'est plus lisible niveau opérationnel. C'est également mieux lorsqu'un contrôle est effectué après ces signalements. Sans ça, nous sommes obligés de choisir au pif le signalement que nous allons rattaché à la mission.
Exemple 2 : Donia (logiciel qui nous envoie des notifications par mail et qui se trompe relativement souvent) nous signale un navire dans une zone interdite au mouillage en Med. Nous rentrons le signalement puis appelons le sémaphore pour confirmer. Le sémaphore analyse la situation, tente de contacter le navire, etc. Nous devons mettre que le sémaphore à joué une part importante dans l'analyse du signalement.
- Nous avons besoin du détail des sources
- je vois avec l'équipe pour savoir s'il faut saisir plusieurs horaires ou non
- Le risque de doublon est surtout présent avec le fonctionnement actuel puisque l'on ouvre un signalement pour chaque personne qui nous signale la même chose.

**Comment by AdelineCelier** [comment]
@maximeperraultdev voilà les écrans pour ce ticket sont les n°[4](https://xd.adobe.com/view/42c242b4-5b89-4627-b666-50e2c31aa4ca-1791/screen/41186c34-e86f-4c1f-aa59-d4dc73971761) et [5](https://xd.adobe.com/view/42c242b4-5b89-4627-b666-50e2c31aa4ca-1791/screen/d46f1063-5a30-4855-a68e-4186c0c7ab66)

**Comment by AdelineCelier** [comment]
@maximeperraultdev ça fonctionne bien, juste qques points UI sur les marges : 

- [ ] la marge entre le le menu déroulant pour choisir le sémaphore et le bouton`ajouter une source` est trop importante, elle doit faire 8 px
![image](https://github.com/user-attachments/assets/c9a104b9-4c47-43e7-bae8-9507393fc79f)

- [ ] Idem, qques marges à revoir il me semble une fois qu'une source est ajoutée
![image](https://github.com/user-attachments/assets/a20a4127-9da7-4582-b598-8f935bfee76e)

- [ ] la couleur du filet entre les deux sources doit être en Light Gray (#CCCFD6)

**Comment by AdelineCelier** [comment]
Tout bon pour moi !
