### ISSUE TITLE
[Signalement]Mise en place de la sauvegarde automatique

### ISSUE THREAD

**Issue by claire2212** [MTES-MCT/monitorenv#1329]
EPIC : #1263

Mise en place de l'enregistrement automatiques d'un signalement: 
- [x] Les champs obligatoires pour la création restent les même qu'aujourd'hui
- [x] Allègement des champs en erreur
- [x] Suppression bouton `Enregistrer et quitter` + Ajout Bouton `Fermer`
- [x] Si signalement archivé -> pas de sauvegarde auto. Si on rouvre une signalement on re-bascule en enregistrement auto

Etats des boutons : 
- [x] Signalement pas encore créé : un seul bouton 'Fermer'
- [x] Signalement créé (avec enregistrement auto) : Supprimer / Archiver / Fermer
- [x] Signalement créé (sans enregistrement auto) : Suppression / Rouvrir le signalement / Enregistrer et fermer

**Comment by AdelineCelier** [comment]
On a ouvert un nouveau ticket, le #1383 pour le pb du scroll. On peut fermer ce ticket.
