### ISSUE TITLE
Missions - Ne pas recalculer les zones de missions avec les actions Fish

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorenv#1343]
Actuellement, la zone de mission est calculée selon la dernière action Fish ou Env.
Cette fonctionnalité avait été ajoutée pour gérer le cas suivant : 
1. On créé une action avec ou sans date (qui devient l'action la plus récente) 
2. On rentre une géométrie sur l'action, donc on modifie la zone de mission
3. On change la date et c'est l'action de l'autre centre qui devient la plus récente

**Cela permettait de mettre à jour la zone de mission pour que ça soit bien celle de l'autre centre.**

### Problème
Les contrôles à la débarque de Fish ne sont pas pris en comptes, donc des zones de missions peuvent être supprimées depuis Env.
cf. `useUpdateMissionZone` :
```
if ((!firstAction || firstAction.geom?.coordinates.length === 0) && values.isGeometryComputedFromControls) {
      setFieldValue('geom', undefined)
      setFieldValue('isGeometryComputedFromControls', false)

      return
    }
```

### Solution

- [ ] Si une action ne contient pas de date de début, on ne l'utilise pas pour calculer la zone de mission
- [ ] Si la date d'action est modifiée après que la mission ait été recalculée, on garde la zone de mission actuelle, même si elle est erronée. Car son but opérationnel sera moindre si le CR de contrôle a été rentré quelques temps après le contrôle réél.
  - On ne re-calcule donc plus des zones de missions avec les actions de l'autre centre, pour éviter d'avoir à maintenir du code métier

**Comment by AdelineCelier** [comment]
Tout semble fonctionner correctement 👍🏻
