### ISSUE TITLE
Un seul trigramme bloquant pour valider une action

### ISSUE THREAD

**Issue by manonolivier** [MTES-MCT/monitorenv#1344]
Comme vu avec Adeline, contrairement au CNSP nous n'avons pas besoin de la relecture d'une seconde personne pour valider l'action de surveillance ou de contrôle.
Il faudrait donc garder les 2 trigramme (ouvert par et complété par) mais ne rendre bloquant que le premier.

**Comment by AdelineCelier** [comment]
C'est bon, le trigramme "complété par" n'est plus bloquant.
