### ISSUE TITLE
[Zones de vigilance] Questions tech et design

### ISSUE THREAD

**Issue by thoomasbro** [MTES-MCT/monitorenv#1356]
# Points bloquants à traiter par l'AU

- quelles thématiques afficher ? Si on affiche les thématiques liées au plan de controle, alors ces thématiques sont annualisées. Quelle année afficher (notamment en cas de zone d'intérêt avec récurrence) ? => On affiche les thématiques venant des zones reg (+ celles créées à la volée)
- Ajouter le filtre par période et par thématique (dans l'espace de filtre actuel, ou dans un nouvel espace par type de couche, et définir les modalités de filtrage) => OK fait

# Non Bloquant :
- faut il faire un lien avec les AMP ou seulement avec les couches reg? => Les deux
- comment se fait l'ajout/suppression/modification d'images ? combien d'images max ? 
=> 5 photos max. 
=> Bouton suppression Ok sur les maquettes. 
=> Bouton d'édition: Pas de bouton d'édition
- Saisie avancée des périodes et récurrence: préciser si on va au delà d'une date de début et d'une date de fin
-  Option pour afficher toutes les zones d'intérêt quelle que soit la période ? => Par défaut toutes les zones de vigilances sont visibles
=> on affiche les zones sur le filtre sélectionné ("en ce moment" = zone en cours aujourd'hui)

# Autres décisions :
- Saisie de texte de recherche filtre des zones d'intérêt par nom et commentaire
- Pour les zones reg disponibles dans le menu déroulant d'ajout de lien vers la reg, filtrer géographiquement par la géométrie de la zone d'intérêt (définir l'éventuel buffer à appliquer) => Quand on clique sur ajouter une REG ou AMP on active la recherche par zone (bouton oeil "actif")
- Si une zone reg liée à une zone d'intérêt est supprimée, il faut supprimer la zone d'intérêt = > NON
-  Si une zone reg liée à une zone d'intérêt est supprimée, il faut supprimer la zone reg dans la zone de vigilance

**Comment by AdelineCelier** [comment]
@claire2212 voilà le lien vers les écrans XD des zones de vigilance : 
https://xd.adobe.com/view/642c559c-c388-43a1-b9ad-f1babce5e3a7-317f/

**Comment by claire2212** [comment]
Autres questions : 
- Faut-il supprimer la zone de vigilance quand celle-ci est finie?
- Le formulaire a-t-il une taille fixe avec le footer toujours visible (idem signalement)? 
- Y'a-t-il un système de validation des champs dans le formulaire?
