### ISSUE TITLE
[Unités] Revoir le texte de l'email de diffusion

### ISSUE THREAD

**Issue by ivangabriele** [MTES-MCT/monitorenv#1361]
On n'a plus de concept de clôture, à modifier ?

_Originally posted by @louptheron in https://github.com/MTES-MCT/monitorenv/pull/1338#discussion_r1587934936_

Tache : #1271

**Comment by ivangabriele** [comment]
## Bilan hebdomadaire contrôle de l'environnement marin

---

Bonjour,

Vous trouverez ci-joint les données des contrôles et des surveillances de l'environnement marin auquels votre unité (Unité test) a participé entre le 08/05/2024 00:00 UTC et le 15/05/2024 00:00 UTC qui ont été prises en compte par le Centre d'Appui au Contrôle de l'Environnement Marin (CACEM).

Seuls les contrôles et surveillances des missions clôturées sont transmis dans ce bilan hebdomadaire. Si votre unité est engagée dans une mission qui court sur plusieurs jours et qui n'était pas clôturée au 15/05/2024 00:00 UTC, il est normal que les données correspondantes n'y figurent pas.

Si des données sont manquantes, incorrectes ou incomplètes, n'hésitez pas à contacter le CACEM.

---

Centre d'Appui au Contrôle de l'Environnement Marin - Tél : +33 2 90 74 32 55

**Comment by AdelineCelier** [comment]
Vu avec Vincent, les changements sont validés. 
Je remets le texte complet rectifié ci-dessous : 

### Bilan hebdomadaire contrôle de l'environnement marin

---

Bonjour,

Vous trouverez ci-joint les données des **contrôles** et des **surveillances de l'environnement marin** effectués par votre unité **(Unité test)** **entre le 08/05/2024 00:00 UTC et le 15/05/2024 00:00 UTC** et rapportés au Centre d'Appui au Contrôle de l'Environnement Marin (CACEM).

Seuls les contrôles et surveillances dont les données sont complètes sont transmis dans ce bilan hebdomadaire. Si certaines données n'ont pas encore été transmises au CACEM (par ex. l'établissement d'un PV ou non), il est normal que le contrôle ne figure pas encore dans le rapport.

Si des données sont manquantes, incorrectes ou incomplètes, n'hésitez pas à **contacter le CACEM**.

---

Centre d'Appui au Contrôle de l'Environnement Marin - Tél : +33 2 90 74 32 55

**Comment by AdelineCelier** [comment]
Hey ici, je ne sais pas comment tester ce ticket ?

**Comment by VincentAntoine** [comment]
Tu peux télécharger ce fichier et l'ouvrir dans un navigateur : https://github.com/MTES-MCT/monitorenv/blob/main/datascience/tests/test_pipeline/test_flows/expected_rendered_email.html

**Comment by AdelineCelier** [comment]
Je viens de relire le texte, et je me rends compte d'une petite faute d'accord dans ce que j'avais écrit : 
"Vous trouverez ci-joint les données des contrôles et des surveillances de l'environnement marin effectués par votre unité [..] et rapporté**e**s au Centre.." 
=> ce sont les données qui sont rapportées
