### ISSUE TITLE
Impossible de modifier une mission avec MED en attente

### ISSUE THREAD

**Issue by manonolivier** [MTES-MCT/monitorenv#1363]
Je faisais le point sur les missions qui sont "à compléter" par le CACEM (il manque des trigrammes) et je suis arrivée à une mission où il manquait des trigrammes, je les ais ajouté mais je ne peux pas enregistrer les modifications que j'ai fait parce que MonitorEnv ne veut pas laisser la mise en demeure en attente.
![image](https://github.com/MTES-MCT/monitorenv/assets/147587284/2f3fe6b6-c8fc-44ed-8fd6-ae0dc105481f)

**Comment by claire2212** [comment]
Salut @manonolivier est-ce que tu peux me donner plus de détails sur la mission (unité et dates notamment) en question que je regarde d'où peut venir le problème ?
Au moment de ta saisie la mission était en cours ou terminée? Parce que si elle était terminée c'est normal que tu n'ai pas pu mettre `En attente` car on a gardé le fonctionnement de la mission clôturée (donc mission terminée = obligation de mettre Oui ou Non pour le champ mise en demeure)

**Comment by manonolivier** [comment]
Salut @claire2212, ça concerne toutes les missions avec un PV ou une MED en attente. Pour exemple : BN St Martin le 15/04 de 15h00 à 17h00

La mission est en effet terminée.
Le "en attente" peut durer longtemps (ils peuvent avoir besoin de faire une enquête poussée au bureau et donc la mission terrain est terminée). Sauf qu'entre temps, je ne peux rien modifier (ajouter un trigramme, modifier le nombre de contrôle, la thématique, etc).
Pour être précise, je peux modifier mais ça ne veut pas enregistrer les modifications.
Alors que je ne veux pas forcément que ça parte dans les stats sur metabase directement (anciennement version clôturée) mais je veux préciser des infos a posteriori et laisser en attente quand même.

D'ailleurs, un "en attente" sur l'action 1 m'empêche de modifier des choses dans l'action 2 (action 2 qui n'a pas de en attente)

Pas facile de l'expliquer par écrit, si ce n'est pas clair, on peut s'appeler

**Comment by AdelineCelier** [comment]
@manonolivier on vient de refaire le point avec @claire2212 , on va modifier le comportement de l'enregistrement quand la mission est terminée : il sera possible d'enregistrer la mission (soit enregistrement auto, soit enregistrement manuel) quand bien même tous les champs en rouge ne seront pas remplis (ex. le champ "en attente", qui restera en rouge puisqu'on attend la réponse). L'état des données de la mission restera "à compléter".

**Comment by manonolivier** [comment]
Salut @AdelineCelier et @claire2212 
C'est top, merci !

**Comment by AdelineCelier** [comment]
Claire c'est bon, ça fonctionne bien, en enregistrement auto comme en enregistrement manuel !
