### ISSUE TITLE
Impossible de cliquer sur "éditer la mission" cadres sur la carte mal placés

### ISSUE THREAD

**Issue by manonolivier** [MTES-MCT/monitorenv#1365]
![image](https://github.com/MTES-MCT/monitorenv/assets/147587284/49ad6bac-d6c8-416f-8077-e6daebd071e8)

Quand je passe ma souris sur "editer la mission" : 
![image](https://github.com/MTES-MCT/monitorenv/assets/147587284/92de3d6c-64e5-404a-9689-37e5d832f1be)

**Comment by claire2212** [comment]
Salut @Manon, ok je vais regarder ça. Par contre je ne sais pas si vous le savez mais la pop-up de la mission peut-être déplacée (il suffit de rester cliquer sur la pop-up et de la bouger) , ce qui permet de quand même pouvoir cliquer sur le bouton d'édition de la mission.

**Comment by manonolivier** [comment]
Salut @claire2212, ah non je savais pas, merci

**Comment by claire2212** [comment]
Hello @manonolivier on peut fermer ce ticket?
