### ISSUE TITLE
Noter un nombre de contrôle avec infraction au lieu de dupliquer

### ISSUE THREAD

**Issue by AlexiaLaunay** [MTES-MCT/monitorenv#1375]
Hello,

ça a surement déjà été remonté mais au cas où :

Dans le cas ou un grand nombre de contrôle a été effectué par une unité actuellement on doit dupliquer et valider le contrôle autant de fois qu'il y a eu de contrôle, ce qui peut être très long.

Est-ce qu'il serait possible de simplement noter un nombre de contrôle (ayant le même type d'infraction, même mise en demeure et même Natinf) et que la duplication soit automatique ?

Merci !

**Comment by claire2212** [comment]
Salut @AlexiaLaunay est-ce que c'est bien la même demande que le ticket: #807 ?

**Comment by AlexiaLaunay** [comment]
Salut Claire, oui c'est bien la même demande. Je l'ai rajoutée car on en a reparlé en point de service

**Comment by claire2212** [comment]
@AlexiaLaunay , ok je le clôture dans ce cas, on a bien pris en compte la demande. @AdelineCelier va faire le travail de design et ensuite on prendra le relais pour le dev
