### ISSUE TITLE
Préremplissage contrôle signalement ne s'actualise pas quand on change de signalement

### ISSUE THREAD

**Issue by manonolivier** [MTES-MCT/monitorenv#1381]
J'ai lié 4 signalements à une mission.
J'ai cliqué sur "ajouter un contrôle pour le signalement du navire ADVA.
![image](https://github.com/MTES-MCT/monitorenv/assets/147587284/8cd9e7b7-53b8-4cd9-85b7-67068da7f051)

J'ai voulu changé et j'ai cliquer sur un autre signalement pour changer le rattachement.
![image](https://github.com/MTES-MCT/monitorenv/assets/147587284/e6bb0c7a-204f-4f1c-9188-b89aff2a08b1)

Le pb c'est que ça n'a pas changé les champs prérempli (nom et taille du navire) dans la partie contrôle.

**Comment by claire2212** [comment]
Ce qui a été validé avec Manon: 
- Si une infraction : on change seulement les infos liées au navire (on garde les données renseignées dans Type d'infraction, Mise en demeure, etc)
- Si plusieurs infractions: on les supprime et on en créé une nouvelle avec les données de la cible du signalement

**Comment by claire2212** [comment]
Hello @manonolivier est-ce qu'il faut aussi modifier les thématiques/ sous -thématiques du contrôle lors d'un changement de rattachement à un siganlement ?

**Comment by manonolivier** [comment]
@claire2212 c'est mieux oui

**Comment by claire2212** [comment]
@manonolivier j'ai déjà fait le développement pour faire ce qu'on s'était dit. Mais c'est comme vous préférez, je peux l'enlever.

**Comment by manonolivier** [comment]
@claire2212 non c'est très bien comme ça

**Comment by AdelineCelier** [comment]
@claire2212 le pré-remplissage semble bien s'actualiser, juste qques retours : 

- il y a l'air d'y avoir un petit couac sur le pré-remplissage du champ "Nom du Capitaine", qui reprend le champ "Nom du navire"
![image](https://github.com/MTES-MCT/monitorenv/assets/71878648/5abab15f-a90b-478c-baae-5b5972ec4db9)
- mettre le champ "type de navire" à la même longueur que les autres champs de cible (je crois que tous les champs s'adaptent à la taille de la colonne, sauf "type de navire"
- je me permets de profiter de ce ticket pour remonter un problème UI : je ne suis pas très fan de l'adaptation de la colonne de droite au contenu saisi, notamment parce qu'avec les NATINF, ça donne des trucs chelous comme sur la capture. Possible de laisser la 3è colonne en largeur fixe, et de tronquer les intitulés des NATINF trop longs en leur ajoutant des title ?
![image](https://github.com/MTES-MCT/monitorenv/assets/71878648/49a966d0-a03a-40fa-883f-1042f9caafbc)

**Comment by AdelineCelier** [comment]
@claire2212 C'est presque bon, le champ "taille du navire" est un peu plus long que les autres encore
![image](https://github.com/MTES-MCT/monitorenv/assets/71878648/a8a02fe4-bcb6-4606-9f8a-1a0f1ecc90a0)
![image](https://github.com/MTES-MCT/monitorenv/assets/71878648/6f42804c-d382-4942-9eee-14adb6976230)

**Comment by AdelineCelier** [comment]
c'est bon !
