### ISSUE TITLE
Zones admin – Mettre à jour les zones AEM qui ont changé de tracé

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorenv#1393]
Message d'Alexia Launay le 22/05/24 :
" Les zones AEM de méditerranée ont été mises à jour cette année. Robin les a tracées, la couche est dans la base de données CNSP (prod > aem_2024) (et au format shapefile en pièce jointe si besoin). Est-ce que ce serait possible de les remplacer dans les zones administratives de Monitor assez rapidement ? (on les utilise beaucoup pendant la saison d'été)"

[Modification zones AEM 2024.zip](https://github.com/MTES-MCT/monitorenv/files/15404181/Modification.zones.AEM.2024.zip)

**Comment by claire2212** [comment]
@AdelineCelier , je clôture le ticket c'est fait et vérifié en direct avec le CACEM
