### ISSUE TITLE
Signalements - remettre une case non avere

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#1394]
Cas d'un mouillage 30m dans une zone interdite +24 mais finalement après recherche, autorisation de la Premar. On veut garder une trace du signalement mais préciser que ce n'est pas avéré.
Ne pose pas trop de problème quand une unité se déplace et fait un contrôle puisque le ésultat du contrôle est RAAS

Cas aussi si on souhaite montrer des stats sur la part des signalements "pertinents" des sémaphores par rapport aux unités par rapport aux particuliers

Cocher la cas non avéré ne doit pas nous empêcher de lier à une mission et de mettre un contrôle

**Comment by AdelineCelier** [comment]
@claire2212 micro-détail pour chipoter un peu : je ne mettrais pas de majuscule à "avéré" et "non avéré", car les deux propositions sont dans la continuité de la phrase "le signalement est..."

**Comment by AdelineCelier** [comment]
Top merci
