### ISSUE TITLE
[Signalement] Afficher la cible dans la pop-up d'un signalement et dans la timeline d'une mission

### ISSUE THREAD

**Issue by claire2212** [MTES-MCT/monitorenv#1399]
- Afficher les informations de la cible dans la pop-up d'un signalement (si cible "Autre" afficher "Autre", sinon afficher toutes les infos)
- Afficher les informations de la cible dans la timeline d'une mission.
- Supprimer l'affichage de la source dans la timeline d'une mission

**Comment by AdelineCelier** [comment]
Petite précision : on affiche les infos de la cible, par ordre d'importance : 1/ Nom, 2/ Identifiants (si navire) avec le MMSI en premier, 3/ Taille (si navire).

On peut garder l'info de la source dans la pop-up sur la carte si ça ne charge pas trop

**Comment by AdelineCelier** [comment]
Comme vu ensemble Claire, afin de ne pas trop surcharger la pop-up : 
- pour les identifiants navire : on met le MMSI s'il y en a un, sinon l'immat, sinon l'IMO (cf. [cet écran](https://xd.adobe.com/view/eabe87d5-464f-4ff2-b804-04a365edc03b-bfed/screen/e80b128a-b9d0-4338-b5de-78a002ede3b3))
- en cas d'autre type de cible, on met 1/ le nom de la personne morale ou l'immatriculation du véhicule, 2/ l'identité de la personne contrôlée (cf. [cet écran](https://xd.adobe.com/view/eabe87d5-464f-4ff2-b804-04a365edc03b-bfed/screen/b97336be-1d04-451a-9f38-672268f84ef7))
- pour la source du signalement : on ne la note pas dans la pop-up, mais on ajoute le lien entre les sémaphores et les signalements
  - au survol et au clic sur un sémaphore : on affiche les liens vers tous ses signalements (cf. [cet écran](https://xd.adobe.com/view/eabe87d5-464f-4ff2-b804-04a365edc03b-bfed/screen/ef764224-198e-4014-a118-3e8d56a7dca0))
  - au survol et au clic sur un signalement non rattaché à une mission : on affiche le lien vers son sémaphore-source (cf. [cet écran](https://xd.adobe.com/view/eabe87d5-464f-4ff2-b804-04a365edc03b-bfed/screen/598af66f-3003-4617-8ea9-1017dc1b6768))
  - au survol et au clic sur un signalement rattaché à une mission : on laisse tel quel, à savoir on n'affiche que le lien vers sa mission
- pour la mise à jour de la carte de signalement dans la pop-up, cf. [cet écran ](https://xd.adobe.com/view/eabe87d5-464f-4ff2-b804-04a365edc03b-bfed/screen/ebe1fbd4-83de-4602-bbb6-473846816b32)

**Comment by AdelineCelier** [comment]
Update après discussion ; on n'affiche pas la source dans la pop-up de signalement, et on n'affiche pas non plus le lien avec le sémaphore au clic sur le signalement. Cela semble un peu trop complexe à dev pour un gain utilisateur faible.

**Comment by claire2212** [comment]
@AdelineCelier je suis pas sûre de comprendre ce qu'il faut afficher en première ligne et en 2ème par rapport à ce que tu as écrit. On pourra en reparler?

**Comment by AdelineCelier** [comment]
@claire2212 comme vu ensemble : 

- dans le cas d'une cible de type "navire"
  - on met le nom du navire sur la 1ère ligne si on l'a et le reste (id et taille) sur la 2è
  - on met l'id sur la 1ère ligne si on n'a pas le nom et la taille sur la 2è
- dans le cas d'une cible d'autre type
  - on met l'immat ou le nom de la société en 1ère ligne et l'identité de la personne contrôlée en 2è si on l'a
  - on met direct l'identité de la personne contrôlée en 1ère ligne si on a rien d'autre – et donc idem, pas de 2è ligne
- dans le cas de cibles multiples, on met sur la 1ère ligne `x cibles de type [navire] `

**Comment by AdelineCelier** [comment]
@claire2212 ça me semble good, juste une bébé remarque, pas la peine de mettre une majuscule au type de cibles dans le cas de cibles multiples : 
![Image](https://github.com/MTES-MCT/monitorenv/assets/71878648/128c7996-ab88-4665-85e7-77ab3af73b12)

**Comment by claire2212** [comment]
@AdelineCelier en fait ce n'est pas une question de signalement en cours/archivé mais c'est lié aux filtres appliqués sur les signalements. J'ai pris le parti de n'afficher le rond du sémaphore + les traits que sur les signalements visibles avec les filtres. ok pour toi?

**Comment by AdelineCelier** [comment]
Ah yes compris ! Ok oui c'est une bonne idée 👍🏻
