### ISSUE TITLE
Missions - Améliorer l'étiquette de la zone de mission : distance par rapport au polygone + marges + UI

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorenv#140]
Comme vu ensemble, la distance entre le polygone et son étiquette varie selon le niveau de zoom, ce qui fait que l'étiquette peut se retrouver très loin de son poygone. 

![image](https://user-images.githubusercontent.com/71878648/197498793-ce99ed19-d408-40ec-8c52-62c95e40f280.png)
![image](https://user-images.githubusercontent.com/71878648/197498888-a9e32e51-2afb-4fc2-980e-1729b9d10691.png)
![image](https://user-images.githubusercontent.com/71878648/197499122-b0e04d46-1385-4d67-82da-e6e15e3ee71c.png)

**Comment by AdelineCelier** [comment]
En plus du problème de distance avec le polygone, il y a des problèmes de marge. 
Reprendre les mesures de cet écran XD : https://xd.adobe.com/view/973ae2b4-ecd1-419f-b092-8545e0d8ce57-c269/screen/cd77cc1d-48ba-490d-a1b3-defbefcd1c7e/

**Comment by AdelineCelier** [comment]
EDIT : nouvelle mise à jour des pop-up de mission et de contrôle, voir les écrans [50](https://xd.adobe.com/view/973ae2b4-ecd1-419f-b092-8545e0d8ce57-c269/screen/cd77cc1d-48ba-490d-a1b3-defbefcd1c7e/) et [51](https://xd.adobe.com/view/973ae2b4-ecd1-419f-b092-8545e0d8ce57-c269/screen/23fdfb08-e65e-417c-a42e-ad66fbb26d50/) du XD.

**Ce qui change en termes d'infos affichées** 
- ajouter du champ libre "contact" du formulaire de mission
- mettre le nom de l'unité à la place du nom de l'administration (on retire l'administration)
- détailler les actions de contrôle : plutôt que "x actions de contrôle", mettre "x surveillances, x contrôles"
- remaniement de l'ordre des infos

**Ce qui change en termes d'UI** 
- ajustement des marges et des espacements entre les différents blocs de tests
- bouton "éditer la mission" plutôt que juste "éditer"
- on peut garder le système de clic sur le drapeau de la mission pour figer la pop-up et ainsi  pouvoir cliquer sur le bouton "éditer la mission", mais pour moi celui-ci doit rester visible tout le temps, même juste au survol. Ou alors s'il ne s'affiche qu'au clic, il faudrait supprimer le grand espace blanc visible quand le bouton n'est pas là. Ca donne l'impression que la carte du pop-up n'est pas ajustée. On peut en rediscuter ensemble @thoomasbro quand tu aborderas le ticket.

**Comment by AdelineCelier** [comment]
**Revue pop-up mission**
Bon pour moi, à part un simple détail : dans la phrase "x contrôle et x surveillance réalisé", le "réalisé" n'est pas toujours accordé en genre et en nombre avec les contrôles et les surveillances. Vu qu'il y a pas mal de cas possibles, on peut dire qu'on retire le mot "réalisé", ça n'empêche pas la compréhension. 

**Revue pop-up contrôles**
- J'ai l'impression que cette pop-up ne s'adapte pas à la largeur des textes comme le fait celle sur la zone de mission ? cf. capture ci-dessous, où elle me paraît assez large)
![image](https://user-images.githubusercontent.com/71878648/231527128-c8dd828b-d9b4-48d0-b43d-f7bfff390f19.png)
 
- Peut-être reformuler les mentions dans la pop-up tant que les champs n'ont pas été remplis (cf. capture ci-dessus)
  - "Thématique à renseigner"
  - "0 contrôle (type cible à renseigner)" (=> là-dessus normalement il n'y aura plus de type de cible 
  - "Date à renseigner" 
- J'ai l'impression que la thématique de contrôle n'est pas en Bold, mais peut-être que je me trompe ? 
- Et je me rends aussi compte que lorsque la thématique est sur 2 lignes, on distingue moins bien les deux infos : d'abord la thématique, puis le nombre de contrôles. Mettre la thématique en Bold et le nb de contrôle en Medium peut aider + ajouter 4 px d'écart entre les deux textes (j'ai màj l'écran dans ce sens)
- Il y a un petit espace en trop entre le type de cible et la parenthèse qui se ferme ;)
-

**Comment by AdelineCelier** [comment]
Remontée de Manon du CACEM : il y a un souci de comptage des contrôles au niveau de la pop-up de mission. J'ai l'impression que ça compte le nombre d'actions de contrôles, et non le nb total de contrôles renseigné au sein du contrôle (dans la colonne 3).

**Comment by AdelineCelier** [comment]
@claire2212 tous les points sont bons, sauf les thématiques qui n'apparaissent pas en Bold chez moi
![image](https://user-images.githubusercontent.com/71878648/233034163-b079eb6a-0a2a-4a84-af46-fb24a7554373.png)

Et puisqu'on est sur des histoires de couleur, tu crois que tu peux aussi passer en Slate Gray toutes les mentions qui restent à renseigner ("thématique à renseigner", "date à renseigner", etc.) ?

**Comment by AdelineCelier** [comment]
Le passage en Slate Gray est bon pour moi, en revanche j'ai l'impression que le Bold c'est pas encore ça :-/ 
Il y a peut-être une légère amélioration mais ça me semble très ténu comme différence entre le Bold et le Medium 
![image](https://user-images.githubusercontent.com/71878648/233682751-92978565-dc8e-4ca5-845e-6787029954c4.png)

**Comment by claire2212** [comment]
j'ai crée le ticket #454 pour régler le souci global des fonts. Je passe ce ticket dans la colonne "To deployed in PROD"
