### ISSUE TITLE
Superposition zones mission contrôle - peu lisible

### ISSUE THREAD

**Issue by manonolivier** [MTES-MCT/monitorenv#1404]
Christophe en a parlé avec @claire2212 lors du point hebdo cette semaine. Je ne trouve pas de ticket mais j'ai un bon exemple de comment ça peut être illisible même avec le fonds de carte clair :
![image](https://github.com/MTES-MCT/monitorenv/assets/147587284/1ac4004c-a6a8-4d02-bc29-0ebce0d94556)

La couche carto verte sur la droite de l'écran est présente là où il y a les contrôles mais on ne la voit plus du tout. Même chose pour les signalements (ils n'apparaissent pas sur la capture d'écran mais ils étaient difficilement visibles)

**Comment by manonolivier** [comment]
Salut @claire2212 @AdelineCelier,
Je me permets de remonter ce ticket, je vois que c'est bien pris en compte dans votre kanban mais avez-vous une idée du temps que ça va prendre ?

**Comment by AdelineCelier** [comment]
Hello @manonolivier, tu fais bien de remonter ce ticket s'il vous pose problème au quotidien. 
On n'a pas encore trouvé la solution pour ce souci mais on met le ticket en haut de la pile et on planche dessus dans les jours qui viennent ! On vous tient au courant.

**Comment by AdelineCelier** [comment]
@claire2212 on a rediscuté de ce ticket avec Clémence et on a identifié une piste pour alléger la carto lorsque c'est l'option "zones définies à partir des actions" qui est active :
- on ne met un cercle bleu qu'autour de la dernière action de contrôle
- on relie les icônes de contrôle à l'icône de mission avec un trait continu (comme pour les sémaphores et leurs signalements)
- les zones de surveillance restent affichées en zone bleue quoi qu'il arrive

Ce système de lien entre la mission et ses contrôle apparaît d'ailleurs sur la capture d'écran de Manon ci-dessus, mais pas dans Env aujourd'hui...est-ce que c'est quelque chose qu'on avait dev et qu'on a finalement retiré ? Je ne vois pas de quelle manière afficher ces liens aujourd'hui en prod.

**Comment by AdelineCelier** [comment]
Ok c'est bon, je pense que ce nouveau système aidera pas mal à la lisibilité de la carte c'est cool !
