### ISSUE TITLE
Signalement - bug quand 2 personnes sont dessus

### ISSUE THREAD

**Issue by manonolivier** [MTES-MCT/monitorenv#1407]
Nous étions deux sur un signalement. J'ai modifié la position et après ma manip Constance a écrit des choses dans "Actions effectuées" et mon écran est devenue blanc. Quand c'est Constance qui est sur le signalement et que c'est moi qui écrit, pas de problème sur son écran mais moi ça devient blanc.

J'ai fait "inspecter" et "console" si jamais ça peut être utile :
![image](https://github.com/MTES-MCT/monitorenv/assets/147587284/55a4f5fc-546a-4829-a646-2a3ecbab64f7)

**Comment by claire2212** [comment]
Salut @manonolivier , ok je regarde ça
