### ISSUE TITLE
Zones Administratives - Ajouter des zones

### ISSUE THREAD

**Issue by thoomasbro** [MTES-MCT/monitorenv#141]
*Zones admin à récupérer*
(à voir avec les géomaticiens - Alexia L?)

- façades
- régions (tracé terrestre)
- départements (tracé terrestre)
- eaux territoriales (comprises entre la limite des 12 milles et la limite des eaux intérieures). Pour cette dernière, soit on fait 2 couches, 1 ZEE et 1 eaux territoriales, soit on fait 3 limites (limite ZEE, limite 12 milles, limite eaux intérieures)
  - Commentaire Alexia : les eaux territoriales sont comprises entre la ligne de base droite et la limite des 12 milles. Les eaux intérieures sont comprises entre la ligne de base droite et la laisse de basse mer (pour visualiser tu as un schéma sur ce site : [Le Shom, expert des délimitations maritimes | Shom](https://www.shom.fr/fr/liste-actualites/le-shom-expert-des-delimitations-maritimes#:~:text=Ainsi%2C%20la%20limite%20de%20la,partir%20de%20ces%20m%C3%AAmes%20lignes.) )
- ligne de base droite ([Carte interactive | limitesmaritimes.gouv.fr](https://limitesmaritimes.gouv.fr/carte-interactive))
- ligne de laisse de basse mer ([Evolution des services web géographiques | Sandre - Portail national d'accès aux référentiels sur l'eau (eaufrance.fr)](https://www.sandre.eaufrance.fr/actualite/evolution-des-services-web-g%C3%A9ographiques)
- limite de salure des eaux (normalement dispo sur datashom)
- zones ECA (_Emission Control Area_), SECA (_Sulphur Emission Control Area_) et NECA (_Nitrogen Emission Control Area_) de la convention Marpol pour les contrôles des émissions Sox Nox.
Les zones données par Alexia ici : [marpol_zones_neca_seca.zip](https://github.com/MTES-MCT/monitorenv/files/10338054/marpol_zones_neca_seca.zip)

suite découpage de #36

**Comment by TEAMCACEM** [comment]
Pouvez-vous ajouter aussi la compétence des CROSS (en lien avec l'affichage des unités) ?

**Comment by TEAMCACEM** [comment]
Les demandes de statistiques ont commencé à arriver pour 2023. Nous avons besoin dans la base de données et dans l'interface Monitor Env de ces limites administratives.

**Comment by TEAMCACEM** [comment]
SVP ce ticket de octobre 2022 n'a jamais été traité... il manque encore toutes les zones administratives dans Monitor Env :
- façades
 - régions
 - départements
 - eaux territoriales
 - ligne de base droite 
- zones ECA (Emission Control Area), SECA (Sulphur Emission Control Area) et NECA (Nitrogen Emission Control Area) de la convention Marpol

**Comment by thoomasbro** [comment]
Comme il y a de nombreuses couches qui viennent de sources diverses, j'ai créé des tickets pour chacune des couches. Cela facilitera le suivi et l'éventuelle priorisation.

Les tickets créés sont mentionnés dans la conversation, le suivi se fera maintenant sur chacun des tickets dédiés.

**Comment by manonolivier** [comment]
Bonjour @AdelineCelier @thoomasbro,

Je reviens sur ce ticket parce que ce n'était pas urgent mais ça le devient un peu.

Principalement pour :
- ligne de basse mer
- limite de salure des eaux (dispo sur MFish donc ça va mais ce n'est pas pratique de naviguer entre les différents outils)
- limite transversale de la mer (je vois que ce n'est pas mis dans les besoins mais c'est la frontière entre DPM et domaine public fluvial donc important qu'on l'ait) (même chose, c'est une limite sur MF donc ça va mais ce n'est quand même pas pratique)

**Comment by AdelineCelier** [comment]
@manonolivier Thomas me confirme que les zones qui sont déjà dans Fish seront faciles à récupérer et à mettre dans Env. Faut qu'on regarde pour la ligne de basse mer, mais en tous cas on rediscute du sujet à notre prochain point de synchro pour essayer de le reprioriser.
