### ISSUE TITLE
Signalement - fenêtre qui remonte quand les champs bloquants sont rentrés

### ISSUE THREAD

**Issue by manonolivier** [MTES-MCT/monitorenv#1414]
Quand on a rempli tous les champs nécessaire à l'enregistrement, la fenêtre "remonte" au début du formulaire, ce n'es pas pratique.

**Comment by claire2212** [comment]
@manonolivier , oui on a un ticket déjà la-dessus : #1383. Je m'en occupe dès que j'ai un moment

**Comment by claire2212** [comment]
Fait dans la pr https://github.com/MTES-MCT/monitorenv/pull/1418

**Comment by AdelineCelier** [comment]
Reste un petit saut, mais le formulaire ne remonte plus !
