### ISSUE TITLE
Sémaphore - ajout lien vers legicem

### ISSUE THREAD

**Issue by manonolivier** [MTES-MCT/monitorenv#1416]
Les sémaphores ATL et MEMN ont des fiches individualisées qui sont en ligne sur legicem. Ce serait possible d'intégrer un lien vers ces articles dans les petits encarts sémaphores ?
Ca nous permet d'avoir un apercu direct sur leur zone de compétence et ce qu'ils ont dans leur secteur qui nous concerne

**Comment by claire2212** [comment]
Hello @manonolivier , @AlexiaLaunay, c'est possible. Il faudrait ajouter une colonne dans la table qgis des sémaphores avec le lien Légicem. Une fois fait tenez-moi au courant (en me donnant le nom de la colonne) et je ferais le nécessaire côté application.
@AdelineCelier pour info

**Comment by AdelineCelier** [comment]
Hello, merci Claire pour l'info. 
@manonolivier @AlexiaLaunay vous pourriez nous donner un ex de fiche sémaphore qu'il y a dans Légicem ? Je ne les ai pas retrouvées. 
Je vois que vous mentionnez des zones de compétence des sémaphores : est-ce que ce sont des tracés que vous avez à dispo ? Si oui, est-ce que ce ne serait pas plus pratique de les mettre directement dans Env ?

**Comment by manonolivier** [comment]
Salut  @claire2212 et @AdelineCelier ,

Top, merci Claire, on te tient au courant quand c'est fait (si ce n'est pas déjà fait)

Voici le lien vers les fiches ATL : https://extranet.legicem.metier.developpement-durable.gouv.fr/fiches-semaphores-namo-sa-a5074.html?id_rub=2370

Justement c'est impossible d'avoir un tracé précis à mettre sur MEnv, c'est pour ça que la solution trouvée était d'effectuer un renvoi vers ces fiches (malheureusement il n'y en a pas encore pour la MED). Impossible d'avoir des tracés précis pour deux raisons : 
- les zones n'ont pas l'air d'être tracées officiellement (on a plusieurs cas de sémaphores qui se renvoient la balle parce qu'ils considèrent que ce n'est pas dans leurs zones) + les zones de compétences peuvent se chevaucher
- les sémaphores n'ont pas de visuel sur tous les alentours du sémaphore et (normalement) les fiches donnent ces précisions (ex : tel arrêté impossible à surveiller car pas de visuel radar / hors de portée VHF, etc)

**Comment by AdelineCelier** [comment]
Ok bien compris, merci @manonolivier pour l'explication !

@claire2212 le lien vers l'écran XD : https://xd.adobe.com/view/eabe87d5-464f-4ff2-b804-04a365edc03b-bfed/screen/6ef168e7-7882-41fd-886d-7901b5f13f7d

**Comment by claire2212** [comment]
Hello @manonolivier , est-ce que ce lien doit être visible aussi sur MonitorExt ou seulement pas vous?

**Comment by manonolivier** [comment]
Salut @claire2212, sur MonitorExt ce n'est pas indispensable mais ce serait bien aussi, je demande juste la confirmation à Pierre et je reviens vers toi directement
