### ISSUE TITLE
Composants - Amélioration liste déroulante

### ISSUE THREAD

**Issue by thoomasbro** [MTES-MCT/monitorenv#142]
*Ajout de menus déroulants pour filtrer les zones*

l'UI du menu déroulant des filtres n'est pas encore tout à fait tel que dans la bibliothèque de composants (couleur de la typo du placeholder, états hover, active et filled, ainsi que couleurs et états des valeurs du menu déroulant).

(repris de #77)

**Comment by AdelineCelier** [comment]
@thoomasbro j'ai voulu aller dans le storybook vérifier direct le composant "dropdown menu", mais je ne l'ai pas trouvé...c'est moi qui ai mal cherché ou c'est normal ? 

Il reste quelques points pour que ce soit iso avec la bibliothèque XD :
- les valeurs des champs doivent être par défaut en Marianne medium Gunmetal 13px
- au survol, ces valeurs doivent passer en Blue Yonder 
- lorsqu'elles sont sélectionnées, elles doivent passer en Blue Gray, et leur fond en Blue GRay 25% (j'ai l'impression que ce n'est pas toujours le cas, cf. menu déroulant des NATINF)
- au survol, le contour du menu déroulant passe en Blue Yonder. Et son contour fait 1px, là j'ai l'impression qu'il est encore plus fin...non ?
- lorsque le menu déroulant est ouvert, son contour passe en Blue Gray (c'est peut-être déjà le cas, mais le contour est tellement fin que j'ai du mal à être sure...et j'arrive pas à retrouver la bonne classe dans l'inspecteur)
- dans le champ de recherche :
  - la loupe a une drôle de tête, j'ai l'impression que son manche est plus petit que sur l'icône que j'ai dessiné ^^
  - les marges autour de la loupe sont de 6px en haut, en bas et à sa droite
  - ok pour mettre un placeholder "rechercher", cela rend plus visible l'action possible. Mettre une marge un peu plus importante à sa gauche, de 8px par ex. 

Ce ticket n'est pas prioritaire, on pourra fignoler tout ça plus tard.
