### ISSUE TITLE
[Carte] Améliorations UX

### ISSUE THREAD

**Issue by claire2212** [MTES-MCT/monitorenv#1445]
Petites corrections / améliorations remontées dans l'EPIC : #1442

- Dans la recherche des lieux, si on tape trop vite le nom (mais pas forcément hyper vite non plus), cela ne remonte rien. Il faut effacer la dernière lettre du mot pour qu'un résultat apparaisse
- La pop-up au survol des zones apparaît aussi lorsqu'on trace une zone/un point de mission ou de signalement, c'est gênant
- La pop-up au survol des zones ne disparaît pas quand on efface le résultat d'une recherche de zones
- Il faudrait que les résultats de la recherche se referment automatiquement quand on clique sur un volet en-dessous. Systématiser la fermeture des autres volets à l'ouverture de l'un d'entre eux

**Comment by AdelineCelier** [comment]
@claire2212 sur le dernier point, je n'ai pas l'impression que ce soit réglé : quand les résultats des zones reg sont ouverts dans la recherche et que je clique sur "zones administratives" par ex, le volet des zones admin s'ouvrent mais le volet des résultats reg ne se ferme pas. Cela fait que les zones admin sont tronquées. 

https://github.com/MTES-MCT/monitorenv/assets/71878648/858e322c-064d-4024-ae27-6d328b92e08e
