### ISSUE TITLE
Ajouter un renvoi vers les missions d'une unité directement depuis sa fiche du module 'moyen'

### ISSUE THREAD

**Issue by AlexiaLaunay** [MTES-MCT/monitorenv#1451]
Hello,

L'idée : dans les contacts des unités (liste des unités de contrôle du module 'moyen'), sous le premier renvoi "créer une mission avec cette unité", ajouter un second renvoi "voir les missions existantes de cette unité" ?

**Comment by AdelineCelier** [comment]
@TEAMCACEM Hello, c'est noté !
Pour l'affichage des missions de l'unité, est-ce que ça vous va si on affiche celles qu'ils ont fait les 6 derniers mois ?

**Comment by AdelineCelier** [comment]
Note : reprendre ce qui a été dessiné dans les premiers écrans XD des moyens.

**Comment by manonolivier** [comment]
@AdelineCelier Est-ce qu'il est possible d'avoir les 6 derniers mois en affichage mais conserver la possibilité d'accéder à l'année en cours ?

**Comment by AdelineCelier** [comment]
Sur ce point, voici ce qui a été dessiné : 
- dans le cas où l'unité n'a pas de mission en cours, on ajoute simplement un bouton "voir les missions de cette unité" en-dessous du bouton "créer une mission avec cette unité" (cf. [cet écran](https://xd.adobe.com/view/e419eaed-c054-4382-b1bb-fdf429fddeb9-b14a/screen/4ff0872e-4592-45de-a487-f103c6830d24)). Ce bouton renvoie vers la vue liste des missions en la filtrant sur les missions de l'unité sur une période de 6 mois. @AlexiaLaunay cela peut être par défaut d'une autre durée si vous préférez, après vous aurez toujours la main sur le filtre pour changer la période si besoin.
- dans le cas où l'unité a une mission en cours, on ajoute un tag "Mission en cours" dans le bandeau de la fiche unité, et on ajoute un bouton "Ouvrir la mission en cours" à côté du bouton "Voir les missions de l'unité" (cf. [cet écran](https://xd.adobe.com/view/e419eaed-c054-4382-b1bb-fdf429fddeb9-b14a/screen/2804b400-cace-489b-9c99-27dcdf8ff90e/)).

**Comment by AdelineCelier** [comment]
@maximeperraultdev ça me semble bien fonctionner, juste 2 points repérés : 
- voilà la bonne icône pour le bouton "voir les missions de l'unité"
![Image](https://github.com/user-attachments/assets/9b0654b2-90ce-4b4c-b99b-aacf974dfc7d)

- quand on passe sur la vue liste pour afficher les missions de l'unité sur les 6 derniers mois, il faudrait afficher le date picker du filtre "période spécifique" avec les dates sélectionnées automatiquement.

**Comment by AdelineCelier** [comment]
c'est good !
