### ISSUE TITLE
Missions – Eviter que la liste des missions remonte automatiquement quand elle s'actualise

### ISSUE THREAD

**Issue by AlexiaLaunay** [MTES-MCT/monitorenv#1454]
Hello,

on a remarqué quelques problèmes sur les listes déroulantes :
- Sur la liste déroulante des signalements : 
quand on fait défiler la liste des signalements, ce n'est pas fluide, ça fait des sauts ce qui rend la recherche d'un signalement difficile

- Sur la liste déroulante des missions :
Lorsqu'il y a une actualisation la liste déroulante remonte automatiquement

- Quand on applique un filtre avec une période spécifique en notant directement les dates au clavier, les calendriers restent affichés et cachent donc la liste

**Comment by AdelineCelier** [comment]
Hello @AlexiaLaunay, 
On revient sur ce ticket qui date un peu, désolée du temps de réponse
- sur la liste des signalements, on ne voit de sauts de notre côté, est-ce que ça le fait tjs chez vous?
- sur la liste des missions : ça on reproduit, on va voir si on peut régler le problème
- sur le filtre "période spécifique" : 
   - aujourd'hui le calendrier disparaît dès qu'on clique n'importe où ailleurs dans l'écran
   - on peut rajouter le fait de masquer le calendrier en tapant sur la touche "Entrée" une fois que vous avez saisi la date. Est-ce que ça vous conviendrait comme ça ?

**Comment by AlexiaLaunay** [comment]
Hello @AdelineCelier ,
On n'a plus de saut non plus pour le défilement de la liste des signalements 👍 
Pour le filtre sur la période spécifique, faire disparaitre le calendrier juste en cliquant à côté est très bien
Merci !

**Comment by AdelineCelier** [comment]
Ok merci pour ta réponse !
Reste juste le point sur la liste des missions : il ne faut pas qu'elle remonte automatiquement quand il y a une actualisation.
