### ISSUE TITLE
Besoin de scroller pour afficher les tabelaux

### ISSUE THREAD

**Issue by manonolivier** [MTES-MCT/monitorenv#1464]
Vous avez peut-être déjà vu mais depuis les dernières mises en prod, on doit déplacer la barre du bas pour afficher les boutons zoomer, dupliquer, modifier et autres sur les tableaux signalements et missions :
![image](https://github.com/MTES-MCT/monitorenv/assets/147587284/e02db278-eca6-4e90-82d5-fef5bc8102be)
![image](https://github.com/MTES-MCT/monitorenv/assets/147587284/131924c6-e75d-4d38-bbca-bac29ebf5c0a)

**Comment by claire2212** [comment]
@manonolivier oui le souci est repéré, on essaye de le régler au plus vite. Désolée pour cette régression

**Comment by manonolivier** [comment]
Ca roule, merci @claire2212

**Comment by AdelineCelier** [comment]
@maximeperraultdev c'est beaucoup mieux comme ça ! Juste 2 questions : 
- est-ce possible de faire en sorte que le scroll soit toujours à 4 px max du bord droit du tableau ? Là quand je mets ma side window en plein écran, la barre de scroll s'éloigne du tableau. 
- est-ce qu'on peut aligner le texte "x signalements" sur le bord droit du tableau et non sur la barre de scroll, pour éviter que le texte soit décalé par rapport au tableau ?

**Comment by maximeperraultdev** [comment]
@AdelineCelier Yes c'est possible. Je vois pas le souci chez moi j'ai un trop petit écran 💻
