### ISSUE TITLE
Filtre de date des tableaux qui bug

### ISSUE THREAD

**Issue by manonolivier** [MTES-MCT/monitorenv#1466]
Pour "aujourd'hui" j'ai des missions d'hier qui sont terminées et complètes : 
![image](https://github.com/MTES-MCT/monitorenv/assets/147587284/c3ce3c11-54c0-4f96-ab0d-1a98f920bf6c)
J'ai mis l'unité ULAM 33 mais ça me le fait avec les autres alors que la date de fin est bien fixée au 15/06 (donc hier)

Quand je mets "une semaine", ça n'a pas l'air de bugger : 
![image](https://github.com/MTES-MCT/monitorenv/assets/147587284/5c00805e-2743-4ee0-9ddc-3755cc8155b3)

**Comment by claire2212** [comment]
@manonolivier ok je regarde

**Comment by AdelineCelier** [comment]
Le filtre de période me semble fonctionner correctement à nouveau.
