### ISSUE TITLE
Ajouter une validation front sur le numéro de téléphone des contacts unités

### ISSUE THREAD

**Issue by VincentAntoine** [MTES-MCT/monitorenv#1467]
Certains numéros de téléphone entrés ne sont pas valables, ce qui les rend inutilisables pour la diffusion automatique de SMS.

- La validation devra permettre la saisie de tous les formats (numéros étrangers, indicatifs...), à creuser pour ne pas en rater.
- Les numéros en base sont saisis avec des espaces - i.e. "06 00 11 22 33" : 
  - retirer les espaces par une migration DB
  - interdire l'introduction d'espaces (via la validation du champ)
  - faire en sorte que l'affichage se fasse comme s'il y avait des espaces, par groupes de 2 chiffres, pour faciliter la lecture
- Certains numéros en base sont d'un format incorrect, au-delà des espaces (par exemple "06 00 00 00 00 ou 07 00 00 00 00", ou encore "BLABLA 06 00 00 00 00"). Ces numéros sont visibles dans le tableau Metabase CACEM / 1 - Suivi utilisation de Monitorenv / Numéros de téléphone au format incorrect. --> A corriger manuellement via Monitorenv

**Comment by maximeperraultdev** [comment]
Question vis à vis des numéros internationaux : 
 - Est-ce que l'affichage se fait comme un numéro français (par groupe de 2 chiffres ou autre)

**Comment by AdelineCelier** [comment]
Ce qui a été acté : 
- interdire les autres caractères que les chiffres, 
- limiter le nombre de chiffres à 17 caractères, 
- permettre de copier-coller n'importe quelle combinaison mais si le n° ne commence pas par 0x ou 00, afficher un message d'erreur sous le champ : "Le numéro saisi n'est pas valide. Si c'est un numéro satellitaire ou d'outre-mer, ajouter 00 avant les premiers chiffres." 
- simplifier les règles de groupage
    - grouper par 2 les n° à 10 chiffres
    - pour les n° commençant par 00, grouper les deux 00 puis faire des groupes de 3 chiffres
    - pour tous les autres n° qui ont des formats moins habituels, grouper les n° par 3

**Comment by AdelineCelier** [comment]
@maximeperraultdev j'ai fait des tests en copiant-collant des n° de téléphone du tableau des unités et moyens, pour avoir des n° réels. Ca marche bien dans l'ensemble je trouve ! 

- [ ] Juste je me rends compte que la règle `pour les n° commençant par 00, grouper les deux 00 puis faire des groupes de 3 chiffres` est ptet un peu bizarre dans le cas de n° à 10 chiffres hors 00 (ex. 00 47 23 41 25 90). Y'aurait moyen de dire que pour ces numéros-là on les groupe par 2 plutôt que par 3 ?
- [ ] Je vois qu'on peut rentrer 18 caractères max, pas 17 : est-ce que c'est parce que tu es tombé sur une autre norme qui disait 18 caractères max ?

**Comment by maximeperraultdev** [comment]
@AdelineCelier Pas de souci pour le 1er point, concernant le deuxieme c'est pour gérer le `+` qui peut être présent.
