### ISSUE TITLE
bug impossible de supprimer un contrôle

### ISSUE THREAD

**Issue by manonolivier** [MTES-MCT/monitorenv#1468]
La DF 64 nous avait dit aller sur un signalement mouillage (n°24-01014) le 15/06. Nous l'avons donc lié à la mission, et ajouté un contrôle avec PV en attente.
![image](https://github.com/MTES-MCT/monitorenv/assets/147587284/d81a97fe-b9fd-4b5d-b0a2-05e649e98531)

Aujourd'hui 17/06 nous recevons le compte-rendu des douane et on voit que finalement ils ne sont pas allé contrôler.
Je veux donc supprimer le contrôle. Je clique sur la poubelle rouge mais ça fait planter tout Monitor. Je ne peux pas cliquer sur des boutons (l'écran n'est pas figé parce que je peux scroller) ni sur la fenêtre signalement/mission/SIG.
Je dois rouvrir un onglet monitor (actualiser ne suffit pas à résoudre le bug).

J'ai essayé de détacher le signalement de la mission. Ce qui n'est pas possible quand le signalement est archivé. Je mets donc une date au hasard dans le signalement, le rouvre et le détache de la mission.
Le contrôle passe de infraction avec PV en attente à contrôle RAS.
Je ne peux toujours pas supprimer le contrôle.

**Comment by claire2212** [comment]
Hello @manonolivier , je viens de tester de supprimer le contrôle rattaché au signalement et j'ai pu le supprimer sans souci. j'espère ne pas avoir fait de bêtise du coup, il reste donc un contrôle sur cette mission et un signalement rattaché. Tiens-moi au courant, je suis au CACEM aujourd'hui et demain si le cas se représente on pourra regarder en direct

**Comment by manonolivier** [comment]
@claire2212 C'était l'autre contrôle qu'on voulait supprimer mais j'ai refait le contrôle lié au signalement et j'ai réussi à supprimer le contrôle RAS

Bizarre parce que c'était impossible de supprimer ce contrôle RAS sur l'ordi de Constance également

**Comment by claire2212** [comment]
@manonolivier oh mince, désolée. Si le souci arrive encore aujourd'hui ou demain, n'hésite pas à me dire

**Comment by manonolivier** [comment]
@claire2212 le problème est encore arrivé. Impossible de supprimer le contrôle entouré de rouge (ni Philippe ni moi y arrivons) : 
![image](https://github.com/MTES-MCT/monitorenv/assets/147587284/7a75b833-a9d5-4a7d-a927-7a226e43df74)
Et même chose, ça fait planter tout monitor

**Comment by claire2212** [comment]
@manonolivier je viens de trouver le souci, je suis dessus.
