### ISSUE TITLE
bug impossible de supprimer une mission

### ISSUE THREAD

**Issue by manonolivier** [MTES-MCT/monitorenv#1470]
Nous n'arrivons pas à supprimer de missions "ULAM 13 le 17/06 à 16h15 qui n'a pas d'actions CACEM de rentré" et "24F le 18/06 à 7h04"

@claire2212 @AdelineCelier apparemment au CNSP non plus ils ne peuvent pas supprimer de mission

**Comment by claire2212** [comment]
@manonolivier oui, on a mis en place lors de la dernière mise en production la vérification des actions côté RapportNav, mais on a un souci technique, je fais le point avec la DSI cet après-midi. Je vous tiens au courant

**Comment by claire2212** [comment]
@manonolivier on a trouvé le souci, mais on a toujours pas de réponse de la DSI. Je te dis dès que c'est réglé

**Comment by claire2212** [comment]
@manonolivier on peut clôturer ce ticket?

**Comment by manonolivier** [comment]
yes @claire2212
