### ISSUE TITLE
[Zones de vigilance] Création du formulaire de zone de vigilance

### ISSUE THREAD

**Issue by claire2212** [MTES-MCT/monitorenv#1477]
- Création du formulaire de vigilance (sans lien aux AMP/ zones réglementaires + sans ajout d'images)
- Création de la vue de consultation d'une zone de vigilance
- Pour le moment affichage de toutes les zones de vigilances par défaut sur la carte 
- Création du bouton pour créer une zone de vigilance

EPIC: #1462

**Comment by AdelineCelier** [comment]
## Retours UX

- [ ] J'ai voulu supprimer un polygone tracé dans le formulaire, mais quand j'ai tracé de nouvelles zones, l'ancienne zone est réapparue. Et j'ai l'impression que ça a supprimé le nom de la zone en même temps. Mais je n'arrive pas à reproduire...
- [ ] Ce que j'arrive à reproduire, c'est que quand je clique sur la poubelle pour supprimer le polygone, celui-ci ne disparaît pas, il ne disparaît que si je reclique sur le bouton "définir un tracé pour la zone de vigilance". 
- [ ] J'ai par mégarde tracé une zone "croisée" (ou "papillon") et n'ai pas compris tout de suite pourquoi je ne pouvais pas valider les tracés. On pourrait peut-être afficher une erreur sous le bouton disant "le tracé n'est pas valide" ?
- [ ] Quand je clique sur "enregistrer", le formulaire se ferme complètement au lieu de revenir à la vue de consultation

## Retours UI

- [ ] Le daterange picker s'affiche avec un grand espace à gauche
![Image](https://github.com/MTES-MCT/monitorenv/assets/71878648/2e60a569-af04-475c-9455-9c3c7afc7a25)

- [ ] Une demi-case vide s'affiche au début du menu déroulant des thématiques
![Image](https://github.com/MTES-MCT/monitorenv/assets/71878648/60ab7731-a698-478e-adb8-d1eaf97e3663)

- [ ] La zone tracée s'affiche sur 2 lignes, possible de ne l'afficher que sur une seule ?
![Image](https://github.com/MTES-MCT/monitorenv/assets/71878648/b2df2bfc-40ef-4dcd-9fe6-af363a858a48)

- [ ] Il faut 4 px d'écart entre les différents liens utiles
![Image](https://github.com/MTES-MCT/monitorenv/assets/71878648/e7c21f3c-eca4-4aa7-af9a-2d32adad24a3)

**Comment by AdelineCelier** [comment]
@claire2212 

- [ ] je me demande si c'est utile au final d'afficher les sections pour lesquelles rien n'a été rempli : dans l'exemple ci-dessous, je me dis qu'on peut virer la section "réglementations en lien" et "liens utiles" non ?
![Image](https://github.com/MTES-MCT/monitorenv/assets/71878648/d9f41d9e-48d1-4aab-8e48-9ff37e5413a8)

- [ ] je n'avais pas vu à la première revue, désolée, mais le date picker pour la définition de la fin de la récurrence est tronqué, on ne peut pas changer de mois dans le calendrier
![Image](https://github.com/MTES-MCT/monitorenv/assets/71878648/9949254d-6882-4399-8a05-fdb990faff22)

**Comment by claire2212** [comment]
@Adeline, pour le fait de ne pas afficher les sections non remplies, j'ai peur qu'on se retrouve avec des affichage un peu "légers" des fois. Si par exemple la personne n'a renseignée que le minimum (nom +  tracé sur la carte), on n'aurait rien à afficher, donc on aurait juste le header et le footer ?

**Comment by AdelineCelier** [comment]
Ok tous les points cochés sont bons pour moi ! 
@claire2212 oui je comprends ta crainte...disons qu'on pourrait laisser affichées les sections qui sont obligatoires pour la publications, et masquer celles qui ne le sont pas si rien n'a été saisi dedans. Ça concerne donc : 
- les reg en lien
- les AMP en lien
- les liens utiles
- la source de l'info

Ça te semblerait ok ? Et bien entendu ce n'est pas bloquant pour la mep !
