### ISSUE TITLE
Rapportage - doublons sur les natinfs

### ISSUE THREAD

**Issue by thoomasbro** [MTES-MCT/monitorenv#150]
La table natinf (infractions) est importée automatiquement. Les champs récupérés sont:
- id
- natinf_code
- regulation
- infraction_category
- infraction
Les champs affichés sont natinf_code et infraction

Il y a un certain nombre de doublons, au moins sur le code natinf.

Doit-on stocker uniquement le natinf ?

Faut il trouver un moyen de dédoublonner la liste ?

**Comment by AdelineCelier** [comment]
@thoomasbro je n'avais pas vu tes questions, qu'as-tu statué en fin de compte ?

**Comment by thoomasbro** [comment]
J'ai décidé de dédoublonner en prenant la première entrée de la table pour chaque natinf, en triant les natinfs par la colonne "regulation". Cette colonne est parfois vide, donc le tri me permet de récupérer en priorité les lignes pour lesquels cette colonne est renseignée.

**Comment by AdelineCelier** [comment]
Ok, et du coup dans la colonne "regulation" il y avait quoi ?

**Comment by thoomasbro** [comment]
Souvent l'article de loi correspondant
