### ISSUE TITLE
Moyen de contact unité modification automatique

### ISSUE THREAD

**Issue by manonolivier** [MTES-MCT/monitorenv#1505]
On voudrait rajouter à toutes les unités Marine nationale Atlantique et Manche la mention "vérifier selon la zone de mission" dans l'encart "Modalités de contact avec l’unité"
Parce que les moyens marine Atlantique peuvent faire des mission en Manche et vice versa. Ca peut donc porter à confusion.
A la main ça va être un peu fastidieux donc nous nous demandions s'il était possible de l'automatiser ?

**Comment by claire2212** [comment]
Hello @manonolivier oui je pense que c'est possible, je m'en occupe. Par contre il me faudrait la liste des unités concernées si possible.

**Comment by manonolivier** [comment]
Salut @claire2212, je t'envoie ça par mail

**Comment by claire2212** [comment]
Hello @manonolivier, c'est fait. Par contre tu verras que tout se met sur une ligne (avec les commentaires qui étaient déjà présents). Mais ce sera fixé lors de la prochaine MEP (j'ai ajouté les retours à la ligne)
