### ISSUE TITLE
Signalements - champs bloquants

### ISSUE THREAD

**Issue by manonolivier** [MTES-MCT/monitorenv#1515]
Est-ce qu'il serait envisageable d'ajouter des champs bloquants dans les signalements pour éviter les oublis ?
Pour l'instant, il y en a surtout pour la taille des navires. Ce champ est indispensable pour les mouillages mediterranée mais pas forcément pour le mouillage ailleurs ou pour les travaux en milieu marin.
S'il était possible de faire une alerte quand ce n'est pas rempli au lieu d'un champ bloquant ce serait top.
Et sinon, un champ bloquant c'est pas dérangeant et on mettra UNK ou 0 quand on ne souhaite pas rentrer la taille

**Comment by AdelineCelier** [comment]
@manonolivier étant donné que le champ ne serait pas bloquant tout le temps, je pense qu'il vaut mieux mettre un message de rappel en effet. 
Je propose qu'on mette un encart informatif au moment où la thématique "mouillage" est saisie, dans le cas où la taille du navire n'a pas été remplie, disant : "N'oubliez pas d'indiquer la taille du navire si la réglementation s'appliquant à la zone de mouillage dépend de la longueur du navire" (ou quelque chose de similaire.

**Comment by manonolivier** [comment]
@AdelineCelier oui un message de ce type peut être suffisant. Au lieu de parler de la taille peut-être parler de l'identification générale du navire ?

**Comment by AdelineCelier** [comment]
@manonolivier mmmh qu'entends-tu par l'identification générale ? Pour rappeler aussi de remplir au moins un identifiant (MMSI, IMO ou immat) ? J'avais l'impression que c'était surtout la taille du navire qui posait pb, c'est pour ça que je l'avais tourné comme ça.

**Comment by manonolivier** [comment]
@AdelineCelier Oui c'est ça pour rappeler de mettre immat, type de navire, nom qui peuvent aussi manquer (moins souvent mais possible. C'était aussi pour que ce soit un message moins long

**Comment by AdelineCelier** [comment]
@manonolivier ok, je récap alors : 
- le message bleu doit s'afficher quand la thématique "mouillage" est choisie et que : 
  - aucun identifiant de navire (nom, MMSI ou immat) n'a été rempli 
  - la taille du navire n'a pas été remplie
  - le type de navire n'a pas été rempli ? **mais est-ce que c'est une info que vous avez systématiquement ?**
- on ajuste le message en disant : "N’oubliez pas d’identifier le navire et d'indiquer sa taille du navire afin de permettre un bon traitement du signalement". 

Qu'en penses-tu ?

**Comment by AdelineCelier** [comment]
Ok allez on part là-dessus ! 
Je récap la règle pour quand doit s'afficher l'encart bleu : 
- s'il manque un des 3 identifiants (MMSI/IMO/immat)
- s'il manque le nom du navire
- s'il manque la taille du navire
- s'il manque le type du navire

**Comment by AdelineCelier** [comment]
Parfait !
