### ISSUE TITLE
Bug - signalement ne se créé pas

### ISSUE THREAD

**Issue by manonolivier** [MTES-MCT/monitorenv#1526]
Je n'ai pas beaucoup d'explications donc je ne sais pas si ça va vous être utile mais dans le doute :
j'ai créé un signalement et rempli tous les champs bloquants mais il n'a pas voulu se créé :
![image](https://github.com/MTES-MCT/monitorenv/assets/147587284/06badbd2-9178-45d3-a33a-497691e275d2)
J'ai donc fermé le signalement, il ne s'est pas enregistré et j'ai du tout retaper

**Comment by claire2212** [comment]
Hello @manonolivier ok je vais regarder, si ca arrive à nouveau essaye de re-saisir juste un champ pour voir si ça créé le signalement ensuite. Je veux bien que tu me tiennes au courant si ce petit "hack" fonctionne, ça me donnera des pistes

**Comment by manonolivier** [comment]
Salut @claire2212 c'est arrivé de nouveau et en effet en supprimant puis retapant le MMSI ça a fonctionné
