### ISSUE TITLE
Recherche cible contrôle dans les missions

### ISSUE THREAD

**Issue by manonolivier** [MTES-MCT/monitorenv#1566]
J'ai essayé avec un contrôle du 17/07 par la BN Roquebrune les Issambres qui a contrôle le navire qui s'appelle "Q" mmsi : 319560000.
La recherche par mmsi fonctionne mais pas quand on cherche le nom du navire.

J'ai essayé avec un autre navire, le VOYAGER et ça fonctionne bien. Peut-être qu'on en peut pas chercher qu'une seule lettre ?

**Comment by maximeperraultdev** [comment]
@manonolivier Effectivement la recherche ne commence qu'à partir de 3 caractères saisies

**Comment by manonolivier** [comment]
@maximeperraultdev Bien noté C'est possible de la faire commencer à partir de une lettre ? Si c'est impossible, pas de soucis, je passerai l'information aux autres et nous ferons les recherches par MMSI quand c'est possible

**Comment by maximeperraultdev** [comment]
@manonolivier Oui je pense que c'est possible. Ce comportement est le même que la recherche de cible sur les signalements. Si vous voulez je peux également permettre la recherche dès le premier caractère.

**Comment by manonolivier** [comment]
@maximeperraultdev yes ce serait pas mal, on a quelques navires qui n'ont qu'une seule lettre merci !

**Comment by AdelineCelier** [comment]
C'est bon pour la recherche sur une seule lettre !
