### ISSUE TITLE
La requête PATCH renvoie `Invalid CORS request` quand on veut mettre à jour un contact

### ISSUE THREAD

**Issue by VincentAntoine** [MTES-MCT/monitorenv#1569]
Reproduction : sélectionner une unité, cocher ou décocher la case "contact de diffusion" d'un numéro de téléphone. Cliquer sur "Enregister les modifications" : les modifications ne sont pas prises en compte et la requête PATCH échoue et renvoie `Invalid CORS request`

**Comment by ivangabriele** [comment]
J'ai passé un bon moment avec la DSI mais je ne pense pas que cela vienne de leur part.

La configuration Apache du serveur d'intégration déclare `Access-Control-Allow-Origin` et `Access-Control-Allow-Methods` à ALL (`*`) (ce n'est d'ailleurs pas son rôle à mon avis mais c'est un autre sujet).
La configuration Apache du serveur de production déclarait seulement `Access-Control-Allow-Origin` à ALL. Au cas où, j'ai fait aussi ajouter `Access-Control-Allow-Methods` pour être ISO mais ça n'a évidemment pas régler le soucis.

Il n'y a rien concernant la réécriture potentielle de headers dans un sens ou dans l'autre du côté du reverse proxy. Il n'y a rien dans les logs d'erreur Apache et les requêtes PATCH renvoyant `Invalid CORS request` passe comme une réponse normale dans les logs Apache.

Après une petite recherche Google je peux confirmer que seul Spring peut renvoyer ce genre de réponse.

De manière à la fois étrange et intéressante, **j'ai réussi à faire passer le PATCH en prod sans erreur en faisant un curl à partir du serveur d'intégration.**

> Les PATCH fonctionnait sans soucis en prod dans la première version que j'avais développé, il y a donc sûrement quelque chose de différent dans le code backend, dans les configs ou dans les mais qui a produit cette erreur.

> Ma recommandation est de chercher de ce côté-là.

L'autre solution en attendant est de bypasser complètement le problème en désactivant totalement les CORS sur Spring.
