### ISSUE TITLE
[Zone de vigilance] Pouvoir filtrer les zones de vigilance par zone et par thématique

### ISSUE THREAD

**Issue by claire2212** [MTES-MCT/monitorenv#1579]
Filtrage des zones de vigilance: 
- Afficher des zones de vigilance selon une zone déterminée
- Afficher des zones de vigilance selon des thématiques
- Pouvoir enregistrer des zones de vigilance dans "Mes zones de vigilances"

EPIC: https://github.com/MTES-MCT/monitorenv/issues/1462

**Comment by AdelineCelier** [comment]
@claire2212 tout a l'air bon pour moi, à part le bug que tu avais déjà relevé sur le nom de la zone de vigilance dans la recherche. 

![Image](https://github.com/user-attachments/assets/9f287bdc-f7e0-40e5-9bd6-94297ca804a4)

**Comment by AdelineCelier** [comment]
Top c'est good
