### ISSUE TITLE
signalement - pouvoir décocher ce qu'on a rentré

### ISSUE THREAD

**Issue by manonolivier** [MTES-MCT/monitorenv#1582]
J'ai coché "moteur" dans type de navire pour un signalement avant de me rendre compte que je n'avais pas l'info pour ce navire. Je veux donc laisser ce champ non rempli
Je ne peux pas décocher "moteur", je suis donc obligée de refaire tout le signalement.

**Comment by AdelineCelier** [comment]
A voir s'il ne faudrait pas généraliser ce comportement à tous les composants de sélection simple ?

**Comment by AdelineCelier** [comment]
ça m'a l'air bon, il manquait la croix qui permet de supprimer la sélection sur le champ "type de navire".
