### ISSUE TITLE
[Statistique][Actions] Les actions de type NOTE sont à l'état `TO_COMPLETE`

### ISSUE THREAD

**Issue by maximeperraultdev** [MTES-MCT/monitorenv#1636]
## Piste

- L'attribut `completion` n'est pas présent sur l'objet `EnvActionNoteEntity`
- Le typage en base de données est une énumération `mission_action_completion default 'TO_COMPLETE'`

### Related issue

https://github.com/MTES-MCT/monitorenv/issues/1629

**Comment by VincentAntoine** [comment]
OK en inté
