### ISSUE TITLE
Ajout et visualisation de photos

### ISSUE THREAD

**Issue by claire2212** [MTES-MCT/monitorenv#1643]
Pourvoir ajouter, consulter et supprimer des photso dans une zone de vigilance

**Comment by AdelineCelier** [comment]
@claire2212 ça marche bien ! je vois juste 2 points : 

- l'icône avec la poubelle me semble vraiment très petite, possible de mettre l'icône à 14 x 14 px, voire 16x16 ? on peut faire des tests ensemble si tu veux.
- quand j'essaye de charger un doc qui n'est pas au bon format (type pdf), j'ai bien un bandeau d'erreur qui apparaît, mais je me demande si ça ne serait pas plus clair de mettre explicitement une phrase d'erreur (au même endroit que la phrase "vous avez atteint le nb max d'images") disant "les formats .pdf ne peuvent pas être ajoutés" (et spécifier les principaux formats qui ne marchent pas).
