### ISSUE TITLE
Unité archivée qui apparait toujours sur leISG

### ISSUE THREAD

**Issue by manonolivier** [MTES-MCT/monitorenv#1646]
Les unités archivées appariassent toujours sur le SIG (exemple de la BN Saint-Cast). Est-ce possible de faire en sorte qu'elles n'apparaissent plus ?

Problème "aggravé" maintenant qu'il est possible de créer une mission via la fiche de l'unité. En effet, on peut ouvrir la fiche de la BN Saint Cast et ouvrir une mission avec cette unité alors qu'elle n'existe pas. Pour ce cas, ce n'est pas grave puisqu'elle n'existe plus du tout, on ne risque pas de l'avoir au téléphone mais pour une unité archivée parce que c'est un doublon ou dont le nom ressemble à une unité toujours en place, c'est un risque d'erreur.

**Comment by claire2212** [comment]
Hello @manonolivier c'est réglé je pense. Tu confirmes ?
