### ISSUE TITLE
Rapportage - Permettre la clôture de la mission

### ISSUE THREAD

**Issue by thoomasbro** [MTES-MCT/monitorenv#167]

**Comment by AdelineCelier** [comment]
@thoomasbro de mon côté, ça ne fonctionne toujours pas : je ne peux pas clôturer une mission, quand bien même j'ai rempli les champs de fin de mission, d'administration, unité et même zone de mission.

**Comment by AdelineCelier** [comment]
C'est bon, on peut bien clôturer direct une mission !
