### ISSUE TITLE
Impossible de retours depuis fiche unité

### ISSUE THREAD

**Issue by manonolivier** [MTES-MCT/monitorenv#1675]
Quand on clique sur la fiche d'une unité depuis la fenêtre de recherche des unités, il n'est pas possible de retourner directement à la recherche, il faut cliquer sur la croix puis recliquer sur le bouton "liste des unités". Est-ce qu'il est possible d'avoir un bouton retour en arrière sur les fiches unités ?
Pour l'instant, on a juste une croix : 

![Image](https://github.com/user-attachments/assets/687ff13e-e7d2-46a7-a733-6236295aaa80)

Ce n'est pas très dérangeant parce que lorsque l'on clique de nouveau sur "Liste des unités" notre ancienne recherche n'a pas disparu mais ce serait juste un peu plus pratique

**Comment by AdelineCelier** [comment]
@manonolivier oui c'est vrai que je me suis déjà fait la réflexion aussi !
C'est noté, on va regarder ça.

**Comment by AdelineCelier** [comment]
@claire2212 comme discuté, je propose de faire un truc assez simple : on rajoute un chevron "retour" à gauche dans le bandeau de la fiche unité, et donc on centre le nom de l'unité dans le bandeau. 
Cf [écran ici](https://xd.adobe.com/view/e419eaed-c054-4382-b1bb-fdf429fddeb9-b14a/screen/04ebe383-0bc8-404f-bd86-3c6816d2ad33).
