### ISSUE TITLE
AMP épinglées - fenêtre qui ne s'étend pas

### ISSUE THREAD

**Issue by manonolivier** [MTES-MCT/monitorenv#1677]
La fenêtre ne se développe pas et reste toute petite, je dois donc scroller pour voir les différentes couches AMP

![Image](https://github.com/user-attachments/assets/5a635139-ce78-433c-9acd-0b8c46e09a66)

![Image](https://github.com/user-attachments/assets/ab8fc1fb-26e5-4bad-9afb-5fc6f94fc1f5)

**Comment by AdelineCelier** [comment]
ça me semble déjà mieux comme ça !
