### ISSUE TITLE
Vue par défaut des missions à passer en "aujourd'hui"

### ISSUE THREAD

**Issue by manonolivier** [MTES-MCT/monitorenv#1683]
Pour l'instant, la vue par défaut est sur une semaine et personne au CACEM l'utilise. Tout le monde rebascule sur la vue "aujourd'hui". Est-ce qu'il serait possible que ce soit par défaut la vue aujourd'hui, comme ça quand on clique sur "réinitialiser les filtres" ça nous met sur la vue que nous utilisons au quotidien

**Comment by AdelineCelier** [comment]
good !
