### ISSUE TITLE
Missions - Ajustements filtres dans le tableau des missions

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorenv#169]
J'ai mis à jour les écrans concernant les filtres du tableau des missions (écrans [47](https://xd.adobe.com/view/973ae2b4-ecd1-419f-b092-8545e0d8ce57-c269/screen/6e95f927-d9fe-4d94-95c5-d1d59689ec6c/) à [50](https://xd.adobe.com/view/973ae2b4-ecd1-419f-b092-8545e0d8ce57-c269/screen/ee528d65-c43f-41f4-a9c4-03cb1049948a/)).

Voici pour moi les filtres importants et leurs valeurs : 
- Période
  - Aujourd'hui
  - Semaine en cours
  - Mois en cours
  - Trimestre en cours
  - Période spécifique : le choix de cette valeur fait apparaître le date range picker (cf écrans)
- Statut 
  - En cours
  - Terminée
  - Clôturée 
- Façade
  - liste des façades dans lesquelles une mission a été saisie
- Administration 
  - liste des administrations, avec une barre de recherche dans le menu déroulant du filtre (ce filtre est une demande du CACEM)
- Unité
  - liste des unités, avec une barre de recherche dans le menu déroulant du filtre [PRIORISÉ]
- Type de mission
  - Mer
  - Terre 
  - Air 
- Nature de contrôle : ce filtre pour moi va détecter les missions pour lesquelles des contrôles env ou pêche ont été ouverts. Car on ne peut pas trop s'appuyer sur le champ "nature de mission", qui s'appelle maintenant "intention principale de mission"
  - Env
  - Pêche

**Comment by AdelineCelier** [comment]
@thoomasbro j'ai oublié de reporter un point abordé pendant la réunion CACEM de vendredi dernier : ils souhaiteraient que le champ NATINF soit bloquant même si c'est "Sans PV" qui est coché ! En gros dès qu'il y a eu infraction, il faut y associer un NATINF, qu'il y ait eu PV ou non. Le seul cas où le NATINF ne serait pas bloquant serait si le type d'infraction est "en attente". Et dans ce cas d'ailleurs ce serait intéressant de remonter un tag dans la colonne "alerte" de la vue liste des missions, disant qu'il y a une infraction à compléter.

**Comment by TEAMCACEM** [comment]
il manque le filtre façade ?

**Comment by claire2212** [comment]
EDIT : 
 -Ajouter la possibilité de pouvoir sélectionner plusieurs administrations et plusieurs unités
- Ajouter un filtre thématique + pouvoir filtrer la colonne
- Enlever la colonne "Alerte"

**Comment by AdelineCelier** [comment]
@claire2212 de ce que j'ai pu voir malgré le bug sur les façades, cela me semble bien fonctionner ! Mais je vous propose de quand même bien revoir ce ticket en intégration de votre côté une fois la question des façades réglées. 

Le seul retour que j'ai n'est pour moi pas bloquant pour une mep, mais à régler quand même car c'est perturbant : 
les menus déroulants s'affichent par-dessus les champs des filtres, et non sagement en-dessous ^^ 
![image](https://user-images.githubusercontent.com/71878648/233708611-074fe464-e1e0-457a-b7cd-efacabf1870a.png)
