### ISSUE TITLE
Zones de vigilance – Revoir le comportement du volet carto afin de permettre l'affichage de toutes les zones de vigilance

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorenv#1698]
Afin de faciliter l'affichage des différentes types de zones (reg, AMP, vigilance), revoir le comportement du volet carto : 
- faire en sorte que les 3 tiroirs des 3 différents types de zones apparaissent dès que le volet carto est ouvert (aujourd'hui, elles n'apparaissent qu'à partir du moment où tu as lancé une recherche avec un mot-clé ou un filtre)
- par défaut les cases à cocher des 3 tiroirs sont décochées, mais si tu en coches 1 ça affiche les zones (comme quand tu coches un filtre par ex)
- pour donner conscience à l'utilisateur du nb de zones qu'il va potentiellement afficher, afficher entre parenthèses le nb total de zones pour chaque type (et ça s'ajuste si tu rajoutes des filtres, comme aujourd'hui). Aujourd'hui tant qu'il n'y a pas de recherche lancée, chaque type de zone affiche "(0 zone)"

**Comment by claire2212** [comment]
@AdelineCelier quand tu testeras, je veux bien que tu testes tous les cas (recherche par texte, par filtre, par zone, quand les items sont cochés et qu'on fait une recherche, quand ils sont décochées etc etc) pour voir si le comportement est ok pour toi. J'ai déjà bien testé mais je ne voudrais pas oublier un cas où on se retrouve avec toutes les couches affichées (ce qui a mon avis peut faire planter l'app)
A noté que ce comportement se répercute aussi sur MonitorExt

**Comment by AdelineCelier** [comment]
@claire2212 j'ai essayé de tester un peu dans tous les sens, et je vois juste un cas où ça a l'air de déconner : 
- je fais une recherche "quiber" dans la barre de recherche, ça m'affiche 25 résultats en zone reg, 4 en AMP et 0 en ZV. 
- quand j'efface le mot "quiber", je retrouve la totalité des résultats pour les zones reg et pour les AMP, mais pas pour les ZV, qui restent à 0.

![Image](https://github.com/user-attachments/assets/f3762323-efcd-46d3-b779-5a2116240d32) 
![Image](https://github.com/user-attachments/assets/625b92d5-9b46-4c98-a7ca-e9e2ec45feeb)

**Comment by claire2212** [comment]
@AdelineCelier oui j'avais repéré ce bug, je l'ai réglé dans la pr sur le tableau des zones de vigilance. Je repasse ce ticket dans to deploy in Int, si ca te va

**Comment by AdelineCelier** [comment]
ça marche !

**Comment by AdelineCelier** [comment]
le souci me semble bien réglé !
