### ISSUE TITLE
2/ Étendre les résultats de la recherche aux autres champs des métadonnées

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorenv#17]
Pour optimiser les chances de trouver la bonne info, je pense qu'il faut que la barre de recherche tape dans tous les champs :
- layer name
- entity name
- façade
- ensemble reg
- thématique
- références réglementaires

A voir si ça fait trop large et si ça remonte trop de choses, mais a minima il faut aller chercher les champs façade et surtout thématique.

**Comment by thoomasbro** [comment]
Je trouve ça étrange de rechercher dans façade avec la recherche full text.
Si je tape "namo" je suis sensé retrouver toutes les couches namo. Ok, mais ça me semble étrange comme recherche.

Si je tape "namo amp", je voudrais uniquement les amp en zone namo. Ca me semble cohérent. Mais si je tape "med amp", je vais récupérer toutes les couches avec le texte "med", sans que ce soit forcément lié à la façade "med". 

Il faut que je réfléchisse un peu plus à l'archi de l'outil de recherche pour avoir des résultats pertinents.

Est ce qu'on pourrait essayer de récupérer des exemples de recherche ?

**Comment by thoomasbro** [comment]
Si on recherche dans des champs qui ne sont pas affichés sur la liste de résultat, il n'y aura pas de highlight et il pourrait être  difficile de comprendre pourquoi un résultat a été retourné.

**Comment by AdelineCelier** [comment]
Oui je vais essayer de recenser des exemples de recherche, de voir ce que les utilisateurs ont le réflexe de taper dans la barre de recherche. 
J'entends la question du highlight, pour les façades on pourrait le faire sur les titres de façade qui apparaissent dans les résultats de recherche. Pour les thématiques c'est plus complexe. Mais en même temps aujourd'hui tu ne vois pas un highlight sur un mot qui est dans le titre d'une zone, à l'intérieur d'un layer name...il faut qu'on affine cette question effectivement.

**Comment by AdelineCelier** [comment]
Je ne suis pas sure que ce ticket soit toujours pertinent. 
Je pense qu'il faut voir à l'usage si le système de mots-clés ne suffit pas. Je ne suis pas sûre finalement qu'étendre la recherche par mots-clés au champ "référence rég" soit très utile.
Je propose de fermer ce ticket, on en rouvrira un si des problèmes ou des améliorations sont identifiés sur la recherche par mots-clés.
