### ISSUE TITLE
Rapportage – Pouvoir dupliquer des infractions au sein des contrôles

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorenv#170]
Retour du CACEM (mail de Manon du 04/11/2022) :
"Est-il possible d’ajouter la fonction dupliquer (qui existe pour les actions faites lors des missions) aux infractions (la plupart du temps les personnes qui reçoivent un PV lors d’un contrôle ont souvent commis les mêmes infractions) ?"

Plus de détails le 01/02/23 :
> Exemple : Lors d'une mission, j'ai eu 28 contrôles mouillages et 28 rappel à la règlementation. Cela équivaut dans Monitor Env à enregistrer 28 infractions sans PV avec le natinf 4473. Il est indispensable de pouvoir dupliquer l'infraction pour faciliter la saisie. Autrement je dois créer 28 infractions et c'est terriblement long et fastidieux. Idem pour la pêche à pied, cela va être très fastidieux pour les infractions sans ou avec PV.

**Comment by AdelineCelier** [comment]
@TEAMCACEM on va s'occuper de cette question de la duplication des infractions. 
Juste pour comprendre comment vous renseignez les infractions actuellement : vous ne renseignez jamais l'identité (immat ou nom) de la cible contrôlée ? Et si vous ne le faites pas, c'est parce que l'unité n'est pas capable de vous donner l'info ? Parce que ce n'est pas pratique ? Je pose cette question aussi parce que si l'on veut créer un historique de contrôle et identifier de possibles multirécidivistes cela passe par ces infos-là. C'est peut-être un changement d'habitude à prendre avec les unités, j'imagine que ça ne se fera pas en qques jours. 
Bref mais si je pense à ça, c'est parce que les fois où l'identité/l'immat seront saisies, il faudra faire attention à ce que ces infos ne soient pas dupliquées (peut-être une forme de vérif auto à mettre en place).

**Comment by TEAMCACEM** [comment]
On a pas souvent l'info de la cible contrôlée (immat ou nom) mais ça va surement évoluer, c'est pourquoi on l'a prévu.
En effet, si on a à le renseigner, cela ne peut pas être dupliquer.

**Comment by TEAMCACEM** [comment]
C'est super on peut dupliquer les infractions. En revanche on ne sait pas laquelle on duplique.
Pouvez-vous faire apparaitre le numéro de natinf dans le résumé de l'infraction pour savoir quelle infraction dupliquer ?
Exemple : 1 infraction le code natinf 2593 et 3 infraction à le code natinf 12900 à dupliquer. Je ne peux pas savoir quelle infraction dupliquer sans regarder dans l’infraction. Cela peut être source d'erreur si on dupliquer la mauvaise infraction.

**Comment by AdelineCelier** [comment]
Ok bien vu. J'ai retouché le résumé de l'infraction pour faire apparaître le n° de NATINF (c'est comme ce que j'avais dessiné pour Fish maintenant). Ce qui change : 
- les infos sont affichées sous forme de tags
- les n° de NATINF sont spécifiés, en plus du nb de NATINF
- s'il n'y a pas de mise en demeure, le tag n'apparaît pas (ça faisait une info supplémentaire sans grande valeur ajoutée je trouve). 

@louptheron tu crois que tu pourrais te charger de ces retouches ?
