### ISSUE TITLE
Zone de vigilance - Impossible de sélectionner une reg épinglée

### ISSUE THREAD

**Issue by manonolivier** [MTES-MCT/monitorenv#1753]
C'est dommage de ne pas pouvoir associer une règlementation que nous avons épinglé à une zone de vigilance. L'onglet "Mes zones réglementaires" apparait bien mais il n'y a pas le "+" : 
![Image](https://github.com/user-attachments/assets/03c3efcf-3743-4236-a561-9c28c7ec4968)

**Comment by claire2212** [comment]
Hello @manonolivier ah oui effectivement, ca doit être in régression, je m'en charge. Bonne journée
