### ISSUE TITLE
Recherche dans sous thématique

### ISSUE THREAD

**Issue by manonolivier** [MTES-MCT/monitorenv#1762]
Est-ce que ce serait possible de permettre la saisie des thématiques via les sous-thématiques. Un peu comme le fonctionnement des unités (on peut remplir d'abord l'unité et l'administration se remplit automatiquement) ?
Ca faciliterai par exemple l'usage des sous-thématiques qui se trouvent dans "autres".

**Comment by claire2212** [comment]
Hello @manonolivier , ok je fais ça. Est-ce que je le fais pour les signalements et les missions?

**Comment by AdelineCelier** [comment]
@claire2212 je n'ai pas réussi à reproduire le bug, même en bidouillant dans tous les sens, je pense qu'on peut dire que c'est bon !

**Comment by manonolivier** [comment]
salut @AdelineCelier et @claire2212, ce serait cool de le faire partout yes

**Comment by AdelineCelier** [comment]
c'est bon pour les accents !
