### ISSUE TITLE
bug - les couches n'apparaissent plus après une simple recherche

### ISSUE THREAD

**Issue by manonolivier** [MTES-MCT/monitorenv#1763]
Normalement avec une simple recherche, pas besoin de cliquer sur l'oeil ou d'épingler la couche pour qu'elle apparaisse : 

![Image](https://github.com/user-attachments/assets/7de34b18-fd95-4935-aed4-1a6ead662b93)

mais pour certaines ça ne fonctionne pas : 

![Image](https://github.com/user-attachments/assets/644d6be0-afdf-4e85-9b37-a768befb982c)

![Image](https://github.com/user-attachments/assets/ceb7c1b1-7673-40ca-9061-75f684482e6f)

**Comment by claire2212** [comment]
Salut @manonolivier , effectivement je reproduis bien le souci. je regarde ça

**Comment by claire2212** [comment]
@manonolivier on vient de trouver la source du problème. Cela vient du champ de recherche, si tu tapes vite ça ne fonctionne pas, il faut taper "doucement" pour que cela fonctionne. On va bien sûr régler le problème (on a une mise en production prévue mardi) mais d'ici là, il faut y aller tranquille quand vous faites une recherche ;-)
