### ISSUE TITLE
Génération pdf / odt

### ISSUE THREAD

**Issue by maximeperraultdev** [MTES-MCT/monitorenv#1788]

**Comment by AdelineCelier** [comment]
@maximeperraultdev ce que j'ai pu voir à ce stade : 

- [ ] j'ai l'impression qu'il y a une latence dans la prise en compte du commentaire dans le pdf : 
  - j'ai rajouté un commentaire puis j'ai cliqué sur "générer un brief"
  - le commentaire n'apparaissait pas, je me suis dit que c'était peut-être parce qu'il fallait que j'enregistre le tableau de bord, ce que j'ai fait (le bandeau vert est bien apparu)
  - puis j'ai recliqué dans la foulée sur "générer un brief", et là seule la 1è lettre de mon commentaire apparaissait dans le pdf (cf. capture)
  - le temps que j'écrive ces lignes, j'ai retenté une génération de briefs, et là tout le commentaire apparaissait dans le pdf

![Image](https://github.com/user-attachments/assets/4bca6b7a-be27-4f2e-b8b9-4326a412060e)

- [ ] s'il n'y a aucun signalement sélectionné, retirer l'encart avec la légende des drapeaux, elle prend de la place pour rien je pense
- [ ] vous aviez revu avec Xavier les tailles de police pour la 2è partie avec le détail des zones ? Les textes me semblent encore très petits

**Comment by maximeperraultdev** [comment]
@AdelineCelier vu pour le commentaire qui se met mal à jour. Il est possible que le pdf soit en cours de mise à jour. Je peux ajouter un moyen de savoir s'il est en cours de mise à jour. Est-ce que je met le bouton en disabled avec une autre texte. proposition : Chargement du brief. 
Ok pour les signalement.
On a revu certains points mais s'il y a des ajustements on peut adapter facilement.

**Comment by AdelineCelier** [comment]
J'ai l'impression que les 2 premiers points sont bons, il faut juste que je retouche les caractères trop petits sur le pdf, mais pas bloquants pour la mep de demain
