### ISSUE TITLE
Ajouter des ancres permettant un retour aux sections

### ISSUE THREAD

**Issue by maximeperraultdev** [MTES-MCT/monitorenv#1801]

**Comment by AdelineCelier** [comment]
@maximeperraultdev c'est bon ça marche bien, le seul point c'est qu'elles mettent du temps à s'actualiser (parfois plusieurs secondes) : quand je clique sur une ancre, elle ne disparaît pas tout de suite, et les ancres "opposées" mettent également un petit moment à apparaître. Mais je ne sais pas si c'est parce que mon ordi est particulièrement lent ou non, il faudrait voir côté CACEM si ça le fait aussi. 
Cf. vidéo ci-dessous
https://github.com/user-attachments/assets/51725336-718e-4df7-8c5c-31e059d4a854


Et sinon il y a juste un petit point UI : j'ai l'impression que les marges ne sont pas tout à fait bonnes, j'ai l'impression que les ancres sont un peu trop "vers l'extérieur". Cf. marges des maquettes ci-dessous :

**Comment by AdelineCelier** [comment]
@maximeperraultdev on n'y est pas encore tout à fait...
J'ai fait une vidéo pour te montrer le comportement sur mon ordi : 
- quand je déplie une section qui fait passer sous la ligne de flottaison les sections en-dessous, les ancres ne s'affichent pas. C'est quand je commence à scroller dans la colonne que les ancres s'affichent. Ce n'est pas dramatique mais je trouverais plus logique qu'elles s'affichent dès la disparition des sections correspondantes
- il y a parfois des ancres qui restent affichées même quand on a replié les sections.
- j'ai l'impression que le point UI remonté ci-dessus n'est pas tout à fait réglé : les ancres débordent encore un peu sur les bandeaux du haut et du bas – c'est chiant à régler ou pas ?

![Image](https://github.com/user-attachments/assets/83121dcc-2391-41b2-9203-3e16eaac2cb7)

https://github.com/user-attachments/assets/2873b00f-48d8-45b4-bbab-6f48d3e50101
