### ISSUE TITLE
Ajouter la possibilité de trier les missions par 'Année en cours'

### ISSUE THREAD

**Issue by AlexiaLaunay** [MTES-MCT/monitorenv#1804]
Bonjour,

Est-ce qu'il serait possible d'ajouter la possibilité de trier les missions par 'Année en cours', comme c'est le cas pour les signalements ?

Merci

**Comment by AdelineCelier** [comment]
Hello @AlexiaLaunay bien noté, on va développer ça.

**Comment by AdelineCelier** [comment]
c'est bon pour moi !
