### ISSUE TITLE
Tableaux de bord – Revue UX

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorenv#1806]
### Bugs 
- [x] les filtres des thématiques reg et des types d'AMP ne semblent pas s'adapter complètement aux données des zones présentes dans le secteur tracé pour le brief. Par ex., je sélectionne "arrêté de protection" et "espèces protégées" dans les filtres, mais aucune zone reg ou de vigilance ne remonte dans le tableau. 
- [x] #1834
- [x] j'ai créé le tableau de bord BN Ajaccio, l'ai enregistré, puis j'ai été créer une zone de vigilance côté carto au sein du périmètre du brief de la BN Ajaccio. De retour sur mon tableau de bord, je ne la vois pas apparaître dans l'encart "zone de vigilance". Elle n'y apparaît pas non plus après que j'aie fermé puis rouvert l'onglet du tableau de bord. 
- [x] Quand je navigue d'une reg à l'autre, il faut que je clique 2 fois pour afficher le résumé reg : au 1er clic, seule la fenêtre apparaît, mais sans rien, au 2è clic son contenu s'affiche (cf. vidéo)
https://github.com/user-attachments/assets/2a378ce5-82ef-4440-b09e-54763c5e6ca1

### Points manquants
- [x] il manque une pop-up de confirmation quand on quitte le tableau de bord sans l'avoir enregistré. En wording pour cette pop-up : 
  - titre : "Enregistrer les modifications"
  - texte : "Vous êtes d'abandonner l'édition du tableau de bord. Voulez-vous enregistrer les modifications avant de quitter ?"
  - boutons : "Quitter sans enregistrer" / "Retourner à l'édition"
- [x] faire persister les filtres sélectionnés par l'utilisateur a minima en local : il doit pouvoir les retrouver en rouvrant un tableau, et après avoir fermé puis rouvert Env sur son poste.
-  [ ] ~~Sur le fonctionnement du scroll : passer les colonnes 2 et 3 sur le même système de "hauteur max" que la 1. ERRATUM: on part sur le systeme d'ancre~~

### Améliorations suppl. identifiées
- [x] Affichage des résumés des zones reg et AMP : faire comme côté carto, à savoir laisser la ligne de la zone dont le résumé est ouvert en couleur de hover, pour voir quelle zone est consultée dans la liste
![Image](https://github.com/user-attachments/assets/4eff04b6-28eb-48c7-ad5c-83f47f6cd05d) 
- [x] #1835

### Point manquant
- [x] rajouter le bouton "œil" dans le menu briefs sur la carto pour pouvoir afficher/masquer les briefs, comme pour les autres objets de la carte. 

### Bug (pas prio)
- [ ] quand je centre la carte sur un signalement relié à une mission qui n'est pas actuellement affichée sur la carte, ça relie le signalement à un cercle vide. On pourrait afficher l'icône de mission ?
![Image](https://github.com/user-attachments/assets/349ed110-7b17-497f-9835-dccd364291ff)

## Tableaux Metabase

- [ ] les tableaux Metabase sur les zones reg et les zones AMP n'affichent pas de résultats dès qu'il y a un filtre sélectionné (plutôt à voir avec Morgan). Globalement, ils ne me semblent pas très intuitifs à utiliser. 

## Perfs

- [x] par moments, il semble que l'app ralentisse. Comportements que j'ai pu observer (désolée c'est un peu flou, mais ptet qu'il faut garder en tête le sujet des perfs) : 
  - latences quand je tape dans le champ "Commentaires" : ce que je tape met du temps à apparaître
  - latences quand je clique sur l'icône du brief pour figer sa pop-up, et petite latence aussi quand je clique sur "éditer le brief" pour ouvrir la side window
  - en fait j'ai l'impression qu'il y a des latences quand un tableau de bord est ouvert et que je clique sur n'importe quel item de la carte (un signalement, un sémaphore...) : la pop-up met 1 ou 2 secondes à s'afficher et la carte freeze pendant ce temps

**Comment by AdelineCelier** [comment]
@claire2212 comme convenu, je rajoute ici qques points que j'ai repérés pendant la revue d'aujourd'hui.

Sur la carto, quand on affiche les zones du tableau de bord : 
- [ ] quand on clique à un endroit où plusieurs zones se superposent, le curseur qui pointe l'endroit cliqué s'affiche en-dessous des couches, et n'est donc pas très visible.
- [ ] j'ai l'impression que les zones AMP s'affichent au-dessus des zones reg, ce qui fait que si une zone reg est plus petite qu'une AMP, on ne peut pas la sélectionner
- [ ] quand on clique sur une zone depuis la carto ou depuis la liste du tableau de bord, son contour ne se met pas en surbrillance, donc pas facile de repérer laquelle c'est sur la carte.

**Comment by AdelineCelier** [comment]
@maximeperraultdev donc au final pour les scrolls on ne part pas sur les hauteurs max mais sur le système d'ancres. 

Les écrans ont été mis à jour dans le XD, cf. écrans [15](https://xd.adobe.com/view/9c1d04d7-7e1c-4955-bc9a-ee44a592c7d8-c94e/screen/bc693c1a-dcaa-4d5f-8f3d-8e109754b730) à [17](https://xd.adobe.com/view/9c1d04d7-7e1c-4955-bc9a-ee44a592c7d8-c94e/screen/43918046-b7f6-4c12-9c69-70089e678ed5)
Les règles de fonctionnement des ancres : 
- il y a un seul grand scroll pour chacune des 3 colonnes
- aussitôt qu'un des titres de section disparaît (en début ou en fin de colonne), une ancre apparaît pour renvoyer directement vers le titre
- côté UI 
   - il y a une zone-tampon de 24 px entre la barre de filtres et le contenu des colonnes
   - les ancres ont un contour en Gainsboro de 1 px et une ombre portée pour bien se détacher du fond 
   - elles sont décalées de 8 px vers la droite par rapport à la colonne pour donner un effet "marque-page" et permettre de lire le plus de contenu possible.

**Comment by maximeperraultdev** [comment]
Merci @AdelineCelier. On part la dessus, j'ai modifié l'issue pour dire qu'on part sur cette solution. On a également réglé le problème de perf si tu as du temps de regarder ce serait chouette.

**Comment by AdelineCelier** [comment]
Ok tout m'a l'air quasi bon sur ce ticket, modulo les deux points suivants. Je vais créer un nouveau ticket pour le 1er point, et pour le 2è je ne sais pas trop ce que vous voulez faire : est-ce qu'on crée un ticket dédié Env pour ce souci de rendering côté side window ? 

**1er point**
> quand je centre la carte sur un signalement relié à une mission qui n'est pas actuellement affichée sur la carte, ça relie le signalement à un cercle vide. On pourrait afficher l'icône de mission ?
Ticket #1806 créé et mis dans le backlog.

**2è point**
> Quand je navigue d'une reg à l'autre, il faut que je clique 2 fois pour afficher le résumé reg : au 1er clic, seule la fenêtre apparaît, mais sans rien, au 2è clic son contenu s'affiche (cf. vidéo)
En restestant, il y a toujours une latence de qques secondes au 1er affichage du résumé d'une zone, mais j'ai l'impression que c'est un pb de rendering sur la side window, car quand je bouge un peu ma fenêtre, le résumé s'affiche tout de suite (pb identifié côté Fish, cf. ticket [3807](https://github.com/MTES-MCT/monitorfish/issues/3807)).

**Comment by claire2212** [comment]
@adeline, est-ce que tu peux faire un ticket pour le 2eme point? comme ça on met celui-ci en done
