### ISSUE TITLE
Sensibilisation à changer pour prévention

### ISSUE THREAD

**Issue by manonolivier** [MTES-MCT/monitorenv#1829]
Vu en point hebdo
Il faudrait modifier le nom. Le terme prévention permet d'accentuer sur le fait que l'action a été faite en amont d'un contrôle. Ca permet de bien faire la différence entre la prévention et les rappels à la réglementation suite à un contrôle

**Comment by AdelineCelier** [comment]
Hello @manonolivier, on va faire la modif. 
On pensait faire comme ça, qu'en penses-tu : 
![Image](https://github.com/user-attachments/assets/6627671e-b88b-4c49-b338-38c982433af6)

Concernant le nb de personnes concernées, on trouve étrange d'écrire "nombre de personnes prévenues". 
On a d'autres options : 
- soit conserver "nb de personnes sensibilisées", comme sur la capture ci-dessus
- soit mettre "nb de personnes concernées"
- soit mettre "nb de personnes visées"
- ...ou autre suggestion de votre part
Qu'en penses-tu ?

**Comment by manonolivier** [comment]
Salut @AdelineCelier,
En effet personnes prévenues c'est bizarre.
Ca ne nous choque pas de mettre simplement "nb de personnes" mais s'il faut mettre un verbe "nb de personnes informées" c'est correct

**Comment by AdelineCelier** [comment]
Ok partons sur `nb de personnes informées` !

**Comment by AdelineCelier** [comment]
C'est good !
