### ISSUE TITLE
Supprimer la case Tribunal compétent

### ISSUE THREAD

**Issue by manonolivier** [MTES-MCT/monitorenv#1830]
en lien avec le #1759

**Comment by claire2212** [comment]
Hello @manonolivier, il faut supprimer le sélecteur "Tribunal compétent" et la case à cocher "A traiter" c'est bien ça?

 ![Image](https://github.com/user-attachments/assets/23aae5e7-4605-497c-9843-952bf34abc5f)

**Comment by manonolivier** [comment]
Salut @claire2212 oui c'est bien ça merci !

**Comment by AdelineCelier** [comment]
Good !
