### ISSUE TITLE
Ajouter "voir les signalements" sur les fiches sémaphore

### ISSUE THREAD

**Issue by manonolivier** [MTES-MCT/monitorenv#1832]
Comme pour les fiches unités, est-ce que ce serait possible d'ajouter la même chose sur les onglets sémaphores svp ?
Lorsque l'on clique sur un sémaphore, avoir un onglet "voir les signalements de ce sémaphore" sous "créer un signalement"

**Comment by claire2212** [comment]
Salut @manonolivier et ce bouton renverrait sur la vue liste des signalements pré-filtreé sur le sémaphore c'est ça?

**Comment by manonolivier** [comment]
Salut @claire2212
Oui si c'est possible

**Comment by claire2212** [comment]
Salut @manonolivier pour ce qui est de la vue liste ça vous va si je met le filtre sur "Année en cours", avec les signalements en cours ET archivés (en plus du filtre sur le sémaphore) ?

**Comment by manonolivier** [comment]
Salut @claire2212, peut-être plutôt sur un mois parce que sur une année complète ça risque de faire beaucoup pour certains sémaphores.
J'imagine qu'on pourra toujours filtrer après sur une année ?
