### ISSUE TITLE
Zones de surveillance supprimées qui s'affichent

### ISSUE THREAD

**Issue by manonolivier** [MTES-MCT/monitorenv#1837]
Quand on veut modifier ou remplacer un tracé existant, l'ancien tracé reste inutilement visible même si on le supprime au préalable, idem au moment de la création d'un nouveau tracé lorsqu'on clique sur "réinitialiser".
C'est un comportement spécifique aux zones de surveillance, ça ne fait pas la même chose pour les points de contrôle et les zones de mission.
Est-ce que c'était voulu ?

**Comment by claire2212** [comment]
Salut @manonolivier , j'ai essayé de reproduire le cas mais je n'y arrive pas. 
Pour rappel voici comment s'est censé fonctionner : 
- Zone de mission et de surveillance : comme il peut y avoir plusieurs zones de missions et de surveillance, le bouton d'édition de la zone (le bouton avec le crayon) garde le tracé actuel (pour pouvoir le modifier en déplaçant sur les différents points de la zone déjà dessinée) + vous pouvez tracez une autre zone (de mission ou de surveillance). Si une autre zone est tracée elle viendra s'ajouter à la zone déjà tracé et il il aura donc deux polygones dessinés :
![Image](https://github.com/user-attachments/assets/be3960c2-e027-477b-bddc-0d2819335d37)

Si vous souhaitez supprimer complètement le tracé pour en refaire un autre il faut d'abord supprimer le tracé et ensuite cliquer sur "Ajouter une zone de surveillance/mission". J'ai testé ce cas car tu disais que ça ne fonctionnait pas mais pour moi tout fonctionne, je veux bien que tu re-testes pour me dire si c'est ok pour toi.

Ensuite le bouton "Réinitialiser" sur la petite fenêtre côté carte permet de revenir à l'état "initial", c'est à dire au tracé existant quand la mission a été ouverte. Par exemple : J'ai une zone de surveillance tracée, je clique sur le bouton d'édition de la zone (le bouton avec le crayon), je modifie le tracé ou en ajoute un autre. Je clique sur réinitialiser, je vais retrouver mon tracé initial avant les modifications ou l'ajout d'une nouvelle zone.

- Point de contrôle : comme il ne peut y avoir qu'un seul point de contrôle au moment d'éditer le point, le nouveau point remplace le précédant. Le bouton "Réinitialiser" à le même fonctionnement que pour les zones de surveillance/mission

**Comment by manonolivier** [comment]
@claire2212 

Je trace ma zone de surveillance : 
![image](https://github.com/user-attachments/assets/56783b22-3cb3-4f7e-85b8-6efe03108d80)
![image](https://github.com/user-attachments/assets/c96bbe84-6c84-457d-9f27-5089c9d13fbc)

Je clique sur la poubelle parce que je veux en faire une autre complètement différente mais elle apparait quand même : 
![image](https://github.com/user-attachments/assets/c51b1271-1fe8-48aa-bd0b-b3550d7b5c3c)
Ça reste comme ça même quand je clique sur "Ajouter une zone de surveillance" : 
![image](https://github.com/user-attachments/assets/72ff97a1-d405-46ce-be7d-8b6369f6f161)

Ce qui fait que celle que nous sommes en train de tracer se superpose à l'ancienne : 
![image](https://github.com/user-attachments/assets/224a2d30-2da1-43e7-93d9-a9d1788878ac)

**Comment by claire2212** [comment]
@manonolivier alors je pense que ce n'est pas la zone de surveillance qui continue d'apparaître mais la zone de mission. Je pense que tu as créé une zone de surveillance, donc la zone de mission a été définie par rapport à cette zone de surveillance. Quand tu supprimes la zone de surveillance , on continue à voir la zone de mission. Elle se mettra à jour une fois la nouvelle zone de surveillance dessinée

**Comment by manonolivier** [comment]
@claire2212 ah oui d'accord c'est clair, merci pour l'explication.
C'est possible de la supprimer même si c'est parce qu'elle représente la zone de mission ? C'est pour une question de lisibilité, nous devons parfois être très précis et si on a l'ancienne zone + les zones de vigilance, les zones reg et qu'on essaie de dessiner la nouvelle zone de surveillance ça alourdit et cache les informations dessous (fonds de carte, zone reg/zone AMP) qui sont pourtant nécessaires au bon tracé de la zone de surveillance

**Comment by manonolivier** [comment]
Salut @claire2212,
Nous n'avons en effet pas besoin de voir la zone de mission quand on créé une surveillance ni quand on place un point de contrôle. Par contre, on a besoin de voir la zone de surveillance déjà tracée quand on place un point de contrôle (ça permet de savoir directement si on doit remodeler la zone de surveillance (dans le cas où le point est en dehors de la zone initiale) et de savoir à peu près où le contrôle peut être quand on n'a pas l'info précise).

**Comment by AdelineCelier** [comment]
@claire2212 
La zone de mission disparaît bien quand on trace une zone de surveillance ou place un point de contrôle 
Mais j'ai l'impression que quand on modifie la zone de surveillance et qu'on l'enregistre, cela ne met pas à jour la zone de mission, ça garde l'ancien tracé de la surveillance.
Cf. la mission que j'ai créée avec la BSA Hyères du 06/12 au 07/12 : la grande zone est la 1ère zone de surveillance que j'ai tracée, et la plus petite est la 2è. 

![Image](https://github.com/user-attachments/assets/e65e29b1-4edc-46ce-82f0-114b591b3434)

**Comment by claire2212** [comment]
@AdelineCelier comme vu ensemble ce comportement est normal tant que le point de contrôle, qui est au moment de la création la première action de la timeline, n'a pas de date. Une fois la date du contrôle renseigné (qu'elle soit antérieure ou postérieure à la surveillance) la zone se mettra bien à jour.
