### ISSUE TITLE
Pouvoir supprimer des points d'un tracé ?

### ISSUE THREAD

**Issue by manonolivier** [MTES-MCT/monitorenv#1838]
Est-ce que ce serait possible qu'on puisse supprimer un seul point d'un tracé ?

**Comment by claire2212** [comment]
Salut @manonolivier, pourrais-tu m'expliquer quels sont les différents cas d'usage qui peuvent vous amener à vouloir supprimer un seul point?

D'un point de vue technique sera risque d'être assez compliqué à faire, car l'outil qu'on utilise,openLayer , pour tout la gestion de la carto ne le permet pas. Il me semble qu'il y a une fonctionnalité que l'on pourrait implémenter pour supprimer le dernier point tracé mais j'aurais besoin de connaître les cas d'usage pour savoir si le bénéfice sera réel pour vous

**Comment by manonolivier** [comment]
Salut @claire2212, c'était une demande de Christophe, je vois avec lui à son retour de congés !

**Comment by manonolivier** [comment]
Salut @claire2212, j'ai vu avec Christophe, ce n'est pas un besoin fort (on modifie souvent les zones tracées lors de l'ouverture de la mission et ça aurait pu être pratique de supprimer des points en particulier). Si ça demande un gros développement, ça n'en vaut pas la peine. La possibilité de bouger des points suffit.
