### ISSUE TITLE
Zones de vigilance – Retouches formulaire de la zone

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorenv#1873]
Retours suite aux entretiens avec le CACEM sur l'usage des ZV : 

### Dans la fiche en consultation (cf. cet écran)
- [x] Ajouter la date de création de la ZV et/ou de dernière modification
![Image](https://github.com/user-attachments/assets/53d83c61-309c-4da4-8707-003de7d0882a)

- [x] Ajouter une infobulle sur “interne CACEM” pour expliquer que ce champ ne sera pas partagé quoi qu’il arrive
![Image](https://github.com/user-attachments/assets/5cc65cfd-76a9-4473-8ab9-fd43318faa1b)

### Dans le formulaire en édition (cf. cet écran)
- [ ] #1890
![Image](https://github.com/user-attachments/assets/d46e2090-b441-419e-a8ed-9ff1ef446bf1)

- [x] Mettre les ZV par défaut en confidentiel : précocher “interne” à la création de la ZV
- [x] Ajouter la même infobulle qu'en consultation sur “interne CACEM” pour expliquer que ce champ ne sera pas partagé quoi qu’il arrive
![Image](https://github.com/user-attachments/assets/75392e70-764a-434e-b7ec-69b434c17f82)

**Comment by maximeperraultdev** [comment]
Salut @AdelineCelier ! Concernant le point :  Ajouter la possibilité de définir la période de validité comme “infinie” (“en tous temps”). Est-ce qu'on doit griser les champs date et fréquence ?

**Comment by AdelineCelier** [comment]
C'est bon !
