### ISSUE TITLE
[Zones de vigilance] Afficher une pop-up de confirmation  lorsque j'édite une ZV depuis la vue liste et qu'une ZV est déjà en cours d'édition

### ISSUE THREAD

**Issue by claire2212** [MTES-MCT/monitorenv#1887]
Lorsque qu'une zone de vigilance est en cours d'édition sur la carte et que je souhaite en éditer une autre depuis la vue liste, le formulaire ouvert sur la carte se ferme sans demande de confirmation.

**Comment by AdelineCelier** [comment]
C'est bon !
