### ISSUE TITLE
Zones reg – Bug des filtres par mots-clés thématiques

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorenv#191]
Il y a un problème de filtre, je ne sais pas si c'est côté QGIS ou côté Env : si je sélectionne tous les filtres "mouillage" dans un secteur où il y a plusieurs zones avec la thématique "Mouillage", cela masque quand même certaines de ces zones (cf. captures ci-dessous)

Zones avec thématiques mouillage (not. zone ronde sélectionnée)
![image](https://user-images.githubusercontent.com/71878648/205109375-85c69bba-b734-4f6c-8d4d-85b21369af72.png)
Disparition de la zone ronde après application des filtres
![image](https://user-images.githubusercontent.com/71878648/205109321-2734b5f8-ec26-425a-8b98-a7dbe152a9e2.png)

**Comment by TEAMCACEM** [comment]
Même chose pour le filtre ZMEL

**Comment by AdelineCelier** [comment]
Le ticket ne me semble pas réglé, je vois toujours un souci sur le filtrage des zones. 
Ex. la zone PER Sud Atlantique ayant pour thématique "extraction granulats" disparaît quand on applique le filtre "extraction granulats"

Avant le filtre
![image](https://user-images.githubusercontent.com/71878648/216974186-97344b87-1926-4b9e-af54-a3f4f3da2e31.png)

Après application du filtre
![image](https://user-images.githubusercontent.com/71878648/216974343-ae7b4101-b097-4e1e-89de-b05faef5a3ca.png)

**Comment by claire2212** [comment]
@TEAMCACEM je pense que c'est aussi réglé (voir mon commentaire https://github.com/MTES-MCT/monitorenv/issues/497#issuecomment-1559704695) . Pouvez-vous me le confirmer?

**Comment by TEAMCACEM** [comment]
Le problème est bien résolu de notre côté aussi. Merci !
