### ISSUE TITLE
Afficher la fiche sémaphore après la recherche

### ISSUE THREAD

**Issue by manonolivier** [MTES-MCT/monitorenv#1923]
Ce serait pas mal si cette fiche : 
![Image](https://github.com/user-attachments/assets/8ea6c3f6-8be6-424b-bd2e-32a6925f499c)
s'ouvrait automatiquement quand on recherche un sémaphore et que ça zoom sur le sémaphore (pour l'instant on doit cliquer sur le sémaphore pour que la fiche s'ouvre.

**Comment by claire2212** [comment]
Salut @manonolivier , je viens de tester et la fiche s'affiche bien quand je cherche un sémaphore depuis ici : <img width="405" alt="Image" src="https://github.com/user-attachments/assets/6aea8e17-7bb8-4851-bb15-12bbf0e6c2a1" />

Est-ce que tu peux me dire comment tu fais ta recherche que je puisse reproduire le cas où la fiche ne s'ouvre pas ?

**Comment by manonolivier** [comment]
Salut @claire2212,
Je viens de tester et en effet ça fonctionne bien. Quand j'ai rédigé le ticket c'est Antoine qui avait remarqué le "bug" et la fiche ne s'ouvrait pas non plus sur mon ordinateur (peut-être un problème de connexion ?).

**Comment by claire2212** [comment]
@manonolivier ça marche, si ça te va je clôture le ticket dans ce cas
