### ISSUE TITLE
Surveillance - Revoir les manières de saisir les dates et heures/la durée de surveillance

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorenv#205]
**Constat** 
Dans une grande majorité de cas,  comme pour les zones, les dates et heures de surveillance seront équivalentes aux dates et heures de mission : lorsqu’une unité sortira ne trouvera pas de cible à contrôler, elle rappellera pour rapporter une surveillance de la durée de sa mission.
Une des demandes du CACEM est donc de faciliter la saisie de la durée de la surveillance, en pré-cochant notamment le fait que la durée de surveillance = la durée de mission. 

**Ajustements proposés**
Il y aurait 3 manières de saisir ces données dans la surveillance : 
- **option 1** : la case "Dates et heures de surveillance équivalente à celles de la mission" est pré-cochée, ce qui a pour effet de reporter les champs date/heure saisis au niveau de la mission. Si un champ au niveau de la mission n'est pas encore rempli (ex. l'heure de fin), l'utilisateur pourra remplir l'équivalent dans la surveillance, et cela reporte automatiquement la valeur dans le champ côté mission – en gros tant que la case est cochée, les deux sets de champs sont liés et un changement dans l'un se répercute dans l'autre. Ca te semble ok comme comportement ? Le champ durée se remplit auto. 
- **option 2** : l'utilisateur saisit à la main les dates et heures de début et fin de surveillance, le champ durée se remplit auto. 
- **option 3** : l'utilisateur ne saisit qu'une durée de surveillance. Je pense qu'il est intéressant de garder cette possibilité, notamment pour les unités qui sortent plusieurs jours et qui ne vont peut-être pas tout de suite rapporter des dates de début et de fin de leurs surveillances env. 

J'ai mis à jour les écrans XD dans ce sens.

@thoomasbro j'espère que c'est pas trop vénère en termes de changements dans le modèle de données...j'essaye de trouver des compromis entre facilité de saisie et exhaustivité des données ^^'

**Comment by thoomasbro** [comment]
1. Quand la case "Dates et heures de surveillance équivalente à celles de la mission", est ce qu'il ne serait pas plus simple de reporter les dates/heurs de mission et de rendre le champ "disabled", la mise à jour des dates se faisant alors uniquement pour la mission ? ça éviterait d'avoir de changements sauvages (notamment s'il y a plusieurs surveillances pour lesquelles la case est cochée).
2. si la durée correspond effectivement à l'intervalle entre la date de début et la date de fin, ça me semble sain que le champ durée soit calculé automatiquement. Mais du coup, il me semble qu'il ne faut pas permettre de le mettre à jour, non? sinon il faut que ça change la date / heure de fin ?
3. Ca me semble compliqué de garder l'option 3 pour avoir de la cohérence dans les données, mais pourquoi pas. Si une durée est saisie, mais pas de date de début ou de date de fin, qu'est ce que ça veut dire ? En gros, ce qu'on souhaite c'est d'avoir une durée pour toutes les surveillances, que cette durée soit calculée à partir de dates de début/fin ou saisi manuellement ?

**Comment by TEAMCACEM** [comment]
Nous utiliserons surtout l'option 1 et modifier seulement les dates/heures de la mission et non de la surveillance nous convient.

Pour les options 2 et 3, nous n'avons en réalité pas besoin de remplir une durée de mission, on remplit seulement le départ et la fin. La stat de la durée est importante mais seulement pour les statistiques, les bilans, etc nous n'avons pas besoin qu'elle apparaisse sur la fenêtre des missions.

**Comment by AdelineCelier** [comment]
@TEAMCACEM @thoomasbro 
- Pour la question de la durée : ok c'est noté, j'avais l'impression que garder la possibilité de remplir juste une durée pouvait être intéressante dans le cas où l'unité ne donnait pas ses heures de début et de fin de surveillance (je pensais à la Marine notamment). Après plus on est précis mieux c'est, donc ça me va très bien si on se dit qu'on demande systématiquement aux unités de nous donner les infos. Dans ce cas, est-ce qu'on garde le champ durée à titre indicatif et il se remplit automatiquement, ou bien est-ce qu'on se dit que c'est une donnée purement stat et qu'on n'a pas besoin de la voir dans le formulaire ?
- Ok aussi pour dire qu'on désactive les champs de début/fin dans la surveillance à partir du moment où la case est cochée. C'était pour garder un peu de souplesse de remplissage, mais ce sera peut-être plus lisible comme ça effectivement.
- Dans le cas avec plusieurs surveillances : pour moi, on ne peut pas avoir plusieurs surveillances avec des dates de début/fin équivalentes, ou ça veut dire qu'il n'y a qu'une seule surveillance. Je ne vois pas dans quel cas de figure cela peut arriver, surtout si l'on permet de cocher plusieurs thématiques par surveillance. Est-ce que vous confirmez côté CACEM ? Si oui, le comportement adéquat pourrait donc être : 
  - lorsque je rentre une 2è surveillance, cela décoche automatiquement la case "dates équivalentes..." de toutes les surveillances ouvertes 
  - l'utilisateur saisit à la main les différents début/fin de chaque surveillance
  - s'il oublie de saisir celle qui a été décochée, il y a une alerte dans le formulaire qui l'empêche de le clôturer
  - si les date/horaires saisis manuellement sont équivalents ou se chevauchent, il y a une alerte dans le formulaire qui l'empêche de le clôturer
  - l'important est d'expliquer clairement dans le formulaire les erreurs détectées et comment y remédier. Je peux décliner un écran spécifique sur la question. 

Qu'en pensez-vous ?

**Comment by TEAMCACEM** [comment]
On peut avoir plusieurs thématiques par surveillance -> voir point "Pouvoir cocher plusieurs thématiques dans une même surveillance #218"
En revanche, si on indique plusieurs surveillances, elles auront forcement des dates/heures différentes. 

"lorsque je rentre une 2è surveillance, cela décoche automatiquement la case "dates équivalentes..." de toutes les surveillances ouvertes + cela la désactive, on ne peut plus la cocher" -> OUI OK
"l'utilisateur saisit à la main les différents début/fin de chaque surveillance" -> OUI OK
"s'il oublie de saisir celle qui a été décochée, il y a une alerte dans le formulaire qui l'empêche de le clôturer" -> OUI OK
"si les date/horaires saisis manuellement sont équivalents ou se chevauchent, il y a une alerte dans le formulaire qui l'empêche de le clôturer" -> On peut laisser la possibilité d'un chevauchement

**Comment by AdelineCelier** [comment]
@thoomasbro à voir avec Ariane pour la question du chevauchement, je ne sais pas si cela a un sens côté métier. A voir avec le CACEM ce qu'ils en pensent. On demande à Ariane demain au point de synchro. 

Et oui en effet on peut saisir plusieurs thématiques dans une surveillance, mais ce qui doit varier d'une surveillance à l'autre c'est la date/heure et peut-être aussi la zone ? Ne faudrait-il pas appliquer le même système de décochage de la zone de surveillance équivalente à celle de mission dans le cas de plusieurs surveillances ? => à aborder aussi au point de synchro.

**Comment by AdelineCelier** [comment]
Oulah pardon j'étais fatiguée hier soir, j'ai cru que c'était Thomas qui avait répondu au ticket !

**Comment by claire2212** [comment]
- si une seule surveillance au sein de la mission, tu peux choisir soit de saisir une date et heure de début et de fin de surveillance (via le daterange picker), soit de cocher "date et heure de surveillance équivalentes à celles de la mission"
- si plusieurs surveillances au sein de la mission, elles ne peuvent pas être toutes équivalentes à celles de la mission, donc il faut griser les cases à cocher "dates et heures équivalentes" au sein des surveillances. Et si la case de la 1ère mission a déjà été cochée, la décocher
- le champ "durée" est à titre indicatif, il est calculé auto selon la plage de date et heure. Il faudrait que je vire les petites flèches au sein du champ sur mes écrans d'ailleurs

**Comment by VincentAntoine** [comment]
Hello, 

Si je comprends bien on ne va plus stocker la durée de surveillance mais stocker les dates et heures de début et de fin de surveillance.

Pour la stat pas de problème sur le principe, on pourra calculer la durée à partir des dates et heures de début et de fin.

Il va falloir faire une migration pour ajouter une date et heure de fin sur toutes les surveillances depuis le début de l'année, pour les rendre conformes au nouveau schéma de données et permettre de faire des stats dessus. On pourrait en principe calculer la date de fin en faisant `date de début + durée`, mais je viens de voir qu'environ **un tiers des surveillances ont une durée = 0**.

Par exemple depuis le 1er mars 2023, sur 762 surveillances, 247 ont durée = 0.

C'est probablement dû au fait que la valeur par défaut est 0 dans le formulaire actuel et si l'utilisateur ne le change pas alors ça reste comme ça.

Ce problème sera évité par la refonte de cette partie du formulaire (sauf à ce que l'utilisateur saisisse une date de fin égale à la date de début, mais bon ça ne devrait pas arriver, en tout cas infiniment moins souvent qu'avec une valeur par défaut égale à 0 comme c'est le cas actuellement)

Et donc, **pour faire cette fameuse migration dans laquelle on backfill la date et heure de fin sur les surveillances depuis le début de l'année, il faudra faire très attention.**

On pourrait par exemple :
- pour les surveillances dont la durée est > 0 : on calcule `fin de surveillance = début de surveillance + durée de surveillance`
- pour les surveillances dont la durée est = 0 : on suppose alors qu'il s'agit d'une erreur de saisie due à la valeur par défaut de 0, et en l'absence d'autre information, on considère que la surveillance a continué jusqu'à la fin de la mission: `fin de surveillance = fin de mission`

N'hésitez pas à donner vos avis.

**Comment by thoomasbro** [comment]
A mon avis il faudra mettre à jour uniquement les missions non clôturées.

**Comment by VincentAntoine** [comment]
> A mon avis il faudra mettre à jour uniquement les missions clôturées. La date/heure de fin de mission n'est peut être juste pas encore renseignée pour les missions non clôturées.

Yes, de toute façon ce sera bloquant pour clôturer ?

**Comment by claire2212** [comment]
@AdelineCelier , quelques questions et retours: 

- Je n'ai pas mis le DateRangePicker car le fonctionnement du composant oblige à sélectionner une date de débit ET de fin, ce qui ne me semblait pas vraiment correspondre au besoin. J'ai donc mis deux Date Picker, est-ce que ça te va? (voir PJ)

- Si je décoche "date et heure de surveillance équivalentes à celles de la mission" est-ce que ça vide les valeurs de début et fin de mission? Sachant qu'on est forcément dans le contexte d'une seule surveillance ça me paraît bien de garder les valeurs et le CACEM les changent après avoir décocher la checkbox (par exemple si le jour de début est bien le même que celui de la mission mais simplement l'heure est différente). Ici je parle bien dans le cas où on a une seule surveillance, dans le cas de multiples surveillances je décoche la checkox et vide les dates de début et fin comme évoqué plus haut.

- Concernant la durée de surveillance je l'affiche en texte comme ce n'est que de la consultation (voir PJ), je suis preneuse de  tes retours sur le design (emplacement, taille, couleur, etc). A voir si on le garde tout simplement (le CACEM ne semblait pas avoir besoin de visualiser l'info).

- Ensuite comme vu avec Vincent plus haut on va supprimer la donnée duration de la BDD, est-ce ok pour toi? Il se basera sur le début et fin de surveillance pour calculer la durée pour les stats.

![Capture d’écran 2023-04-28 à 15 39 52](https://user-images.githubusercontent.com/23258718/235163171-1ca6ac61-8e13-4257-8179-ce1a67712df7.png)

**Comment by AdelineCelier** [comment]
@claire2212 

- ok pour moi de mettre 2 datepickers, effectivement ce serait contraignant pour l'utilisateur d'avoir à choisir direct début et fin
- ok pour le comportement que tu décris dans le cas d'une seule surveillance : les champs ne sont pas vidés quand on décoche la case
- pour le design de la durée de surveillance, ce que tu as fait me semble pas mal, je te propose de très légers ajustements 
  - mettre juste la durée entre parenthèses et ne la faire apparaître qu'à partir du moment où début et fin sont renseignés 
  - mettre une marge de 16px entre le champ d'heure de fin et le texte 
  - pour la typo, Regular Slate Gray 13 px c'est bien ! 
![image](https://user-images.githubusercontent.com/71878648/235620117-ab07b842-b6cf-40ae-98d1-2022f8bc00d1.png)

- bien vu les commentaires de Vincent, ok pour moi !

**Comment by AdelineCelier** [comment]
- Les deux date picker ne sont pas liés pour moi, on ne peut pas taper les deux dates à la suite. Après il y a encore un problème au moment de la saisie de l'heure, ça "bloque" aux minutes (mais je pense que c'est le ticket [518](https://github.com/MTES-MCT/monitor-ui/issues/518) dans Monitor-UI)
- Je me pose juste la question du calcul de l'arrondi : là ça marque "1h" même quand c'est entre 14h00 et 15h55. Peut-être faire l'arrondi à 30 min ? 
- Petit détail, mais il manque les parenthèses dans le cas de "Moins d'une heure" ;)

**Comment by claire2212** [comment]
- Faire que les deux derniers points

**Comment by AdelineCelier** [comment]
Les deux derniers points sont réglés, je passe le ticket.
