### ISSUE TITLE
Moyens (?) – Le CACEM souhaite position et contact des sémaphores

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorenv#211]
...mais ne veut pas les ajouter dans les moyens : Roxane fait une diff entre les sémaphores et les autres unités parce que les sémaphores ne peuvent pas mettre de PV. Donc c'est vrai qu'il ne faudrait pas pouvoir les assigner à des missions. 
A discuter pendant l'atelier moyens de la rentrée.

**Comment by TEAMCACEM** [comment]
@AdelineCelier Je ne sais pas si c'est le bon ticket mais à aujourd'hui, ce qu'il faudrait c'est que les sémaphores apparaissent de façon physiques (comme toutes unités finalement mais je ne trouve pas ce ticket)

**Comment by AdelineCelier** [comment]
@TEAMCACEM alors il est bien prévu de développer la visualisation des unités et de leurs moyens sur la carte (c'est la prochaine grosse brique fonctionnelle à développer). Je n'ai pas encore fait de ticket sur le sujet, mais c'est bien identifié dans la roadmap.
On pourra aussi spatialiser et créer une fiche pour les sémaphores. 
Après il reste une question à trancher sur le sujet : est-ce qu'on les considère comme des unités comme les autres, même si elles ne mettent pas de PV, et on les laisse dans la liste des unités pour le rapportage ? Ou bien est-ce qu'on se dit qu'une fois qu'on aura le module "signalements", on ne voudra plus que les sémaphores apparaissent dans la liste des unités pour le rapportage ?

**Comment by TEAMCACEM** [comment]
Il est important d'avoir les sémaphores spatialisés comme les unités.
Pour répondre à ta question, cela dépend du volet statistique et comment ça ressort.
On veut montrer :
- le nombre total de signalement des sémaphores (par façade, par sémaphore,...) spatialisés (avéré, non avéré)
- le nombre de contrôles réalisés par les unités via les signalements (par façade, par sémaphore,...)

A prirori on préfère un module unique pour créer les signalements sémaphore et ne pas les garder en unités si le module permet d'associer à un signalement une mission/contrôle.

**Comment by AdelineCelier** [comment]
@TEAMCACEM ce ticket me semble réglé, je le ferme
