### ISSUE TITLE
Missions – Pouvoir rouvrir une mission clôturée

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorenv#214]
On en avait discuté tous les deux + c'est une remontée côté utilisateur : ont remarqué aujourd'hui qu'ils cliquent intuitivement sur le bouton "enregistrer et clôturer" parce que c'est le plus mis en valeur (primary button + le plus à droite), alors même que la mission n'est pas forcément clôturée.

A faire : 
- inverser l'importance des boutons, pour ne pas mettre en avant en 1er le fait de clôturer la mission (donc "enregistrer et clôturer devient un secondary button, et "enregistrer et quitter" un primary button)
- lorsqu'une mission a été clôturée, remplacer les 2 boutons par "rouvrir la mission" : cf [cet écran](https://xd.adobe.com/view/973ae2b4-ecd1-419f-b092-8545e0d8ce57-c269/screen/dc93467f-d657-465a-afb2-858625d5b120/)

**Comment by AdelineCelier** [comment]
@thoomasbro est-ce qu'il serait possible de bloquer l'édition des champs tant que la mission n'est pas déclôturée ou ce serait compliqué ?

Petit retour UI : le commentaire en rouge "Veuillez rouvrir..." doit être en Regular Italic

**Comment by thoomasbro** [comment]
Pour le blocage des champs, j'ai bien vu ce sujet, mais il faut attendre une mise à jour de monitor-ui (c'est partiellement fait dans la version 4, il manque certains champs comme le datepicker) pour permettre l'affichage du contenu sur les champs `disabled`.

**Comment by AdelineCelier** [comment]
@thoomasbro les points UI ont été réglés, pas le blocage des champs. 
Mais si le blocage des champs est une galère, on peut rediscuter de la manière de le faire ! Je suis en train de me dire que peut-être qu'appliquer un léger filtre en Slate Gray sur tout le formulaire, avec une opacité de 30% permettant de le lire quand même pourrait suffire ? 
En tous cas je pense que c'est important de passer ce ticket en prod même si les champs ne sont pas complètement bloqués, parce que c'est relou pour l'utilisateur de ne pas pouvoir rouvrir une mission qu'il a clôturé par mégarde. 
Je t'autorise à le passer en prod, avec l'histoire du filtre gris si cela te semble bien fonctionner ;) 

Ex. ci-dessous (cf. [écran 46](https://xd.adobe.com/view/973ae2b4-ecd1-419f-b092-8545e0d8ce57-c269/screen/dc93467f-d657-465a-afb2-858625d5b120/)): 
![image](https://user-images.githubusercontent.com/71878648/233704669-c693faf1-3594-4ec6-b2a5-06e2c3958488.png)

**Comment by AdelineCelier** [comment]
@claire2212 @thoomasbro je pense que les problèmes qui restaient sur ce ticket vont être résolus par les tickets #528 et #601 
Ok pour vous de fermer et passer celui-ci en done ?

**Comment by AdelineCelier** [comment]
Comme vu avec Claire, je passe ce ticket en done et on se concentre sur le 528.
