### ISSUE TITLE
Rapportage – Pouvoir cocher plusieurs thématiques dans une même surveillance

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorenv#218]

**Comment by thoomasbro** [comment]
Les thématiques étant liées à des sous thématiques, je pense qu'il ne s'agit pas seulement de permettre de changer le select en multiselect pour les thématiques (avec le cas particulier de la protection des animaux). Du coup, je pense que ça a pas mal d'impact sur l'ergonomie de ce volet. Est ce que ça ne vaut pas le coup de refaire une passe sur le xd ?

**Comment by AdelineCelier** [comment]
A valider avec le CACEM : est-ce que ce ne serait pas plus simple de dupliquer la surveillance dans ce cas ?

**Comment by AdelineCelier** [comment]
Après rediscussion avec le CACEM, il a été acté qu'il ne fallait pas dupliquer les surveillances, mais bien saisir plusieurs thématiques. 
@TEAMCACEM petite question : vous souhaitez pouvoir renseigner plusieurs thématiques dans une même surveillance, mais y a-t-il des cas où vous voulez également saisir plusieurs sous-thématiques au sein de la même thématique ?

**Comment by TEAMCACEM** [comment]
Oui et c'est le cas à chaque fois.

**Comment by TEAMCACEM** [comment]
Peu importe la manip à faire pour nous, ce qui importe c'est que pour une mission de 3h00 dans laquelle : 3 thématiques de surveillance, il ne faut pas que ça apparaisse en surveillance 3x3h00 dans les stats

**Comment by AdelineCelier** [comment]
@thoomasbro j'ai mis à jour les écrans dans le XD. Ce sont les écrans [32](https://xd.adobe.com/view/973ae2b4-ecd1-419f-b092-8545e0d8ce57-c269/screen/77963d30-ec2c-422d-bc10-cce820f5e126) à [36](https://xd.adobe.com/view/973ae2b4-ecd1-419f-b092-8545e0d8ce57-c269/screen/682d5e72-d29e-46c0-9e6a-e943f7e6ef11).
Je suis finalement partie sur le même système que pour les unités, cela m'a semblé plus clair et lisible que le multi-cascader de React.

**Comment by TEAMCACEM** [comment]
Roxane : Je crois que cela ne fonctionne pas pour la sélection multiple des thématique de surveillance.
