### ISSUE TITLE
Missions – Problème de défilement du tableau des missions (ne scrolle plus par moments)

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#230]

**Comment by AdelineCelier** [comment]
Ticket ajouté au projet "kanban"

**Comment by TEAMCACEM** [comment]
@AdelineCelier je crois qu'on a trouvé le problème. Pour que la fenêtre des missions défile, il faut que l'onglet de MEnv (l'onglet avec la carte) soit ouvert et "actif". Ca ne défile plus si on a cliqué sur un autre onglet du navigateur. Je sais pas si c'est clair

**Comment by AdelineCelier** [comment]
Ah mais oui c'est vrai c'est étonnant. De mon côté quand je suis sur un autre onglet ça défile quand même mais de façon beaucoup plus saccadée.
@thoomasbro tu arrives à reproduire le bug ?

**Comment by TEAMCACEM** [comment]
@AdelineCelier En plus de ce bug : 
- quand j'ouvre le tableau des missions le premier affichage est celui-ci : 
![image](https://user-images.githubusercontent.com/122106549/220047001-52ce6214-46df-4c24-99e0-51047675c288.png)
ça se remet bien si je mets la fenêtre sur un écran différent de celui où est la fenêtre de base de MEnv

- ça ne scroll pas quand la fenêtre du tableau est sur le même écran que la fenêtre de base de MEnv

**Comment by AdelineCelier** [comment]
Alleluia, le scroll n'a jamais été aussi fluide ! A passer en prod :)
