### ISSUE TITLE
Rapportage - Analyse risque pêche en zone N2000.

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#234]
Comment comptabiliser les surveillances et éventuels contrôles ?

**Comment by TEAMCACEM** [comment]
@AdelineCelier il faudrait ajouter une sous-thématique "Analyse Risque Pêche" à la thématique "activités soumise à EIN" ou une sous thématique "autres" car on va nous demander des stats dessus

**Comment by TEAMCACEM** [comment]
Oui ajouter une sous-thématique "Analyse Risque Pêche en zone Natura 2000" et "Autre"

**Comment by TEAMCACEM** [comment]
A voir au prochain point hebdo intra CACEM mais dans la typologie DEB : ce contrôle apparait dans la thématique "AMP" constituant une sous thématique "ARP en N2000" ==> il faudrait donc peut-être qu'on créé une autre thématique/sous-thématique ?

**Comment by AdelineCelier** [comment]
@TEAMCACEM comme il y a eu plusieurs commentaires d'affilée, je veux juste m'assurer que vos choix sont fixés. 

On parle bien de la thématique "Activités et manifestations soumises à évaluation d’incidence Natura 2000"?
Aujourd'hui, il y a 2 sous-thématiques, "Documents d'évaluation d'incidence Natura 2000" et "Mesures et prescriptions Natura 2000". 
Quelles sont les sous-thématiques que vous voudriez ajouter ? "Analyse de risque pêche" et "Autre", et c'est tout ?

**Comment by TEAMCACEM** [comment]
@AdelineCelier oui c'est ça
