### ISSUE TITLE
Rapportage - Casier/filets non marqués

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#248]
Filets fixes en estuaires = Thématique pêche à pied. Sous thématique selon les cas : braconnage, loisir ou pro
Filets et casiers en mer =

1. Thématique pêche de loisirs (quand non marqués, ça peut être pro mais on ne sait pas donc loisirs). Sous thématique Soit "Autre" et on précise dans les observations de quoi il s'agit. Soit on ajoute "Engins de pêche non marqué" (pose le problème des contrôles de ces engins quand ils sont marqués). Soit "Engins de pêche" (pose le problème des contrôles engins de pêche en pêche embarquée). => **_ss thematique autre_**
2. Type de cible : Quand engin marqué "Personne" Quand engin non marqué : "Véhicule" et "Autre véhicule marin" ? Ajouter un type de cible "Autre" ou "Engin" ? => **_Personne_**

**Comment by TEAMCACEM** [comment]
Adeline : ok, on n’avait pas identifié ce cas pendant les ateliers. Est-ce qu’il ne serait pas possible de mettre le contrôle sur le navire de pêche (le caseyeur à qui appartient le casier par ex) et mettre en commentaire que le pêcheur n’était pas là et qu’on n’a contrôlé que ses casiers ? Si l’on veut pouvoir tracer l’identité de la personne en infraction, il vaut peut-être mieux indiquer son navire non ?

**Comment by TEAMCACEM** [comment]
Roxane : à voir, on a juste un cas non conforme s’il s’agit d’un casier non marqué (aucun navire de pêche ne peut être lié). On peut s’arranger pour choisir une façon de le prendre en compte en l’état, mais une entité « autre » pourrait être utile tant que son utilisation reste exceptionnelle.

**Comment by TEAMCACEM** [comment]
Adeline : ok je comprends. On peut effectivement rajouter un champ « autre », voir dans quels cas il est utilisé, et aviser s’il est nécessaire de rajouter un champ spécifique.

**Comment by TEAMCACEM** [comment]
1 - sous thématique autre
2 - Cible "personne"

**Comment by TEAMCACEM** [comment]
@AdelineCelier on a fermé ce point un petit peu trop tôt : il faudrait ajouter une sous-thématique "autres" dans pêche de loisir notamment pour les cas de casiers non marqués puisqu'il ne s'agit ni de chasse sous marine ni de pêche embarquée

**Comment by TEAMCACEM** [comment]
De façon générale, ajouter une sous-th"matique autre dans toutes les thématiques. Et ajouter la sous-thématique "engin de pêche non-marqué" dans les thématiques "pêche à pied" et "pêche de loisir"

**Comment by AdelineCelier** [comment]
@TEAMCACEM alors c'est bien noté que la sous-thématique "autre" a disparu de quasi toutes les thématiques où elle était à la base. Thomas est en train de voir comment résoudre le problème. 
En revanche, il me semble qu'il y avait des thématiques pour lesquelles il n'y avait pas de "Autre" de base : 
- Police des parcs nationaux
- Police des réserves naturelles
- Police des arrêtés de protection
- Police du conservatoire du littoral
- AMP sans réglementation particulière
Est-ce que vous voulez que l'on rajoute un "Autre" dans ces thématiques-là aussi ?

**Comment by TEAMCACEM** [comment]
@AdelineCelier Désolée pour le retard de réponse mais oui il faut rajouter un autre partout, sait-on jamais
