### ISSUE TITLE
Missions - Supprimer la première unité dans le cas d'une mission multi-unités en cas d'erreur

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#251]
Pour le cas d’une mission multi-unités, est-il possible d’ajouter la possibilité de supprimer le premier moyen (comme pour les suivants) ?

**Comment by TEAMCACEM** [comment]
Adeline : j’ai compris la demande, mais j’ai peur que d’un point de vue ergonomique ce soit un peu étrange d’offrir la possibilité de supprimer tous les champs concernant les unités...cela voudrait dire devoir recliquer sur « ajouter une autre unité » pour faire réapparaître les champs. Du coup l’intitulé du bouton ne collerait pas tout à fait à la situation. Pensez-vous souvent rencontrer le cas décrit au quotidien ?

**Comment by AdelineCelier** [comment]
@TEAMCACEM je vois que vous avez remis cette demande, et que ma réponse y figure aussi ;) 
Je ne sais pas si ma réponse était très claire...est-ce que pour vous ce besoin reste important et prioritaire ? Cela me semblait un peu "niche" comme demande et pas hyper satisfaisant d'un point de vue ergonomique, mais peut-être qu'il y a des aspects de la question que je n'ai pas en tête.

**Comment by TEAMCACEM** [comment]
Non c'est bon pour ce point finalement. Pas besoin de rajouter la possibilité de supprimer l'unité. Si le cas se présente, on rentrera de nouveau les infos.

**Comment by AdelineCelier** [comment]
Ok top
