### ISSUE TITLE
Rapportage - Champs bloquants

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#254]
1. A l'enregistrement
**_Infos générales :_** 
- Zone de mission spatialisée
- Date/horaire début
- Type de mission : mer terre air
- Nature de mission : ENV – Pêche -  Autre 
- Administration et Unité
- Numéro de téléphone pour la mission
- Trigramme « Ouvert par »

2. A la clôture
**_Infos générales :_**
- Champs obligatoires à l’enregistrement
- Date/horaire fin
- Trigramme « Clôturé par »

**_Actions réalisées en mission :_**

_Mission de contrôle_
- Thématique (et non par défaut un « Divers »)
- Sous-thématique (et non par défaut un « Autres contrôles (spécifier dans les observations) » car possible de valider même si le champ « Observations » est vide)
- Spatialiser = dès que contrôle : position doit être renseignée
- Conforme/Non conforme
- NATINF si infraction avec ou sans PV

_Mission de surveillance_
- Thématique
- Sous-thématique

**Comment by AdelineCelier** [comment]
@TEAMCACEM ce ticket est bien pris en compte, j'en avais fait un avant Noël de mon côté, le #124.
A noter que je n'avais pas mis la date et l'heure de début de mission en champ bloquant, sachant qu'ils sont pré-remplis automatiquement.

**Comment by AdelineCelier** [comment]
Bien vu, je l'ai rajouté dans notre ticket !
