### ISSUE TITLE
Moyens - Nouvelles unités (police, etc)

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#257]
Tableau mis à jour par Roxane, à mettre dans pas trop longtemps dans MEnv.
Est-ce qu'on pourra modifier (ajouter des unités) nous mêmes par la suite ? Si non, quelle sera la procédure à suivre ?

**Comment by AdelineCelier** [comment]
Hello, bien vu ce ticket, j'en ai créé un de notre côté, le #264. 
En ce qui concerne le fait de pouvoir ajouter/modifier des unités, on a prévu de faire un petit backoffice sur le sujet. Thomas et Ivan vont bosser dessus une fois que les ajustements sur le rapportage seront faits. En attendant, il faut nous prévenir quand vous voulez faire une nouvelle mise à jour des unités.

**Comment by TEAMCACEM** [comment]
Traité en road map =1er semestre.
= nous poserons la question de la méthodologie.

Si urgence : l'indiquer via kanban.

**Comment by AdelineCelier** [comment]
@TEAMCACEM est-ce qu'on peut passer ce ticket en terminé ? Les unités ont été rajoutées, et il y a d'autres tickets ouverts concernant l'administration des unités.

**Comment by TEAMCACEM** [comment]
yes pas de soucis
