### ISSUE TITLE
Point d'intérêt - visualiser sur la carte

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#259]
Une fois qu'on a créer le point d’intérêt comment savoir où il est sur la carte ? Quand notre écran ne se trouve pas sur la zone, on ne le voit pas, ça ne zoome pas dessus et parfois on ne sait pas où il se trouve. Peut-on zoomer dessus avec un icône une fois le point créé ? (compliqué à expliquer par écrit, dispo pour en parler de vive voix si besoin)

Est-ce que l'on peut prévoir une liste des points d'intérêts comme pour les missions ?

**Comment by AdelineCelier** [comment]
@TEAMCACEM le problème de la carte qui ne se centre pas sur le point d'intérêt quand celui-ci a été créé est bien identifié, il est noté dans le ticket #41. 

Concernant la liste des points d'intérêt, pouvez-vous m'en dire un peu plus sur votre besoin ? Comment est-ce que vous les utilisez actuellement, dans quel contexte ? C'est pour voir quelle est la réponse la plus adéquate selon vos besoins et usages.

**Comment by TEAMCACEM** [comment]
Dans l'idée, on les utilise pour les signalements ponctuels qu'on ne peut pas lié à une mission d'une unité particulière et également pour les orientations des unités avant une mission (faire une capture d'écran d'un point précis avec le détail de ce qu'il faudrait contrôler). Si le développement de la partie signalement / remontée de besoin ne se fait pas avant l'été peut-être qu'on devra utiliser ces points d'intérêts pour spatialiser sur MEnv les signalements #279)

**Comment by AdelineCelier** [comment]
Oui c'est bien noté et je suis d'accord qu'il faudra une vue liste pour les signalements. Pour moi le sujet des signalements est bien identifié comme à faire avant l'été. A voir peut-être s'il doit passer avant le sujet des moyens, s'il est selon vous plus prioritaire encore. A rediscuter avec Ariane, Thomas et l'AU qui normalement sera en charge de cette brique-là. Je me note d'aborder le sujet au prochain point de synchro.

**Comment by TEAMCACEM** [comment]
Les signalements des sémaphores et remontées de besoins sont à mettre dans le même panier pour cette brique là. Les moyens semblent plus prioritaires mais on peut dès lors avoir un atelier pour exprimer les besoins et la forme que cela prendra.

**Comment by AdelineCelier** [comment]
La brique des signalements ayant été repriorisée, je pense qu'on peut fermer ce ticket. @TEAMCACEM ok pour vous ?
