### ISSUE TITLE
Point d'intérêt - N'apparait pas sur les autres postes

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#261]
Quand on créé un point d'intérêt, ce point n'apparait que sur l'écran de celui qui l'a créé, personne d'autre ne peut le voir

**Comment by AdelineCelier** [comment]
@TEAMCACEM oui effectivement, pour le moment ça a été développé comme ça, mais on peut le modifier. Je sais qu'on avait eu la question côté Fish aussi, on pourrait peut-être faire d'une pierre deux coups. 
Idem, pouvez-vous me décrire le cas d'usage plus précisément ?

**Comment by TEAMCACEM** [comment]
Pour nous c'est indispensable que tout le monde y ait accès en tout cas
Comme chacun travaille à des horaires différents, important que la personne sache où se trouve les signalements (dans le cas où le point est un signalement)

**Comment by AdelineCelier** [comment]
Ok bien vu. Etant donné que ce sera une fonctionnalité partagée avec Fish, à voir qui s'occupe de ce développement, mais il sera pris en compte.

**Comment by AdelineCelier** [comment]
Hello @manonolivier on est d'accord qu'au final ce partage des points d'intérêt entre les postes n'est pas nécessaire (cf. conversations qu'on a eues la semaine dernière) ? Je peux fermer ce ticket ?
