### ISSUE TITLE
Point d'intérêt - Impossible de le modifier

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#262]
On peut le supprimer mais impossible de le modifier

![image](https://user-images.githubusercontent.com/71878648/212699776-db2998cb-86f7-4e4e-8e67-c93beaa61150.png)

**Comment by AdelineCelier** [comment]
@TEAMCACEM le problème c'est que l'icône "éditer" ne marche pas, quand on clique dessus il ne se passe rien c'est bien ça ?  
Roxane tu notais dans ton mail de vendredi dernier à 08h30 que vous deviez rentrer la coordonnée en entier "avec des zéros pour compléter", qu'entends-tu par là exactement ?

**Comment by AdelineCelier** [comment]
Oui effectivement c'est étrange...je bascule ce ticket vers notre kanban, on va regarder ça de plus près !
