### ISSUE TITLE
Recherche de lieux - Liste de lieux qui n'apparaissent pas

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#263]
Pour faciliter le rapportage (éviter scroll / déscroll) : est-il possible de mettre des « vignettes » par façade qui permettrait de zoomer sur la zone quand on clique dessus (utile surtout pour l’Outre-Mer)

**Comment by AdelineCelier** [comment]
@TEAMCACEM je peux réfléchir à dessiner quelque chose dans ce sens, j'ai juste un peu peur que ça prenne un peu de place sur la carto...sachant qu'il y a encore pas mal d'icônes et de menus à venir. 
En attendant, est-ce que la barre de localisation ne marche pas mieux maintenant, n'est-ce pas possible de l'utiliser dans ce sens ? Par ex, pour un contrôle en Guadeloupe, taper "Guadeloupe" dedans et sélectionner le résultat permet de zoomer sur la Guadeloupe. 
A ce propos, est-ce que vous avez pu tester un peu plus avant la barre de recherche de lieux ? Est-ce que vous trouvez ce que vous cherchez ?

**Comment by TEAMCACEM** [comment]
Ok pour ne pas créer les vignettes mais sous réserve que la barre de recherche fonctionne vraiment bien
La barre de recherche fonctionne mieux en effet mais il manque encore des lieux qui sont pas connus (ilots antillais par exemple) Et aller sur Maps c'est vraiment pas pratique.

**Comment by TEAMCACEM** [comment]
(depuis aujourd'hui (23/01) la barre de recherche ne fonctionne plus cf #276 )

**Comment by AdelineCelier** [comment]
Vu le ticket 276, je l'ai commenté. 

Est-ce que vous avez encore les noms des ilôts antillais qui ne fonctionnaient pas ? (ou d'autres noms de lieux que vous avez tapé et que vous n'avez pas trouvé).

Je vais faire un test de dessin de raccourci pour centrer sur l'outre-mer. Pouvez-vous me redire quels raccourcis vous voulez pour l'outre-mer ? Comment vous voulez découpez les différentes zones. 

Merci !

**Comment by TEAMCACEM** [comment]
La recherche spatiale fonctionne mieux mais ce n'est pas encore fiable pour les îlots.

Exemple : A Saint-Matin je recherche l'îlet Tintamarre.
Si je tape "ile tintamarre" ou "île tintamarre" la recherche spatiale fonctionne
En revanche, si je tape ou "ilot tintamarre" ou "ilet tintamarre" ou "tintamarre" la recherche spatiale ne fonctionne pas.
La recherche spatiale devrait se focaliser sur le nom plutôt que sur îlet, ile, ilot.
Idem je ne réussi pas à trouver les Glénans mais pour Chausey cela fonctionne...

**Comment by TEAMCACEM** [comment]
Exemple : Plouézec en Bretagne dans le 22

**Comment by TEAMCACEM** [comment]
S'il y a moyen d'avoir une licence Maps ce serait vraiment pas mal

**Comment by AdelineCelier** [comment]
Ok, on va en rediscuter !

**Comment by AdelineCelier** [comment]
On a discuté de la question de la licence Maps en synchro la semaine dernière.
Thomas va tester d'intégrer Maps à Env pour vérifier que ça fonctionne bien, et si c'est concluant on fera en sorte d'acquérir une licence. Si ça se trouve, vu le nb réduit d'utilisateurs de Env, ce sera peut-être même gratuit. 
A suivre dans le ticket #209.

**Comment by AdelineCelier** [comment]
@TEAMCACEM est-ce que maintenant qu'il y a Maps dans Env, vous trouvez bien les lieux que vous ne trouviez pas avant ? Si oui, peut-on fermer ce ticket ?

**Comment by TEAMCACEM** [comment]
@AdelineCelier yes c'est bon
