### ISSUE TITLE
Recherche de lieux - Revoir le comportement des résultats de la recherche 

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#275]
La fenêtre de la liste des lieux cache donc "Missions et contrôles"

**Comment by AdelineCelier** [comment]
Oui, il y a bien un problème de comportement sur les résultats de la barre de recherche. Aujourd'hui le seul moyen de les masquer est d'effacer ce qu'on a tapé dans la barre de recherche. 

Je propose pour améliorer ça : 
1. Rajouter une croix pour effacer plus rapidement ce qu'on a tapé (icone md tertiary button)
2. Quand on clique sur un résultat, cela le sélectionne et referme la liste des résultats (cf. comportement Google Maps)
3. Quand on clique ailleurs sur l'écran (donc ni dans la liste des résultats ni dans la barre de recherche), cela ferme automatiquement la liste des résultats, et dans l'idéal sans pour autant perdre ce qu'on a tapé dedans
@thoomasbro ok pour toi ?

Le point 3 devrait régler le pb du ticket #276 normalement.

**Comment by TEAMCACEM** [comment]
Le fait que le cadre "Missions et contrôles" soit au même endroit que les résultats de la recherche pose un peu problème (résultats de recherche cachés par le cadre ou inversement). Est-ce qu'il serait possible de les bouger pour qu'ils ne se chevauchent pas ?

**Comment by AdelineCelier** [comment]
Je ne suis pas sûre qu'il soit nécessaire de déplacer les items. Si les résultats de recherche sont toujours au premier plan et se ferment dès qu'on sort de la recherche, le problème ne se posera plus il me semble. Dans Fish c'est ce qu'on fait avec la recherche navire, elle est au même niveau que la fiche mais cela ne pose pas problème parce qu'elle se masque dès qu'on en sort : on ne la voit donc que quand on a besoin d'elle.

**Comment by TEAMCACEM** [comment]
On a besoin de rechercher un lieu pendant l'édition de la mission et idéalement pendant l'édition de la zone de mission. Le cadre "Missions et contrôles" ne doit recouvrir a aucun moment les résultats de la recherche spatiale.

**Comment by AdelineCelier** [comment]
Comme vu ensemble, il y a 2 points soulevés sur le sujet : 
1/ le comportement des résultats de la recherche de lieux qui n'est pas bon (cf. ci-dessous mon commentaire du 24/01/23)
2/ le fait qu'aujourd'hui la recherche de lieux n'est pas accessible quand on est en train de tracer une zone de mission ou de saisir un point de contrôle.

Je propose que ce ticket règle la question du comportement de la recherche de lieux (je le renomme dans ce sens), et j'en crée un nouveau pour le point 2.

**Comment by AdelineCelier** [comment]
Ce ticket est bon pour moi, ça peut passer en prod
