### ISSUE TITLE
Rechercher un lieu - Le premier résultat de la recherche n'est plus cliquable

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#276]
Depuis la résolution des autres bugs (le 23/01/23), on ne peut plus rien rechercher dans la barre de recherche des lieux

**Comment by AdelineCelier** [comment]
@TEAMCACEM Je vois que ce ticket est fermé, c'est une mauvaise manip ou bien c'est parce que le pb est réglé pour vous ? 

De mon côté quand je teste j'ai l'impression que c'est seulement le premier résultat de la recherche ne marche pas (quand je clique dessus, ça ne zoome pas sur la carte). Les autres résultats fonctionnent.

**Comment by TEAMCACEM** [comment]
Oui c'est le premier résultat. J'ai remarqué que l'on peut tout de même cliquer dessus mais vraiment sur le bas de la vignette. un peu étrange.
Aussi, lorsque on a la mission en création, "Mission et contrôles" cache les résultats de la recherche. On a l'impression que la recherche spatiale ne fonctionne pas. Peut-on décaler sur l'écran "Les Missions et contrôles" ou bien le résultat de la recherche cela peut prêter à confusion.

**Comment by AdelineCelier** [comment]
Ah oui tu as raison, on peut cliquer en bas du résultat. Ok, donc il y a bien toujours un problème, je remets un tag "bug" et je le bascule dans notre kanban. 

Je vois ce que tu veux dire sur la superposition des résultats de la recherche et du menu "missions et contrôles". Il y a un souci en effet, je vais réfléchir à une solution plus ergonomique.
