### ISSUE TITLE
Mission - Calendrier heure/date ne se ferme pas

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#277]
Lorsque le calendrier des dates s'ouvre dans début et fermeture de mission, il ne se ferme que lorsque l'on clique sur une date. Si on ouvre le calendrier par inadvertance, il est impossible de cliquer n'importe où sur la page pour le faire disparaître. C'est le même problème pour les dates de début et de fin de mission si bien que les deux calendriers peuvent être ouverts en même temps tout en pouvant remplir d'autres champs cachés par les dits-calendriers.
![image](https://user-images.githubusercontent.com/122106549/214061388-b22bcd0d-3e4c-4a43-9e97-5f241e5211d6.png)

**Comment by AdelineCelier** [comment]
Merci pour cette explication pas évidente ;)
J'avais effectivement remonté ce problème à Ivan qui a développé ce date picker. Il me semble qu'il l'avait réglé, @thoomasbro tu as pu intégrer la dernière version en date du date picker dans ta dernière mep ?

**Comment by louptheron** [comment]
Fixé avec la nouvelle version de MonitorUI

**Comment by TEAMCACEM** [comment]
Qu'est ce que MonitorUI ?

**Comment by AdelineCelier** [comment]
C'est un truc de dev ;) normalement le problème est réglé, mais pas encore mis en production.
