### ISSUE TITLE
Mission - Impossible de "déclôturer" une mission en cas de misclick

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#278]
Lorsque l'on clôture une mission par erreur, il n'est à priori pas possible de revenir en arrière et de simplement l'enregistrer (info normalement déjà remonté mais je ne le retrouve pas)

**Comment by AdelineCelier** [comment]
Effectivement, on en avait déjà parlé, j'ai bien fait un ticket de notre côté, le #214 
J
