### ISSUE TITLE
Signalement - Rentrer les signalements des sémaphores

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#279]
En attendant l'atelier Remontées de besoin / signalements :
continuer à remplir le tableau "semaphore" sur le BNUM + les rentrer en note libre mission surveillance sans unités (en attendant d'avoir les sémaphores en unité)
@AdelineCelier est-ce que vous avez une idée de quand est-ce que cette partie de MEnv sera développée ? On en aurait besoin pour cet été et si le délai est plus long, on ferait un autre système pour que ce soit quand même spatialisé (peut-être en ajoutant les sémaphores en unité et en créant le signalement avec une note ou en les mettant en point d'intérêt #259)

**Comment by AdelineCelier** [comment]
A rediscuter en point de synchro, cf. mon commentaire du ticket #259

**Comment by TEAMCACEM** [comment]
Quand est le prochain point synchro ?

**Comment by AdelineCelier** [comment]
C'est jeudi à 17h30 ! Avec Ariane, Thomas, Alexia (coach sur la start-up) et moi.

**Comment by AdelineCelier** [comment]
Hello le CACEM, 
Comme vu avec Ariane au point de synchro la semaine dernière, et comme vu avec toi Manon aussi il y a qques jours, on valide l'usage temporaire des missions en tant que signalements, le temps que cette brique soit développée. 

La procédure est donc : 
- d'ouvrir une mission en renseignant le sémaphore comme unité
- de tracer une petite zone de mission à l'endroit du signalement – pour les stats, on utilisera le centre de la zone pour en faire un point de signalement
- de renseigner en note libre les infos du signalement

C'est une solution temporaire pour ne pas avoir de trou dans les stats, il y aura par la suite un module dédié et mieux adapté pour les signalements.
