### ISSUE TITLE
[Mission] Afficher les filtres dans le menu "Mission" sur la vue carto

### ISSUE THREAD

**Issue by thoomasbro** [MTES-MCT/monitorenv#28]
- Quels filtres afficher ?

**Comment by AdelineCelier** [comment]
[Ecran n°56](https://xd.adobe.com/view/c72c4b9f-8704-453c-9e85-c5a61bce1e6e-927f/screen/2838ac35-3d4e-4df7-a3f4-1db02a5d56b7) dessiné pour ajouter des filtres côté carto. 
Comme côté liste, le filtre de période est par défaut à "aujourd'hui". De toutes façons les filtres se répercutent entre la vue carto et la vue liste.
