### ISSUE TITLE
Filtres dans "Vue détaillé des missions"

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#286]
Je ne retrouve pas ce ticket...
Dans la vue détaillé des missions, on a vraiment besoin de pouvoir filtrer par administration et unité pour retrouver les missions.

**Comment by TEAMCACEM** [comment]
Et aussi de pouvoir filtrer par façade comme c'était dans Poseidon

**Comment by AdelineCelier** [comment]
Oui, ce besoin est bien noté ! 
J'avais ouvert le ticket #169 sur le sujet. Je n'avais pas mis la façade, je le rajoute dans le ticket.
