### ISSUE TITLE
NATINFS - non abouti

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#287]
1) Il était initialement prévu d'avoir des natinfs présélectionner par thématique de contrôle.
Lorsqu'on renseigne une thématique de contrôle, les natinfs affichés pour une infraction doivent être pré-selectionnés.
Ex : thématique de contrôle mouillage, je dois voir apparaitre uniquement des proposition de natinfs relatifs au mouillage.

2) Il était initialement prévu de pouvoir rechercher le natinf soit par son code soit par des éléments de son nom.
Ex : natinf 4473 - la recherche fonctionne sur 4473 mais ne fonctionne pas avec des lettres. On devrait pouvoir le trouver en tapant "navigation" ou "non respect".

3) Il était initialement prévu de pouvoir sélectionner un natinf même s'il n'est pas présélectionner par la thématique. 
Ex : lors d'un contrôle réserve naturelle, je dois renseigner un natinf pêche de loisir. Je dois pouvoir rechercher le natinf 2596 même s'il n'est pas présélectionner dans les natinfs réserves naturelle (cela arrive parfois).

4) Qu'avez-vous prévu pour ajouter les natinfs qui ne sont pas dans la liste fournie initialement et qui n'existent pas dans Monitor ? Cela arrive que l'on doit ajouter des nouveaux natinfs (au CNSP comme au CACEM)

**Comment by AdelineCelier** [comment]
Hello, oui en effet on n'a pas terminé le boulot sur les NATINF.
- On avait discuté des points n°1 et 3 avant les vacances avec Thomas, j'avais ouvert le ticket #183 sur le sujet. 
- Pour le point n°2, j'étais persuadée d'avoir également ouvert un ticket, mais c'était peut-être côté FISH. J'en ouvre un nouveau, le #294. 
- Pour le point n°4, on peut envisager de développer une fonctionnalité dans le backoffice des deux apps pour rajouter des NATINFS, après à voir à quelle fréquence cela arrive, et si c'est juste le temps d'étoffer la base ou bien si de nouveaux NATINFS surviennent régulièrement dans le temps. En attendant, n'hésitez pas à nous lister les NATINFS manquants, que l'on ajoutera à la base nous-même.

**Comment by TEAMCACEM** [comment]
De nouveaux NATINFS surviennent régulièrement dans le temps. Ce sont soit des nouveaux soit des natinfs peu utilisés, soit des natinfs à la marge.

**Comment by AdelineCelier** [comment]
Ok, je crée un ticket. Ce ne sera probablement pas pour tout de suite, mais c'est bien noté.
