### ISSUE TITLE
Contrôle - Dupliquer les infractions

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#288]
Il faut pouvoir dupliquer les infractions.

Exemple : Lors d'une mission, j'ai eu 28 contrôles mouillages et 28 rappel à la règlementation. Cela équivaut dans Monitor Env à enregistrer 28 infractions sans PV avec le natinf 4473. Il est indispensable de pouvoir dupliquer l'infraction pour faciliter la saisie. Autrement je dois créer 28 infractions et c'est terriblement long et fastidieux. Idem pour la pêche à pied, cela va être très fastidieux pour les infractions sans ou avec PV.

**Comment by AdelineCelier** [comment]
Oui, ce besoin a bien été identifié, c'est le ticket #170.
