### ISSUE TITLE
Mission - Préremplissage qui peut fausser les statistiques

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#289]
Ce serait mieux qu'aucun champ ne soit préremplit ou précoché ni dans mission ni dans contrôle en terme de compte-rendu. Si on oublie de remplir ces champs et qu'ils sont prérempli, ça va fausser les statistiques alors que si les champs restent vides, on pourra savoir qu'il y a eu un oubli et donc rectifier le tir.

Exemples :
Type de mission : mer précoché -> à enlever
Nombre total de contrôles prérempli à 0 -> à enlever
Type de cible : Véhicule prérempli -> à enlever
Type de véhicule : Navire prérempli -> à enlever
Type d'infraction : Sans PV précoché -> à enlever
Mise en demeure : Non précoché -> à enlever

**Comment by AdelineCelier** [comment]
Ok bien noté, je comprends la logique, il est effet mieux de retirer ces pré-remplissages. Je bascule ce ticket dans notre kanban. @thoomasbro il est en lien avec les règles de validation des champs, peut-être que tu avais déjà identifié cette question ?
