### ISSUE TITLE
Actions de contrôle - Les dates et heures des actions de contrôle ont disparu

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorenv#291]
![image](https://user-images.githubusercontent.com/71878648/216015695-df162a20-2920-446c-80c1-f93bbf8baa20.png)

**Comment by TEAMCACEM** [comment]
De notre côté c'est bon
![image](https://user-images.githubusercontent.com/122106549/216015964-5c8f9afd-294c-4141-b9a5-805bf875f884.png)

**Comment by AdelineCelier** [comment]
Zut pardon c'est de ma faute, j'étais restée sur l'ancien fonctionnement où une date s'ajoutait par défaut quand on ouvrait l'action. Mais quand j'ajoute une date et une heure manuellement ça fonctionne bien 👍🏻 
Je ferme ce ticket du coup.
