### ISSUE TITLE
Couches reg - Ne s'affichent pas sur certains fonds de carte

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#297]
Quand on ouvre MEnv, on peut afficher les couches reg sur le fond de carte clair.
Si on clique sur n'importe quelle autre fond de carte, les couches reg disparaissent même si on fait une nouvelle recherche. Les couches apparaissent quand même sur le volet latéral gauche et si on clique sur une zone, ça zoom dessus (mais le tracé n'apparait pas).
Une fois qu'on a cliqué sur un autre fond de carte même en sélectionnant de nouveau le fond de carte clair, les zones reg n'apparaissent plus du tout. Il faut actualiser la page.

C'est ce qui se passe sur chrome et mozilla.

Et pour info, c'est seulement avec les couches reg pas les zone administratives.

**Comment by AdelineCelier** [comment]
Comme vu avec vous tout à l'heure, je passe ce ticket dans notre kanban et je le mets en "priority"
