### ISSUE TITLE
V2 Signalements Sémaphores - plusieurs signalements pour une activité

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#299]
Quand cette partie sera développée, il faudra prévoir les activités qui donnent lieu à 2 signalements (drague qui part du port pour aller vers la zone d'activité + drague qui se met en activité)

**Comment by TEAMCACEM** [comment]
@AdelineCelier Ca fait référence aux extractions de granulats marins. Parfois, plusieurs sémaphores nous font des signalements pour la même action.
exemple : Sémaphore du Havre qui nous signale le départ de la drague en direction de la concession et le sémaphore de Fecamp qui nous signale le début d'activité.

Par contre, la demande date un peu et je ne me souviens pas de ce qu'on voulait... Peut-être pouvoir lier ces deux signalements, pour les retrouver au même endroit ?

**Comment by AdelineCelier** [comment]
Mais du coup il y a un intérêt opérationnel ou statistique à noter les deux signalements séparément ? En soi c'est la même activité non ? Est-ce que ouvrir le signalement au premier appel du sémaphore, puis noter ensuite le début d'activité dans la description du signalement ne pourrait pas suffire ?

**Comment by AdelineCelier** [comment]
Ah oui ok pardon j'avais lu trop vite, je n'avais pas compris que les deux signalements venaient de sémaphores différents. 
Cette situation arrive souvent ? 
Bon en l'état je ne sais pas si on peut vraiment améliorer les choses, sachant que les cibles ne sont pas matérialisées sur la carte...il s'agit plus pour moi d'être effectivement attentif à ne pas envoyer plusieurs moyens si c'est la même cible. Vous pensez qu'il y a un risque que cela arrive ? 
Si non, je propose de fermer ce ticket, et d'en rouvrir un si un jour un cas d'usage plus précis se présente.

**Comment by TEAMCACEM** [comment]
Oui ça arrive régulièrement car le navire part d'un port (zone de compétence sémaphore 1) et arrive sur zone d'extraction (zone de compétence sémaphore 2). On compte deux signalements pour la même cible mais on envoi qu'un seul moyen. La vue détaillée des signalements avec les cibles et des dates/horaires permettra de ne pas avoir de confusion.
On reposera ce ticket quand on aura des cibles (historique de contrôles et historique de signalements) sur Monitor Env.
