### ISSUE TITLE
Réglementation – Rendre visibles et accessibles les zones qui se superposent à un point donné

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#306]
Il y a un soucis lorsque les couches se superposent à un endroit :
Exemple de la calanque d'En-Vau qui est réglementée par beaucoup d'arrêtés. En l'espèce, l'AP 099-2021 (mouillage 24m de tout le littoral des calanques) m'intéressait car contrôle mouillage effectué dans la zone.
- QGIS : on peut cliquer à un endroit précis et toutes les couches reg apparaissent : 
![image](https://user-images.githubusercontent.com/122106549/216825240-78a58e72-1fc4-40d4-80e4-54624f95e866.png)
![image](https://user-images.githubusercontent.com/122106549/216825522-abca70d7-f15c-4ef0-a78d-b745f7a91999.png)
- MEnv : 
![image](https://user-images.githubusercontent.com/122106549/216825316-6db0b703-f2b7-4e9c-b16f-19b090bd9fd7.png)
![image](https://user-images.githubusercontent.com/122106549/216825596-05e71ca2-b2e6-4fc9-9dbe-1b1e0e8b4ca0.png)
La couche qui m'intéresse est celle en bleu très foncé, elle apparait autour de l'île à gauche mais pas dans la calanque d'en vau quand je clique dessus alors que l'arrêté s'applique.

**Comment by AdelineCelier** [comment]
@TEAMCACEM Oui en effet, elle est recouverte par d'autres zones plus petites, et donc on ne peut pas cliquer dessus au niveau du point de contrôle...on ne peut que deviner que la zone de l'arrêté s'applique à cet endroit parce qu'il remonte dans les résultats. On peut cliquer dessus à côté mais je suis d'accord que ce n'est pas lisible. 
Ce n'est donc pas vraiment que les couches sont incomplètes, c'est qu'elles ne sont pas lisibles/accessibles quand elles se superposent. 

Je suis d'accord que le système de QGIS fonctionne bien et qu'il faudra décliner qqch de similaire dans Env. 
Je ne sais pas en revanche si cela pourra être réglé de façon prioritaire :-/

**Comment by AdelineCelier** [comment]
Je ferme ce ticket car il a été traité via le #1224.
