### ISSUE TITLE
Recherche reg - Certaines zones ne remontent pas avec la recherche par mots-clés

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorenv#308]
J'ai remarqué ce problème en vérifiant le ticket #191, quand je tape "PER Sud Atlantique" ou "Sud Atlantique", la zone "Extraction granulats - PER Sud Atlantique" ne remonte pas.

**Comment by AdelineCelier** [comment]
Remontée similaire du CACEM sur de nouvelles couches, cf ticket #497 . A voir si cela peut nous aider à identifier d'où vient ce bug ?

**Comment by claire2212** [comment]
@AdelineCelier réglé. Explications ici : https://github.com/MTES-MCT/monitorenv/issues/497#issuecomment-1559704695
