### ISSUE TITLE
Point d'intérêt - Bug pour rentrer certaines coordonnées

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#314]
J'ai voulu entrer le point suivant :  13°03S-045°17E donc en DMD : 13°03.000S 045°17.000E mais impossible de mettre 17.000 il le change automatiquement en 16.100. 16.000 fonctionne mais pas 18.000 par exemple.
Si on ne fait pas attention, on peut ne pas voir que ça a changé tout seul les points, ça peut poser des problèmes. Par exemple, là le 16.100 se situe dans les 3milles et le "vrai point" donné par l'unité le 17.000 se situe à l'extérieur des 3milles.

**Comment by AdelineCelier** [comment]
Ok c'est noté, je bascule le ticket de notre côté.

**Comment by louptheron** [comment]
Cf. https://github.com/MTES-MCT/monitorfish/issues/2376

Fixé dans https://github.com/MTES-MCT/monitor-ui/pull/672
