### ISSUE TITLE
Metabase - codes d'accès CACEM

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#320]
Les demandes de statistiques commencent à arriver. Nous avons besoin que chaque agent puisse avoir accès à Métabase.
Est-ce que des accès ont été créé pour l'adresse mail du cacem dans metabase ? Si oui, pouvez-vous nous communiquer les codes ?

**Comment by AdelineCelier** [comment]
@TEAMCACEM Vincent va passer vous voir pour cette question !

**Comment by TEAMCACEM** [comment]
ça marche
