### ISSUE TITLE
Rapportage - Détails des contrôles dans AMP forte

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#323]
Pour l'instant, on ne rentre pas dans le détail des contrôles effectués dans les AMP à réglementation spéciale.

Peut-être ajouter des sous-thématiques à la thématique "police des réserves/parcs nationaux, etc" pour pouvoir sortir des stats détaillées. Sous-thématiques : mouillage, pêche, espèces pro et autres ?

Si on ne souhaite pas entrer dans le détail : peut-être quand même ajouter la possibilité d'entrer des observations pour préciser le détail des contrôles. Pour l'instant, impossible d'entrer des observations dans les cas d'action de contrôles sans infraction.

**Comment by AdelineCelier** [comment]
Concernant l'ajout d'une observation dans un contrôle sans infraction, il y a le ticket #181 qui est ouvert.

**Comment by TEAMCACEM** [comment]
@AdelineCelier Ok, je l'ajoute dans notre Retours CACEM

**Comment by TEAMCACEM** [comment]
Se mettre d'accord sur des tags pour utiliser les mêmes mots tout le temps à ajouter dans les observations
