### ISSUE TITLE
Zones administratives - A l'affichage d'une zone administrative, centrer la carte dessus.

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorenv#33]
À voir comment centrer correctement les zones très étendues…trouver un bon compromis entre niveau de zoom et centrage.

**Comment by claire2212** [comment]
Certaines zones administratives occupent l'ensemble de la carte, il n'y a donc pas d'intérêt à zoomer dans ce cas là. Le gain à l'usage ne semble pas avéré
