### ISSUE TITLE
Contrôle - Saisir les coordonnées du point de contrôle

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#330]
Pour ajouter un point de contrôle, ce serait bien de pouvoir soit :
- directement entrer les coordonnées (pour l'instant, on passe par la création d'un point d'intérêt et on positionne le point de contrôle dessus)
- ajouter un fichier contenant les coordonnées géographiques de tous les points de contrôle (exemple d'usage : les unités qui nous envoient des tableaux de toutes leurs missions avec des points géo de tous leurs contrôles)

**Comment by AdelineCelier** [comment]
Hello, 
- pour entrer directement les coordonnées, il y a un ticket ouvert sur le sujet (le #131) que Loup est en train de développer. 
- pour l'ajout d'un fichier de coordonnées, je ne sais pas trop comment on ferait, sachant que si je me souviens bien on s'était finalement dit qu'on n'ajoutait qu'un point de contrôle par action de contrôle... qui sont les unités qui vous envoient des fichiers avec des coordonnées ? pour quel type de contrôles ?

**Comment by TEAMCACEM** [comment]
Hello

- Parfait (et pardon pour le doublon)
- Effectivement si le fait d'ajouter plusieurs points pour un même contrôle continue à fausser les statistiques, ce ne sera pas possible.  
Le cas se présentait pour le  parc naturel marin de Mayotte qui nous envoie ses contrôles par mail en indiquant pour chaque contrôle la position géographique. Par exemple, sur une mission ils ont effectué 5 contrôles, tous de pêche de loisir embarquée, avec donc 5 positions différentes. Rentrer les 5 positions est assez long (cela dit ce sera simplifié quand on pourra directement entrer les coordonnées dans l'outil "contrôle"), ajouter directement un fichier contenant l'ensemble des points aurait été pratique.

**Comment by AdelineCelier** [comment]
Ok...pour reprendre ton exemple, vu que ce sont 5 contrôles différents la manip d'ajout de coordonnées via un fichier ne me semble pas hyper évidente.
Je propose qu'on fasse déjà l'ajout au clavier (et donc la possibilité de copier-coller des coordonnées) et on avisera si besoin d'aller plus loin.
