### ISSUE TITLE
Crash de Monitor Env pour supprimer la zone de mission et point de contrôle

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#334]
Lorsque je dessine une zone de mission sans "Valider la zone de mission" et que je souhaite la supprimer avec la poubelle sur la feuille Edition de la mission, Monitor Env plante totalement. Je perds alors toutes les infos de ma mission.

Idem, lorsque je renseigne un point de contrôle sans "Valider le point de contrôle" et que je souhaite le supprimer avec la poubelle dans l'édition du contrôle, Monitor Env plante complètement. Je perds alors toutes les infos de ma mission et mes contrôles. On est obligé de redémarrer Monitor Env et rien n'a été sauvegardé.

**Comment by AdelineCelier** [comment]
Ok vu. Effectivement, il doit y avoir un conflit étant donné que la zone ou le point n'a pas été validé. On pourrait ne faire apparaître la zone ou le point dans le formulaire qu'à partir du moment où on a cliqué sur "valider la zone de mission" ou "valider le point de contrôle". Cela éviterait ce cas limite un peu chelou.

**Comment by TEAMCACEM** [comment]
Oui très bien.
Ou éventuellement faire apparaitre la poubelle dans l'édition de la zone de mission et de l'édition du point de contrôle.

**Comment by AdelineCelier** [comment]
Ah oui en fait vous faisiez ça dans le cas où vous vouliez recommencer la zone que vous veniez de tracer ? 
Dans ce cas il faut plutôt utiliser le bouton "réinitialiser", à gauche de "valider la zone de mission".

**Comment by TEAMCACEM** [comment]
Oui cela fonctionne bien avec "Réinitialiser la zone". Je remonte ce bug car je me suis fait avoir plusieurs fois. Instinctivement j'ai cliqué sur la poubelle et ça a tout planté.

**Comment by AdelineCelier** [comment]
C'est bon pour le point de contrôle, il faut le faire sur les zones de mission

**Comment by AdelineCelier** [comment]
C'est bon pour moi !
