### ISSUE TITLE
Bug ? unité et numéro de contact ?

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#339]
Il y a un problème avec les unités et le numéro de contact.
Maintenant on doit forcément cliquer sur "+ ajouter une autre unité" pour renseigner l'unité -> remettre comme avant
Le champ numéro de contact ne s'affiche plus directement dans "Édition de la mission"

**Comment by AdelineCelier** [comment]
Yes on a vu ce bug, désolée je n'avais pas vu que vous aviez ouvert un ticket sur le sujet, j'ai ouvert le #343 dans notre kanban.
