### ISSUE TITLE
Outils carto - Pouvoir paramétrer l'unité de distance en mètres ou en kilomètres

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorenv#34]
Roxane m'a dit avoir besoin parfois de mesurer les distances en mètres, car certaines réglementations s'expriment en mètres et non en milles. A propose des milles, je mettrais bien l'abréviation "nq" pour nautiques à la place de "nm", qui est l'abréviation anglaise, et qui se différenciera moins de "m" pour les mètres.

Comme pour les unités de coordonnées, le changement d'unité de distance se répercuterait sur les outils de mesure. 

![image](https://user-images.githubusercontent.com/71878648/174029800-45b567c4-7f9c-48af-9174-476759eda653.png)

Lien vers l'écran XD : https://xd.adobe.com/view/64f60826-e259-414d-a9c1-0dedddd742e8-31a5/screen/d8b31270-e5cf-47c8-b7fe-65695d9eb58d

**Comment by claire2212** [comment]
@AdelineCelier pour info je ne peux pas changer `nm` pour `nq` c'est géré par openLayer directement. Et je n'ai pas trouvé de façon de le changer

**Comment by AdelineCelier** [comment]
Ah ok ! Bon eh bien restons comme ça pour l'instant, à voir si Thomas ou Loup ont une idée ? 
Si ce n'est pas possible du tout, ce n'est pas dramatique non plus.

**Comment by thoomasbro** [comment]
Je ne vois pas non plus comment c'est possible de changer 'NM' pour 'nq' dans la barre d'échelle, à moins de faire quelque chose de vraiment compliqué. Par contre actuellement on affiche 'nm' en minuscule, alors que c'est en majuscule dans la barre d'échelle et que c'est plutôt en majuscule dans le système SI (mais peut être pas dans la pratique courante en France). On pourrait soit afficher `NM` plutôt que `nm` pour éviter la confusion avec les mètres `m`toujours en minuscule, soit afficher `nq` dans tous les éléments contrôlés par nous excepté la barre d'échelle qui resterait en `NM`

**Comment by AdelineCelier** [comment]
Ok merci, si nq c'est trop compliqué pas grave tant pis, je pense qu'il vaut mieux afficher la même chose partout et donc garder nm. En revanche je le garderais bien en minuscules dans les mesures sur la carto (pas grave de le laisser en majuscule dans la barre d'échelle). Et pour le différencier des mètres, c'est possible d'afficher "mètres" en toutes lettres et en minuscules sur les mesures de la carto ? Au moins ça lèverait toute ambiguité.

**Comment by AdelineCelier** [comment]
Le passage entre les deux unités fonctionne très bien. 
Juste en testant l'outil mesure avec un cercle, j'ai essayé de rentrer une coordonnée et un rayon : 
- dans la boîte de dialogue, le rayon est affiché en km, et sur la carte il se trace en mètres. Je pense qu'on peut rester sur les mètres, mais du coup il faut remplacer le "(km)" par "(m)" (cf. capture ci-dessous)
- il faudrait que quand je clique sur ok, cela centre sur ma mesure, comme pour le point d'intérêt.

=> Si tu n'as pas le temps de régler le souci avant la mep de demain c'est pas grave, on le fera pour la suivante ! 

![image](https://github.com/MTES-MCT/monitorenv/assets/71878648/0beda2da-3bff-4f29-8669-9c633806c639)
