### ISSUE TITLE
Crash de la SideWindow quand on rajoute un nouveau moyen

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorenv#346]
Depuis le composant : `ControlUnitSelector.tsx`

Cette partie pose problème: `resourcesField.value.map(resource => resource.id)}` car il n'y a pas d'id.
```
<TagPicker
              block
              cleanable={false}
              container={() => resourcesRef.current}
              creatable
              data={combinedResourceList}
              disabled={!_.isNumber(unitField.value)}
              labelKey="name"
              onChange={handleResourceChange}
              size="sm"
              value={resourcesField.value.map(resource => resource.id)}
              valueKey="id"
              {...props}
            />
```

Stacktrace:
```
TypeError: nodes[i] is undefined
    findNodes treeUtils.js:340
    filterNodesOfTree treeUtils.js:360
    useSearch utils.js:444
    InputPicker InputPicker.js:180
```

**Comment by claire2212** [comment]
Salut @AdelineCelier, pour résoudre ce souci j'ai enlevé la possibilité de créer un moyen au niveau du sélecteur. On en a discuté avec Thomas aujourd'hui et la création des moyens est apparement prévue dans la roadmap, on pourra donc retravailler ce sujet à ce moment là. J'espère que ça te va.

**Comment by AdelineCelier** [comment]
@claire2212 alors j'ai tapé un truc dans le menu déroulant des moyens, et j'ai fait "entrée", et là j'ai eu un gros "Something went wrong" un peu flippant 😅 

![image](https://user-images.githubusercontent.com/71878648/231507558-6b50e97b-9e73-45e9-be53-eb892f64ef25.png)
