### ISSUE TITLE
Missions – Ajouter la pop-up d'enregistrement du formulaire quand on clique sur la croix

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorenv#347]
Aujourd'hui on peut perdre les infos saisies dans le formulaire en cliquant sur la croix pour fermer la side window. 
Il faudrait faire apparaître la même pop-up que celle qui s'affiche quand on clique sur "quitter".

**Comment by AdelineCelier** [comment]
@claire2212 en fait je me rends compte qu'il n'y a pas de croix "interne" au formulaire de mission, c'est juste la croix de la side window ! Il y avait une croix sur mes maquettes, et je n'avais pas réalisé qu'il n'y en avait pas dans l'app, désolée. Je comprends pourquoi du coup c'est la pop-up du navigateur qui apparait, et non une pop-up custom comme dans les autres cas. 
Mais cela pose problème car du coup la pop-up apparaît aussi quand on veut fermer la side window alors qu'elle est sur la vue liste des missions (et qu'il n'y a rien à enregistrer). 
Je pense qu'il vaudrait mieux mettre une croix dans le bandeau bleu (cf. écrans), et afficher la même pop-up que celle du ticket #178 .

**Comment by claire2212** [comment]
@AdelineCelier il y a avait un souci sur la gestion de l'affichage du prompt natif du navigateur. Je l'ai résolu, le prompt ne s'affiche maintenant que si tu veux fermer la sidewindow alors que tu n'as pas enregistré les modifications de ta mission (ça me paraît important de garder ce fonctionnement).
 Pour ce qui est de la croix dans le header du formulaire j'ai fait une pr mais après en avoir discuté avec @thoomasbro on était pas convaincu de l'utilité de ce bouton supplémentaire. On pourra en rediscuter à ton retour et  faire un nouveau ticket au besoin

**Comment by AdelineCelier** [comment]
@claire2212 ok je comprends. Et du coup le prompt natif ne s'affiche plus dans le cas où l'on ferme la side window alors qu'elle est en vue "liste des missions" (et non "formulaire") ?

**Comment by claire2212** [comment]
@AdelineCelier oui c'est ça :-)

**Comment by AdelineCelier** [comment]
Ok, ça me va ! Et en effet, pas la peine pour l'instant de rajouter un bouton du coup.
