### ISSUE TITLE
Nouvelle administration - DEALM Mayotte DTAM St-Pierre-Et-Miquelon

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#359]
Ajouter les 2 nouvelles administrations : DEALM Mayotte à la place de DIRM/DM Mayotte et DTAM Saint-Pierre et Miquelon à la place de DIRM/DM  Saint-Pierre et Miquelon

Unités de DEALM Mayotte :
- ULAM 976 Mayotte
- DEAL Mayotte
- Police de l’eau 976 Mayotte
- DPM 976 Mayotte

Unités de DTAM Saint-Pierre et Miquelon :
ULAM 975 Saint-Pierre et Miquelon

**Comment by TEAMCACEM** [comment]
Action prioritaire svp

**Comment by thoomasbro** [comment]
Les unités existent déjà, mais sont rattachées comme suit:
- DREAL / DEAL
  - DEAL Mayotte
  - Police de l’eau 976 Mayotte
  - DPM 976 Mayotte

- DIRM/DM:
  - ULAM 976 Mayotte 
  - ULAM 975 Saint-Pierre et Miquelon


 Il s'agit donc de créer 2 nouvelles administrations `DEALM Mayotte` et `DTAM Saint-Pierre et Miquelon` et de changer l'affectation des unités ? 

Cela aura un impact sur toutes les missions passées.

**Comment by TEAMCACEM** [comment]
Oui.

Je ne sais pas comment sont gérées les missions passées.

**Comment by AdelineCelier** [comment]
@TEAMCACEM en gros si on crée de nouvelles administrations, les missions faites depuis le 1er janvier 2023 par les unités listées ci-dessus seront attribuées à leurs nouvelles administrations (DEALM et DTAM), et seront donc retirées du comptage des missions de leurs anciennes administrations (DIRM/DM et DREAL/DEAL)
Ce serait ok pour vous comme ça ?
