### ISSUE TITLE
Zones administratives - En retirer certaines, en rajouter d'autres

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorenv#36]
**Zones admin à retirer**
- Zones Cormoran
- Rectangles statistiques
- Zones du 1241
- Zones ORGP
- Zones pour situations VMS Brexit

**Zones admin à récupérer**
(à voir avec les géomaticiens - Alexia L?)
- façades
- régions (tracé terrestre)
- départements (tracé terrestre)
- eaux territoriales (comprises entre la limite des 12 milles et la limite des eaux intérieures). Pour cette dernière, soit on fait 2 couches, 1 ZEE et 1 eaux territoriales, soit on fait 3 limites (limite ZEE, limite 12 milles, limite eaux intérieures)

**Comment by thoomasbro** [comment]
Ticket découpé. 
Zones retirées ok.
Zones à ajouter : cf #141

**Comment by AdelineCelier** [comment]
Ok pour moi ! A voir si tu ne peux pas profiter de la discussion avec Alexia pour récupérer ces zones admin aussi ?
