### ISSUE TITLE
Rapportage - Bouton souris pour rentrer une zone de mission/surveillance

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#361]
A quoi est censé servir le 4e bouton ? Quand on clique dessus, rien ne se passe
![image](https://user-images.githubusercontent.com/122106549/221584614-570514c7-9b07-49a9-a7db-4b13c5c9e728.png)

**Comment by AdelineCelier** [comment]
Oui désolée, il ne devrait pas apparaître pour l'instant, la fonctionnalité n'est pas encore développée. 
L'idée c'était qu'il permette de sélectionner des tracés déjà affichés sur la carte (type une AMP). Mais le jour où on développera cette fonctionnalité, c'est possible qu'il soit plus simple de sélectionner la zone directement dans un menu déroulant, on n'a pas encore creusé.

**Comment by TEAMCACEM** [comment]
@AdelineCelier ok niquel cette fonctionnalité si elle voit le jour ! Merci pour la réponse, je ferme le ticket
