### ISSUE TITLE
Tableau missions - bug des résultats

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#366]
Des résultats sont incohérents.

Si je cherche des missions en filtrant avec l'unité "BSL Port les galets" je n'ai aucun résultat

![Réunion 1](https://user-images.githubusercontent.com/122106549/222065618-9d94e4bb-d2ac-4a30-b68d-b0135041a20f.png)

Si je ne mets aucun filtre (mais que je range les résultats par façade), je n'ai aucune mission de la BSL Port les galets

![Réunion 2](https://user-images.githubusercontent.com/122106549/222065638-7b882d5e-b519-4568-b5e8-e96408d4fde5.png)

Si je mets un filtre de date (er que je range les résultats par façade), 2 missions de la BSL Port les galets apparaissent

![Réunion 3](https://user-images.githubusercontent.com/122106549/222065639-12dc8827-86ba-481d-8d04-35a257cb39f6.png)

**Comment by TEAMCACEM** [comment]
Des résultats sont incohérents.

Si je cherche des missions en filtrant avec l'unité "BSL Port les galets" je n'ai aucun résultat

![Réunion 1](https://user-images.githubusercontent.com/122106549/222065618-9d94e4bb-d2ac-4a30-b68d-b0135041a20f.png)

Si je ne mets aucun filtre (mais que je range les résultats par façade), je n'ai aucune mission de la BSL Port les galets

![Réunion 2](https://user-images.githubusercontent.com/122106549/222065638-7b882d5e-b519-4568-b5e8-e96408d4fde5.png)

Si je mets un filtre de date (er que je range les résultats par façade), 2 missions de la BSL Port les galets apparaissent

![Réunion 3](https://user-images.githubusercontent.com/122106549/222065639-12dc8827-86ba-481d-8d04-35a257cb39f6.png)

**Comment by AdelineCelier** [comment]
@TEAMCACEM ah c'est étonnant ça ne le fait pas de mon côté...
Je vois que ce commentaire date un peu (désolée de ne pas y avoir répondu plus tôt), est-ce que ça le fait toujours chez vous ?

**Comment by TEAMCACEM** [comment]
@AdelineCelier alors ça le fait toujours mais on sait pourquoi : il doit y avoir un filtre pour ne pas que trop de missions apparaissent quand on ne filtre pas nous mêmes les dates. Je pense que ça n'affiche que les missions des 30 derniers jours. Donc si on ne remplit pas le filtre des dates, il y a seulement les missions des 30 derniers jours.
Exemple : 
l'ULAM 972 me demande le 16/03/2023, le nombre de missions depuis le début de l'année
Si je coche uniquement le filtre unité, j'ai seulement les missions depuis le 14/02 : 
![image](https://user-images.githubusercontent.com/122106549/225586988-468a56cc-3c69-45e0-b5cf-e1d4e8cc5731.png)
Si j'ajoute le filtre "depuis le 01/01/2023", j'ai 20 missions de plus :
![image](https://user-images.githubusercontent.com/122106549/225587175-27591f29-8265-4172-8183-33308dcac620.png)

C'est source d'erreur de devoir remplir le champ de date de début donc ce serait mieux si on ne devait pas le faire pour chaque recherche. Mais si le fait d'enlever ce "filtre par défaut" de 30 jours fait bugger MonitorEnv parce qu'il y a trop de missions qui apparaissent en permanence : on peut changer notre manière de faire et faire attention à toujours renseigner la date de début

**Comment by AdelineCelier** [comment]
Ok vu, effectivement j'observe la même chose chez moi maintenant, j'avais peut-être mal testé la première fois.
Il y a en effet un filtre par défaut sur les 30 derniers jours, Thomas l'avait affiché mais il n'apparaît plus (en tous cas de mon côté). 

@thoomasbro je pense qu'il faut se repencher assez rapidement sur les règles de filtrage du tableau, car aujourd'hui c'est effectivement source de confusion et d'erreur : 
1/ rendre visibles et compréhensibles le filtrage temporel par défaut 
2/ s'accorder sur le comportement du tableau dans le cas où le filtrage par l'utilisateur génère l'affichage d'un grand nombre de mission (variation du filtre temporel + pas de filtrage sur les missions clôturées par ex.) : est-ce qu'on met une pagination (mais quid du lien avec la carte), est-ce qu'on contraint une certaine période max (et on se dit que pour les périodes longues Metabase doit pouvoir répondre au besoin ?)...identifier plusieurs hypothèses à présenter au CACEM pour choisir la plus adaptée aux besoins. 
=> à faire avec Fish, puisqu'il y aura les mêmes problématiques de leur côté.

**Comment by AdelineCelier** [comment]
Ces problèmes ont été réglés dans d'autres tickets, je ferme celui-ci.

**Comment by manonolivier** [comment]
Bonjour @claire2212 @maximeperraultdev et @thrulight 

Dans la liste des missions, certaines ne s'affichent pas. Dans cet exemple, j'ai filtré à la date du 08/06 et au bout d'un moment (22 missions affichées), les lignes sont toutes blanches : 

<img width="1909" height="1078" alt="Image" src="https://github.com/user-attachments/assets/e83e5551-dae1-44fe-bf8a-0d0808e2a2d9" />

**Comment by maximeperraultdev** [comment]
Bonjour @manonolivier, 

Je corrige ça vite !
