### ISSUE TITLE
Zone des missions multiples - ne doit pas zoomer

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#370]
On enregistre parfois plusieurs zones pour une même mission (mission pêche à pied, carénage sauvage, etc...). Cela zoom sur la zone précédente lorsque l'on veut créer une nouvelle zone (+Ajouter une zone de mission) et ce n'est pas du tout pas pratique. On doit alors dézoomer alors qu'on avait bien la fenêtre positionner sur la zone où on veut créer la seconde zone. Pouvez-vous enlever le zoom automatique ?
Idem lorsque je souhaite ajouter un point de contrôle. Cela zoom automatiquement sur ma zone de mission. Pouvez-vous enlever ce zoom automatique qui est gênant ?

**Comment by AdelineCelier** [comment]
@TEAMCACEM Alors je comprends le retour, pour moi ce n'est pas vraiment un bug. C'est plutôt qu'il y a des cas pour lesquels le zoom est intéressant (quand il n'y a qu'une seule zone de mission et que les contrôles sont dans la zone ou à côté), et d'autres cas où il ne l'est pas (quand ce sont des zones de mission différentes, et/ou que les contrôles ne sont pas dans la zone de mission). 
Mais ça veut dire qu'il y a des cas où vous dessinez des zones de mission très éloignées les unes des autres ? Vous avez un ex. de mission de ce type pour que je puisse me rendre compte ?
Et idem, pourquoi dans le cas d'un ajout de point de contrôle est-ce gênant de zoomer sur la zone de mission ? Ca arrive vraiment souvent que les points de contrôle soient en-dehors ou très loin de la zone de mission initiale ?

**Comment by TEAMCACEM** [comment]
@AdelineCelier 
- quand on veut entrer une seconde zone, ça zoom fort sur la première donc même si la seconde zone qu'on veut créer n'est pas loin, elle sort de la vision de la fenêtre. Ce n'est pas pratique parce qu'on fait notre sélection de zones reg intéressantes / de lieux-dits avant de cliquer sur "ajouter une mission" (vu qu'on n'a pas accès aux boutons des zones reg pendant le tracé de la zone) donc on a bien préparé l'endroit où on va tracer la seconde zone de mission et en cliquant sur "ajouter une zone de mission" ça annule tout en zoomant sur la première zone de mission tracée. ==> le zoom n'est jamais utile au moment où on clique sur "ajouter une zone de mission" (ce sera déjà sur la zone si on est en train de créer la mission et si on souhaite l'éditer a posteriori on a le bouton "centrer sur la carte" qui nous permet de le faire)
- pour l'ajout de point de contrôle : le problème c'est que ça "dézoome" pour que toute la zone de mission apparaisse dans la fenêtre mais même raisonnement que dans le point d'avant : on a déjà fait notre repérage de la zone précise où poser le point de contrôle avant de cliquer sur "ajouter un point de contrôle" ==> le zoom n'est jamais utile au moment où on clique sur "ajouter un point de contrôle" (ce sera déjà sur la zone si on est en train de créer la mission et si on souhaite l'éditer a posteriori on a le bouton "centrer sur la carte" qui nous permet de le faire)

**Comment by claire2212** [comment]
@TEAMCACEM j'ai enlevé le zoom, si tout est ok pour vous je ferme l'issue
