### ISSUE TITLE
Améliorer la recherche de nom d'unité

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#372]
La recherche par nom d'unité est très stricte. pouvez-vous l'assouplir ?
ULAM 50 : ça ne fonctionne pas si je tape "ulam50"
DF 46 : ça ne fonctionne pas si je tape "df56"
Police de l'eau 06 : ça ne fonctionne pas si je tape "police eau" ni avec "06"
etc etc

[EDIT] Nouvelle remontée CACEM le 29/03/2023

> La recherche d'unité est trop stricte.
> Exemples :
> Pour rechercher "ULAM 976 Mayotte"
> - je tape "ulam mayotte", ça ne trouve pas
> - je tape "ulam976", ça ne trouve pas
> Pour rechercher "DF P2 Kermorvan"
> - je tape "DFP2, ça ne trouve pas
> Pour recherche "police de l'eau 83"
> - je tape "police 83", ça ne trouve pas
> - je tape "police eau", ça ne trouve pas
> 
> Les espaces semblent altérer la facilité de recherche.

**Comment by AdelineCelier** [comment]
Ok vu c'est vrai que c'est strict.

@thoomasbro est-ce qu'il serait possible de ne pas prendre en compte la casse et les espaces (cas 1 et 2) ? Et pour le cas 3, c'est étonnant que la Police de l'eau 06 ne remonte pas quand on tape 06, tu as une idée de pourquoi ?

**Comment by TEAMCACEM** [comment]
@AdelineCelier si ça fonctionne quand on tape juste 06 je pense qu'elle voulait dire quand on tape "police 06" ou quelque chose du genre

**Comment by AdelineCelier** [comment]
A voir si on peut régler ces problèmes avec la recherche de monitor-ui actuelle updatée par Thomas avec du fuzzy search.

**Comment by AdelineCelier** [comment]
@claire2212 j'ai l'impression que ça marche mieux, on peut déjà passer ça en prod. 

Après il y a encore un cas où les résultats ne remontent pas, c'est quand on cherche des mots séparés. 
Par ex "Police 83" pour "Police de l'eau 83" ne fonctionne pas, idem "ULAM Mayotte" pour "ULAM 976 Mayotte.
Est-ce qu'il y aurait un réglage qui permettrait de faire remonter ces résultats ou bien compliqué ? 
Si c'est trop compliqué ou si ça risque de brouiller d'autres cas de recherches, ça ne vaut peut-être pas le coup de l'implémenter.
