### ISSUE TITLE
Contrôle - Dates des contrôle qui se suppriment

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#382]
De manière un peu aléatoire, soir la date et heure ne s'enregistre pas soit elle se supprime tout seul lorsque l'on navigue dans la fenêtre d'édition de la mission (cliquer sur un autre contrôle par exemple)

**Comment by AdelineCelier** [comment]
@TEAMCACEM est-ce que ça le fait uniquement sur les dates de contrôle, ou bien aussi sur les dates et heures de mission ?

**Comment by TEAMCACEM** [comment]
uniquement les contrôles
