### ISSUE TITLE
Sémaphores - signalement non-avéré

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#393]
Comment fait-on pour comptabiliser les signalements non avérés sur monitor Env ? Doit-on les noter dans un fichier à part ?

**Comment by AdelineCelier** [comment]
Ces cas seront traités dans le module signalements. @TEAMCACEM ok pour fermer ce ticket ?

**Comment by TEAMCACEM** [comment]
Ok et en attendant on le met dans note libre
