### ISSUE TITLE
Fenêtre Vue détaillée des missions - premier plan

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#396]
Lorsque je clique sur "Vue détaillée des mission", la page s'ouvre au premier plan. C'est ce que l'on veut mais cela ne fonctionne pas lorsque la page est déjà ouverte.
On travaille avec "Vue détaillée des mission" ouverte en permanence mais je travaille souvent sur autre chose au premier plan. Lorsque je clique sur "Vue détaillée des missions", la page n'apparait pas au premier plan et je dois aller la chercher dans mes pages ouvertes. Ce n'est pas très pratique. Est-ce que lorsque l'on clique sur "Vue détaillée des mission", elle peut apparaitre au premier plan ?

**Comment by AdelineCelier** [comment]
Ce ticket relève du même problème que le ticket #394. Si on trouve une solution pour remonter la fenêtre avec la carto, je pense qu'elle fonctionnera aussi dans l'autre sens. Je le supprime et renomme le 394 pour l'élargir.
