### ISSUE TITLE
Recherche d'unité - facilité la recherche par mot

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#404]
La recherche d'unité est trop stricte.

Exemples :
Pour rechercher "ULAM 976 Mayotte"
- je tape "ulam mayotte", ça ne trouve pas
- je tape "ulam976", ça ne trouve pas
Pour rechercher "DF P2 Kermorvan"
- je tape "DFP2, ça ne trouve pas
Pour recherche "police de l'eau 83"
- je tape "police 83", ça ne trouve pas
- je tape "police eau", ça ne trouve pas

Les espaces semblent altérer la facilité de recherche.

**Comment by AdelineCelier** [comment]
@TEAMCACEM il y a déjà le ticket #372 sur le sujet, qui est bien identifié mais qui n'a pas été traité encore. 
Je reporte le commentaire de ce ticket dans le 372 et ferme celui-ci.
