### ISSUE TITLE
METABASE - Comment fait-on pour avoir des graphes visualisable ?

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#408]
Pour rappel, la commande initiale pour les statistiques est :
- graphes exportables en image ou pdf
- graphes avec le chiffre de la donnée dans la barre (actuellement uniquement le pourcentage)
- graphe avec titre
- graphe avec le nom de l'axe modifiable

**Comment by AdelineCelier** [comment]
@VincentAntoine tu me disais qu'il y avait eu des mises à jour de Metabase qui permettaient plus de format d'export. Tu peux nous redire ici ce qui est possible maintenant + si les autres points de ce ticket sont possibles/encore pertinents au vu de l'usage actuel de Metabase ?

**Comment by VincentAntoine** [comment]
Oui il est possible de faire un export en image depuis le menu en haut à droite :

![image](https://github.com/MTES-MCT/monitorenv/assets/27647971/b3e5edd3-0021-4c2a-9910-d7f72ef01c24)

Cliquer sur "Télécharger les résultats" puis 

![image](https://github.com/MTES-MCT/monitorenv/assets/27647971/9453f7d0-6626-4c4a-96d3-f80f81658eb8)


> graphes avec le chiffre de la donnée dans la barre (actuellement uniquement le pourcentage)
De quel graphe s'agit-il ?

> graphe avec titre
De quel graphe s'agit-il ?

> graphe avec le nom de l'axe modifiable
Pas possible avec Metabase

**Comment by TEAMCACEM** [comment]
- Le ticket date du 30 mars donc Metabase a bien évolué depuis 5 mois.
- L'évolution de Métabase qui permet le téléchargement du graphe en différent format (dont image) répond à la demande.
- "_graphes avec le chiffre de la donnée dans la barre (actuellement uniquement le pourcentage)_" -> je crois que il y a désormais un chiffre donnée de graphe
- "_graphe avec titre_" -> il y avait des graphes sans titre lors de la création du ticket mais c'est réglé depuis. Il serait bien d'ajouter à chaque titre "de l'année 2023 à la date t/07/2023"
- "_graphe avec le nom de l'axe modifiable_" -> résolu car on a des noms d'axe corrects désormais

**Comment by TEAMCACEM** [comment]
En fait idéalement il faudrait que tout les filtres que j'applique (façade, administration, période,...) se retrouve indiqué dans le titre des graphes.
On est hyper à cheval là dessus car après on nous demande des explication sur des graphes et s'il n'y a pas un titre précis on ne sait même pas à quoi cela correspond.

EX : 
![image](https://github.com/MTES-MCT/monitorenv/assets/122106549/c0a628c0-5f64-4b7b-91e0-10248f1845a0)

ici les filtres 01/01/2023 au 24/08/2023 et unités DDTM 62 n'apparait pas dans le titre

**Comment by VincentAntoine** [comment]
Je vois.
Dans Metabase on ne peut pas modifier les titres ou annotations en fonction de filtres sélectionnés, il faudra le préciser dans vos docs séparément. Ou bien donner accès aux personnes qui vous demandent les chiffres, afin qu'elles consultent elles-mêmes les données dans Metabase, ce qui sera aussi le cas de plus en plus, avec notamment les DML qui vont désormais accéder à Metabase à partir de la semaine prochaine.
Peut-on clore ce ticket ?

**Comment by TEAMCACEM** [comment]
(Roxane) Je réouvrre ce ticket. 
Je dois pouvoir télécharger une figure avec son titre et l'ensemble des titres des abscisses et des ordonnées (sans regroupement "Autre").
Lorsque ma figure comporte des données "Autre", soit je l’enregistre directement en .png et j'ai les données "Autre" qui restent ainsi ; soit je dois l'ouvrir en cliquant sur le titre pour l'avoir en plus grand mais le téléchargement en .png n'enregistre pas le titre. Ca ne convient pas dans les deux cas.

**Comment by roxaneducacem** [comment]
Certaines figurent ont des ordonnées avec regroupement "Autre" et il n'est plus possible de modifier la visualisation du graphe. Comment visualiser le graphe en entier svp ?

**Comment by roxaneducacem** [comment]
Je supprime ce ticket. morga, reprend le travail

**Comment by AdelineCelier** [comment]
Hello Roxane, tu peux archiver le ticket plutôt que le supprimer ? Cela permet de garder trace des échanges, si besoin de revenir dans l'historique. 
Merci !

**Comment by roxaneducacem** [comment]
Oui ok je le fais pour le reste des tickets

**Comment by VincentAntoine** [comment]
Flippant le ghost :fearful:
