### ISSUE TITLE
Point d'intérêt - La carte ne se centre pas sur le point quand on le crée

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorenv#41]

**Comment by claire2212** [comment]
@AdelineCelier faut-il zoomer quand on met le point sur la carte où quand on clique sur "OK" pour enregistrer le point d'intérêt? Je pense que le mieux est la 2ème solution , tu es ok?

**Comment by AdelineCelier** [comment]
@claire2212 mmh oui je pense que ce serait plus logique en cliquant sur ok. Seul point que je vois avec cette solution c'est que si tu as saisi les coordonnées au clavier et que tu as fait une erreur de frappe qui place ton point à un autre endroit, tu ne t'en aperçois qu'à ce moment-là. Mais bon, ça n'est pas très long de modifier le point le cas échéant.

**Comment by AdelineCelier** [comment]
Ca marche bien.
