### ISSUE TITLE
Unités - Renommage (changement de lieu d'affectation)

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#415]
J'ai remarqué que les changements d'affectation qui on eu lieur fin 2022 n'ont pas tous été pris en compte dans les unités de Monitor Env (issu du fichier de base sur les unités/moyens de Roxane).

- La P613 Charente (anciennement à la BGMAR la Rochelle) est à la BGMAR Cayenne
- BGMAR La Rochelle a maintenant la P604 Scarpe
- il y a une erreur dans PGMAR Violette - P722 Violette, c'est PGMAR Pointe-à-Pitre - P722 Violette

**Comment by AdelineCelier** [comment]
Ok merci, il y a dû y avoir un problème à un moment. 
Je bascule ce ticket de notre côté
