### ISSUE TITLE
Rapportage - Différence entre l'heure affichée et l'heure rentrée

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#418]
Je ne sais pas si c'est lié au #290 mais parfois l'horaire affiché au milieu de la capture ne correspond pas à celle rentrée à droite
![MoniteurEnv Heure](https://user-images.githubusercontent.com/122106549/230085514-e1c44174-39bb-4b7d-931d-7749ec152276.PNG)

**Comment by AdelineCelier** [comment]
@thoomasbro Est-ce que tu penses que c'est lié au bug remonté par Ivan concernant le passage à l'heure d'été ?

**Comment by thoomasbro** [comment]
Non, je pense que c'est un bug qui a été corrigé sur les actions de contrôle, mais qui reste peut être à quelques endroits, après la mise à jour des composants de date de monitor-ui.

**Comment by AdelineCelier** [comment]
Ok, on refait une passe pour vérifier où le bug peut s'être encore glissé.

**Comment by AdelineCelier** [comment]
J'ai l'impression que ce bug n'est pas revenu, je passe le ticket.
