### ISSUE TITLE
Notes libres – Il manque l'horodatage des notes libres

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorenv#422]
Il faudrait que les notes libre ssoient automatiquement horodatées avec leur horaire d'ouverture par l'utilisateur. 
Cela permettrait de conserver cette logique de "main courante" dans la colonne 2 du formulaire de mission.

**Comment by claire2212** [comment]
@AdelineCelier j'ai l'impression que c'est déjà le cas (voir la capture d'une mission en prod)  : 

![Capture d’écran 2023-05-30 à 15 27 44](https://github.com/MTES-MCT/monitorenv/assets/23258718/05bec035-f6cc-4252-9235-042012b843df)
