### ISSUE TITLE
Rapportage - Bug lors de la suppression de thématiques de surveillance

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#423]
J'ai voulu enlever la thématique du milieu (police espèces) mais ça a supprimé la 3e (réserve) tout en laissant quand même "réserve" et enlevant "espèces" de la colonne du milieu

![image](https://user-images.githubusercontent.com/122106549/230598464-d3d66e0a-7de5-4411-96c7-efd9c2b1f071.png)

![image](https://user-images.githubusercontent.com/122106549/230598401-6f5e2102-94b8-47f9-8c02-26cc788fcd74.png)

**Comment by AdelineCelier** [comment]
@TEAMCACEM en effet désolée, il y a des choses bizarres qui se passent quand on supprime une thématique au milieu d'autres thématiques. Je bascule ce ticket dans notre kanban.
