### ISSUE TITLE
L'œil pour visualiser un groupe de zones épinglées ne centre pas les zones sur la carte

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#426]
On est dans le cas où je recherche le nom d'une couche, je l'épingle car je veux la visualiser. Je clique sur l'oeil de la couche dans "Mes zones réglementaires mais ça ne zoome pas sur la couche

**Comment by AdelineCelier** [comment]
@TEAMCACEM j'ai tenté de reproduire chez moi, ça ne le fait en effet pas quand on clique sur l'œil au niveau du groupe de zones, en revanche ça fonctionne quand on clique sur l'œil au niveau d'une zone au sein du groupe. Vous me confirmez que ça me fait pareil chez vous ? 
Je bascule le ticket en tous cas pour le problème au niveau du groupe de zones.

**Comment by AdelineCelier** [comment]
Traiter aussi le cas dans les résultats de recherche : quand on clique sur le nom d'un groupe de zones, il faudrait que la carte se centre sur ce groupe.

**Comment by AdelineCelier** [comment]
c'est bon ça fonctionne
