### ISSUE TITLE
Pas de préremplissage d'heure lors du choix d'une date

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#437]
Lorsque je choisis une date de fin sur e calendrier (mission, surveillance et contrôle), l'heure 00:00 est automatiquement remplie. Merci de supprimer ce préremplissage.
Lorsque je choisis une date sur le calendrier, je ne peux pas directement taper l'heure mais doit cliquer sur l'encart de l'heure pour la taper.
Aussi, lorsque je choisi une date et que je veux renseigner l'heure, je ne peux pas taper HH:MM directement. Obligé de cliquer sur HH et taper puis cliquer sur MM et taper.

**Comment by AdelineCelier** [comment]
@TEAMCACEM de mon côté le problème sur le fait de directement taper la date et l'heure sans interruption semble réglé. Est-ce bien le cas chez vous aussi ?
Concernant le pré-remplissage, il doit indiquer aujourd'hui "23h59" et non plus "00h00". Du coup c'est comme si vous n'aviez indiqué que la date, c'est juste que ça montre que ça prend la journée entière. Ok pour vous ?

**Comment by AdelineCelier** [comment]
Comme discuté avec vous (surtout Roxane je crois), il faut forcément indiquer une heure à partir du moment où il y a une date, sinon on ne peut pas déterminer une plage temporelle. 
Donc quoi qu'il arrive le 23h59 sera enregistré en base. Il a été convenu qu'on le gardait affiché pour plus de clarté. 
Je ferme donc ce ticket.
