### ISSUE TITLE
Mission - Pouvoir supprimer une mission après son enregistrement (régression)

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#440]
A l'heure actuelle, on ne peut pas supprimer la mission en cours ou terminée ou clôturée

**Comment by TEAMCACEM** [comment]
On pouvait supprimer avant. Mais je ne sais plus si c'était uniquement les misions clôturées ou pas. On souhaite pouvoir supprimer les mission peut importe leur statut.

**Comment by AdelineCelier** [comment]
@thoomasbro Le comportement du bouton est à nouveau le bon, en revanche quand je clique sur "confirmer la suppression" dans la pop-up, il ne se passe rien...je ne peux que cliquer sur "retourner à l'édition". Donc au final je ne peux toujours pas supprimer ma mission ;)
Et petit retour UI : l'icône de poubelle a perdu sa jolie couleur rouge !

**Comment by claire2212** [comment]
@AdelineCelier, @thoomasbro  j'ai trouvé le souci, c'est ma faute. je règle ça rapidement (et remet la poubelle en rouge)

**Comment by AdelineCelier** [comment]
Top merci !

**Comment by AdelineCelier** [comment]
c'est bon, la suppression fonctionne à nouveau, j'avance le ticket.
