### ISSUE TITLE
La recherche NATINF est sensible aux accents

### ISSUE THREAD

**Issue by VincentAntoine** [MTES-MCT/monitorenv#443]
> les natinfs sont enregistrés sans accent mais la recherche de natinfs est trop sensible par rapport aux accents. Peut-on la rendre moins sensible ?

**Comment by AdelineCelier** [comment]
Hello, j'avais créé le ticket [1923](https://github.com/MTES-MCT/monitorfish/issues/1923) dans MonitorFish pour chercher à traiter plus largement la question de la recherche, car le CACEM a aussi fait des retours sur la recherche d'unités par ex, et que ces questions vont se poser aux deux Monitor. 

@louptheron @thoomasbro @ivangabriele comment voulez-vous procéder sur ce point ? Est-ce que le ticket 1923 vous convient (et si oui, est-ce qu'on le laisse dans MonitorFish, ou bien est-ce qu'on le bascule dans MonitorUI, dans le sens où c'est un élément commun ?) ? Ou bien préférez-vous découper le ticket 1923 en plus petits tickets (un sur les accents, un sur les espaces...etc.) ?

**Comment by AdelineCelier** [comment]
Après discussion avec Claire et Thomas, on a convenu qu'il reste intéressant de rajouter un peu de fuzzy search dans le composant de recherche, dans l'optique de tolérer petites coquilles et fautes d'orthographe.
