### ISSUE TITLE
Dans le "pense bête"/remontées de besoins : ajouter les AOT EIN2000 temporaires

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#449]

**Comment by AdelineCelier** [comment]
Hello le CACEM, toujours besoin de ces zones AOT EIN2000 temporaires ?
Je ne suis pas sure de voir de quoi il s'agit...est-ce toujours à prendre en compte ?

**Comment by manonolivier** [comment]
Oui, ça fait référence par exemple aux Manaut en N2000 qui ont fait l'objet d'une EIN. L'idée serait de pouvoir avoir l'info "sur telle zone il y a une manaut tel jour" comme les remontées de besoin "à tel endroit il y a besoin de contrôler telle activité". A l'heure actuelle, nous ne sommes pas destinataires de toutes ces EIN, on utilise le tableau MANAUT du CROSS d'Etel mais ça fait qu'on doit aller vérifier dans ce doc, l'idée serait d'avoir l'info direct dans ME.

Ce n'est pas en prio, ce ticket avait été fait pour ne pas oublier de penser à cette possibilité.

**Comment by AdelineCelier** [comment]
@manonolivier, je retombe sur ce ticket. Est-ce que ces zones peuvent rentrer dans le cadre des zones de vigilance ou pas ?

**Comment by manonolivier** [comment]
@AdelineCelier yes carrément, il faut qu'on voit en interne comment rentrer ces infos par contre mais en effet pas besoin d'un développement MEnv en plus

**Comment by AdelineCelier** [comment]
Cool ! Est-ce que vous voulez garder le ticket dans la colonne "à intégrer aux procédures" ou bien on le ferme ?

**Comment by manonolivier** [comment]
Non on peut le fermer, merci !
