### ISSUE TITLE
Il est possible d'ajouter plusieurs points de contrôle (et ça ne devrait pas)

### ISSUE THREAD

**Issue by VincentAntoine** [MTES-MCT/monitorenv#457]
- [ ] Au moment de la saisie du point de contrôle dans une action de contrôle, si on clique à plusieurs endroits sur la carte, tous les points sélectionnés sont enregistrés dans une unique géométrie MULTIPOINT -> empêcher ceci, par exemple en ne conservant que le dernier point sélectionné sur la carte, dans le cas où l'utilisateur cliquerait à plusieurs endroits
- [ ] Une fois un point de contrôle ajouté, le bouton "Ajouter un point de contrôle" n'a plus d'effet (comme attendu) mais n'est pas désactivé visuellement (grisé ou autre), ce qui serait sans doute préférable par souci de clarté
- [ ] Ne pas afficher les pop-up de surveillance et contrôle durant l'ajout d'un point de contrôle ou d'une zone de surveillance

**Comment by AdelineCelier** [comment]
Les trois points décrits dans le ticket sont bons pour moi, en revanche j'ai repéré un comportement qui n'est pas hyper gênant mais qui n'est pas logique : quand j'ai ajouté un point de contrôle sur la carte, si je clique sur "quitter" plutôt que "valider le point", ça enregistre quand même le point de contrôle. Donc les deux boutons "quitter" et "valider" ont le même comportement. 
Si l'on clique sur "quitter", pour moi c'est qu'on ne veut pas enregistrer le point.
