### ISSUE TITLE
contact de l'unité - obligation à l'ouverture de mission mais pas à la cloture

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#463]
Peut-on rendre le contact de l"unité obligatoire que lors de l'ouverture de mission ?
Si je rentre une mission à postériori (mail ou en décalé), je n'ai pas besoin de renseigner le contact (que j' n'ai pas) et je rentre par défaut un caractère pour pouvoir clôturer la mission

**Comment by AdelineCelier** [comment]
@TEAMCACEM je vois le souci, effectivement c'est gênant dans le cas d'une mission saisie a posteriori. 
En fait il y a 2 types d'obligations : soit au 1er enregistrement, soit à la clôture. Mais pour pouvoir clôturer une mission, il faut bien l'enregistrer une première fois. Du coup je ne suis pas sure qu'on puisse faire la différenciation. @claire2212 et @thoomasbro, vous confirmez ?

Peut-être que le plus simple serait encore de ne pas rendre ce champ bloquant du tout...étant donné qu'il n'est important "que" pour le pan opérationnel de la mission, mais pas pour le pan statistique.

**Comment by TEAMCACEM** [comment]
Effectivement c'est uniquement important pour l’opérationnel pour rappeler l'unité mais pas pour les statistiques. 
Faites comme vous voulez mais s'il doit être bloquant, cela doit uniquement être à l'enregistrement de début de mission.

**Comment by TEAMCACEM** [comment]
Parfait
