### ISSUE TITLE
Points d'intérêt – Dans certaines sessions, impossible de supprimer des points d'intérêt

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#464]
j'ai (Manon) quelques points qui ne peuvent pas être supprimé (on peut le modifier cependant mais pas du tout le supprimer, même en lui donnant un nom, une observation et autres), pour l'instant 2 sur 2 ordis différents, on peut voir aussi qu'il y a un bug sur la ligne de pointillés :

![image](https://user-images.githubusercontent.com/122106549/235437443-de03a382-f0c5-4fef-b6d0-a0f2077281dc.png)

**Comment by AdelineCelier** [comment]
@Manon ok donc ça le fait sur plusieurs ordis maintenant ! 
Je le passe en bug dans notre Kanban.

**Comment by TEAMCACEM** [comment]
(Adrien) Cela arrive lorsqu'on crée un point d'intérêt puis qu'on ferme le module en cliquant sur la tête d'épingle. Le point d'intérêt ne part plus et reste à vie sur MENV sur l'ordinateur qui a créé le point. Si on ouvre une session avec le même utilisateur sur un autre ordinateur, le point n'apparaît pas.

**Comment by TEAMCACEM** [comment]
@claire2212 ça marche

**Comment by TEAMCACEM** [comment]
Idem pour moi certains points ne peuvent pas être supprimés et cachent le reste

**Comment by claire2212** [comment]
@TEAMCACEM , Roxane j'avais montré à Manon comment les enlever "manuellement", est-ce que tu peux voir avec elle? Sinon on peut s'appeler et on le fait ensemble. On a bien identifié le souci mais il n'est pas prioritaire car on s'est dit qu'une fois les signalements finis vous vous serviriez moins des points d'intérêts

**Comment by TEAMCACEM** [comment]
Ok

**Comment by maximeperraultdev** [comment]
@TEAMCACEM Est-cec que le problème sur la ligne de pointillés est dû à un dezoom ?

**Comment by manonolivier** [comment]
@maximeperraultdev Yes

**Comment by AdelineCelier** [comment]
@TEAMCACEM il est possible que les derniers devs qu'on ait fait sur les points d'intérêt règlent le problème des points qui ne peuvent pas se supprimer, mais on n'est pas certains car le bug n'est pas reproductible de notre côté. 
Est-ce que vous pouvez nous dire si cela arrive à nouveau ?

**Comment by manonolivier** [comment]
Yes on vous tient au courant

**Comment by AdelineCelier** [comment]
Hey @TEAMCACEM est-ce que vous avez eu d'autres problèmes avec les points d'intérêt depuis juin ? 
Si non, peut-être qu'on peut fermer ce ticket ?

**Comment by manonolivier** [comment]
@AdelineCelier Il y a juste eu Johanna qui a eu le cas cet été je crois mais on peut le fermer, c'était peut-être des points qui dataient d'avant juin parce que je crois qu'elle n'en avait pas parlé pendant longtemps parce que ça ne la gênait pas vraiment
