### ISSUE TITLE
Signalements - Affichage et recherche des Sémaphores

### ISSUE THREAD

**Issue by claire2212** [MTES-MCT/monitorenv#465]
1. Sur la carte ajout d'un bouton (idem Point d'intérêt) pour l'affichage et la recherche des sémaphores. 

2. Au clic ouverture d'une pop-up : 
       - Champ de recherche des sémaphores (par nom): 
                            - Recherche resetée au changement d'onglet. 
                            - Gestion d'un historique de 4/5 sémaphores
                            - Au clic sur le sémaphore choisi on centre la carte sur celui-ci
       - Bouton "Oeil" pour masquer/afficher les sémaphores (idem Mission), par défaut ils sont affichés.
      
3. Icône Sémaphore : Pas de gestion de présence de signalements ou non (avec le cercle). Sera fait plus tard.

4. Au survol d'un sémaphore :  
         - Affichage d'une pop avec le contact du sémaphore
         - Pas de bouton pour le moment
         - Pas de tag avec nombre de signalement
         
5. Au clic sur la pop-up : possibilité de déplacer la pop-up

 Maquette : https://xd.adobe.com/view/e38d0e55-0dfe-43d6-9a1b-c85e26189d86-b6de/grid

**Comment by TEAMCACEM** [comment]
Salut Claire et Adeline,
Effectivement on va se servir de ce module comme l’annuaire sémaphore donc on doit pouvoir copier le mail/tel au besoin. Un bouton copy semble convenir

**Comment by AdelineCelier** [comment]
Hello le CACEM
Ok bien noté ! Dans ce cas je dessine qqch dans ce sens.

**Comment by AdelineCelier** [comment]
**Sur la pop-up des sémaphores**
- A voir si possible de toujours afficher la pop-up au-dessus de l'icône du sémaphore, avec env 8px d'écart entre l'icône et la pop-up. 
- A voir aussi si possible de ne pas afficher les tooltips quand on prend la pop-up et la déplace sur la carte. 
- Il y a un truc un peu bizarre qui se passe avec le lien en pointillés quand je clique sur un sémaphore pour figer sa pop-up, puis que je recherche un autre sémaphore (ça centre donc la carte sur l'autre sémaphore), et que je reviens ensuite sur le 1er sémaphore dont j'avais figé la pop-up.
![image](https://github.com/MTES-MCT/monitorenv/assets/71878648/d9eba190-f171-43a6-97d4-3c35a4151c22)


**Sur le menu de recherche**
Est-ce qu'il serait possible de faire une largeur fixe pour le menu déroulant avec le résultat des recherches ? Là, la taille varie selon ce qu'on tape (cf. captures). Le mieux serait de le faire aussi large que le menu global. 
![image](https://github.com/MTES-MCT/monitorenv/assets/71878648/af211f13-e6be-49be-9bdc-f0a905423e2a)
![image](https://github.com/MTES-MCT/monitorenv/assets/71878648/51b4e512-cb65-43c1-a0ad-5018f326510b)

**Comment by AdelineCelier** [comment]
@claire2212 tous les points que je t'ai remontés sont bons pour moi.
En revanche deux autres problèmes : 
- j'ai l'impression que les boutons pour copier ne fonctionnent plus : quand je clique dessus, le tooltip ne devient pas vert + ça ne copie pas l'info dans le presse-papiers. 
- les sémaphores réapparaissent à l'édition d'une zone ou d'un point sur la carte

**Comment by claire2212** [comment]
@AdelineCelier pour la copie des sémaphores qui ne fonctionne pas, c'est parce qu'on est en http, en local et en prod c'est ok. Les navigateurs ne permettent pas la copie si le site n'est pas sécurisé

**Comment by AdelineCelier** [comment]
@claire2212 
- ah oui pardon j'avais oublié ce point, bien noté. 
- comme discuté ensemble, le mieux serait de trouver une solution qui conserve le choix de l'utilisateur, mais qui masque quand même les éléments quand on est en édition d'une zone ou d'un point. A voir s'il y a une solution efficace à mettre en place, si complexe et chronophage, on peut garder cette amélioration pour plus tard.
