### ISSUE TITLE
Signalements - Création d'un signalement

### ISSUE THREAD

**Issue by claire2212** [MTES-MCT/monitorenv#467]
1. Ajout d'un bouton "Créer un signalement" sur la pop-up de sémaphore
2. Au clic sur le bouton "Créer un signalement" : Ouverture du formulaire de signalement
3. Formulaire : 
         - Quand le formulaire est ouvert, la barre de recherche est décalée à gauche du formulaire
         - La source (Sémaphore) et le nom du sémaphore est pré-remplie
4. Ajouter un bouton sur la carte pour créer un signalement
5. Créer tableau de signalement

**Comment by AdelineCelier** [comment]
## Revue UX

### Formulaire de signalement

- [ ] Il n'y a pas besoin de mettre d'indication "en cours" dans le bandeau du formulaire (je ne crois pas que c'était dans les maquettes ?)
- [ ] En revanche, on peut mettre un tag "archivé" dans le bandeau, tel qu'il est dans les maquettes (écran xx par ex.)
- [ ] Je mettrais les items des menus déroulants par ordre d'importance (en tous cas par ordre de fréquence) : 
  - menu "type de cible" : 1 véhicule / 2 société / 3 personne physique
  - menu "type de véhicule" : 1 navire / 2 autre véhicule marin / 3 véhicule terrestre / 4 véhicule arien (d'ailleurs ce serait pas mal de vérifier que c'est cet ordre-là aussi dans le formulaire des missions)
- [ ] une fois tracés (et avant d'enregistrer le signalement), la zone ou le point n'apparaissent plus sur la carte. 
- [ ] Question que je me pose : est-ce qu'il ne faudrait pas mettre les heures de signalement en UTC, vu que tout est en UTC dans l'app ?
- [ ] Archivage du signalement : la phrase en rouge me semble apparaître trop tôt (cf capture d'écran : cela fait moins de 24h que le signalement a été ouvert).
![image](https://github.com/MTES-MCT/monitorenv/assets/71878648/ac3d8d47-a059-4cef-a78e-5e4087e93e6f)


 
### Affichage sur la carte

- [ ] Quand on ouvre le formulaire d'un signalement, je pense qu'on pourrait automatiquement fermer sa pop-up. 
- [ ] Quand la description du signalement est longue, elle est tronquée au bout de 2 lignes (comportement normal). Possibe d'afficher la suite du texte au survol, ou bien cela rentre en conflit avec la fonctionnalité de déplacement de la pop-up ?
- [ ] Couleur du drapeau : il faudrait la changer à partir du moment où le type de signalement est coché par l'utilisateur : rouge pour infraction, bleu pour observation. 
- [ ] Le bouton dans la pop-up du sémaphore "créer un signalement" masque le sémaphore : on ne peut plus cliquer sur l'icône, donc on ne peut plus figer la pop-up, donc on ne peut plus récupérer les contacts du sémaphore. 


## Revue UI

### Formulaire de signalement

- [ ] Il manque un + dans le bouton "ajouter une cible"
- [ ] Les boutons "ajouter un point" et ajouter une zone" me semblent plus hauts que les autres boutons. J'ai aussi rectifié les maquettes pour qu'ils prennent toute la largeur, c'est plus élégant comme ça au final je trouve. 
- [ ] Il y a toujours un problème avec les coordonnées qui ne rentrent pas en largeur (cf. capture). Dans la maquette cela rentre...voir quelles dimensions peuvent être reprises pour coller au mieux à la maquette ? Ou alors est-ce que c'est un pb autre ?
![image](https://github.com/MTES-MCT/monitorenv/assets/71878648/cf0191d4-0956-455f-af93-729eb934e75e)

- [ ] Petit espace en trop après la parenthèse de la phrase à côté de la validité du signalement ;)
![image](https://github.com/MTES-MCT/monitorenv/assets/71878648/2de1f198-2a70-420f-8cb6-a344669d7ef7)


### Affichage sur la carte

- [ ] La croix qui s'affiche pour le point de signalement semble avoir un liséré rouge-orangé et être noire : possible de la mettre de la même couleur que le drapeau ?

**Comment by thoomasbro** [comment]
> Je trouve l'affichage du "fin dans..." à côté de la croix un peu serré...est-ce qu'on pourrait envisager de retirer la croix, et que la pop-up de signalement se ferme au clic ailleurs sur la carto ? Je ne sais plus pourquoi au final on avait opté pour une croix dans les autres pop-ups plutôt que ce comportement-là.

Cela permet de se déplacer dans la carte et éventuellement d'avoir d'autres interactions (couches, etc.) tout en gardant certains éléments ouverts.

**Comment by thoomasbro** [comment]
> Le nom du sémaphore (et plus globalement de la source) est à mettre en minuscules dans la pop-up du signalement

Les noms des sémaphores sont rentrés en capitales dans la base de données. Si on veut passer en minuscules, on va avoir des problèmes d'accents (semaphore au lieu de sémaphore). Si on est tout en minuscule, cela sera étrange pour les noms propres des sémaphores. En titleCase, on va avoir aussi des comportements étranges ("Semaphore Du Bec De L'aigle" au lieu de "Sémaphore du bec de l'aigle").

Je pense que le plus adapté serait de mettre à jour correctement la base des sémaphores dans qgis.

**Comment by AdelineCelier** [comment]
@thoomasbro 

- pour la croix dans la pop-up : ah oui en effet ça permet de se déplacer sur la carte...pour les interactions avec le reste, au final je ne sais pas si c'est hyper utile, je trouve que souvent une pop-up reste intempestivement ouverte quand on aurait aimé qu'elle se ferme toute seule. Mais il y a en effet la question de se déplacer sur la carte. Bon laissons comme ça pour l'instant, je vais réfléchir à un dessin plus adéquat.
- Ah ok en fait j'ai noté le point des majuscules parce que dans la recherche des sémaphores, ceux-ci apparaissent bien en minuscule, avec les accents et les majuscules au bon endroit...tu sais comment ça se fait ?

**Comment by thoomasbro** [comment]
> Ah ok en fait j'ai noté le point des majuscules parce que dans la recherche des sémaphores, ceux-ci apparaissent bien en minuscule, avec les accents et les majuscules au bon endroit...tu sais comment ça se fait ?

Oui, je viens de regarder et en fait dans la table des sémaphores il y a deux colonnes: nom et unité. Le nom est en majuscule et toujours saisi, l'unité est saisie avec les minuscules, mais parfois n'est pas saisie du tout. On affiche donc l'unité si elle est saisie, et sinon le nom. C'est ce qui est fait dans la liste déroulante. Pour la carte, l'information vient du backend où cette logique de substitution n'était pas implémentée. Je corrige.

**Comment by AdelineCelier** [comment]
## 2è revue (28/07/2023) EN COURS

### Formulaire de signalement

- [ ] Retirer complètement le tag "en cours" dans le bandeau du formulaire
- [ ] Il faudrait masquer les pop-ups ouvertes des sémaphores quand on passe en mode édition d'une zone ou d'un point.
- [ ] Retirer la pastille du tag "archivé" (cf. maquettes)
- [ ] Espacement entre encart des cibles et bouton "ajouter une cible" : il est de 8 px
- [ ] Validité du signalement : "fin dans x minutes" quand la validité est de moins d'une heure
