### ISSUE TITLE
Plusieurs fenêtres de Monitor Env

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#477]
Pouvez-vous faire mettre la possibilité d'ouvrir plusieurs fenêtres de Monitor Env ?
Parfois je suis en train de chercher de la réglementation, je sélectionne une zone pour faire veux faire une orientation, etc... et hop en un instant je dois tout quitter car je dois enregistrer une mission.

J'ai essayé en ouvrant 2 fenêtres de Monitor Env mais la zone de mission est tout de même à tracer sur la première fenêtre.

**Comment by AdelineCelier** [comment]
Je crois qu'on en avait parlé à l'oral de cette question, est-ce qu'elle vous semble toujours d'actualité avec les onglets de mission ?
A noter qu'il est possible d'ouvrir plusieurs onglets de MonitorEnv en même temps, mais il faut faire attention à ne pas se mélanger les pinceaux dans les "side window" (la 2è fenêtre avec les vues détaillées. En effet, l'app fonctionne en couple "onglet/side window" : par ex si l'on ouvre une mission à partir d'un onglet, on ne pourra la remplir que dans la side window qui lui est attachée, pas les autres potentiellement ouvertes à partir d'autres onglets.

**Comment by AdelineCelier** [comment]
Hello, je retrouve ce ticket...ressentez-vous toujours un besoin d'ouvrir plusieurs fenêtres de MonitorEnv simultanément ?

**Comment by manonolivier** [comment]
Salut @AdelineCelier,
En effet, plus besoin. On pense que faire des couleurs différentes serait encore moins lisible

**Comment by AdelineCelier** [comment]
Ok ça marche, je le ferme alors !
