### ISSUE TITLE
Pouvoir renseigner un contrôle sans clôturer la mission

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#478]
Permettre de renseigner un contrôle sans obliger à clôturer la mission

**Comment by AdelineCelier** [comment]
@TEAMCACEM Hello, de mon côté je peux faire "enregistrer et quitter" en ayant saisi les infos d'un contrôle. Cela ne fonctionne pas chez vous ?

**Comment by AdelineCelier** [comment]
Ok, bon n'hésitez pas à nous dire si le problème revient. En attendant je ferme ce ticket.
