### ISSUE TITLE
Couche reg - certaines n'apparaissent pas avec la recherche

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#497]
J'ai voulu chercher les cantonnements en Martinique, j'ai donc tapé dans la barre de recherche couche reg "cantonnement" et rien n'est apparu sur cette zone :
![image](https://github.com/MTES-MCT/monitorenv/assets/122106549/507acd56-11e5-4673-8b0c-3b03215e4cec)

Alors que si je fais un aperçu de toutes les couches, la zone de cantonnement apparaît bien :
![image](https://github.com/MTES-MCT/monitorenv/assets/122106549/50e04f7e-d4ec-40f8-a893-401127a126f4)

Même chose si on recherche "Ramiers" qui est le nom de l'ilôt : la zone de l'Arrêté de protection de biotope apparaît mais pas le cantonnement :
![image](https://github.com/MTES-MCT/monitorenv/assets/122106549/e385daeb-0403-4298-8c54-3b222011620d)

**Comment by AdelineCelier** [comment]
@TEAMCACEM merci pour ce retour, j'avais repéré le problème aussi de mon côté, que j'avais noté dans le ticket #308 . On a du mal à voir d'où vient ce problème...peut-être qu'avec ces nouveaux exemples on aura plus d'indices.

**Comment by claire2212** [comment]
@TEAMCACEM le souci est réglé pour "Cantonnement de pêche - Ile Ramiers Martinique" et ""Extraction granulats - PER Sud Atlantique". 
Il s'agit de la propriété `type` qui n'était pas renseigné, Alexia a résolu le souci.

Si d'autres cas apparaissent pourriez-vous faire un ticket global dans lequel on viendrait ajouter au fur et à mesure les zones qui ne remontent pas dans la recherche? (je peux créer le ticket de base si vous voulez)
