### ISSUE TITLE
Renommer la sous-thématique "Perturbation d'animaux" en "Dérangement d'espèces protégées"

### ISSUE THREAD

**Issue by VincentAntoine** [MTES-MCT/monitorenv#508]
Bien penser à faire les changements partout où c'est nécessaire (dans les `env_actions`, les `control_objectives`...)

**Comment by AdelineCelier** [comment]
@VincentAntoine est-ce que ce ticket est toujours d'actualité ? J'ai l'impression que ça a été renommé dans la mouture des thématiques qui est en prod actuellement.

**Comment by VincentAntoine** [comment]
Il y a deux sous-thèmes qui se ressemblent :

![image](https://github.com/user-attachments/assets/93afafb6-dbbd-4021-b913-fa4485487e50)

Je vais voir avec le CACEM ce qu'il faut faire.

**Comment by VincentAntoine** [comment]
C'est bon comme ça, la sous-thématique "Perturbation d'animaux" était utilisée en 2023 et pour 2024 c'est le bon intitulé. Et ce n'est pas nécessaire de renommer l'historique de 2023, ça n'a d'impact que pour les stats et comme les bilans sont déjà faits ça ne changera rien.
