### ISSUE TITLE
Missions – Empêcher la suppression des missions CNSP ouvertes dans Fish

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorenv#510]
Aujourd'hui, le CACEM peut supprimer toutes les missions qui s'affichent dans Env. Il serait souhaitable de disable la suppression des missions qui ont été ouvertes dans Fish, pour éviter les erreurs fâcheuses. 
On va mettre le même comportement dans Fish pour les missions CACEM.

**Comment by claire2212** [comment]
@AdelineCelier on rend disabled le bouton où on ne l'affiche pas du tout?
Les boutons "Enregistrer et quitter" et "enregistrer et clôturer" restent eux bien actifs/visibles?

**Comment by AdelineCelier** [comment]
All good !
