### ISSUE TITLE
HEURE - pouvoir saisir sans interruption HH:MM

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#511]
- pouvoir saisir sans interruption HH:MM
- ne pas indiquer 23:59 pour une date de fin de mission

**Comment by TEAMCACEM** [comment]
On ne peut toujours pas taper au clavier date jour/mois/année et heure HH:MM sans interruption

**Comment by AdelineCelier** [comment]
En l'état actuel des composants ce n'est pas faisable malheureusement. Il faudrait passer de deux composants de sélection de dates séparés à un seul sélecteur d'une plage de dates, avec lequel il faudrait toujours choisir une date de début et une date de fin en même temps. 
Après tu peux toujours utiliser la touche "tab" pour passer avec le clavier d'un champ à l'autre, je viens de tester de mon côté ça fonctionne bien entre le champ d'horaire de début de mission et celui de date de fin de mission.

**Comment by TEAMCACEM** [comment]
D'accord. En revanche, je ne crois pas que cela fonctionne avec tab sur mon ordinateur.

**Comment by AdelineCelier** [comment]
Comme vu avec toi Roxane, la touche "tab" (tabulation) fonctionne bien pour passer avec le clavier d'un champ à l'autre. 
Pour rappel, la touche tab c'est celle-ci ;)
![image](https://github.com/MTES-MCT/monitorenv/assets/71878648/27cd5dd7-24cc-42f2-b038-974957007202)
