### ISSUE TITLE
Pouvoir copier-coller une position en DMS, dans la barre de recherche de localisation ou dans le point d'intérêt

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorenv#52]
C'est une manip qu'ils font souvent au CACEM : ils vont vérifier la position au mouillage d'un navire dans Anaïs, copient ses coordonnées et les collent dans QGIS – et demain dans Env.

Dans le point d'intérêt, cela ne fonctionne pas de copier-coller, cela rogne une partie des caractères

Dans la barre de recherche de localisation, ce sera possible à terme de rentrer des coordonnées ?

**Comment by louptheron** [comment]
La copier de la position DMS bloquait à cause du format :
- ANAIS affiche : **47° 34′ 34″ N 6° 20′ 35″ W**
- Alors que le champ demande : **47° 34′ 34″ N 006° 20′ 35″ W**
Il manquait deux zéros pour que le copier/coller passe la validation du champ.

ANAIS va modifier l'affichage des coordonnées pour afficher les zéros avant le chiffre si besoin, c'est dans leur backlog.

**Comment by AdelineCelier** [comment]
Normalement Anaïs a fait la modif, mais pas encore en prod. Affaire à suivre, en attendant laissons le ticket ici.
