### ISSUE TITLE
Missions – Adapter les boutons du formulaire en cas de clôture des missions

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorenv#528]
**Vu avec le CACEM : deux cas de figure possible**
- ils ont clôturé la mission par erreur -> bouton "rouvrir la mission"
- ils veulent modifier une mission clôturer sans la rouvrir -> bouton "enregistrer"

**Ce que j'ai dessiné :** 
- Comme tu le suggérais Thomas, j'ai rendu le statut de la mission visible par un tag qui s'ajoute sous le tag "ouvert par..."
- Quand on clôture une mission et qu'on la rouvre, les boutons "quitter" et "enregistrer et quitter" ne bougent pas, et le bouton "enregistrer et clôturer" a été remplacé par un bouton "rouvrir la mission". En cliquant sur ce dernier, un message en vert apparaît disant "la mission a bien été rouverte" + le tag de statut se met à jour + le bouton redevient "enregistrer et clôturer"
- Il n'y a finalement pas de changement d'état du formulaire, on peut toujours continuer à l'éditer. Il faut donc rétablir l'état des boutons tels qu'ils sont dans une mission non clôturée. 

Cf. dans le XD écrans [44](https://xd.adobe.com/view/973ae2b4-ecd1-419f-b092-8545e0d8ce57-c269/screen/25b91fb3-202d-4f17-839a-75a80732fee0/) et [45](https://xd.adobe.com/view/973ae2b4-ecd1-419f-b092-8545e0d8ce57-c269/screen/f456ac47-2b27-47cf-b0a7-3930d53fff8c/)

**Comment by claire2212** [comment]
- Lié à #601

**Comment by AdelineCelier** [comment]
Cela me semble bon, seul point que j'ai remarqué : 
- dans le formulaire d'une mission ouverte, je clique sur "enregistrer et clôturer" et il manque des infos dans mon formulaire 
- les erreurs à corriger s'affichent bien, donc ma mission n'est pas clôturée
- mais le tag de statut change et devient "clôturée"

![image](https://github.com/MTES-MCT/monitorenv/assets/71878648/96f73169-7e51-4bd1-a31f-202eba79ced6)
