### ISSUE TITLE
Missions – Réfléchir à un système pour que l'utilisateur n'oublie pas de valider une zone ou un point qu'il vient de tracer

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorenv#529]
Cf. problèmes générés dans le formulaire par le fait de tracer une zone sans la valider, puis d'ouvrir une nouvelle surveillance et de vouloir tracer une nouvelle zone : la zone non validée apparaît comme déjà tracée dans la nouvelle surveillance, et quand on veut la supprimer cela fait planter le formulaire.

**Comment by claire2212** [comment]
@Adeline, j'ai fait ce ticket sur ce sujet #578 et sur fish: https://github.com/MTES-MCT/monitorfish/issues/2163
