### ISSUE TITLE
Départements - Statistiques par département

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#537]
On a beaucoup de CODOP mi-année au moins de juin. On doit sortir les statistiques par département. Comment je fais dans Metabase car le filtre département n'existe toujours pas ? 

Système D : Je peux filtrer par les unités basés dans ce départements mais si ces unités ont fait des missions/contrôles hors département c'est faux. Idem, si des unités basées hors du département ont fait des missions/contrôles dans le département, c'est faux.

On a aussi besoin du nombre de contrôle et nombre d’infraction par thématique. 

Les ateliers réalisés en 2022 évoquent tous ce besoin de statistiques par département (1 à10 fois par an selon les DML). Qu'est ce qui a poser problème pour ne toujours pas avoir ce filtre ? 

Pour info :
- CODOP 83 du 21 février -> CACEM pas capable de donner les statistiques du 83
- Réseau contrôle NAMO du 6 avril -> CACEM pas capable de sortir les stats 2023 par département NAMO
- CODOP 85 du 5 avril -> CACEM pas capable de donner les stats pour le 85 (on a fait pas unité)
- CODOP 33 du 2 mai -> CACEM pas capable de sortir les stats 33
- CODOP 62-80 le 30 mai -> stats pour le 62-80 à sortir
- DMSOI 12 juin -> stats pour Réunion et TAAF à sortir
- MEMN 14 juin -> stats pour les départements de MEMN à sortir
- CODOP 44 20 juin -> stats pour le 44 à sortir
- CODOP 35 -> stats pour le 35 à sortir
-  COPIL CACEM 22 juin -> stats 2023 à sortir
- NAMO réseau contrôles 5 juillet -> stats par département NAMO à sortir

**Comment by AdelineCelier** [comment]
J'ai l'impression que ce ticket est en doublon avec le #419, je me trompe ?

**Comment by TEAMCACEM** [comment]
Le filtre département avait disparu il me semble mais ça a été réglé depuis
