### ISSUE TITLE
problèmes d'unités correspondantes entre monitor env et metabase

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#538]
BGC Dunkerque absente des unités dans Métabase mais présente dans Monitor Env - pourquoi ?

Idems pour :
PGMAR Cherbourg - Armoise
BSAT Margny les Compiègne
OFB BIM Normandie
Guépard Yankee
33F Cherbourg
33F Lanveoc
PAM Jeanne Barret
Poste à cheval de st-valery
BGMar Boulogne - Aber Ildut

**Comment by AdelineCelier** [comment]
Il me semble que Vincent avait répondu à cette question : si l'unité n'est pas présente dans Metabase, c'est qu'il n'y a pas d'action enregistrée à son nom. 
Qu'est-ce qui a été décidé au final ? Que l'on laissait comme ça, ou bien qu'on rajoutait aussi les unités sans activité dans Metabase ? 
ping @VincentAntoine

**Comment by TEAMCACEM** [comment]
Je ne sais pas ce qui a été dit mais ce n'est pas forcément le cas.
Exemple : BNC La Réunion qui est dans MENV avec 2 missions dont une en inter-administration et elle n'apparait pas dans les dashboard

**Comment by AdelineCelier** [comment]
Ok, côté @TEAMCACEM vous voyez bien ces unités dans Metabase ? 
Si oui, tout le monde est ok pour fermer ce ticket ?

**Comment by TEAMCACEM** [comment]
Oui les deux unités apparaissent bien désormais
