### ISSUE TITLE
Rapportage - Ajustements sur l'ajout d'une infraction

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorenv#54]
- Attention à bien ajuster les champs selon le type de cible choisi : immat. si c’est un véhicule, prénom et nom si personne physique, nom de la société si société…
- Menu “type de véhicule” : en fait c’est “type de navire”, si le véhicule choisi plus haut est bien un navire.
- Lorsqu’on ouvre une 2è infraction, ne pas recopier les champs de la 1ère (aujourd’hui c’est le cas, et c’est déstabilisant)
- Il manque un bouton “annuler” pour sortir d’une infraction sans l’enregistrer
- Attention, l’intitulé de l’infraction apparaît parfois en anglais (“vessel” au lieu de “navire”)

**Comment by AdelineCelier** [comment]
- Il faudrait griser le bouton "Ajouter une nouvelle infraction" tant que les 3 champs "Nb total de contrôles", Type de cible (et "Type de véhicule" si applicable) ne sont pas remplis. 
- Je pense qu'on peut retirer les champs "type de navire" et "taille du navire" dans l'infraction si le véhicule sélectionné n'est pas un navire, ce sera plus lisible. 
- Ok pour remplacer l'intitulé du bouton "annuler" par "supprimer l'infraction", mais l'UI des boutons est à revoir (cf. écrans : valider est un bouton primaire, supprimer doit rester un bouton tertiaire)
- Quand on valide l'infraction, il y a un champ qui apparaît comme "non renseigné". Il devrait reprendre le type de véhicule mentionné au-dessus de l'infraction (cf. écrans)

**Comment by thoomasbro** [comment]
Ok sauf le point " griser le bouton "Ajouter une nouvelle infraction" tant que les 3 champs "Nb total de contrôles", Type de cible (et "Type de véhicule" si applicable) ne sont pas remplis." cf. nouvelle issue #108

**Comment by AdelineCelier** [comment]
Ok pour le ticket 108.
Il y a juste encore un "NR" à la place de la mention "Avec PV" ou "Sans PV", mais j'imagine que tu vas régler ça dans le ticket [#101](https://github.com/MTES-MCT/monitorenv/issues/101) ?
