### ISSUE TITLE
Point d'intérêt - certains ne peuvent pas se supprimer

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#554]
J'avais déjà ouvert un ticket il me semble mais je ne le retrouve pas... Désolée si je fais doublon.
En tous les cas, il y a un problème sur certains postes : des points d'intérêt ne peuvent pas être retirés (aucune réaction quand on clique sur la poubelle et même chose si on remplit tous les champs ou seulement quelques uns). Ca me (Manon) concernait seulement mais Adrien commence aussi à en avoir.

**Comment by claire2212** [comment]
- Duplicate #464

**Comment by AdelineCelier** [comment]
Yes ce ticket est en doublon, je le ferme et on garde le 464 !
