### ISSUE TITLE
Missions (UI) – Les boutons "ajouter un point de contrôle" et "ajouter une zone de surveillance" ont rétréci

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorenv#570]
Je pense que dans l'idéal il faudrait faire la même chose que sur Fish (ce qui n'est pas exactement ce que j'ai fait dans les écrans XD, désolée j'ai pas mis à jour) : les boutons font la même largeur que les champs du formulaire pour un bon alignement vertical. La ligne avec la zone ou le point ajouté + les 2 boutons d'édition et de suppression s'alignent aussi en largeur sur les autres champs. 

Cf. ci-dessous : 
![image](https://github.com/MTES-MCT/monitorenv/assets/71878648/b2ac5bcf-c3eb-4ea8-a7c9-d6d9ab5ba09a)

**Comment by claire2212** [comment]
@AdelineCelier  ok c'est à faire partout j'imagine? par que pour la zone de mission c'est pareil, les boutons sont "en dehors". J'avais modifié ça pour tout aligner mais on m'a dit que ce n'était pas iso maquettes   :-(
