### ISSUE TITLE
[Map] Amélioration de la pop-up d'édition de point de contrôle ou de zone de mission/surveillance

### ISSUE THREAD

**Issue by claire2212** [MTES-MCT/monitorenv#578]
Problème : Quand on ajoute un point de contrôle sur la carte, si on clique sur "quitter" plutôt que "valider le point", ça enregistre quand même le point de contrôle. Donc les deux boutons "quitter" et "valider" ont le même comportement.
Si l'on clique sur "quitter" on ne devrait pas enregistrer le point saisi.

Solution envisagée : Avoir une valeur temporaire , et la valeur dans le formulaire ne se mettrait à jour qu'au click sur le bouton "Valider le point de contrôle" . 
A faire pour point de contrôle et zone de mission surveillance

En attente du retour d' @AdelineCelier qui doit valider le fonctionnement avec le CACEM/ CNSP

/!\ A faire aussi côté fish: https://github.com/MTES-MCT/monitorfish/issues/2163

**Comment by AdelineCelier** [comment]
@claire2212 juste pour être bien sûre, quels seraient les "impacts" exactement de cette valeur temporaire ? Les coordonnées n'apparaîtraient pas dans le formulaire c'est ça ? il y aurait autre chose ? Et est-ce que ça veut dire aussi qu'on renonce à afficher un jour les coordonnées dans le menu sur la carto quand on est en mode édition (je sais que ça ne marche pas pour l'instant mais je n'ai pas perdu espoir 😇 )

**Comment by claire2212** [comment]
@AdelineCelier oui c'est ça les coordonnées n'apparaîtraient pas dans le formulaire tant que l'utilisateur n'as pas cliquer sur "Valider". Je ne vois pas d'autre chose.
Pour ce qui est d'afficher les coordonnées dans le menu, si ce que tu veux dire c'est que quand je clique pour sélectionner un point de contrôle les coordonnées du point s'affiche dans la modal d'édition je pense que c'est tout à fait possible (mais j'ai l'impression que c'est une question piège ;-) )

**Comment by AdelineCelier** [comment]
Ok ça ne me choque pas que les coordonnées n'apparaissent dans le formulaire qu'à la validation dans le menu d'édition sur la carto. 
En ce qui concerne l'affichage des coordonnées dans le menu d'édition après un clic sur la carto, c'est peut-être une question-piège dans le sens où Loup m'avait dit que c'était un peu relou à faire, et on l'avait laissé de côté pour l'instant. Mais peut-être qu'à deux vous trouverez une solution plus rapide ? En tous cas ce n'est pas prioritaire, mais en termes d'usage je trouverais ça plus lisible pour l'utilisateur quand même, surtout si les coordonnées ne s'affichent plus dans le formulaire avant validation.

**Comment by AdelineCelier** [comment]
Après discussion, on se dit qu'il vaut mieux retirer complètement retirer le bouton "quitter" qui n'est pas clair, car au final il devrait avoir le même comportement que réinitialiser puis valider. 
A noter que le bouton "réinitialiser" ne fonctionne pas dans le cas d'une édition de point de contrôle : à régler dans la foulée.

**Comment by AdelineCelier** [comment]
Bouton "quitter" bien retiré et réinitialisation du point de contrôle effective. Mission accomplie.
