### ISSUE TITLE
Dates d'action ne peuvent pas être égales à la date de mission

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#596]
Parfois, MENV nous empêche de clôturer la mission si la date/heure du début de surveillance est la même que celle de la mission :
![image](https://github.com/MTES-MCT/monitorenv/assets/122106549/453af62a-f8dc-4139-ad44-1208f5b8910a)
Pour ce cas, même quand on coche "date et heure de surveillance équivalente, ça met le même message d'erreur

**Comment by claire2212** [comment]
Bonjour @TEAMCACEM, je n'arrive pas à reproduire. Pouvez-vous me dire si cela arrive dans le cadre d'une mission déjà créée ou dans le cas d'une nouvelle mission? Merci

**Comment by TEAMCACEM** [comment]
Salut @claire2212 à chaque fois que ça m'arrive c'est sur une mission déjà ouverte que je souhaite fermer
