### ISSUE TITLE
Fenetre qui ne s'affiche pas entierement

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#628]
![image](https://github.com/MTES-MCT/monitorenv/assets/122106549/851f2b33-03f4-4dd9-8d62-8cb76366a493)
La fenêtre est coupée sur la droite et il n'y a pas de barre pour aller sur la droite. On peut accéder à ce qu'il y a à droite en sortant du "plein écran".
Je sais pas si c'est clair

**Comment by TEAMCACEM** [comment]
Bonjour, 
je viens d'avoir un cas : ma page était en plein écran, j'ai ajouté une action de contrôle, jusqu'ici pas de souci, j'ai ajouté un contrôle avec infraction et rempli les champs et c'est à ce moment là qu'il y a eu le problème d'affichage

**Comment by claire2212** [comment]
@TEAMCACEM merci de votre réponse. J'ai réussi à reproduire, je règle ça.
