### ISSUE TITLE
Carto - Au clic sur la carte sur une zone AMP, afficher la couche dans l'arbre des couches.

### ISSUE THREAD

**Issue by thoomasbro** [MTES-MCT/monitorenv#643]
Au clic sur une zone sur la carte, il faudrait que les résultats de recherche scrollent automatiquement jusqu'à la zone et que son nom apparaisse en surbrillance.

cf. https://github.com/MTES-MCT/monitorenv/issues/162

**Comment by AdelineCelier** [comment]
ça fonctionne bien de mon côté.
