### ISSUE TITLE
Carto - Le dernier caractère n'est pas toujours pris en compte dans la recherche des couches

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorenv#647]
Quand on tape rapidement dans la barre de recherche carto, le dernier caractère n'est pas pris en compte. Il peut donc y avoir une certaine inconsistance dans les résultats de recherche, en fonction de comment l'utilisateur a tapé son mot-clé.

**Comment by claire2212** [comment]
Hello @AdelineCelier j'ai l'impression que le souci est réglé. Tu confirmes?

**Comment by claire2212** [comment]
Problème résolu
