### ISSUE TITLE
Pouvoir ne pas enregistrer de natinf

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#655]
Dans l'ajout des natinfs, ajouter une case "pas de natinf" ou "N/A" parce qu'il arrive d'avoir des infractions qui n'en ont pas (CGV ou autres) et pour l'instant, pour pouvoir clôturer la mission, on entre un NATINF qui se rapproche le plus de l'infraction mais ce n'est pas correct

**Comment by TEAMCACEM** [comment]
Pour info : on avait un équivalent natinf pour les contraventions de grande voirie mais ça a disparu depuis plusieurs mois cf ticket #718

**Comment by AdelineCelier** [comment]
Est-ce que maintenant que les CGV sont revenus, ce ticket a toujours du sens ?

**Comment by TEAMCACEM** [comment]
Oui CGV est revenu mais permettre la possibilité de renseigner "Autre natinf" pour pas perdre l'info au moment venu avec un nouveau natinf

**Comment by AdelineCelier** [comment]
Ok, je viens de rajouter dans Poséidon un "Autre NATINF" avec le code 0, et j'ai mis le code 1 à CGV au final (ça me semblait plus logique d'attribuer le 0 à "autre" ;).
