### ISSUE TITLE
Recherche reg – Problèmes avec recherche par mots-clés et avec filtres "thématique" et "type d'AMP"

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#658]
(Manon)En lien avec le #497 mais qui est clôturé.

On voit qu'il y a bien une reg qui concerne les balbuzards :
![image](https://github.com/MTES-MCT/monitorenv/assets/122106549/e5995828-4271-4bac-8b4b-bb7e3cd16a7c)

Mais en tapant le mot "balbuzard" dans la barre de recherche, je ne le trouve pas :
![image](https://github.com/MTES-MCT/monitorenv/assets/122106549/05e144a0-55a6-41e9-acf1-cd7344ff8527)

Si je tape "quietude", je trouve la couche par contre.

**Comment by AdelineCelier** [comment]
Ok en effet ça ressemble au ticket 497, est-ce que vous pouvez voir avec Alexia (si ce n'est pas elle qui a rédigé le ticket ;)) si la propriété "type" est bien renseignée dans la table QGIS pour cette zone ?
...mais vu qu'en tapant "quiétude" ça remonte bien, j'ai peur que ce ne soit pas ça. @claire2212 ou @thoomasbro vous auriez une idée de ce que ça pourrait être ?

Je bascule le ticket dans notre kanban.

**Comment by TEAMCACEM** [comment]
@AdelineCelier Alexia est partie en congés pour 10 jours, je vois ça demain avec les autres si quelqu'un sait se servir des tables QGIS

**Comment by TEAMCACEM** [comment]
Roxane : je peux regarder mais je n'ai pas accès au projet QGIS

**Comment by TEAMCACEM** [comment]
Roxane : La propriété "type" est bien renseignée pour cette couche dans QGIS (id 4522). Autre remarque, le layer name est "Zone de quiètude nids de Balbuzard - Façade occidentale Corse", la recherche reg Monitor Env fonctionne pour "quiètude", "nids" et "zone" mais pas pour "Balbuzard", "Corse", "occidentale"...

**Comment by AdelineCelier** [comment]
De nouveaux cas sont remontés par le CACEM (cf. ticket #665 que j'ai fermé pour le reporter ici) : 
AP 206-2020 (Mouillage - RN Bouches de Bonifacio) n'apparait pas dans la thématique mouillage ni avec la recherche de mot Bonifacio

D'autre part, je suis aussi passée en salle et on a testé plusieurs filtres avec Manon (dans les filtres "thématiques reg." et "types d'AMP"), et les filtres ne s'appliquaient pas sur la carte : ex. filtre "APB" appliqué, et aucune zone n'apparaît alors qu'il y a des zones avec ce filtre renseigné dans leurs métadonnées.

**Comment by AdelineCelier** [comment]
Le problème me semble réglé ! 

@TEAMCACEM à la prochaine mise en production (qui sera probablement faite par Claire début aout), vous pourrez à nouveau utiliser la recherche et les filtres correctement normalement. Il ne faudra pas hésiter à utiliser le filtre "AMP" dans "thématiques réglementaires" afin de filtrer les zones reg d'un secteur appartenant à une AMP. Cela devrait vous aider à y voir plus clair dans les zones très denses.

**Comment by claire2212** [comment]
@TEAMCACEM pouvez-vous me confirmer que le problème est bien réglé s'il vous plaît?

**Comment by TEAMCACEM** [comment]
Roxane : je n'ai pas l'impression désolée... 

- le mot clé "Balbuzard" ne donne rien et devrait rechercher "Zones de quiétude des nids de Balbuzard" alors que les mots-clé "nids" et "occidentale" fonctionnent
- la recherche thématique "PN" ne donne aucun parcs nationaux
- la recherche de mot-clé "Guadeloupe" donne 380 résultats dont certains sont complètement hors-sujet (ex : Immersion Guidel) pourquoi ?
- la recherche par thématique "APB" donne 68 résultats dont certains ne sont pas des APB (ex : RN Arguin qui est une réserve)
- la recherche thématique "Bruit" donne 20 résultats mais il y a que 8 affichés
- la recherche thématique "Cultures marines" donne 34 résultats mais seuls 4 sont affichés
- la recherche thématique "Pollution et rejets" donne 26 résultats mais seuls 7 sont affichés
- supprimer les catégories RNN et RNR pour juste garder RN
- la recherche thématique "Rechargement" donne 5 résultats mais seuls 73sont affichés
- la recherche thématique "Récolte de végétaux marins" donne 29 résultats mais seuls 8 sont affichés
- la recherche thématique "SAGE" donne 2626 résultats et à vue d’œil il y a environ 50 SAGE
- la recherche thématique "Stationnement" donne 15 résultats mais seuls 6 sont affichés

- la recherche de Type d'AMP "Parc national" fait ressortir d'autres parcs (naturels marins par exemple)

Je n'identifie pas d'où vient les problèmes j'espère que ces exemples suffisent à les déceler

**Comment by TEAMCACEM** [comment]
(Roxane)
Il reste donc comme problèmes :

-  la recherche thématique "PN" ne donne aucun parcs nationaux. Selon Alexia à première vue pas de différence dans la table attributaire de la couche REG sur le mot-clé 'PN' par rapport aux autres mots-clés
- la recherche de mot-clé "Guadeloupe" donne 380 résultats dont certains sont complètement hors-sujet (ex : Immersion Guidel) pourquoi ?
- la recherche thématique "SAGE" donne 2626 résultats et à vue d’œil il y a environ 50 SAGE.
- la recherche de Type d'AMP "Parc national" fait ressortir d'autres parcs (naturels marins par exemple)

C'est difficile d'être exhaustif il y a peut-être d'autres problèmes

**Comment by claire2212** [comment]
@TEAMCACEM merci de vos retours, je regarde ça aujourd'hui et vous tiens informés

**Comment by claire2212** [comment]
@TEAMCACEM j'ai trouvé le souci pour la recherche sur la thématique 'PN' , pour ce qui est du nombre de résultats pour les autres recherches (Guadeloupe, Glénan, Parc national) cela vient de la finesse de la recherche qui devrait peut-être être un peu plus restrictive. Je fais des tests en début de semaine prochaine

**Comment by claire2212** [comment]
Bonjour @TEAMCACEM , Alexia aurais-tu la possibilité de me sortir la liste des zones règlementaires dont la thématique est `SAGE` s'il te plaît (si ce n'est pas trop compliqué / long à faire)? 
J'ai l'impression qu'on a 4 groupes actuellement (pour un total de 6 zones) qui ont la thématique SAGE : SAGE Littoral - Manche, SAGE Littoral - Nord, SAGE Seine Maritime et Eure, et SAGE - Scorff 

Il y a d'autres résultats nommés `SAGE -xxxxxxx` mais ils n'ont pas la thématique SAGE renseignée (ex : SAGE - La vilaine, SAGE - Golfe du Morbihan et ria d'Etel, SAGE - Le Blavet)

Merci d'avance et bonne journée

**Comment by TEAMCACEM** [comment]
Bonjour Claire, 
je t'envoie les listes par mail
Bonne journée

**Comment by AdelineCelier** [comment]
J'ai l'impression qu'on arrive à un bon équilibre là. 
@TEAMCACEM on passe le ticket en prod et on vous laissera vérifier mais ça me semble pas mal !

**Comment by TEAMCACEM** [comment]
(Roxane) on testera au fur à mesure car c'est impossible d'être exhaustif sur ce ticket
