### ISSUE TITLE
Supprimer la thématique AMP sans réglementation particulière

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#661]
Supprimer la thématique AMP sans réglementation particulière

**Comment by AdelineCelier** [comment]
@TEAMCACEM Comme discuté avec Manon : 
- pour les surveillances, il est possible de remplacer automatiquement la thématique "AMP sans reg. particulière" par "Divers" dans les missions passées.
- pour les contrôles, si vous souhaitez indiquer des thématiques plus précises, cela doit se faire au cas par cas, donc à la main malheureusement. 

Je pense qu'il est du coup nécessaire de régler le cas des contrôles avant de supprimer complètement la thématique, parce que je ne pense pas qu'on puisse virer la thématique d'un contrôle si on ne la remplace pas. 
Tenez-nous au courant de votre avancée sur le sujet !

**Comment by TEAMCACEM** [comment]
Ok et bien pouvez-vous nous indiquer les missions à modifier svp ?

**Comment by TEAMCACEM** [comment]
(Manon) A voir avec metabase (possible de faire une recherche des contrôles avec cette thématique)

**Comment by AdelineCelier** [comment]
Hello le CACEM, on est d'accord qu'avec le passage à la nouvelle typologie en 2024, ce ticket n'est plus d'actualité ?

**Comment by AdelineCelier** [comment]
Je me permets de fermer ce ticket qui me semble avoir été réglé avec le passage à la nouvelle typologie.
