### ISSUE TITLE
AP 206-2020 mouillage

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#665]
AP 206-2020 (Mouillage - RN Bouches de Bonifacio) n'apparait pas dans la thématique mouillage ni avec la recherche de mot Bonifacio

**Comment by AdelineCelier** [comment]
Ca m'a l'air d'être le même problème (ou en tous cas très proche) que remonté dans le ticket #658. 
Ok pour vous si je note le problème avec cette zone dans le ticket 658 et que je ferme celui-ci ?
