### ISSUE TITLE
Impossibilité de cloturer la mission une fois la mission réouverte

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#676]
Impossible de cloturer la mission une fois la mission réouverte. il faut quitter puis reveneir dessus pour la cloturer. débloquer ce problème pour pouvoir cloturer directement après avoir reouvert et modifier la mission.

**Comment by claire2212** [comment]
@AdelineCelier non je n'avais pas créé de ticket pour ce sujet. Il me semble qu'on s'était dit qu'on mettrait en place les bandeau d'alerte pour régler ce souci

**Comment by AdelineCelier** [comment]
Ok en effet, dans ce cas on garde lce ticket, et j'en ai créé un sur la création des bandeaux, le #769.

**Comment by claire2212** [comment]
@AdelineCelier je ferme ce ticket comme on a plus la notion de clôture, et que le ticket sur le remplacement des bandeaux est créé

**Comment by AdelineCelier** [comment]
Yes top !
