### ISSUE TITLE
Unités – Affichage des bases sur la carte

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorenv#698]
**Ticket faisant partie de la V1 pour la brique "unités"**

- [x] Afficher les bases des unités sur la carte : géoréférencement sur la ville donnée comme base (à faire par le CACEM : cleaner la liste des bases pour éviter les doublons et les termes autres que des noms de villes)
- [x] Au clic sur l'icône d'une base, afficher la liste des unités qui y ont un ou plusieurs moyens.

Note concernant les bases : 
La notion de base est rattachée aux moyens. Si une unité a plusieurs moyens dans différentes bases, son nom apparaîtra dans chacune de ces bases. Les moyens quant à eux n'apparaîtront que dans leurs bases respectives.

**Comment by AdelineCelier** [comment]
**Choix faits après discussion entre Ivan, Vincent et Adeline**

- définition des bases (Vincent s'en occupe) : 
  - récupération du nom des villes dans le fichier de Roxane et géocodage
  - pour les bases des CDL, récupérer le centre des zones
- administration via le backoffice en rentrant les coordonnées des bases => à voir à l'usage si c'est suffisant, ou s'il faudra une administration plus souple via QGIS

**Comment by ivangabriele** [comment]
@AdelineCelier J'ai déplacé la question de la taille et du positionnement dynamiques des pop-ups dans le nouveau ticket #989.

**Comment by AdelineCelier** [comment]
- [ ] Sur l'affichage des bases au-dessus des sémaphores : l'icône des sémaphores est bien en-dessous de celle des bases maintenant, en revanche la pop-up des sémaphores reste au-dessus de celle des bases. Je le note ici, mais à voir ce qu'on décidera concernant le comportement des pop-ups. Peut-être qu'il ne faudrait qu'une pop-up ouverte à la fois, tous types de pop-ups confondus
![image](https://github.com/MTES-MCT/monitorenv/assets/71878648/206f13e3-ed27-4097-8330-28b4c9df1538)

- [ ] Sur le fait de donner plus de marge aux numéros dans les pastilles, je ne vois pas la différence...est-ce que parce que c'est trop léger ou bien est-ce que tes changements ne s'affichent pas chez moi ?
![image](https://github.com/MTES-MCT/monitorenv/assets/71878648/4461dcfc-5724-4d34-b2f2-c0b13bb37532)

- [ ] Je n'avais pas repéré avant, mais le titre dans la fiche d'une unité n'est pas tronqué non plus, il faut faire comme pour le titre des bases
![image](https://github.com/MTES-MCT/monitorenv/assets/71878648/cf739a78-e653-46b9-a9da-e7113f9e9f7d)

- [ ] Autre truc que je n'avais pas repéré : quand je filtre la liste des unités avec le moyen "drône", il y en a 3 qui remontent, mais seul 1 unité sur les 3 a effectivement un drône dans sa liste des moyens. 
![image](https://github.com/MTES-MCT/monitorenv/assets/71878648/d1c091a6-291f-485a-ab9c-a83d31eabe15)

**Comment by ivangabriele** [comment]
@AdelineCelier J'ai transformé le commentaire restant en #2793 pour pouvoir bouger cette carte dans Done.

**Comment by AdelineCelier** [comment]
Yes bien vu merci, le ticket commençait à être un peu trop long !
