### ISSUE TITLE
Unités – Affichage et édition de la fiche unité

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorenv#699]
**Ticket faisant partie de la V1 pour la brique "unités"**

- [x] Au clic sur le nom de l'unité dans la pop-up d'une base, affichage de la fiche de l'unité
- [x] Affichage et édition des contacts de l'unité
- [x] Affichage et édition des moyens de l'unité, excepté leur photo. A la place, on met le placeholder avec l'icône reprenant la nature de moyen (nautique, aérien, terrestre).

**Comment by AdelineCelier** [comment]
**Ce qui a été décidé après discussion entre Ivan, Loup, Thomas et Adeline**

- On conserve finalement le nom du moyen, le CACEM a l'air de l'utiliser dans certains cas (pour différencier par exemple 2 missions simultanées d'une même unité).
  - cela veut dire qu'il faut faire le matching entre moyens en base et moyens dans le doc de Roxane, comme pour les unités
- Dans la fiche unité 
  - on renseigne le type de moyen
  - on renseigne le nom du moyen 
  - si l'on ne veut pas mettre de nom au moyen, on peut enregistrer le moyen sans nom, et l'app duplique automatiquement le type de moyen dans le nom
- Sur les champs "type" et "nom", 
  - à partir du moment où le moyen est relié à une mission, on ajoute une pop-up de warning disant : "êtes-vous sûr de vouloir modifier le nom / le type du moyen ? Cela aura un impact sur les x missions dans lesquelles ce moyen est mentionné."
  - quand l'utilisateur fait une modif malgré le warning, on pousse un message sur Sentry pour avoir une trace des modifications.

**Comment by AdelineCelier** [comment]
## Ce qui a été décidé après discussion avec Ivan, Vincent et Adeline

**Sur les unités**
- On essaye de récupérer le maximum d'infos du tableau de Roxane pour éviter au CACEM des saisies manuelles fastidieuses.
- Pour cela, il faut refaire un match entre les unités en base et les unités dans le tableau 
  - 1 tableau avec les unités qui sont dans le tableau mais pas en base, afin de permettre de retrouver les paires, ou bien d'identifier les possibles unités manquantes en base
  - 1 tableau avec les unités qui sont en base mais pas dans le tableau, afin de donner au CACEM la liste des unités pour lesquelles il faudra rentrer les infos de contact, bases et moyens direct dans l'app.
- RAPPEL : une fois que le CACEM utilisera la fonctionnalité signalements, il faudra penser à retirer les sémaphores des unités.

**Sur les contacts**
- Certains mails et tels vont ensemble 
  - pour les CO, on associe par défaut le 1er contact tel avec le mail renseigné
  - pour les autres contacts, on demande au CACEM s'ils veulent faire les paires tels/mail dans un tableau Excel ou bien direct dans l'app quand elle sera en prod. 

**Sur les commentaires**
- On demande au CACEM si c'est ok de noter par défaut tous les commentaires dans le champ "commentaires" du moyen, avec le texte sur la zone d'intervention du moyen

**Comment by AdelineCelier** [comment]
## Revue de la fiche unité et moyens

**Revue UX**
- [ ] Il faudrait que la fiche ne masque pas les icônes du menu de droite. Quand une fiche est ouverte, elles se masquent partiellement à droite, et réapparaissent au survol. Cf. comportement que pour la fiche signalements dans Env ou la fiche navire dans Fish.
- [ ] Récupérer dans le tableau de Roxane les infos des colonnes "modalités de contact" et "secteur d'intervention de l'unité" pour remplir les champs correspondants dans la fiche
- [ ] Je pense qu'il y a eu des couacs d'assignation pour certains contacts. Cf. contact de CO de Gendarmerie pour les Cultures Marines du 50. @VincentAntoine est-ce qu'il est possible de faire quelque chose ? 

**Revue UI**
- [ ] Il manque les icônes placeholders à la place de la photo des moyens 
- [ ] Petit décalage de la fiche unité, qui pour moi doit venir vraiment à ras du haut de la barre de recherche qu'il y a derrière

![Image](https://github.com/MTES-MCT/monitorenv/assets/71878648/f3ca09dd-e750-48aa-8761-8781de41ffee)

**Comment by AdelineCelier** [comment]
@ivangabriele comme discuté, il reste le placement de la fiche et le comportement des icônes du menu. 

@VincentAntoine concernant les infos encore à récupérer :
- [ ] on peut normalement récupérer les secteurs d'intervention dès maintenant, ils n'ont pas été impactés par les décalages dans le tableau
- [ ] pour les CO et les modalités de contact, comme convenu, on met d'abord en prod puis on extrait une liste des unités/moyens avec des ID qu'on donne au CACEM pour qu'ils renotent les infos au propre.

**Comment by AdelineCelier** [comment]
Ok tout est bon pour moi au niveau de la fiche, il reste juste le point du menu rétractable, mais je crée un nouveau ticket sur le sujet puisqu'on a dit qu'on verrait ça plus tard, après le ticket sur les bases.

**Comment by ivangabriele** [comment]
Je clos ce ticket @AdelineCelier ^^.
