### ISSUE TITLE
Unités – Liste des unités sur la carte avec filtres

### ISSUE THREAD

**Issue by ivangabriele** [MTES-MCT/monitorenv#707]
**Ticket faisant partie de la V1 pour la brique "unités"**

- [x] Afficher un nouveau menu "unités" sur la cartographie, avec un bouton pour afficher/masquer les bases des unités sur la carte
- [x] Lister les unités dans le menu
- [x] Filtrer les unités dans le menu

**Comment by AdelineCelier** [comment]
## Revue 2è version

(En plus des points de la première revue qui n'ont pas été traités)

- [ ] Les types de moyens apparaissent en majuscules et en anglais, les passer en français, avec une majuscule juste à la première lettre
- [ ] Pour la mise en prod, retirer le bouton "Voir la vue détaillée des missions", vu que pour l'instant il ne renvoie à rien

**Comment by AdelineCelier** [comment]
@ivangabriele, tout est bon sauf les unités historiques qui apparaissent toujours dans la liste. 

Et je vais faire la maxi reloue (pardon pardon) mais au final tu peux virer la majuscule au type de moyen dans la liste ? 😇 je sais pas pourquoi je t'ai demandé de la garder, ce sont des noms communs, il n'y a pas de raison de leur mettre une majuscule.

**Comment by AdelineCelier** [comment]
C'est bon, les unités historiques n'apparaissent plus dans la liste !
