### ISSUE TITLE
Rapportage - Le "dates et heures de surveillance équivalentes à celles de la mission" se décoche

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#708]
Quand on ouvre une mission, on met une date de débute t une date de fin prévue par l'unité. Le "date et heure de surveillance équivalentes...." se coche bien automatiquement et rempli la date de début et de fin de la surveillance de la mission.

Mais quand on veut clôturer la mission. On revient dessus et à ce moment la case est décochée sans qu'on ne fasse quoi que ce soit et si on modifie l'heure de fin de la mission, ça ne modifie pas l'heure de fin de la surveillance.

**Comment by claire2212** [comment]
@TEAMCACEM livré lors de la précédente mise en prod. C'est ok pour vous?

**Comment by TEAMCACEM** [comment]
ok
