### ISSUE TITLE
Rapportage - Contravention de grande voirie qui a disparu des NATINF

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#718]
Ce n'est pas un NATINF à proprement parlé mais c'est important de l'avoir parce que certaines procédures sont purement administrative. Il y était au début de MENV mais on ne le retrouve plus.

**Comment by AdelineCelier** [comment]
Hello @TEAMCACEM 
On vient de régler le problème avec Vincent. En fait on ne prenait dans Poséidon que les NATINF qui ont un n°. 
Donc on a modifié le CGV dans Poséidon pour lui donner le n°0, et l'appeler "CGV - Contravention de grande voirie". 
Ok pour vous ?

**Comment by TEAMCACEM** [comment]
Oui parfait
