### ISSUE TITLE
Nouvelle mission - indiquer le nom de l’unité  dans le chapeau en haut quand plusieurs fenêtres ouvertes pour s'y retrouver plus facilement

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#721]
Nouvelle mission - indiquer le nom de l’unité dans le chapeau en haut quand plusieurs fenêtres ouvertes pour s'y retrouver plus facilement

**Comment by claire2212** [comment]
@TEAMCACEM livré lors de la mise en prod du jour. C'est ok pour vous?

**Comment by TEAMCACEM** [comment]
Oui c'est bien
