### ISSUE TITLE
Signalements - Mise à jour du tableau pour sélection multiple

### ISSUE THREAD

**Issue by claire2212** [MTES-MCT/monitorenv#728]
Mise à jour du tableau des signalements pour correspondre au maquettes et permettre la sélection multiple et différentes actions depuis le tableau directement (archivage, suprression, etc)

Maquette : 

https://xd.adobe.com/view/69dcd22c-eb8b-4ede-bd7c-473483429986-3c8f/screen/ad07877b-406a-4f35-86f3-dfa5f1eabbd5/specs/

**Comment by AdelineCelier** [comment]
ça me semble tout ok !
