### ISSUE TITLE
Signalement - ajouter une thématique "autre" dans type de cible

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#731]
Quand on rentre une observation ça peut concerner un mammifère échoué par exemple.

J'ai vu qu'on pouvait valider un signalement sans mettre de cible. On peut également faire ça au lieu d'ajouter une case "autre".
(Manon)

**Comment by AdelineCelier** [comment]
ça marche, on va rajouter un "autre" dans la liste des types de cible. Le détail pourra être renseigné dans le champ libre "description du signalement".

**Comment by AdelineCelier** [comment]
Good pour moi :)
