### ISSUE TITLE
Signalement - Ajouter trigramme

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#732]
Ca nous permet de savoir vers qui se tourner si on a une question sur un signalement que nous n'avons pas suivi de base (Manon)

**Comment by AdelineCelier** [comment]
Ok en effet cela peut être utile. Je le bascule dans notre kanban. 
Il faudrait rendre le champ obligatoire ?

**Comment by TEAMCACEM** [comment]
Oui ce serait mieux

**Comment by AdelineCelier** [comment]
Ok, vous êtes tous d'accord avec ça ? ;)

**Comment by TEAMCACEM** [comment]
yes

**Comment by AdelineCelier** [comment]
On peut le rajouter comme ça, en fin de formulaire : 
![image](https://github.com/MTES-MCT/monitorenv/assets/71878648/bdcb0338-5cd4-4cd9-9f24-5f6e8db2e063)

**Comment by TEAMCACEM** [comment]
Oui en fin de formulaire.
Pas "Suivi par" mais juste "Trigramme" ou "Enregistré par".

**Comment by AdelineCelier** [comment]
C'est "saisi par" ;)

**Comment by TEAMCACEM** [comment]
Ah désolé j'ai mal lu

**Comment by AdelineCelier** [comment]
C'est bon pour moi.
