### ISSUE TITLE
Fenêtre "Vue détaillée des signalements" indépendante de la fenêtre "Vue détaillée des missions" et possibilité d'avoir plusieurs signalements en même temps

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#733]
La Fenêtre signalement doit être indépendante ouverte de la fenêtre mission
On doit pouvoir créer et ouvrir plusieurs signalements en même temps comme pour les missions

**Comment by AdelineCelier** [comment]
Yes c'est bien prévu, ça n'a pas encore été développé.

**Comment by AdelineCelier** [comment]
Juste on avait discuté du fait de rendre indépendante ou non la fenêtre de signalement par rapport à celle des missions, et il me semble qu'on était arrivé à la conclusion que ce n'était pas nécessaire. 
Dans quel cas est-ce que cela vous serait utile ?

**Comment by TEAMCACEM** [comment]
(Roxane) je parle de la fenêtre "vue détaillée des signalements" que l'on doit pouvoir voir en même temps que "vue détaillée des missions". Hésiter pas à mettre des couleur pour une rendu plus instinctif. Style vue détaillée des signalements en une couleur et vue détaillée des missions en une autre couleur

**Comment by TEAMCACEM** [comment]
@AdelineCelier  (Manon) En effet, on en a discuté et ça n'apparait pas forcément utile (on s'est dit qu'on verrait à l'usage si c'est nécessaire). Par contre, je viens d'avoir un cas embêtant. J'ai ouvert un signalement et comme il faut aussi le rentrer en mission, j'ai validé mon signalement puis ouvert une fiche mission puis j'ai du retourner sur le signalement pour copier coller des infos. En revenant sur la fenêtre de la mission, tous les champs que j'avais rempli étaient vide.

**Comment by claire2212** [comment]
Hello Manon, merci de ce retour. Je viens de reproduire le problème, je règle ça au plus vite!
Le souci apparaît quand tu es sur une mission et que tu cliques sur l'icône Signalements (menu latéral gauche) pour retourner sur la liste des signalements. Donc en attendant que le problème soit résolu, je te conseille de repasser par la vue Liste des missions puis d'aller sur la vue des signalements.
Est-ce que tu veux que je fasse un mail au CACEM pour expliquer ça à tout le monde?

**Comment by TEAMCACEM** [comment]
Non pas besoin. on utilise pas encore ces chiffres là pour cette année.
