### ISSUE TITLE
Rapportage - pouvoir cliquer n'importe où sur la fenêtre pour faire disparaitre la case "sous-thématique"

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#735]
Sauf erreur de ma part, avant on pouvait cliquer n'importe où et ça fermait cette "fenêtre" : 
![image](https://github.com/MTES-MCT/monitorenv/assets/122106549/36886bf5-8398-4e61-be40-57f6bf15eb5e)
maintenant on doit cliquer sur le petit rectangle allongé blanc

**Comment by TEAMCACEM** [comment]
ça cache tout

**Comment by claire2212** [comment]
@TEAMCACEM je ne suis pas sure de comprendre le dernier commentaire

**Comment by TEAMCACEM** [comment]
On ne peut pas quitter la sélection des sous-thématiques qui cache le reste des infos à remplir

**Comment by claire2212** [comment]
@TEAMCACEM ah ok. Oui j'avais bien compris le problème, je l'ai réglé. Je vais essayer de faire une mise en production début de semaine prochaine.

**Comment by claire2212** [comment]
@TEAMCACEM livré lors de la mise en prod du jour. C'est ok pour vous?
