### ISSUE TITLE
Annule la mission en cours d'édition quand j'ajoute une nouvelle mission

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#738]
Lorsque je souhaite ajouter une nouvelle mission dans l'onglet Mission et contrôles alors que je suis en train d'en éditer une, on perd tout!

**Comment by claire2212** [comment]
@TEAMCACEM je reproduis effectivement ce bug, mais seulement depuis le bouton "Ajouter une nouvelle mission" depuis la carte. Je règle ça vite, en attendant je vous conseille d'utiliser le bouton de création de mission de la vue tableau

**Comment by TEAMCACEM** [comment]
Effectivement mais ça m'est arrivé plusieurs fois de perdre ma mission en cours

**Comment by claire2212** [comment]
@TEAMCACEM livré lors de la mise en prod du jour. C'est ok pour vous?

**Comment by TEAMCACEM** [comment]
ok
