### ISSUE TITLE
Cible signalement

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#739]
En mettre plus ou pouvoir en renseigner manuellement car ce n'est pas exhaustif actuellement
Ex : pollution

Pouvoir renseigner le détail du signalement

**Comment by AdelineCelier** [comment]
Est-ce que ce ticket est le même que celui-ci : https://github.com/MTES-MCT/monitorenv/issues/731?
On pourrait en effet juste mettre un "autre" dans le menu déroulant, et décrire le signalement dans le champ libre "description du signalement".

**Comment by AdelineCelier** [comment]
Comme vu avec vous, bien le même ticket que le #731, je ferme celui-ci.
