### ISSUE TITLE
Mettre à jour les thématiques de contrôle

### ISSUE THREAD

**Issue by thoomasbro** [MTES-MCT/monitorenv#74]
https://docs.google.com/spreadsheets/d/1m-ga-ryy8uggDbvjanPLq5dZ2zLgxYVwSh9-1fzg43w/edit?usp=sharing

**Comment by AdelineCelier** [comment]
*Points UX*
Il y a encore des problèmes avec la thématique Natura 2000, qui se scinde en plusieurs thématiques (2000, 2001, 2002...) – cf. ticket de bug #59 

*Points UI*
Sur les écrans, la thématique et la sous-thématique font partie de 2 menus déroulants différents. Au vu de la longueur des intitulés, c'est plus lisible de faire comme ça. Dans le cas où il n'y a qu'une sous-thématique pour la thématique sélectionnée, il faudrait que l'unique sous-thématique soit sélectionnée par défaut

**Comment by AdelineCelier** [comment]
Le problème Natura 2000 est réglé, il y a malheureusement peut-être encore des changements dans les thématiques (😬), il faut que j'en reparle avec Ariane lundi. Mais j'avance ce ticket et j'en ouvrirai un nouveau si besoin.
