### ISSUE TITLE
Symbologie et coloris des signalements

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#740]
Est-ce que la symbologie des signalements pourrait être vraiment différentes que celles des unités (drapeau rectangulaire vs drapeau triangle sont des symboles proches).
Idem les signalements observations en blanc ne sont pas bien lisible sur les cartes du SHOM à fond blanc. Peut-on mettre un peu de couleur ?

(Manon) Possibilité d'avoir la même symbologie que MFish (ce qui résoudrait le problème des drapeaux qui sont un peu similaires :
mission mer : 
terminée ![image](https://github.com/MTES-MCT/monitorenv/assets/122106549/6a74d3dc-380f-4d84-8f20-6de1ecab19ee)
en cours ![image](https://github.com/MTES-MCT/monitorenv/assets/122106549/ae767e09-1124-4a67-bc85-6db590726bbf) clôturée ![image](https://github.com/MTES-MCT/monitorenv/assets/122106549/15ec512e-2831-47b2-a557-e1e744b5ab4c)

mission mer et terre : 
![image](https://github.com/MTES-MCT/monitorenv/assets/122106549/f9476c75-ced0-4ec0-a360-10c84fbf0606)

mission terre : 
![image](https://github.com/MTES-MCT/monitorenv/assets/122106549/d81ece15-56bc-4583-8cdc-9602ab44f2dd)

**Comment by AdelineCelier** [comment]
Yes, si les icônes de Fish vous semblent bien, on peut aussi les mettre dans Env !

Concernant les icônes de signalement blanches, je vois en effet qu'elles sont moins visibles sur le fond SHOM, après c'est vrai que c'était aussi volontaire qu'elles ressortent moins que les autres, dans le sens où ce sont des signalements archivés. Et le gris ressort moins bien sur le fond de carte "neutre". Je peux quand même essayer de voir avec Clémence si on ne peut pas trouver un système plus coloré qui fonctionne à peu près sur tous les fonds de carte.

**Comment by TEAMCACEM** [comment]
(Roxane) Je ne suis pas du tout bonne en graphisme donc je vous laisse gérer les choix. Rendre les symboles et couleurs un peu plus distincts les uns des autres serait une bonne aide visuelle.

**Comment by TEAMCACEM** [comment]
@AdelineCelier validé par l'équipe : peut-on avoir une clio pour le symbole mission terre ?

**Comment by AdelineCelier** [comment]
Hahaa ok, quel modèle de Clio plus exactement ? 

Blague à part vous préférez une voiture plutôt qu'une ancre pour les missions terre c'est ça ? 
Je pense que c'est de l'ordre des possibles ;)
Cela va être pris en compte dans le ticket #588.

**Comment by manonolivier** [comment]
Oui c'est ça plutôt une voiture vu que chez nous les mission terre ne sont pas forcément dans les ports
