### ISSUE TITLE
Élargir la zone de description du signalement

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#741]
Élargir la zone de description du signalement

**Comment by claire2212** [comment]
@TEAMCACEM vous pouvez l'élargir manuellement en cliquant en bas à droite du champ sur les deux petits traits formant un triangle 

![Capture d’écran 2023-08-10 à 10 11 48](https://github.com/MTES-MCT/monitorenv/assets/23258718/24cc7bf1-269a-4c7e-87cd-c3989207589d)

Si c'est suffisant pour vous, je vous laisse clore cette issue, sinon j'en reparle avec Adeline à son retour. 
Merci
