### ISSUE TITLE
Pouvoir masquer / afficher les points d'intérêt

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#745]

**Comment by AdelineCelier** [comment]
Bien noté, je le rajoute dans le ticket #775 d'amélioration des points d'intérêt.

**Comment by claire2212** [comment]
Hello @TEAMCACEM je peux clôturer et passer ce ticket en done? ça a été fait pour le dernière mise en prod normalement

**Comment by AdelineCelier** [comment]
@manonolivier on est bons sur ce ticket aussi non ?

**Comment by manonolivier** [comment]
yes
