### ISSUE TITLE
Signalement - masquer les signalements terminés sur la carte

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#750]
En ayant la barre de recherche (cf #734) ça résoudra probablement le problème mais dans tous les cas nous n'aurons pas besoin de voir les signalements terminés sur la carte.

**Comment by AdelineCelier** [comment]
En effet, les filtres qui seront livrés prochainement vous permettront de masquer les signalements archivés. Par défaut, ils seront paramétrés sur les signalements en cours.
Le tableau et la carte fonctionnant ensemble, je ne trouve pas souhaitable de masquer définitivement les signalements archivés de la carte. Cela peut ponctuellement être utile.
