### ISSUE TITLE
Changer la couleur des points d'intéret ?

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#751]
La couleur fait qu'on les voit très mal par dessus une couche reg :
![image](https://github.com/MTES-MCT/monitorenv/assets/122106549/f2153339-cbea-4f11-a942-2fb438735013)

**Comment by TEAMCACEM** [comment]
(Roxane) On utilise surtout "Autre". "Navire de pêche" n'a pas vraiment de sens pour le CACEM. On peut mettre juste "Navire". On peut laisser le même icone pour tout les point d’intérêts si ça simplifie le visuel.

**Comment by AdelineCelier** [comment]
Ok bien noté, merci.

**Comment by claire2212** [comment]
Hello @TEAMCACEM est-ce que je peux clôturer ce ticket? on a changé les couleurs et l'icône des points d'intérêts depuis la dernière mise en prod

**Comment by AdelineCelier** [comment]
@manonolivier je vois que tu as bougé ce ticket en juillet 2024 dans "à développer", mais on est d'accord qu'il est déjà fait non ?

**Comment by manonolivier** [comment]
@AdelineCelier oula oui, je ne sais pas ce que j'ai fait
