### ISSUE TITLE
AMP - étiquettes et lien Legicem

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#752]
Pouvoir cliquer sur la zone AMP et savoir de quelle AMP il s'agit -> afficher son nom (comme pour les zones réglementaires)
Pouvoir cliquer sur la zone AMP et cliquer sur le lien vers Legicem -> lien legicem (comme pour les zones réglementaires)

**Comment by AdelineCelier** [comment]
- Sur le fait d'afficher le nom de la zone AMP, il y a le ticket #643 qui est ouvert et en cours de développement. 
- Concernant le lien vers Legicem, vous parlez des AMP avec réglementation ? Si oui, ces liens sont pour moi mis au niveau des zones réglementaires. Si non, ça veut dire qu'il y a des pages Legicem pour les AMP qui n'ont pas de réglementation ?

**Comment by manonolivier** [comment]
Oui, on a des pages legicem pour toutes les AMP y compris celles qui n'ont pas de réglementation. Pour l'instant, leur contenu est relativement succin mais à terme, nous allons y mettre tous les enjeux biodiv importants sur la zone, ce serait donc très intéressant niveau opérationnel d'avoir le lien vers la page legicem
