### ISSUE TITLE
Affichage de recherche REG et AMP

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#754]
Peut-on remodeler l'affichage en haut à gauche ainsi :

- avoir la recherche "Thématique réglementaire" ouverte en permanence (le bouton est inutile)
- avoir la recherche "Type d'AMP" ouvert en permanence

=> (Manon) je trouve ça utile de pouvoir cacher cette fenêtre.

- mettre la recherche "Thématique réglementaire", les résultats "Zones réglementaires" en dessous et les zones épinglées "Mes zones réglementaires" (ajouter le terme "épinglées") encore en dessous
- mettre la recherche "Type d'AMP", les résultats "Zones AMP" en dessous et les zones épinglées "Mes AMP" encore en dessous (ajouter le terme "épinglées")

=> (Manon) oui pourquoi pas

**Comment by manonolivier** [comment]
Est-ce que c'est possible aussi de faire une recherche des mots-clés comme pour les thématiques quand on rentre une action dans une mission ? Ce n'est pas une urgence car c'est rangé dans l'ordre alphabétique mais ce serait pratique de nous éviter de scroller
![image](https://github.com/MTES-MCT/monitorenv/assets/147587284/0b6c2420-b4d0-4388-a138-f9e18e9e09ae)

**Comment by AdelineCelier** [comment]
@manonolivier pardon je n'avais pas vu ton commentaire sur la recherche dans le menu "thématique réglementaire". J'ai fait un ticket spécifique sur le sujet, le #1130.

En ce qui concerne le fait de retravailler l'arborescence du volet carto, est-ce toujours un besoin ? 
De mon côté je me pose la question de l'intérêt de ce que proposait Roxane, car cela veut dire que ça intercalerait des zones épinglées et des recherches, je trouve ça un peu bizarre...qu'en pensez-vous ?

**Comment by manonolivier** [comment]
Tu as raison, ce n'est plus un besoin, on laisse comme ça, on s'est habitué !
