### ISSUE TITLE
Visibilité encart Fonds de carte

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#758]
Je ne sais pas si c'était déjà remonté mais je n'ai pas trouvé de ticket donc dans le doute : 

L'encart est transparent ce qui fonctionne bien sur le fond blanc mais dès que c'en est un autre c'est illisible :
![image](https://github.com/MTES-MCT/monitorenv/assets/122106549/802ee72f-efe5-412e-b6fb-b6f4b4296301)

**Comment by AdelineCelier** [comment]
c'est réglé en inté !
