### ISSUE TITLE
Trigramme bloquant qui ne devrait pas l'être

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#759]
Ce n'est pas urgent mais : 
J'ai repris une mission ouverte le matin pour modifier la zone de mission, ajouter des thématiques de surveillance et ajouter aussi d'autres actions de surveillance mais impossible de enregistrer et quitter la mission sans rentrer un trigramme "cloturé par"
![image](https://github.com/MTES-MCT/monitorenv/assets/122106549/ca627053-f223-4900-9b2e-363c0e990019)
Et puis le texte en rouge n'est pas normal je pense

J'ai juste à rentrer mon trigramme et je peux "Enregistrer et quitter"

**Comment by claire2212** [comment]
Bonjour @TEAMCACEM plusieurs questions pour que je puisse reproduire ce souci (au delà du texte qui effectivement n'est pas le bon) : 
- la mission était-elle déjà clôturée?
- Si oui, l'avez-vous réouverte avant de faire les modifications? ou avez-vous fait les modifications PUIS cliquer sur " Enregistrer et quitter" ?
- Avant les modification y avait-il un trigramme de clôture renseigné qui a été supprimé?


Merci d'avance et bonne journée.

**Comment by TEAMCACEM** [comment]
vu par téléphone

**Comment by claire2212** [comment]
@TEAMCACEM , Manon je suis désolée je n'arrive plus à reproduire ce qu'on a vu par téléphone. je m'étais noté : 
- Création de mission avec trigramme de clôture
- Clôture de la mission
- Réouverture de la mission
- Modifications quelconques + suppression du trigramme de clôture
- "Enregistrer et quitter" 
- Problème sur le champ de trigramme de clôture

C'était bien ça?

**Comment by TEAMCACEM** [comment]
Non pas tout à fait jusque là ça fonctionne c'est après : 
- Création de mission avec trigramme de clôture
- Clôture de la mission
- Réouverture de la mission
- Modifications quelconques + suppression du trigramme de clôture
- "Enregistrer et quitter"
- Revenir sur la mission pour modifications
- "Enregistrer et quitter" => blocage, il faut rentrer un trigramme
- Rentrer un trigramme
- "Enregistrer et quitter" fonctionne

**Comment by claire2212** [comment]
ok! Merci et desolée pour l'aller-retour

**Comment by AdelineCelier** [comment]
Vérifié et c'est ok
