### ISSUE TITLE
Saisie coordonnées – Afficher les erreurs de saisie dans les coordonnées

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#763]
Impossibilité de rentrer le point au delà de 5 minutes
ex :  42°24.88N-008°34.77E

**Comment by TEAMCACEM** [comment]
normal car DMS => jusqu'à 59 secondes max ici format en DMD
a voir si on peut ne pas bloquer la saisie en DMS

**Comment by manonolivier** [comment]
c'est la même chose que le #729, non ? On peut clôturer aussi comme c'est repris dans un ticket global ?
