### ISSUE TITLE
Pouvoir changer le système de coordonnées dans la création du point d’intérêt

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#764]
J'ai plein de couches ouvertes qui m’empêchent de changer mon système de coordonnées car ça cache la fenêtre. Prévoir la possibilité de changer le système dans la fenêtre de création d'un point d’intérêt

**Comment by AdelineCelier** [comment]
Problème de chevauchement de la fenêtre réglé, réglage du système de coordonnées directement à côté du champ à venir, cf. ticket [#2435](https://github.com/MTES-MCT/monitorfish/issues/2435).
