### ISSUE TITLE
Metabase - Affectations plusieurs facades pour une mission

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#765]
Exemple : Le Floréal a fait une mission Réunion et Mayotte (donc 2 facades) avec une surveillance qui comprend la zone des deux facades : 
![image](https://github.com/MTES-MCT/monitorenv/assets/122106549/765a0106-7dd2-4202-ba83-263bbdfd57ea)

Sur MEnv la facade SOI apparait bien : 
![image](https://github.com/MTES-MCT/monitorenv/assets/122106549/e3d49918-860b-40c1-aaf1-5f9bbb26a388)

Sur Metabase la mission du Floréal n'apparait pas pour la facade SOI :
![image](https://github.com/MTES-MCT/monitorenv/assets/122106549/cc35cb45-d494-4103-8d54-3a44ee97401d)
![image](https://github.com/MTES-MCT/monitorenv/assets/122106549/b07eee41-befe-4d33-9f5f-3ac8b2890bee)

J'ai trouvé ce problème par hasard, je ne sais pas s'il concerne d'autres missions et d'autres facades

**Comment by AdelineCelier** [comment]
@VincentAntoine est-ce que c'est normal ou bien il y a un pb qque part dans les données ?

**Comment by VincentAntoine** [comment]
Il n'y a qu'une façade par mission et par action, comme discuté ici : https://github.com/MTES-MCT/monitorenv/issues/237#issuecomment-1561237343
Cette mission se trouve majoritairement dans la façade Mayotte et donc elle compte dans la façade Mayotte.
