### ISSUE TITLE
Demander une confirmation avant de fermer la fenêtre Missions et contrôle

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#767]
J'avais ouvert des missions que je devais finir de remplir mais sans faire exprès j'ai fermé la fenêtre et rien n'a été enregistré.
Serait-il possible de faire en sorte que cette "fonctionnalité" qui bloque le "quitter" d'une mission modifiée bloque aussi le fait de fermer la fenêtre : 
![image](https://github.com/MTES-MCT/monitorenv/assets/122106549/6503eafe-37a8-444e-a967-c915709ccbd2)

**Comment by claire2212** [comment]
@TEAMCACEM vous n'avez pas eu de confirmation comme la capture ci-dessous? 
Sur quel navigateur est-ce arrivé?

<img width="1509" alt="Capture d’écran 2023-08-22 à 08 40 34" src="https://github.com/MTES-MCT/monitorenv/assets/23258718/65901b2b-e39e-43a8-8bb4-cd4b8de8a1d2">

**Comment by TEAMCACEM** [comment]
Roxane : J'ai l'impression de que ça ne marche pas pour la deuxième ou troisième fenêtre de mission en cours d’édition.

**Comment by AdelineCelier** [comment]
De mon côté j'ai l'impression que c'est bon. Après j'avoue que je ne me souviens plus exactement du mode de déclenchement de ce problème @claire je crois qu'on en avait parlé sur Mattermost mais on n'a pas recopié dans le ticket (my bad).
