### ISSUE TITLE
Volet reg - Changement couleur croix pour supprimer zone

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorenv#77]
J'ai retouché les écrans suite aux retours des tests utilisateurs : 

Les principaux changements UX sont : 
- retravail de la recherche via la carte, en s'inspirant du système "SeLoger" (cf [ticket 46](https://github.com/MTES-MCT/monitorenv/issues/46))
- remplacement des cases à cocher par des épingles (cf [ticket 48](https://github.com/MTES-MCT/monitorenv/issues/48))
- ajout de menus déroulants pour filtrer les zones (cf [ticket 47](https://github.com/MTES-MCT/monitorenv/issues/47)) 
- Ajout d'éléments pour afficher/masquer/supprimer les zones et les groupes de zones (reprend donc le [ticket 51](https://github.com/MTES-MCT/monitorenv/issues/51))
- Affichage/recherche des zones manquantes d'un groupe de zones : à discuter ensemble pour voir faisabilité

Les écrans reprennent bien tous les composants de la nouvelle bibliothèque de composants pour Monitor. 
Donc normalement tout est au carré côté UI dans les écrans, j'ai aussi repris les espacements des éléments pour aérer un peu et essayer de me rapprocher du système 8px/16 px/24px...sans être (psycho)rigide non plus ^^

**Comment by AdelineCelier** [comment]
**Sur le système SeLoger**
Le système marche bien, c'est top !
Petits ajustements identifiés : 
- [ ] quand on fait "relancer la recherche ici" ça dézoome pas mal la carte. C'est un peu perturbant que ça ne garde pas le même niveau de zoom par rapport à la recherche initiale. 
- [ ] centrer en largeur dans l'écran les boutons "effacer les résultats de la recherche" et "relancer la recherche ici"
- [ ] écartement de 8 px entre les deux boutons

**Sur le remplacement des cases à cocher par des épingles**
- [ ] Lorsque j'épingle une zone, cela l'ajoute à la section "mes zones reg" mais cela ne doit pas continuer de l'afficher lorsque j'ai modifié ou fermé ma recherche. Là on se retrouve avec des zones affichées sans savoir comment les masquer.
- [ ] L'icône épingle est un bouton tertiaire, qui n'a donc pas de fond. Ses états hover/active/disabled se manifestent par un changement de couleur de l'icône elle-même, pas de son fond (cf. bibliothèque)

**Ajout de menus déroulants pour filtrer les zones**
- [ ] il faudrait pouvoir rechercher dans le menu au clavier (dans l'idéal direct dans le champ, sinon garder la barre de recherche proposée par React – cf la bibliothèque, où j'ai mis cette barre de recherche)
- [ ] l'UI du menu déroulant des filtres n'est pas encore tout à fait tel que dans la bibliothèque de composants (couleur de la typo du placeholder, états hover, active et filled, ainsi que couleurs et états des valeurs du menu déroulant). 
- [ ] le placeholder "thématique de contrôle" n'est pas centré dans le champ du menu
- [ ] pour moi, le bouton-lien "réinitialiser les filtres" ne doit apparaître que si des filtres ont été sélectionnés
- bien justifier le "réinitialiser les filtres" sur le bord gauche du menu des filtres et réduire sa marge en-dessous, elle doit faire 16 px jusqu'au filet qui sépare la section des filtres des résultats de la recherche
- idem, bien justifier les tags des filtres sélectionnés sur le bord gauche (marge gauche = 16 px) et la marge entre le tag et le menu des filtres est de 16 px aussi

**Comment by AdelineCelier** [comment]
PS : j'ai conscience que ça fait beaucoup de retours dans un seul ticket, dis-moi si tu veux qu'on les découpe en plusieurs tickets !

**Comment by thoomasbro** [comment]
> il ne faut pas que la sélection d'un filtre efface ce qu'on a tapé dans le menu déroulant. En ce moment je tape "mouillage", je sélectionne un des filtres, ça efface automatiquement ce que j'ai tapé et ça fait remonter la liste des filtres tout en haut.

Je pense que ce qui te gène actuellement est lié au fait qu'il y a plusieurs intitulés similaires (mouillage / Mouillage / mouillages) et que pour tous les sélectionner, il faut saisir plusieurs fois le même texte. Je pense qu'il faut dans ce cas précis résoudre le problème à la base et n'avoir qu'une seule entrée "Mouillage".

Ceci dit, je comprends le souci. Malheureusement il va falloir refaire le composant en entier alors. Car dans le TagPicker d'origine les tags sont dans le selecteur et non déplacés en dessous, ce qui est donc cohérent : quand ils sont sélectionnés, ils "remplacent" le texte saisi. Comme on a déplacé les étiquettes en dehors du champ, c'est beaucoup moins cohérent. D'ailleurs, les items sélectionnés ne sont plus visibles et masqués par le dropdown dans cette nouvelle configuration proposée.

**Comment by thoomasbro** [comment]
> mettre la croix pour supprimer des zones en Slate Gray

Pour moi on était sur un tertiary small button donc gun metal
Je change quand même en slate Gray ?

**Comment by AdelineCelier** [comment]
Conclusion de notre discussion sur le tagpicker : faire en sorte que le composant n'efface pas la recherche de l'utilisateur après que celui-ci ait sélectionné une valeur demanderait de refaire tout le composant. 
Cette demande des utilisateurs étant possiblement liée au fait qu'il y a des doublons dans les thématiques, on attend de voir si retirer les doublons suffit à régler le problème. 
A voir à l'usage s'il faut refaire le composant ou non, mais ce n'est pas une priorité aujourd'hui.

**Comment by AdelineCelier** [comment]
> Pour moi on était sur un tertiary small button donc gun metal. Je change quand même en slate Gray ?

Alors les tertiary small button sont en Charcoal par défaut et non Gunmetal ;) Mais tu as raison, je propose un petit écart ici par rapport à la lib, pour éviter d'avoir une 3è couleur en plus des deux couleurs de l'œil à côté de la croix. Disons que c'est un petit ajustement visuel.

**Comment by AdelineCelier** [comment]
Ce ticket est trop gros, il ne reste que des petits points UI. Je ferme celui-ci et en rouvre un autre.
