### ISSUE TITLE
Fonds de carte – Le fond blanc du menu a disparu

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorenv#774]
menu fantôme 👻 

![image](https://github.com/MTES-MCT/monitorenv/assets/71878648/0af714a7-bc99-4c16-b473-bb6f1645ada3)

**Comment by TEAMCACEM** [comment]
Ticket #758 qui a déjà été ouvert

**Comment by AdelineCelier** [comment]
Ah bien vu merci ! Je ferme celui-ci.
