### ISSUE TITLE
Signalements – Revue formulaire sur la carte

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorenv#776]
## Revue post-vacances ;)

- Mettre le sémaphore en valeur sur la carte quand on clique sur l'icône "centrer sur la carte" dans le formulaire : l'afficher en surbrillance (en Blue Gray) pendant 5 secondes et afficher sa pop-up. Si la couche des sémaphore est masquée, la réafficher au clic sur l'icône et faire le même comportement pour le sémaphore centré. 👍🏻 
- Ne pas réafficher la couche des missions quand on crée un point ou une zone de signalement 👍🏻 
- Modale de tracé de zone/point sur la carte : si on oublie de valider la zone ou le point avant de fermer le signalement, la modale reste ouverte. Ok pour la fermer en même temps que le signalement (puisque de toutes façons la zone ou le point est validée et enregistrée même si on n'a pas cliqué sur "valider"). 👍🏻 
- Il faudrait repositionner l'icône du drapeau par rapport à la croix en dessous : la hampe du drapeau doit pointer vers le centre de la croix (cf. écrans) 👍🏻 
- Suite au retour du ticket #740, pourrait-on faire un test concernant les signalements archivés : mettre le contour du drapeau blanc en Blue Gray ou maximum Red en fonction de si c'était une observation ou une infraction ? A voir si cela ressort un peu mieux sur un fond de carte SHOM.

**Comment by AdelineCelier** [comment]
Tous les premiers points du ticket sont bons. 
Concernant l'aspect des signalements archivés : 
- ça marche bien, ça ressort mieux. Il faudrait juste mettre les croix en bleu ou rouge dans le cas de signalements avec des points, et les pointillés des zones en bleu ou rouge + l'intérieur de la zone en blanc avec opacité réduite (pour reprendre les mêmes principes que l'icône)
- comme pour les signalements actifs, il faut que le point ou la zone restent affichés au clic sur l'icône.
- j'ai l'impression que la zone de clic sur l'icône d'un signalement ne couvre pas tout le drapeau. Par moments mon curseur est sur le drapeau mais je ne peux pas cliquer. Je peux cliquer au niveau de la croix en revanche, mais pas hyper pratique. 
- j'ai aussi remarqué dans un cas que la pop-up se superposait à l'icône, m'empêchant de cliquer dessus (cf. vidéo), je sais pas si c'est possible de faire qqch pour y remédier. 
- je ne me souviens plus de ce qu'on s'était dit concernant les liens en pointillés entre l'icône et sa pop-up : ce serait compliqué à faire ? Je vois que ça marche plutôt bien sur les sémaphores. 


https://github.com/MTES-MCT/monitorenv/assets/71878648/ced533c4-7ac1-4a09-8aac-3f3e9d8fe1e4

**Comment by AdelineCelier** [comment]
**Revue de la revue**

- > Il faudrait juste mettre [...] l'intérieur de la zone en blanc avec opacité réduite (pour reprendre les mêmes principes que l'icône)
Le fond d'une zone d'un signalement archivé est bien blanc quand on a cliqué dessus, mais pas juste quand on le survole, là j'ai l'impression qu'il est bleu. Je pense qu'on peut le mettre blanc dès le survol, comme les zones sont rouges ou bleues dès le survol pour les signalements actifs.

- > comme pour les signalements actifs, il faut que le point ou la zone restent affichés au clic sur l'icône.
C'est bizarre, maintenant ça marche pour certains signalements et pas pour d'autres...est-ce que c'est lié au moment de création des signalements, avant ou après ton fix ?

- > j'ai aussi remarqué dans un cas que la pop-up se superposait à l'icône
Je n'ai plus vu ce cas, ça m'a l'air réglé.

**Comment by claire2212** [comment]
@AdelineCelier , pour le point deux j'avoue que je ne comprends pas pourquoi la croix ou la zone ne reste pas visible pour les "vieux signalements". Je ne vois pas de raison qui explique ça.

Pour le point un je l'ai traité dans la pr des multi signalements, et le point trois j'ai effectivement réussi à trouver une solution :-) .

**Comment by AdelineCelier** [comment]
Super pour le point 3, merci !
Et pour les "vieux" signalements, faisons comme on s'est dit en standup : on met en prod et on voit si le problème persiste.

**Comment by AdelineCelier** [comment]
@claire2212 bon là c'est un peu du pinaillage je reconnais (ne me tape pas 😇), mais je vois que l'icône du drapeau de signalement se glisse "sous" la zone de signalement quand tu cliques dessus...tu vois ce que je veux dire ? Je trouve ça un peu étrange, mais clairement pas bloquant, c'est de l'UI. 

![image](https://github.com/MTES-MCT/monitorenv/assets/71878648/2ccbb1ce-359f-4137-a597-96a54ac42b9f)

**Comment by AdelineCelier** [comment]
Perfectus !
