### ISSUE TITLE
Remettre la position de contrôle obligatoire

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#784]
rendre la position de contrôle et action de contrôle obligatoire

On a remarquer que ce n'est pas obligatoire alors que ça doit l'être

**Comment by AdelineCelier** [comment]
Ah il y a eu une petite régression, c'était le cas avant. Merci on rectifie ça.

**Comment by TEAMCACEM** [comment]
Oui lors de la clôture de mission. Du coup y a t il des contrôles sans position qui ont été enregistrés ?

**Comment by AdelineCelier** [comment]
J'ai l'impression qu'elle est obligatoire si on renseigne un contrôle dans le premier enregistrement, mais que quand on le renseigne dans une mission déjà enregistrée, elle ne l'est plus. 
Et j'ai l'impression que la zone de surveillance n'est pas obligatoire non plus, alors qu'elle devrait l'être (soit case cochée, soit nouvelle zone tracée).

**Comment by claire2212** [comment]
@Adeline, pour le point 1 je n'arrive pas à reproduire l'erreur est bien affichée à chaque fois (mai seulement en cas de clôture comme indiqué dans le ticket)
Pour le point 2 je n'ai effectivement mis en place cette validation que pour le contrôle, je met ça aussi sur les surveillances (toujours en cas de clôture seulement)

**Comment by AdelineCelier** [comment]
@claire2212 oulah oui désolée j'ai mal relu le ticket vendredi, et j'ai testé en cas d'enregistrement sans clôture ! J'ai été trop vite.

**Comment by AdelineCelier** [comment]
C'est bon aussi pour la surveillance !
