### ISSUE TITLE
Couleur - changer la même couleur des sémaphores et des missions terminée en une couleur différente

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#793]
Changer la même couleur des sémaphores et des missions terminée en une couleur différente car c'est pas très distinctif sur la carte

**Comment by AdelineCelier** [comment]
Hello, 
Désolée, je me rends compte que je n'ai pas répondu à ce ticket. 
Pour les icônes de mission, il est prévu qu'on reprenne celles qu'il y a dans Fish (cf. ticket #588), et qui ont une icône selon le type de mission (mer, terre, air). Je pense que ça devrait aider déjà à mieux les distinguer.

**Comment by manonolivier** [comment]
yes au vu des écrans du ticket 588 c'est parfait, on peut clôturer ce ticket ?

**Comment by AdelineCelier** [comment]
Ok je le ferme !
