### ISSUE TITLE
Signalements - Pouvoir créer / éditer plusieurs signalements

### ISSUE THREAD

**Issue by claire2212** [MTES-MCT/monitorenv#796]
- Pouvoir créer et éditer plusieurs signalements en même temps
- Affichage des formulaires sur la vue tableau

**Comment by claire2212** [comment]
vu avec @AdelineCelier : 
- Un seul signalement peut-être "actif" (comme pour les missions): 
Si un signalement est ouvert sur la carte et que je souhaite en un ouvrir u nautre sur le tableau, le signalement de la carte est réduit et n'est donc plus "actif". Les données du formulaire sont sauvegardées.
Même comportement dans l'autre sens (Tableau -> Carte)

- Un même signalement ne peut être ouvert sur les deux pages. Si le signalement X est ouvert sur la carte et que je souhaite l'éditer depuis la vue tableau, le formulaire de la carte se ferme et s'ouvre sur la vue tableau

**Comment by TEAMCACEM** [comment]
Pourquoi ne pas avoir fait la même chose que pour les missions ? Car il arrive que l'on doit ouvrir plusieurs signalements en même temps. Et ça va être le cas aussi pour les remontées de besoins.

**Comment by TEAMCACEM** [comment]
Sache que l'on est pas frustré ni déçu sur l'avancée de la fonctionnalité signalements coté CACEM car ce n'était pas une fonctionnalité prioritaire et urgente. En revanche on a du mal, étant donné que c'est livré petit à petit, à savoir ce que l'on doit commenter ou pas en fonction des évolutions apportées. 
L’objet de mon commentaire était surtout de savoir si vous aviez bien prévu de pouvoir ouvrir la vue détaillée des missions et la vue détaillée des signalements sur 2 fenêtres séparées ?

**Comment by AdelineCelier** [comment]
@claire2212 l'édition entre les deux vues (carte et liste) fonctionne bien je trouve, c'est cool ! 

**Retours UX**
- Je crois que j'ai loupé un truc dans les revues précédentes : dans le cas de la création d'un nouveau signalement, les boutons dans le bandeau du bas ne sont pas les bons. Avant premier enregistrement du signalement, il n'y a que 2 boutons "valider le signalement" et "annuler". 
- Il y a des signalements qui s'ouvrent tout seuls : je crée un signalement, je le renseigne puis je l'enregistre. J'en crée un nouveau, et cela crée aussi automatiquement un autre signalement en-dessous, dans lequel la source est pré-remplie avec le dernier sémaphore sur lequel j'ai fait un signalement. 
- Idem, dans la même mécanique, j'ai l'impression que le dernier signalement que j'ai édité se rouvre tout seul quand j'ouvre à sa suite un autre signalement. 

**Retours UI**
- Je sais que ce n'est pas ce qu'a dessiné Clémence, mais je me demande si ce ne serait pas plus élégant de ne mettre que 2px entre chaque bandeau de signalement 
![image](https://github.com/MTES-MCT/monitorenv/assets/71878648/a17d1cc4-3f58-4292-a856-c38574e6f6c7)
- IDans le cas où j'enregistre et quitte un signalement, son séparateur reste au-dessus de la "pile" de signalements (cf. capture)
![image](https://github.com/MTES-MCT/monitorenv/assets/71878648/1153f542-e077-452a-90b6-f6b5c49817dc)

**Comment by AdelineCelier** [comment]
Seul point restant que je vois : 
- ce sont bien les bons boutons maintenant, mais le bouton "annuler" n'a pas d'effet. Il devrait fermer le signalement (avec une pop-up de confirmation s'il y a eu des modifs.

**Comment by claire2212** [comment]
@AdelineCelier je viens de tester en inté et en local et le bouton "Annuler" fonctionne bien. Tu peux me dire si de ton côté il ne fonctionne jamais ou s'il y a un cas d'usage particulier?

**Comment by AdelineCelier** [comment]
@claire2212 ah bizarre je ne crois pas que c'était dans un cas particulier. Je reteste et te dis.

**Comment by AdelineCelier** [comment]
Après avoir retesté, le seul cas où j'arrive à reproduire c'est quand on ne remplit rien dans le formulaire de signalement. Dans ce cas-là il faudrait juste fermer le formulaire, sans pop-up de confirmation.

**Comment by claire2212** [comment]
@AdelineCelier je ne reproduis le cas dont tu parles que si je créé un signalement depuis un sémaphore. Le comportement est donc normal puisqu'on a pré-rempli le formulaire avec le sémaphore en question (il y a donc eu un changement sur le formulaire, donc la pop-up de confirmation)

**Comment by claire2212** [comment]
ok, vu le problème. Je le fixe

**Comment by AdelineCelier** [comment]
c'est booon le bouton annuler fonctionne, maravilleux.
