### ISSUE TITLE
Signalements - Backend de rattachement des signalements aux missions

### ISSUE THREAD

**Issue by thoomasbro** [MTES-MCT/monitorenv#799]
# Résumé du modèle métier et questions
1. Un signalement peut être lié à une mission et à une seule
2. Un signalement peut être lié à un seul controle ou une seule surveillance, mais pas les deux
3. Un contrôle ou une surveillance peut être liée à un seul signalement. Cependant prévoir dans le modèle la possibilité de rattacher plusieurs signalements à une surveillance (ou un contrôle) en cas d'évolution.

4. Pourquoi garder l'historique des affectations de signalement à des missions ?
5. Sur l'écran 65: on affiche la date d'affectation ou la date du signalement pour le rattachement ? 
6. Cela aurait plus de sens sur la timeline d'afficher la date du signalement. Mais alors, quid de la date de désaffectation ?

7. Que se passe-t-il si on affecte un signalement à la mission, qu'on le détache, puis qu'on le rattache une nouvelle fois? 
8. Est ce qu'on doit afficher les 3 actions dans l'historique?

9. Que se passe-t-il lorsqu'un signalement est détaché d'une mission alors que des contrôles/surveillance sont liés à ce signalement? 
   10. Faut-il les détacher aussi? **non, cf. 11**
   11. ou faut-il interdire le détachement du signalement de la mission tant que des contrôles/surveillance sont liés à ce signalement? **oui, interdire le détachement du signalement de la mission s'il y a un contrôle/surveillance liée**

12. Un signalement est il modifiable lorsqu'il est lié à un contrôle/une surveillance? **Synchronisation thématique/cible entre signalement et contrôle/surveillance quasi impossible techniquement. Deux possibilité --> cible et thématique non modifiable si rattachement, il faut modifier le signalement avant de créer le contrôle/la surveillance. --> modifiable, mais alors il peut y avoir un indicateur qui note qu'il y a un écart entre le signalement et l'action de contrôle/surveillance**
    13.  si oui, que se passe-t-il si on modifie les signalement, notamment les thématiques/cibles?
    14.  si non, que se passe-t-il si on modifie les thématiques/cibles depuis le contrôle/la surveillance?

15. Validation de la mission: ajouter un pop-up si un signalement est affecté à la mission, mais sans être affecté à un contrôle ou une surveillance (--> @AdelineCelier)

# Proposition de modèle de données:
Même si on est plutot sur des relations 1-N, on va partir sur des relations N-N 
pour pouvoir garder l'historique des affectations de signalements à des missions et anticiper d'éventuels changements métiers

 - missions_reportings
    - id_mission*
    - id_reporting*
    - date_affectation*
    - date_desaffectation

  - envactions_reportings
     - id_envaction*
     - id_reporting*
     - date_affectation*
     - date_desaffectation

# Evolution des APIs

- Pas de création de nouveau endpoint
- L'ajout/suppression sur les tables liées se fait depuis les entrées `create`/`update` des endpoints `reportings`/`missions`

**Comment by thoomasbro** [comment]
- Sur la date affichée dans la timeline, je vois un risque d'incohérence en termes d'interface : on affiche la date d'*affectation* (action utilisateur) pour les signalements alors qu'on affiche la date du contrôle ou de la surveillance (date de l'évènement) et non la date de *création* du controle.

- Stocker directement l'info dans la table reportings l'id de la mission fait qu'on ne peut pas garder l'historique d'affectation/désaffectation d'un signalement que pour une seule mission. On ne peut pas gérer le cas suivant:
- affectation du signalement `23001`à la mission `A`
- désaffectation du signalement
- affectation du signalement `23001`à la mission `B`
--> sans création de nouvelle table, on ne pourra pas conserver l'information d'affectation/désaffectation à la mission `A`


 Mais je n'ai peut être pas bien compris l'usage de cette fonctionnalité.

- contrôle fait / surveillance faite (écran 5 / 6): Effectivement. Est ce qu'on considère que le contrôle / la surveillance est réalisée lorsqu'un controle/une surveillance est rattachée au signalement ? ou faut il prendre en compte la date ?. Solution plus simple : "Contrôle à faire" pourrait être affiché lorsque **Le signalement nécessite un contrôle** (`isControlRequired`) est coché mais qu'aucun controle/surveillance est rattaché.  

il va y avoir une complexité supplémentaire si on veut stocker l'information en base en prenant en compte la date du controle/signalement. On peut le faire uniquement si ça a un intérêt statistique à mon avis.

**Comment by AdelineCelier** [comment]
Hello, suite à un téléphone avec Clémence, je récapitule ici ce qu'on s'est dit : 
- concernant l'historique des affectations/désaffectations de mission : cette notion d'historique des différentes actions effectuées sur une mission allait dans la logique de conserver une trace de tout ce qui se passe sur une mission. L'idée est que cette timeline serve vraiment de main courante/fil conducteur – pour se rapprocher de la logique de ce qui est fait dans RapportNav. On s'est dit que cela restait intéressant à terme, mais que cela pouvait être fait en V2 ou V3 – si cela ne complexifie pas les choses de l'implémenter à posteriori. 
- concernant le rattachement des signalements 
  - à un contrôle : Clémence a bien validé qu'on ne pouvait rattacher qu'un seul signalement par contrôle, donc on resterait sur les radio buttons
  - à une surveillance : Clémence confirme qu'en effet dans le cas d'une surveillance il pourrait arriver que l'utilisateur veuille attacher plusieurs signalements, auquel cas on pourrait mettre des check boxes. 

Ok pour vous @claire2212 et @thoomasbro ?

**Comment by thoomasbro** [comment]
Suite au point de synchro, on ne conservera pas l'historique des détachements.
On part donc sur un modèle simplifié, dans lequel on stocke uniquement l'identifiant de mission dans la table des signalements, avec la date de rattachement et la date de détachement.
