### ISSUE TITLE
Thématiques - Revoir la méthode de mise à jour des thématiques

### ISSUE THREAD

**Issue by thoomasbro** [MTES-MCT/monitorenv#804]
La mise à jour de thématiques est complexe dans le json des `env_actions`. Faire évoluer le modèle vers quelque chose de plus relationnel pour faciliter la mise à jour.

**Comment by claire2212** [comment]
je ferme ce ticket car mise en place de la nouvelle typologie début 2024  + création de tables en BDD (#755)
