### ISSUE TITLE
Positions CROSS - et compétences géographiques + tel/mail

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#805]
Mettre sur la carte la position des CROSS avec tel/mail et zone de compétences

**Comment by AdelineCelier** [comment]
Les CROSS font partie du tableau des unités, elles apparaîtront donc sur la carto dans le module unités/moyens avec leur tel/mail. Concernant les zones de compétence, il y aura un champ libre "secteur d'intervention" sur la fiche de l'unité dans lequel on pourra spécifier la zone de compétence de l'unité. 
A voir à l'usage s'il est nécessaire de rajouter une vraie zone sur la carte, mais si oui ce serait fait dans un 2nd temps.

**Comment by AdelineCelier** [comment]
Ok, est-ce que vous avez le tracé des zones de compétence de votre côté ?
Et je remonte le ticket 141 en haut de la pile, je suis désolée il traîne effectivement depuis un bon moment ! 
J'en parle au point de synchro Env tout à l'heure.

**Comment by TEAMCACEM** [comment]
Voir avec Alexia

**Comment by AdelineCelier** [comment]
@manonolivier ça faisait partie des derniers tickets que je voulais voir avec toi : c'est toujours un besoin cette zone de compétence des CROSS ? 
Si oui, vous avez pu récupérer le tracé ?
