### ISSUE TITLE
Infraction - Pouvoir dupliquer l'infraction x fois sans cliquer x fois

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#807]
Pour de nombreuses infractions, le fait de dupliquer en cliquant de nombreuses fois n'est pas très ergonomique (ex : en pap).

![image](https://github.com/MTES-MCT/monitorenv/assets/122106549/b2e8c1b2-60a0-4913-9556-53ec29f99846)

Peut-on avoir le choix entre dupliquer en cliquant ou entrer le chiffre x fois ?

**Comment by AdelineCelier** [comment]
Ok bien compris le problème, il faut que je dessine quelque chose sur le sujet.

**Comment by AdelineCelier** [comment]
@TEAMCACEM hello, j'ai dessiné ces écrans pour la duplication d'infraction. J'ai plutôt ajouté un champ "nombre de cibles avec cette infraction" dans le formulaire d'infraction, ce qui permet d'éviter d'avoir 500 cartes d'une même infraction dans la colonne 3. 
Par défaut le champ serait rempli à 1. 
![image](https://github.com/MTES-MCT/monitorenv/assets/71878648/73b47a08-e496-4abf-9a25-bf0fe2807dc1)

Je pense qu'il faut faire attention à n'utiliser ce champ qu'avec parcimonie, exclusivement dans le cas où vous n'avez aucune info pour caractériser la cible contrôlée. C'est pour ça que j'ai ajouté ce petit message dans l'icône "attention". Je veux bien votre retour sur ce message.
![image](https://github.com/MTES-MCT/monitorenv/assets/71878648/d411a729-4aa5-45f1-bdfc-cb5d9723f74a)

Une fois le formulaire d'infraction validé, le nombre de cibles concernées s'afficherait directement sur la carte de l'infraction.
![image](https://github.com/MTES-MCT/monitorenv/assets/71878648/8eb33391-98f7-4da1-9168-ffaaefd8f505)

Qu'en pensez-vous ?

**Comment by AdelineCelier** [comment]
@maximeperraultdev voici les écrans XD, [27](https://xd.adobe.com/view/c72c4b9f-8704-453c-9e85-c5a61bce1e6e-927f/screen/01cf83bb-7fe8-466c-8905-a9a2b3711132/), [28](https://xd.adobe.com/view/c72c4b9f-8704-453c-9e85-c5a61bce1e6e-927f/screen/2b78fde4-4faa-4a11-9229-abaada3449e7/) et [29](https://xd.adobe.com/view/c72c4b9f-8704-453c-9e85-c5a61bce1e6e-927f/screen/bbb0bfa9-0bc3-4d6b-8083-e996c0020975/)

**Comment by Morraff** [comment]
Je m'interroge sur comment cette nouvelle fonctionnalité va "apparaitre" dans la base de donnée MEnv. Pour le moment, chaque infraction fait l'objet d'un dictionnaire clef valeur avec un identifiant particulier. Est ce que c'est possible de conserver le même format dans la base de données pour chaque infraction dupliquée de manière aussi "brutale" ?

**Comment by maximeperraultdev** [comment]
@Morraff Elle devrait apparaitre comme une nouvelle clé `nbTarget` avec pour valeur un nombre > 1. Les infractions ne sont pas réellement dupliquées. On indique uniquement que cette infraction impacte un certain nombre de personnes non-identifiées.

**Comment by AdelineCelier** [comment]
@maximeperraultdev juste 2 retours : 

- quand je mets plus de cibles que 1, cela grise seulement une partie des champs d'identification d'un navire (tous sont grisés sauf le MMSI et l'IMO). 
![image](https://github.com/user-attachments/assets/65ddce74-bab2-4d26-8a88-7862f35c1941)

- il faut mettre à jour les tags dans la carte du contrôle dans la colonne 2. Cf. capture ci-dessous, sur 5 contrôles il faudrait 3 PV et 2 RAS.
![image](https://github.com/user-attachments/assets/aa6bca2d-8b93-4cba-b0de-226a3b37ef9e)

**Comment by maximeperraultdev** [comment]
@AdelineCelier Ok pour le premier point. Concernant le second (je pense que ce n'est pas le bon screenshot)

**Comment by AdelineCelier** [comment]
C'est bon !
