### ISSUE TITLE
Mettre à jour la liste déroulante des moyens des unités à enregistrer à jour

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#821]
Il manque des moyens dans la liste déroulante des moyens. La mettre à jour avec le fichier Unités-moyens

(MO) Par exemple PNM d'Iroise : aucun moyen sur MENV alors que dans la tableau il y a 5 moyens nautiques et 2 voitures

**Comment by AdelineCelier** [comment]
Désolée je me rends compte que je n'avais pas répondu à ce ticket. 
On est en train de bosser dessus pour la brique unités/moyens, cela devrait arriver bientôt ! On en discutait justement hier avec Ivan et Vincent.

**Comment by TEAMCACEM** [comment]
Yes on est pas encore à faire des stas sur les moyens mais ça va nous aider sur le coté opérationnel et les missions qui paraissent doublons mais ne le sont pas forcément.

**Comment by AdelineCelier** [comment]
Petite question : on avait décidé de ne conserver que les types de moyens et pas forcément leurs noms, en se disant que la plupart n'ont pas de nom et que le type de moyen donne assez d'infos. 
Ca veut dire que dans la liste des moyens dans la mission, il n'y aura plus que des types : "semi-rigide", "patrouilleur", "voiture"...
Est-ce que ce serait ok pour votre usage, ou bien est-ce qu'il y aurait des cas où le nom du moyen serait tout de même utile ?

**Comment by TEAMCACEM** [comment]
Non on garde les deux justement 👍 
![image](https://github.com/MTES-MCT/monitorenv/assets/122106549/a3a70cc4-d20a-4593-8d76-dbe5a7c4c435)
![image](https://github.com/MTES-MCT/monitorenv/assets/122106549/660f0214-3489-41f0-8493-d22828adc551)

D'autant plus que ça permet de discriminer les missions "similaires"

**Comment by AdelineCelier** [comment]
Helloce ticket a été réglé avec la brique unités/moyens, je le passe en terminé.
