### ISSUE TITLE
Erreur du Natinf 23004 dans Monitor Env - impossibilité de corriger dans Poseidon

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#822]
(Roxane) Le Natinf 23004 est faux dans Monitor Env. La dénomination est "MOUILLAGE NON CONFORME AUX PRESCRIPTIONS DU REGLEMENT DE POLICE DU MOUILLAGE SUR LE DOMAINE PUBLIC MARITIME" comme le 23004 et devrait être "REFUS D'OBTEMPERER AUX ORDRES DES FONCTIONNAIRES ET AGENTS EN MATIERE DE POLICE DU MOUILLAGE".
Je ne peux pas le corriger dans Poseidon car le natinf est déjà utilisé. 

Merci de corriger dans Monitor Env en ce sens :

23003 = MOUILLAGE NON CONFORME AUX PRESCRIPTIONS DU REGLEMENT DE POLICE DU MOUILLAGE SUR LE DOMAINE PUBLIC MARITIME

23004 = REFUS D'OBTEMPERER AUX ORDRES DES FONCTIONNAIRES ET AGENTS EN MATIERE DE POLICE DU MOUILLAGE

**Comment by TEAMCACEM** [comment]
Et bien je ne sais pas pourquoi mais sur mon monitor env 23003 et 23004 sont les mêmes...

![image](https://github.com/MTES-MCT/monitorenv/assets/122106549/f99ccf0b-be8e-4801-8095-ae2946da357b)

![image](https://github.com/MTES-MCT/monitorenv/assets/122106549/71ed51a5-51a5-4c29-a7d0-0f7afb4d7e9a)

**Comment by AdelineCelier** [comment]
Wow hyper bizarre, @thoomasbro @claire2212 une idée d'où ça pourrait venir ?

**Comment by TEAMCACEM** [comment]
J'ai regardé sur le monitor env de christophe et il a aussi 23003 et 23004 identiques

**Comment by claire2212** [comment]
@AdelineCelier très bizarre premier test j'ai bien deux valeurs différentes, et depuis j'ai les mêmes valeurs `"MOUILLAGE NON CONFORME AUX PRESCRIPTIONS DU REGLEMENT DE POLICE DU MOUILLAGE SUR LE DOMAINE PUBLIC MARITIME"` .
C'est l'api qui nous renvoie ça, je regarde

**Comment by AdelineCelier** [comment]
Cela m'a l'air bon, mais de mon côté ça ne s'était pas affiché en doublon. Mais si tu as vérifié aussi c'est que ça doit être ok. 
Juste on a parlé hier au daily de faire une passe plus globale sur ces NATINF pour vérifier que le problème n'existait pas sur d'autres NATINF : est-ce que c'est fait, ou est-ce qu'il faut ouvrir un ticket sur le sujet ?

**Comment by claire2212** [comment]
@AdelineCelier non ce n'est pas fait. Je pensais demander au CACEM de faire une passe dans Poséidon pour faire une vérification. Avec la modification qu'on a fait avec Vincent il leur suffit juste de cocher sur "bloqué" sur les natinfs en doublon. Tu en penses quoi je leur fais un mail?

**Comment by AdelineCelier** [comment]
Ah bah s'ils peuvent avoir la main dessus oui, on peut leur faire un mail ! 
Juste tout vérifier d'un coup à la main peut être assez fastidieux j'imagine, du coup ce serait leur dire que s'ils tombent sur un cas similaire ils le traitent ? Parce que j'imagine que c'est compliqué d'automatiser une vérification ?
