### ISSUE TITLE
Façade Outre-Mer - filtre ne marche pas dans vue détaillée des missions

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#823]
Façade Outre-Mer - le filtre ne marche pas dans vue détaillée des missions :
- cela fonctionne pour MED mais pas pour Guadeloupe par exemple
- c'est impossible de rechercher les missions de l'outre-mer

**Comment by AdelineCelier** [comment]
@VincentAntoine j'ai l'impression que c'est lié aux tickets #656 et #768 non ?

**Comment by claire2212** [comment]
Résolu dans la PR : https://github.com/MTES-MCT/monitorenv/pull/787
