### ISSUE TITLE
[Signalement] Pouvoir rattacher un signalement à une mission

### ISSUE THREAD

**Issue by claire2212** [MTES-MCT/monitorenv#827]
- Lié à #799 

Maquettes : https://xd.adobe.com/view/69dcd22c-eb8b-4ede-bd7c-473483429986-3c8f/grid

**Comment by claire2212** [comment]
**Gestion des layers/ overlays pour la sélection d'une mission à rattachée à un signalement :** 
        - N'afficher que les missions en cours pour la sélection (au hover on a la zone de mission qui apparaît)
        - Au clic on entoure la mission + trait entre mission et signalement (la zone apparaît également) + affichage de la mission dans le formulaire de signalement
Solution technique : Création de 2 layers et d'un overlay spécifique pour les missions qui peuvent être rattachées à un signalement (Layer avec toutes les missions en cours + layer avec la mission sélectionnée).
Questions : 
- Comment gérer le trait entre signalement et mission qui sont sur deux layers différents ? 
- Quid du cas où on à un signalement ouvert avec une mission rattachée (ex: id 1) et l'affichage des missions sur la carte dont la mission avec l'id 1? On se retrouve avec la mission affichée deux fois l'une sur l'autre

**Comment by thoomasbro** [comment]
1. Gestion du trait entre le signalement et la mission
Je mettrais le trait entre mission et signalement dans un style avec création de la géométrie à partir du centroide de mission et centroide du signalement. Ce style peut être dans l'une ou l'autre des couches.
La couche signalement avec le signalement sélectionné serait peut être la plus appropriée, puisque c'est le signalement qui va porter l'information en cours d'édition il me semble.

2. Je n'ai pas compris pourquoi il y avait 2 fois la mission affichée. Quelles seraient les couches affichées dans ce cas ?

**Comment by claire2212** [comment]
@thoomasbro pour le point 2 tu peux avoir deux fois la même mission affichée si :
- tu ouvres un signalement avec la mission 1 rattachée (sur la carte on voit donc le signalement + le trait + la mission entourée)
- La mission 1 est visible sur la carte car elle est renvoyée par l'api des missions

**Comment by thoomasbro** [comment]
J'afficherais la mission une seule fois, uniquement dans la couche OpenLayers des missions. La couche signalement affiche le signalement + le trait mais pas la mission.

**Comment by claire2212** [comment]
@thoomasbro je me rends compte que le fait d'afficher la mission dans la couche des missions peut poser des problèmes si l'api ne renvoie pas la mission (à cause des filtres). Le problème est le même côté missions -> affichage des signalements rattachés à cette mission, si les signalements ne sont pas renvoyés par l'api à cause des filtres on affiche un trait + un rond sans rien dedans.

Je devrais peut-être faire un couche spécifique quitte à avoir une superposition non?

**Comment by thoomasbro** [comment]
Effectivement. Une couche spécifique c'est une bonne idée. L'autre solution serait de tester si la mission est déjà dans le front, et de l'appeler si besoin, et de faire la jointure dans la couche mission.

**Comment by AdelineCelier** [comment]
## Revue du rattachement des signalements aux missions - EN COURS

**Revue UX**

- [ ] La date d'ajout du signalement n'apparaît qu'à l'enregistrement de la mission, et non dès le rattachement du signalement => possible de changer ça ?
- [ ] En faisant le test, je me rends qu'il pourrait être utile d'afficher le signalement sur la carte quand on saisit un point de contrôle pour le contrôle auquel on a rattaché le signalement...il est probable que dans certains cas le point de signalement soit le même que le point de contrôle. 

**Revue UI**

- [ ] Le bouton "Lier un signalement" me semble petit (texte et icône)
![image](https://github.com/MTES-MCT/monitorenv/assets/71878648/379ebb88-409b-4550-ac21-0402809fec32)
- [ ] Il manque encore le fait d'afficher les liens quand on clique sur une mission ou sur un signalement non ?
- [ ] J'ai l'impression que les icônes de signalement deviennent bien vertes une fois qu'on enregistre la mission à laquelle on les a liés, mais qu'elles reprennent leur couleur initiale quand on rouvre la mission. Possible de les rendre vertes dès le lien fait (et pas seulement à l'enregistrement) et de les laisser vertes tout le temps ?
- [ ] C'est un détail, mais il me semble qu'on s'était dit que ce serait pas mal de voir la croix du signalement quand on affiche le lien qui le relie à une mission, pour comprendre que le lien part du point précis du signalement. Ce serait à faire au moment du lien + quand on clique sur la mission/le signalement
- [ ] Possible de mettre toutes les icônes au-dessus des traits de liens ?
![image](https://github.com/MTES-MCT/monitorenv/assets/71878648/40cf6201-bc7e-4145-ad25-151eb9be245b)

**Comment by AdelineCelier** [comment]
# Revue de la revue UX ;)

- [ ] Écran blanc : voir erreur Sentry
- [ ] Pour les missions en cours qui s'affichent sur la carto quand on veut lier un signalement : rallonger la durée de la mission en cours, passer de 1 mois à 3 mois. Ceci pour être surs qu'on affiche bien les missions longues.
- [ ] Le détachement d'un signalement depuis une mission ne met pas à jour le signalement quand celui-ci est rangé (donc pas fermé). 
- [ ] Dans le cas d'un signalement archivé, le bouton "détacher de la mission" est bien grisé côté mission, mais pas côté signalement
![image](https://github.com/MTES-MCT/monitorenv/assets/71878648/a3134252-dbfb-412a-96e4-e658730ab7e7)
- [ ] Quand je "range" un signalement, sa zone et son lien avec sa mission ne se masquent pas. Comme discuté, ce serait plus intuitif que cela se comporte comme si on fermait le signalement.

**Comment by claire2212** [comment]
@AdelineCelier alors en fait j'ai dit des bêtises pour les missions du CNSP qui ne s'affichent pas. Elle ne s'affichent pas parce qu'il n'y a pas de date de fin on dirait. Pas besoin d'augmenter le filtre à trois mois finalement je recupère toutes les missions en cours sans limite de temps.
Par contre je ne comprends pas pourquoi les missions sans date de fin de s'affichent pas

**Comment by AdelineCelier** [comment]
Ah ok si tu récupères toutes les missions en cours c'est très bien !
Mais zut en effet ça veut dire qu'il y a un petit bug si les missions du CNSP ne s'affichent pas.

**Comment by AdelineCelier** [comment]
Comme discuté ensemble, un problème semble persister sur la mise à jour du signalement actif quand il est rangé. 

https://github.com/MTES-MCT/monitorenv/assets/71878648/079613bb-37ba-4e72-96ad-189fa87460a4

**Comment by AdelineCelier** [comment]
Top c'est bon ça fonctionne maintenant !
