### ISSUE TITLE
Etat Toggle sur le bouton mission

### ISSUE THREAD

**Issue by thoomasbro** [MTES-MCT/monitorenv#83]

**Comment by AdelineCelier** [comment]
Les états "toggle" des boutons sur la carto ne sont plus tout à fait bons : 
- la couleur "actif" me semble encore en Blue Yonder, et non en Blue Gray
- l'état actif/non actif n'est plus lié à l'ouverture/la fermeture des menus reg ou mission, mais au fait de cliquer sur l'icône ou bien cliquer ailleurs que sur l'icône.
