### ISSUE TITLE
Information du jour/heure de l'ouverture d'une mission

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#847]
(Manon) : c'est une information qui peut nous être utile en cas de problèmes de stats ou autres donc pas besoin d'avoir l'information sur MEnv mais est-ce possible d'avoir l'info dans les extractions metabase ?

Exemple de cas :
En cas de mission ouverte avec la même unité, le même jour sur une zone à peu près similaire. Pour tirer au clair cette situation, ce serait pas mal d'avoir accès au jour/heure d'ouverture de la missions :
- si les missions ont lieu le 25/08 et une est ouverte le 25/08 et l'autre le 30/08 = probablement problème de saisie des agents (rapportage par mail de l'unité et l'agent CACEM n'a pas vu qu'une mission avait déjà été ouverte)
- si les missions ont lieu le 25/08 et les deux sont ouvertes le 25/08 à la même heure = probablement 2 moyens différents qui vont au même endroit

**Comment by AdelineCelier** [comment]
Hello Manon, 
Merci pour ton retour. 

En effet, c'est un vrai besoin, on l'a identifié en se repenchant justement sur les questions d'enregistrement soulevées par les problèmes de doublons de missions. 
Les décisions prises sur le sujet sont retracées dans le ticket [#2465](https://github.com/MTES-MCT/monitorfish/issues/2465). 
Donc on a bien identifié l'intérêt d'enregistrer la date et l'heure de premier enregistrement de la mission. 
Pour l'instant on n'a pas l'info dans Mattermost, mais Vincent avait fait un tableau pour aider au dédoublonnage des missions, ici : https://metabase.din.developpement-durable.gouv.fr/question/1588-liste-des-missions-monitorenv-ou-une-unite-participe-a-plusieurs-missions-au-meme-endroit-et-simultanement

Dites-nous si vous rencontrez des difficultés dans l'utilisation du tableau !

**Comment by TEAMCACEM** [comment]
Pouvez-vous revoir la finesse du tableau car il sélectionne certaines missions qui ne sont pas du même type (terre, mer, air) ou certaines missions sont conjointes ?

**Comment by AdelineCelier** [comment]
@VincentAntoine je te laisse voir si c'est possible de retirer les missions conjointes, et les missions d'une même unité de types différents !

**Comment by VincentAntoine** [comment]
C'est fait pour la partie type de mission, j'ai éliminé les cas où on a une mission terre et une mission mer. Par contre quand il y a une mission terre et mer et une mission terre et air (ou plus généralement dès qu'au moins un type est commun aux missions) je les ai gardées, même s'il y a des types en plus ou en moins en dehors du type commun.
Par contre pour les mission conjointes je ne suis pas sûr de comprendre pourquoi il faudrait les retirer ? Une même unité n'a a priori pas le don d'ubiquité, y compris en mission conjointe ?

**Comment by AdelineCelier** [comment]
Dans le cadre de la synchro des missions, on va rajouter cette info de la date et l'heure de création de la mission. Cf. ticket #1159 ouvert sur le sujet, que Claire va faire dans les prochains jours.

**Comment by claire2212** [comment]
Salut @manonolivier je peux clôturer ce ticket?
