### ISSUE TITLE
Incompatibilité de saisie de mission commune CACEM (Monitor Env) / CNSP (Monitor Fish)

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#855]
(RRR) Je résume ici les constats qui nous font pour l'instant créer des missions "doublons" entre le CNSP et le CACEM :

- certains champs obligatoires sur Monitor Env ne le sont pas sur Monitor Fish (date fin, heure fin, trigramme, téléphone, spatialisation de mission) et il manque donc des infos pour l’opérationnel
- 1 seule clôture de mission (cela passe la mission dans clôturée alors que l'autre centre n'a pas encore renseigné ses actions)
- pas de visualisation des actions de l'autre centre dans la mission (on se sent un peu aveugle sur ce qu'à fait l'unité dans l'autre domaine) -> ce serait bien de pouvoir visualiser ce qu'il s'y passe (sans modification possible)
- les moyens ne sont pas renseignés et permettraient de différencier des missions qui semblent similaires mais ne le sont pas (1 unité avec 2 équipes au même moment)
- bien vérifier s'il n'y a pas une mission ouverte de l'unité

**Comment by AdelineCelier** [comment]
Bonjour Roxane, 
Merci pour ce récapitulatif qui résume bien les problèmes à date. 
Certains points sont identifiés et on peut y répondre via le logiciel. 
D'autres posent encore des questions sur les procédures et sur l'organisation des centres et des unités. Je pense qu'il serait utile qu'on recale un point CNSP/CACEM pour essayer de trancher ensemble ces questions et de trouver la solution la plus acceptable. 

J'ai envoyé un mail pour qu'on organise un échange sur le sujet.

**Comment by TEAMCACEM** [comment]
Recap réunion
https://docs.google.com/document/d/1iqo7snjUcxmmjwYBfWWKZkbQOB3NAZrpNWQgm81JM0Y/edit?usp=sharing

**Comment by claire2212** [comment]
Salut @manonolivier je pense qu'on peut fermer ce ticket non?
