### ISSUE TITLE
Mission - revoir les marges sur le volet actions

### ISSUE THREAD

**Issue by thoomasbro** [MTES-MCT/monitorenv#86]
+ sur volet détail

**Comment by AdelineCelier** [comment]
Les marges gauche et droite sont bonnes, en revanche il faut aussi une marge de 32px entre le groupe date/heure et la carte de l'action
![image](https://user-images.githubusercontent.com/71878648/187641786-a5369069-cae1-4be9-a1cc-42f161fa3549.png)
