### ISSUE TITLE
Zones administratives - Ajouter les zones de compétence des CROSS

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorenv#864]

**Comment by AdelineCelier** [comment]
@manonolivier je crois que c'était une demande de Roxane, mais je ne sais pas s'il y a encore un besoin de votre côté ?

**Comment by manonolivier** [comment]
@AdelineCelier yes, c'est toujours d'actualité

**Comment by claire2212** [comment]
voir sur data.gouv (zones de responsabilités françaises)

**Comment by AdelineCelier** [comment]
@maximeperraultdev je vois que les noms des zones sont à cheval sur les tracés, donc à la frontière entre deux zones, ce n'est pas hyper clair du coup je trouve. 
Est-ce qu'il serait possible de plutôt placer le nom des zones au centre de chaque zone de compétence ?

**Comment by maximeperraultdev** [comment]
@AdelineCelier Tout a fait possible de le centrer. Je le fait.
Par contre pour le CROSS Jobourg, je viens de vérifier c'est une erreur des données que j'ai récupérer de data.gouv.fr... On va faire la modif 👍

**Comment by maximeperraultdev** [comment]
@AdelineCelier C'est bon pour Jobourg

**Comment by AdelineCelier** [comment]
Merci !
