### ISSUE TITLE
Rapportage - Stockage des métadonnées pour chaque polygone de zone de mission saisi

### ISSUE THREAD

**Issue by thoomasbro** [MTES-MCT/monitorenv#87]
Il peut y avoir plusieurs zones pour une mission.
La zone de mission peut être dessinée ou être une copie d'une zone réglementaire (AMP par exemple).

Doit-on stocker les métadonnées liées à cette zone (i.e. nom de la zone ou "zone dessinée") ?

**Comment by claire2212** [comment]
La fonctionnalité n'ayant pas été développée (sélection d'une zone type AMP comme Zone de mission) ce ticket n'a pas lieu d'être
