### ISSUE TITLE
Signalements - j'ai l'impression que cocher "ce signalement nécessite un contrôle" ne change rien (pas de couleur spéciale, pas présent dans les filtres) Manon

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#872]

**Comment by claire2212** [comment]
@Sallut @TEAMCACEM , salut Manon. Et tu as toute à fait raison, la case ne sert pour l'instant à rien :-) 
Elle sera utile pour le rattachement de mission (en cours de développement), si la case est cocher alors tu pourrais rattacher une mission au signalement.

Si c'est ok pour toi je te laisse fermer le ticket et le passer en `Done`.
Merci
