### ISSUE TITLE
Problème de géolocalisation et d'affichage d'une mission datant de Janvier

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#882]
ADRIEN & ALEXIA

Bonjour les dev,

Nous avons découvert un OVNI sur Env.

Alexia s'occupait de spatialiser les surveillances et contrôles de missions pour lesquelles il manquait des informations. Pour une mission de l'ULAM 29 Douarnenez du 24 janvier 2023 à 11h30, impossible de trouver le drapeau indiquant qu'elle est clôturée. Aucune zone en surbrillance n'apparaît bien qu'il existe un polygone de zone de mission selon la fiche.

![Plan 2 - mission invisible](https://github.com/MTES-MCT/monitorenv/assets/122106549/5ca64760-0e82-4060-a006-848048ed596b)

Il existe une deuxième mission de la même unité à quelques heures et quelques kilomètres de distance. Lorsqu'on clique sur l’œil pour zoomer d'une mission à l'autre, Env fait défiler la carte du monde **en entier** pour géolocaliser lesdites missions. Ce faisant, nous avons découvert que certaines missions sont susceptibles d'avoir été renseignées sur deux "planisphères" différents. Nous avons remarqué que les points d'intérêts et missions ne s'affichent pas d'un "planisphère à l'autre"

![Plan 1](https://github.com/MTES-MCT/monitorenv/assets/122106549/9bccec65-f880-4726-a568-a0ab23d875cc)

![Plan 2](https://github.com/MTES-MCT/monitorenv/assets/122106549/01fdfaba-c9df-411b-a192-9fa4f96505cd)

A priori, aucun souci côté Metabase après vérification sur les cartes de pression de surveillance / contrôle dispo 

Passez au CACEM voir Alexia pour mieux comprendre le problème qui est très visuel.

**Comment by claire2212** [comment]
Salut @TEAMCACEM , on a identifié le problème. La zone a été tracé en ayant fait "le tour du monde" ce qui donne entraîne ces soucis d'affichage. 
Un ticket à été crée de notre côté : https://github.com/MTES-MCT/monitorenv/issues/461

A priori il n'y a que cette mission qui est concernée par ce problème.
