### ISSUE TITLE
Enlever la sous-thématique "braconnage" dans pêche à pied -> échéance Janvier 2024 avec la nouvelle typologie

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#883]
Faire le même fonctionnement que la thématique espèces protégées : 
pouvoir sélectionner loisir ou pro en sous thématique
et ensuite le type de pêche à pied (filet fixe, etc) en sous-sous-thématique

**Comment by claire2212** [comment]
Hello @TEAMCACEM je peux fermer ce ticket?

**Comment by claire2212** [comment]
Hello @manonolivier on peut clôturer ce ticket?
