### ISSUE TITLE
bug d'affichage - Superpositions d'éléments

### ISSUE THREAD

**Issue by TEAMCACEM** [MTES-MCT/monitorenv#894]
(Manon) Je ne sais pas à quoi c'est dû parce que quand j'actualise monitor ça se remet bien
![image](https://github.com/MTES-MCT/monitorenv/assets/122106549/85c08064-63f6-4320-a9a9-d6dfb50c1585)

**Comment by claire2212** [comment]
Bonjour @TEAMCACEM , est-ce que vous pouvez me dire si le souci arrive quand vous cliquez sur un résultat dans la liste des zones règlementaires ou amp?

**Comment by manonolivier** [comment]
Salut @claire2212 désolée pour la réponse tardive, je n'avais pas vu ton commentaire.
Oui ça le fait quand on clique sur un résultat dans les listes. Adrien me disait que ça le faisait aussi quand on trace une zone de mission mais je n'ai pas réussi à le faire de mon côté
