### ISSUE TITLE
Contrôle - Possibilité de sélectionner le type de cible alors que le champ est disabled

### ISSUE THREAD

**Issue by claire2212** [MTES-MCT/monitorenv#921]
<img width="499" alt="Capture d’écran 2023-10-26 à 17 32 12" src="https://github.com/MTES-MCT/monitorenv/assets/23258718/3221aeeb-c6e5-4e53-82e5-e7e6affacd88">

**Comment by AdelineCelier** [comment]
ça me semble good !
