### ISSUE TITLE
Unités – Retouches diverses sur le backoffice et la fiche unité

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorenv#926]
**Types de contact dans la fiche unité** 
- [x] Trier la liste des noms de contact par ordre alphabétique (sauf l'option "créer un nom de contact personnalisé", à laisser en bout de liste)
- [x] Permettre une recherche dans la liste 👍🏻 
- [x] Aujourd'hui, on peut direct taper un nom de contact personnalisé. Il faudrait empêcher ça, sinon le risque c'est que les utilisateurs fassent toujours ça et ne choisissent pas des items de la liste. 
- [x] Modifier le type de contact "bureau" en "bureau de l'unité" 👍🏻 

**Revoir le wording dans les pop-ups d'alerte** 
- [x] Dans le cas où l'on veut supprimer un moyen rattaché à une mission, rectifier une coquille dans la popup : mettre un masculin ("avant de **le** supprimer") à la place du féminin ("avant de la supprimer"). 👍🏻 
- [x] Dans le cas où on veut supprimer une administration dont les unités ne sont rattachées à aucun item (mission ou signalement), changer le wording de la pop-up s'affichant à la suppression : "Des unités sont encore rattachées à cette administration. Veuillez les supprimer avant de pouvoir supprimer cette administration." 👍🏻 
- [x] Dans les pop-ups s'affichant à l'archivage, remplacer "Elle n'apparaîtra plus dans MonitorEnv" par "Elle n'apparaîtra plus **dans MonitorFish et dans MonitorEnv**" 👍🏻 

**Retouches ergonomie/UI**

- [x] Quelque chose que je n'avais pas remarqué : quand on édite un moyen, le formulaire d'édition s'affiche en-dessous de la carte du moyen (voire en-dessous de toute la liste des moyens, ce qui est un peu perturbant). Je pense qu'il vaudrait mieux que le formulaire **remplace** la carte du moyen le temps de l'édition. Et que la carte réapparaisse quand on clique sur "enregistrer". Ok pour toi ? 👍🏻 
- [x] Petit détail UI dans le formulaire d'édition d'une base dans le backoffice : mettre une marge de 16 px entre le champ "nom de la base" et le champ "coordonnées". 👍🏻 
- [x] Lors de l'archivage ou de la suppression d'un item (admin, base, unité), rajouter un message toast vert disant "L'admin/l'unité/la base a bien été archivée/supprimée". 👍🏻

**Comment by ivangabriele** [comment]
Vu ensemble pour celui-ci :

> Aujourd'hui, on peut direct taper un nom de contact personnalisé. Il faudrait empêcher ça, sinon le risque c'est que les utilisateurs fassent toujours ça et ne choisissent pas des items de la liste.

C'est donc un bug si c'est le cas et je ne le reproduis pas sur ma branche de fix.

**Comment by AdelineCelier** [comment]
**Types de contacts fiche unité**

- [ ] le tri par ordre alphabétique n'a pas l'air d'avoir fonctionné
![image](https://github.com/MTES-MCT/monitorenv/assets/71878648/e6af33ae-7987-4c9a-b31d-22a6dfbad06f)

- [ ] le bug que je t'ai remonté sur le fait qu'on peut éditer un contact même s'il n'est pas personnalisé est toujours présent
https://github.com/MTES-MCT/monitorenv/assets/71878648/0d51b208-6705-4505-ac66-8cece96c349a

**Comment by AdelineCelier** [comment]
@ivangabriele je remets ce ticket en todo pour les deux points qui restent à traiter ci-dessus.

**Comment by ivangabriele** [comment]
> le bug que je t'ai remonté sur le fait qu'on peut éditer un contact même s'il n'est pas personnalisé est toujours présent
https://github.com/MTES-MCT/monitorenv/assets/71878648/0d51b208-6705-4505-ac66-8cece96c349a

@AdelineCelier Le nom dans la base de donnée est bien un nom personnalisé. Je pense qu'il y a eu un soucis de nommage sur les unités dont le nom est à renseigner lors de la migration. Cette valeur devrait être à "UNKNOWN" qui elle correspond au nom prédifini "Nom de contact **non** renseign**é**" et là elle est directement égale à "Nom du contact **à** renseign**er**".

Je pourrais éventuellement ajouter une migration qui remplace tous les "Nom du contact à renseigner" par "UNKNOWN" si on veut que le frontend détecte ça comme un nom prédifini. Mais c'est un peu dirty de faire ça.

@VincentAntoine ?

**Comment by AdelineCelier** [comment]
La liste est bien en ordre alphabétique maintenant, et je vois bien les ajouts/changements de valeurs dont on a parlé Ivan. 
Il reste à faire la partie avec Vincent.
Je remets donc ce ticket en todo en attendant, pour qu'on ne le perde pas de vue.

**Comment by AdelineCelier** [comment]
Ce ticket semble réglé, on le ferme.
