### ISSUE TITLE
Rapportage - Etat des actions de contrôle ou surveillance avant remplissage

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorenv#93]
J'ai décliné dans [cet écran](https://xd.adobe.com/view/973ae2b4-ecd1-419f-b092-8545e0d8ce57-c269/screen/4bb61158-32aa-4c48-9984-51701efcf450/) l'état des cartes d'actions de contrôle/surveillance/observations pour montrer leur état avant qu'ils soient remplis.

**Comment by thoomasbro** [comment]
Ok. Voir #97 pour les tags.

**Comment by AdelineCelier** [comment]
@thoomasbro je suis désolée je ne suis plus sûre de ce qu'on avait finalement tranché à l'oral, mais pour moi on s'était finalement dit que la carte "contrôle" encore non renseignée serait comme les cartes surveillance et observation, à savoir avec une seule ligne de texte disant "contrôle à renseigner".

**Comment by thoomasbro** [comment]
> @thoomasbro je ne suis plus sûre de ce qu'on avait finalement tranché à l'oral, mais pour moi on s'était finalement dit que la carte "contrôle" encore non renseignée serait comme les cartes surveillance et observation, à savoir avec une seule ligne de texte disant "contrôle à renseigner". On s'était dit que ça permettait de voir rapidement ce qui était vide encore.

Quel champ doit être renseigné pour considérer que le contrôle a été renseigné ?

**Comment by AdelineCelier** [comment]
@thoomasbro mmh est-ce qu'on peut dire que ça se remplit au fur et à mesure ? quand tu renseignes la thématique, elle remplace le "non renseigné", quand tu renseignes le nb de contrôles et les cibles, la phrase grise apparaît, et quand tu renseignes les infractions ls tags apparaissent. 
Qu'en penses-tu ?

**Comment by AdelineCelier** [comment]
Ok c'est bien implémenté comme ça.

Deux derniers détails :
- dans la phrase grise, le mot "contrôle" est au pluriel même quand il n'y a qu'un seul contrôle
- dans le titre, je mettrais aussi le mot "contrôle" au singulier tant qu'il n'est pas indiqué dans la case "nb total de contrôles" un chiffre supérieur à 1

**Comment by thoomasbro** [comment]
I ❤️ css
<img width="73" alt="Capture d’écran" src="https://user-images.githubusercontent.com/4479037/201078276-5bc68b85-83cf-4313-956e-6922058bbd2e.png">

**Comment by AdelineCelier** [comment]
Haha bon je n'ai pas vu de saute d'humeur de CSS sur les dates dans le volet central, je propose qu'on valide ce ticket, pour ton plus grand bonheur.
