### ISSUE TITLE
Les fiches des zones reg ne s'affichent pas

### ISSUE THREAD

**Issue by VincentAntoine** [MTES-MCT/monitorenv#937]
Quand on clique sur une zone reg pour voir sa fiche, une erreur se produit

`Uncaught (in promise) TypeError: o[n.arg.endpointName] is undefined`

**Comment by louptheron** [comment]
ça semble venir d'ici : https://github.com/MTES-MCT/monitorenv/compare/v1.15.0...main#diff-384fa1cf4c7bad8f3e4a1ea4b2678d8b786f0ff20e24cc8b77ede188841dc8feL54

Issue : https://github.com/reduxjs/redux-toolkit/issues/2160#issuecomment-1257222693

**Comment by AdelineCelier** [comment]
Problème réglé !
