### ISSUE TITLE
Signalements – Revue UI du rattachement des signalements

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorenv#944]
**Revue UI**

- [x] Le bouton "Lier un signalement" me semble petit (texte et icône)
![image](https://github.com/MTES-MCT/monitorenv/assets/71878648/379ebb88-409b-4550-ac21-0402809fec32)
- [x] La pastille dans le tag ne suit pas la courbe gauche du tag...je sais pas si je suis claire, à comparer avec le composant dans la bibliothèque XD ;) 👍🏻 
![image](https://github.com/MTES-MCT/monitorenv/assets/71878648/d57f63ca-07b9-470a-8448-d30da062f01a)
- [x] Les icônes changent de couleur entre leur couleur d'origine et le vert de façon parfois erratique. Je pense qu'à partir du moment où un signalement est rattaché à une mission, il doit rester vert en toutes circonstances.
- [ ] C'est un détail, mais il me semble qu'on s'était dit que ce serait pas mal de voir la croix du signalement quand on affiche le lien qui le relie à une mission, pour comprendre que le lien part du point précis du signalement. Ce serait à faire au moment du lien + quand on clique sur la mission/le signalement
- [x] Possible de mettre toutes les icônes au-dessus des traits de liens ? 👍🏻 
![image](https://github.com/MTES-MCT/monitorenv/assets/71878648/40cf6201-bc7e-4145-ad25-151eb9be245b)
- [x] Dans le signalement en mode "lecture seule" dans une mission, il y a juste un petit retour à la ligne du "(h)" du champ "Validité" qui ne devrait pas être 👍🏻 
![image](https://github.com/MTES-MCT/monitorenv/assets/71878648/9f2476ce-1e4d-4fd2-acc1-e230719c0cc7)

**Comment by claire2212** [comment]
@AdelineCelier pour ton retour : 
```
C'est un détail, mais il me semble qu'on s'était dit que ce serait pas mal de voir la croix du signalement quand on affiche le lien qui le relie à une mission, pour comprendre que le lien part du point précis du signalement. Ce serait à faire au moment du lien + quand on clique sur la mission/le signalement
```

Justement il me semblait qu'on avait dit non et que quand je mettrai les nouvelles icônes on aurait plus ce souci. Non?

**Comment by AdelineCelier** [comment]
Mais les nouvelles icônes c'est pour les missions, pas pour les signalements non ?
Pour moi les nouvelles icônes de missions (rondes) devaient atténuer le fait que le trait rentrait dans le cercle.
Il me semblait qu'on avait dit que c'était pas mal d'afficher la croix du signalement parce que ça permettait de visualiser son point exact et montrait que le trait n'était pas "flottant" sous le drapeau. 
Mais comme je disais c'est vraiment un détail donc si c'est chiant à faire on peut laisser comme ça pour l'instant et aviser plus tard.

**Comment by AdelineCelier** [comment]
## Revue en cours

- [ ] Masquer les bases quand on est en train de lier un signalement via le signalement ou la mission

**Comment by AdelineCelier** [comment]
## Revue de la revue UI

- [ ] Le bouton semble à une taille plus adéquate, toutefois j'ai l'impression qu'il fait qques pixels de plus que le bouton "Ajouter"... non ? Après ça c'est ptet des ajustement à voir quand on fera une repasse sur les tailles des composants dans monitor-ui ? 
![image](https://github.com/MTES-MCT/monitorenv/assets/71878648/0b1b213d-b43b-44ab-b256-39aa9b38cf0d)

- [ ] J'ai l'impression qu'il reste des cas où le signalement repasse brièvement au rouge. Quand cela arrive, il semblerait que l'app détecte des modifications dans le signalement, quand bien même je n'ai rien édité dedans. 
https://github.com/MTES-MCT/monitorenv/assets/71878648/2ca6302e-c383-424d-b29c-2151b6cf6407

**Comment by claire2212** [comment]
@AdelineCelier pour le bouton "Lier un signalement" depuis une mission, il est effectivement plus haut que le bouton "Ajouter". Ce ne sont pas les mêmes composants (le bouton "Ajouter" est un menu dropdown"). Donc oui c'set le fait que les boutons soient plus gros que voulu. Je peux modifier en dans Env pour ce bouton si tu veux

**Comment by AdelineCelier** [comment]
mmh bon en vrai on peut attendre de faire la repasse dans monitor-ui dans ce cas.

**Comment by AdelineCelier** [comment]
Pour ce point-ci : "les coordonnées du point de signalement et le bouton "centrer sur la carte" s'affichent sur 2 lignes dans le formulaire. Normalement ça devrait rentrer sur une ligne."

=>on met en prod et on attend de voir si ça le fait sur les écrans du CACEM, car cela n'arrive pas tout le temps, cela dépend de la taille de la scrollbar, et donc de la version de Firefox utilisée.
