### ISSUE TITLE
Missions - Impossible de modifier les unités ou moyens des anciennes missions lorsqu'il y a au moins un moyen rattaché

### ISSUE THREAD

**Issue by ivangabriele** [MTES-MCT/monitorenv#955]

**Comment by AdelineCelier** [comment]
@ivangabriele je ne suis pas bien sûre de savoir comment vérifier ce fix.
Est-ce qu'il y a un comportement spécifique à reproduire pour vérifier que c'est bon ? C'est le bug sur le fait qu'une mission ne s'enregistrait pas dans certains cas quand il y avait des moyens ?
On pourra voir ensemble lundi matin.
