### ISSUE TITLE
Carte - Ajout d'un trait entre les pop-up et l'icône au déplacement de la pop-up (sémaphores, signalements, bases)

### ISSUE THREAD

**Issue by claire2212** [MTES-MCT/monitorenv#960]
Mise en place d'une ligne pointillée lors du déplacement des pop-up pour les sémaphores, signalements et bases sur la carte

**Comment by AdelineCelier** [comment]
C'est bon pour ces 3 pop-ups ! 
Est-ce qu'il y a une raison technique pour laquelle ce n'est pas fait pour les missions ? (ça peut être fait dans un 2nd temps bien sûr, c'est juste pour savoir)
