### ISSUE TITLE
Unités – Mettre à jour les données des pop-ups des bases "en temps réel" sur la carte

### ISSUE THREAD

**Issue by ivangabriele** [MTES-MCT/monitorenv#990]
- [ ] Lorsqu'on ouvre la pop-up d'une base sur la carte et que l'on modifie les moyens attachés à cette base, les données de la pop-up ne se mettent pas à jour. Il faut la fermer et la ré-ouvrir pour que les données à jour s'affichent.
- [ ] Lorsqu'on ouvre la pop-up d'une base sur la carte et qu'une mise à jour a été effectuée ailleurs sur les moyens attachés à cette base, la mise à jour locale automatique (toutes les 5 minutes) ne met pas à jour les données de la pop-up.

**Comment by ivangabriele** [comment]
@AdelineCelier Tu me diras si ce ticket est nécessaire. Je le mets pour l'instant dans le backlog.

**Comment by AdelineCelier** [comment]
@ivangabriele ok merci. Je pense que ça va dépendre de ce qu'on décide en termes de comportements des pop-ups...peut-être qu'à partir du moment où on clique sur une unité de la base, la pop-up pourrait se refermer ? Je sais pas encore trop, mais on pourra trancher ça ensemble, et aviser si ce ticket est nécessaire ou non.

**Comment by claire2212** [comment]
Au vu de ce qui a été décidé sur le comportement des pop-ups, plus besoin de faire ce ticket.
