### ISSUE TITLE
Carte - Les éléments qui sont derrière une pop-up ouverte s'affichent lorsqu'on passe la souris "dessus"

### ISSUE THREAD

**Issue by ivangabriele** [MTES-MCT/monitorenv#996]

**Comment by AdelineCelier** [comment]
Mmh en effet. Non ce n'était pas particulièrement réfléchi, et c'est vrai que ça vient plutôt ajouter du bordel visuel qu'autre chose, on pourrait retirer ce comportement.

**Comment by AdelineCelier** [comment]
J'ai repris ce point dans le ticket #1003 sur le comportement global des pop-ups. Je ferme donc ce ticket-ci.
